### ISSUE TITLE
Feature request : allow multiple and range date selection in datepicker

### ISSUE THREAD

**Issue by Eagleseb** [ng-bootstrap/ng-bootstrap#1037] opened 2016-11-13 14:29 UTC
Hi folks, it would be great if datepicker could support multiple date selection and range selection like this one: [ng2-datepicker](https://www.npmjs.com/package/ng2-datepicker).

Thanks !

**Comment by pkozlowski-opensource** [comment] 2016-11-13 14:32
Duplicate of #753. In short - it is in the works, should land soon. Also check long-term plans for datepicker: #862

**Closed by pkozlowski-opensource** 2016-11-13 14:32 UTC

**Comment by avineet1993** [comment] 2018-04-29 09:35
how can we change multipledate seperator in ng2-datepicker?
