### ISSUE TITLE
NavTabs: Don't destroy on hide but initialise only on click 

### ISSUE THREAD

**Issue by ahadjithoma** [ng-bootstrap/ng-bootstrap#3815] opened 2020-07-16 13:14 UTC
### Bug description:

I have a page with a lot of tabs and each one has its own reactive forms and http calls to initialise those forms. When I open a tab and go back and forth to that tab i dont want it to re-initialise since i might have some filters that i want them to stay as they are left. The input property `destroyOnHide` looked promising but the thing is that all tabs are initialised at the page load even if the user does not navigate to them. This results to a bad page loading time. Ideally, i want the tabs to be initialised only on select, and destroy only when the user navigates to a different url route.

### Link to minimally-working StackBlitz that reproduces the issue:

I believe the description is enough but in case you have different opinion, I can provide with a demo 

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 9
ng-bootstrap: 6
Bootstrap: 4

**Comment by jnizet** [comment] 2020-07-17 06:02
You can do that pretty easily by just keeping a set of visited IDs (thanks to the `activeIdChange` output), and only displaying the content of a tab (thanks to *ngIf) if its ID is in the set of visited Ids.

Here's a demo: https://stackblitz.com/edit/angular-fg9wda?file=src%2Fapp%2Fnav-keep-content.ts

**Comment by ahadjithoma** [comment] 2020-07-17 09:07
Indeed, I can do this but it would be awesome if i didn't have to implement it each time but rather just add a directive that ng-bootstrap will do it for me behind the scenes.

**Comment by benouat** [comment] 2020-07-17 12:33
Correct me if I am wrong, but what you would like to have a kind of `@Input() lazy` that would postponed the initial rendering of the panel.

Regarding our API, I am wondering if we could do that or not... 🤔 everything being directives now for navs, we don't have that much flexibility _internally_ speaking.

My point here is being that I am not sure we could provide a better solution that the one proposed by @jnizet.

**Comment by ahadjithoma** [comment] 2020-07-17 13:09
@benouat 
>Correct me if I am wrong, but what you would like to have a kind of @Input() lazy that would postponed the initial rendering of the panel?

exactly this. 

> My point here is being that I am not sure we could provide a better solution that the one proposed by @jnizet.

Solution is fine and it is what i need. I was thinking if we can have that solution provided by ngbNav, using an input as you said. To be honest, I don't know how feasible or not it is to provide such input. Otherwise, I will try to wrap ngbNav with @jnizet's solution inside a custom component to use it in various components of our project

**Comment by maxokorokov** [comment] 2020-08-20 13:59
Looks like a duplicate of #1584 to me. Lazy initialization is not implemented.

**Closed by maxokorokov** 2020-08-20 13:59 UTC
Labels: component: nav, component: tab, type: feature
