### ISSUE TITLE
Tooltip flashes when mouse is over the edge of element

### ISSUE THREAD

**Issue by r-icarus** [ng-bootstrap/ng-bootstrap#2775] opened 2018-10-09 19:33 UTC
### Bug description:

When a user moves the mouse over the element and leaves the pointer at the edge, the tooltip starts to flash very rapidly. 

It is easy to reproduce if the mouse is close to the place where the tooltip arrow that points to the element

You can also reproduce it on the docs page:

https://ng-bootstrap.github.io/#/components/tooltip/examples

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/angular/lpygqknaedv

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 6.1.7

ng-bootstrap: 2.2.2

**Comment by pkozlowski-opensource** [comment] 2018-10-14 07:52
So, this is an interesting one. It can be easily reproduced by zooming a page and playing with a tooltip on the left. What is going on that when tooltip opens it "covers" trigger element (tooltips have higher z-index) making the tooltip disappear. But when you hide a tooltip a mouse is still on the edge of the trigger element so a tooltip appears and the whole thing repeats. 

Ultimately the problem is with the position - we need to adjust it so tooltip doesn't cover the trigger element.

**Comment by wannadream** [comment] 2018-11-05 20:35
The offset value in 'rem' causes the problem in different zoom level. 

https://github.com/ng-bootstrap/ng-bootstrap/blob/b20355ed7d8e5e8faabfe15e690b6416df0da3c6/src/tooltip/tooltip.scss#L4

Originally, the issue happens when zoom level is between 150% and 250%.
I did some test. After I changed it to 0.35rem, the flashing issue happens at zoom level 135%.
Anyway, it's not stable.

**Comment by fbasso** [comment] 2019-01-17 15:58
After investigation, the issue comes because the tooltip border overlap the element border. As the open/close reacts on hover, which is in fact a mouseenter/mouseleave, when the mouse is over the border and the tooltip displayed, the mouseleave is triggered closing the tooltip, triggering a mouseenter, as the mouse is over the element border.

Finally, the sequence tooltip close -> mouserenter -> tooltip open -> mouseleave is done foreever.

An idea to (easily) fix this is to shift the tooltip of 1 pixel (I tried it successfully).

**Closed** 2019-02-07 09:37 UTC
Labels: component: tooltip, type: bug
