### ISSUE TITLE
Boundaries texts

### ISSUE THREAD

**Issue by gpteamcs** [ng-bootstrap/ng-bootstrap#1291] opened 2017-02-05 09:28 UTC
Hello,
I have a feature request that i need an option that make me change the boundaries arrows to texts like [Next , Last , Previous , First]  and also make those texts as inputs

Thanks

**Comment by pkozlowski-opensource** [comment] 2017-02-06 14:18
Duplicate of #899

**Closed by pkozlowski-opensource** 2017-02-06 14:18 UTC
