### ISSUE TITLE
Typeahead: Focus when navigating with arrow keys gets lost

### ISSUE THREAD

**Issue by PendelinP** [ng-bootstrap/ng-bootstrap#1797] opened 2017-08-31 06:21 UTC
### Bug description:
If you style the typeahead control with a fixed height and set overflow to auto, the arrow-key navigation doesn't work appropriately when the focused element gets outside the visible area.

So it would be nice to automatically scroll to the selected element.

### DEMO:
http://plnkr.co/edit/ffZi6LSRkJUhpxA2AyvN

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.0.3

ng-bootstrap: 1.0.0-beta.3

Bootstrap: 4.0.0-beta

**Comment by pkozlowski-opensource** [comment] 2017-08-31 06:46
This is a duplicate of #1119

**Closed by pkozlowski-opensource** 2017-08-31 06:46 UTC
