### ISSUE TITLE
Add possibility to check if dropdown is visible (typeahead)

### ISSUE THREAD

**Issue by kotmatpockuh** [ng-bootstrap/ng-bootstrap#1846] opened 2017-09-13 12:10 UTC
### Bug description:
It's impossible to add any custom scrollbar right now on typeahead dropdown (we have to check whether it's visible or not). Please add a new output.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4

ng-bootstrap: 1.0.0-beta.4

Bootstrap: 4 beta1

**Comment by pkozlowski-opensource** [comment] 2017-09-13 12:30
Yes, makes sense. We are already tracking this one in #1559, exactly for the use-case you are brining up here.

I'm going to close this one as a duplicate of #1559, please check if the solution proposed in there covers your use case (we are not planning on adding an `@Output` but rather to export a directive instance on which you would have access to the `isOpen()` method.

**Closed by pkozlowski-opensource** 2017-09-13 12:30 UTC

**Comment by kotmatpockuh** [comment] 2017-09-13 12:38
@pkozlowski-opensource yes. It's a pretty good solving of this issue.
