### ISSUE TITLE
Property does not exist on NgbModalConfig

### ISSUE THREAD

**Issue by taufiqahmed** [ng-bootstrap/ng-bootstrap#3568] opened 2020-01-28 10:47 UTC
Getting Typescript error : `Property 'centered' does not exist on type 'NgbModalConfig'`.
Only 'backdrop' and 'keyboard' property is available to configure globally from NgbModalConfig.

Angular: 7.2
ng-bootstrap: 4.2.2
Bootstrap: 4.3.1

**Comment by maxokorokov** [comment] 2020-01-28 11:02
I think this was fixed in a more recent version. With the latest works fine:

https://stackblitz.com/edit/angular-ikpvgw?file=app/modal-config.ts

**Comment by maxokorokov** [comment] 2020-01-28 11:05
Duplicate of #3406

**Closed** 2020-01-28 11:05 UTC
Labels: component: modal, resolution: duplicate, resolution: support
