### ISSUE TITLE
Angular 4 showing depricated element usage in ng-bootstrap

### ISSUE THREAD

**Issue by ashishdoneriya** [ng-bootstrap/ng-bootstrap#1459] opened 2017-04-09 07:45 UTC
The &lt;template&gt; element is deprecated. Use &lt;ng-template&gt; instead (&quot;
  &lt;div class=&quot;card&quot;&gt;
    [WARNING -&gt;]&lt;template ngFor let-panel [ngForOf]=&quot;panels&quot;&gt;
      &lt;div role=&quot;tab&quot; id=&quot;{{panel.id}}-header&quot; [attr.ar&quot;): ng:///home/ashish/workspace/angular/node_modules/@ng-bootstrap/ng-bootstrap/accordion/accordion.d.ts.NgbAccordion.html@2:4

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.0

ng-bootstrap:^1.0.0-alpha.22

Bootstrap:4

**Comment by pkozlowski-opensource** [comment] 2017-04-09 07:54
Duplicate of #1337 (check https://github.com/ng-bootstrap/ng-bootstrap/issues/1337#issuecomment-288971917) that will be solved via #1439. For now you can safely ignore the warning - we are perfectly aware of it and will remove it as soon as we drop 2.x support via  #1439.

**Closed by pkozlowski-opensource** 2017-04-09 07:54 UTC
