### ISSUE TITLE
Dropdown. Clicking on the scroll list collapses.

### ISSUE THREAD

**Issue by Kolpak86** [ng-bootstrap/ng-bootstrap#3109] opened 2019-04-05 09:06 UTC
### Bug description:

Clicking on the scroll list collapses.

The issue reproduces on link below:
https://stackblitz.com/edit/angular-mhj4yu?file=app/dropdown-basic.html

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30974219/55616706-18417080-579b-11e9-80ee-35dbe08f1c2b.gif)

**Comment by benouat** [comment] 2019-04-05 09:40
Thank you @Kolpak86 to report the issue.
Nonetheless, I am closing it as a duplicate of #3063

**Closed by benouat** 2019-04-05 09:40 UTC
Labels: resolution: duplicate
