### ISSUE TITLE
firstDayOfWeek is not the left most day of the week

### ISSUE THREAD

**Issue by wratho** [ng-bootstrap/ng-bootstrap#4729] opened 2024-06-17 21:34 UTC
### Bug description:
In the online exampled and in my own application the `firstDayOfWeek` is the 2nd column. 
![image](https://github.com/ng-bootstrap/ng-bootstrap/assets/28812961/b1f80020-8c7c-4054-b7bb-7c5cb780ec51)
This is the first example in the [datepicker overview](https://ng-bootstrap.github.io/#/components/datepicker/overview) and as you can see the firstDayOfWeek of 1 has S[unday] in the left most column
In my app i have a firstDayOfWeek = 7 and S[aturday] is the left most column
![image](https://github.com/ng-bootstrap/ng-bootstrap/assets/28812961/bef91e64-dd2b-4d57-8745-b64a9e73a0fe)

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-xiclhg-k5arou?file=src%2Fmain.ts

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 18.0.3

ng-bootstrap: 17.0.0

Bootstrap:

**Comment by wratho** [comment] 2024-06-17 21:51
I've also noticed that the `weekday` config setting doesn't appear to work? I set it to "long" and nothing changes. Every value is kept to the single letter values.

**Comment by maxokorokov** [comment] 2024-06-18 06:52
Could you provide more data please, because your StackBlitz works fine for me (see screenshot)... maybe OS, time zone, date/time, basically any relevant info you might think of to reproduce the issue.

![Screenshot 2024-06-18 at 08 50 12](https://github.com/ng-bootstrap/ng-bootstrap/assets/8074436/cd7507b9-4846-4a6f-a8d9-9e6cdc1706a9)

**Comment by HaiFish** [comment] 2024-06-24 11:38
The issue happens here too, timezone here is -03:00, if i change timezone to London, the issue is not present anymore

**Comment by cetdelosaltos** [comment] 2024-07-15 17:43
I have the same issue and I'm in -4:00GMT

**Comment by samvloeberghs** [comment] 2024-07-27 15:14
I can confirm that this seems to be an issue for people in "negative" timezones (GMT-0n:00) and working for "positive" timezones ( GMT+0n:00 )

**Comment by Core121** [comment] 2024-08-16 03:03
Looking to release an angular 18 update for my website, but this bug is preventing me from releasing knowing it'll be shipped with it. Any idea as to when we can see a fix available?

**Comment by edisonaugusthy** [comment] 2024-08-19 19:03
Any Updates on this..?

**Comment by phillipwildhirt** [comment] 2024-08-20 13:33
Does anyone else feel like two months is too long not to have a patch?

I'm including ng-bootstrap's own git website just to make this really clear. Aug 19 (yesterday) is NOT a Sunday. It's a Monday. -6 GMT (CDT) here.
<img width="627" alt="image" src="https://github.com/user-attachments/assets/ccac3c61-3e7b-4f76-b782-96a4be18054b">

**Comment by Core121** [comment] 2024-08-20 16:46
@maxokorokov

**Comment by wratho** [comment] 2024-08-22 16:28
> Is there any work-around for this? And any ETA on when a fix will be available? Thanks!

technically you can offset by one day if your users are localized to the left or right of the GMT line, but no work around that is universal that im aware of.

**Comment by gdh2024-gdh** [comment] 2024-08-27 02:42
Posted a bug (#7552) for paperless-ngx and they closed it pointing to this via issue #7410, #7382.  Any update on when this can be fixed so folks depending on this component within their apps can in turn fix their apps. :)

**Comment by Core121** [comment] 2024-08-27 14:03
I moved to using a different library, doesn't seem like we're going to get a fix any time soon

**Comment by DavidBowdoin** [comment] 2024-08-27 18:40
As a workaround, we are still using the old version `"@ng-bootstrap/ng-bootstrap": "^16.0.0"`
And then added this override for npm at the bottom of our package.json
```
  "overrides": {
    "@ng-bootstrap/ng-bootstrap": {
      "@angular/core": "^18.0.0",
      "@angular/common": "^18.0.0",
      "@angular/forms": "^18.0.0",
      "@angular/localize": "^18.0.0"
    }
  },
```

**Comment by evasilevsky** [comment] 2024-08-27 18:53
As a workaround, I was able to dynamically change the firstDayOfWeek parameter by looking up the timeZoneOffset off of the javascript Date object. 

`this.firstDayOfWeek = new Date().getTimezoneOffset() > 0 ? 1 : 0;`

Then, pass that value into the **firstDayOfWeek** parameter into the **ngbDatePicker** component or directive. I'd suggest storing this globally on the app somewhere so you don't need to look it up every time you need to load a date input field that needs a date picker. 

To test this, I was just modifying my windows time GMT zone. Note: the getTimezoneOffset() function used here will return positive for a negative GMT and negative for a positive GMT. 

Examples: 
**(UTC -08:00) Pacific Time (US & Canada)** will return 420 
**(UTC +09.00) Seoul** will return -540

**Comment by shamoon** [comment] 2024-08-27 20:08
> As a workaround, I was able to dynamically change the firstDayOfWeek parameter by looking up the timeZoneOffset off of the javascript Date object.

This doesn't work. 

`firstDayofWeek = 1` yields:
<img width="238" alt="Screenshot 2024-08-27 at 1 02 33 PM" src="https://github.com/user-attachments/assets/bbd95d96-8cc9-457e-983d-795c8029c28d">

`firstDayofWeek = 0`:
<img width="240" alt="Screenshot 2024-08-27 at 1 02 52 PM" src="https://github.com/user-attachments/assets/20776244-db03-43b9-a7ca-b858f457a490">

That just shifts where the week starts per row, it still shows August 27 as Monday, which it is not.

There is a PR linked above that says it fixes this. In the absence of a working workaround, with respect to the maintainers, hopefully it can be reviewed and merged soon.

**Comment by evasilevsky** [comment] 2024-08-27 20:35
> > As a workaround, I was able to dynamically change the firstDayOfWeek parameter by looking up the timeZoneOffset off of the javascript Date object.
> 
> This doesn't work.
> 
> `firstDayofWeek = 1` yields: <img alt="Screenshot 2024-08-27 at 1 02 33 PM" width="238" src="https://private-user-images.githubusercontent.com/4887959/361956300-bbd95d96-8cc9-457e-983d-795c8029c28d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3OTEwNjMsIm5iZiI6MTcyNDc5MDc2MywicGF0aCI6Ii80ODg3OTU5LzM2MTk1NjMwMC1iYmQ5NWQ5Ni04Y2M5LTQ1N2UtOTgzZC03OTVjODAyOWMyOGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjdUMjAzMjQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTkyYTAwY2RiN2U5ZDFkYzk5OGY4YzBiYzQzYzNhMjYyNjJlMDQwNGU2YWM5MWE2MzY5YmU1N2M3ZDBkYzY3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OaOU9TPixfDGkHwY46BTLNl7MHDmDtK5a733A4W_3rM">
> 
> `firstDayofWeek = 0`: <img alt="Screenshot 2024-08-27 at 1 02 52 PM" width="240" src="https://private-user-images.githubusercontent.com/4887959/361956273-20776244-db03-43b9-a7ca-b858f457a490.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3OTEwNjMsIm5iZiI6MTcyNDc5MDc2MywicGF0aCI6Ii80ODg3OTU5LzM2MTk1NjI3My0yMDc3NjI0NC1kYjAzLTQzYjktYTdjYS1iODU4ZjQ1N2E0OTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjdUMjAzMjQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTE3OTc0YWNhNTg4NGZmMTdiOTJlMzE3YWEzM2NiYTU2ZGY1MGNjYTMwODhhZWViNWM3MmQzMWViODQxNWYyMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jaz4qmbiR6DUxVvRY-xYgY0zZLvCeJ_-sMyCfhljh5g">
> 
> That just shifts where the week starts per row, it still shows August 27 as Monday, which it is not.
> 
> There is a PR linked above that says it fixes this. In the absence of a working workaround, with respect to the maintainers, hopefully it can be reviewed and merged soon.

The problem itself can be reproduced if you switch time zones. At this point, the firstDayOfWeek parameter itself cannot be trusted to do what the documentation says it does. So, in my testing, I found that 0 or 1 work the way I want them to when we switch time zones on my OS. 
You can easily see that the issue is "resolved" if you look at the demo @wratho originally posted, but put your OS in a positive GMT time zone.  https://stackblitz.com/edit/angular-xiclhg-k5arou?file=src%2Fmain.ts

I modified that original demo with my change and now it works correctly as I switch time zones. 
https://stackblitz.com/edit/angular-xiclhg-uh2mfq?file=src%2Fapp%2Fdatepicker-basic.ts

**Comment by shamoon** [comment] 2024-08-27 20:40
https://stackblitz.com/edit/angular-xiclhg-uh2mfq?file=src%2Fapp%2Fdatepicker-basic.ts:
<img width="1602" alt="Screenshot 2024-08-27 at 1 40 29 PM" src="https://github.com/user-attachments/assets/eb7f4060-7d20-4f39-9794-24543d460716">

I am in GMT-7

**Comment by evasilevsky** [comment] 2024-08-27 20:44
And the bug is GONE!

**Comment by shamoon** [comment] 2024-08-27 20:55
Im sorry to the others subscribed to this thread but mate, look at the screenshot again, or in fact any of the 3 I've posted. August 27 is not a Monday.

**Comment by evasilevsky** [comment] 2024-08-27 21:09
> Im sorry to the others subscribed to this thread but mate, look at the screenshot again, or in fact any of the 3 I've posted. August 27 is not a Monday.

Thank you, you are correct. I was laser-focused on the headers being wrong. Thank you for pointing that out to me. I'll modify the original post to say this doesn't work. 

People make mistakes. Thank you again for being patient with me.

**Comment by Hoang-Minh** [comment] 2024-08-27 23:02
Any plan on how and when this bug will get resolved ? 
Our app is supposed to go live next week. I've been waiting for the fix for almost 2 months now. I've been telling my QA that the fix is going to be deployed soon :((((. I don't want to swap out to another lib and re-write our UI logic again....

Thank you.

**Closed** 2024-08-28 10:17 UTC
Labels: needs: info, needs: investigation, component: datepicker

**Comment by joelamos** [comment] 2024-09-06 23:30
Many thanks!
