### ISSUE TITLE
Accordion dynamic data id and dynamic opening.

### ISSUE THREAD

**Issue by Bank5z0rSqt** [ng-bootstrap/ng-bootstrap#1826] opened 2017-09-07 10:25 UTC
Hello, i'm new with ngb.

### Bug description:
After feeding some data to Accordion with` *ngFor`, first `ngb-panel` tab is not open by default. When i set dynamic ID to the panel, and hardcode that dynamic id to` activeIds` in `ngb-accordion` element, nothing happens. I think `activeIds` can't see the change on new id-s. My end goal is to have each panel opened by click on some element in outside component. I assume that could be done only with dynamic id-s. I wonder why isn't it working, and if there is a better way to do this, I would really like to hear it :)

Here's a ss of ID-s, showing they are the same, but it didn't add active class to panel element. https://prnt.sc/gi650w
### Link to minimally-working plunker that reproduces the issue:

Here's basic dynamic data plunker. 
http://plnkr.co/edit/VutTgYmWAxyuzep4qp1H?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.1.3.
ng-bootstrap: v1.0.0-beta.3
Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment] 2017-09-07 11:46
`activeIds` on the tabset level needs to match _exactly_ the `id` given to a tab, and this is not the case in your plunker (thnx for providing one, it is always easier to trouble-shoot with plunkers!). In your particular example, we've got:
* `activeIds="1-header"` (as string)
* `[id]="dummy.id"` and it will result in things like `1`, `2` etc. (as number).

So, in the plunker neither value (`1-header` vs. `1`) nor type (`string` vs. `number`) matches. This is why initially no panel is active (open). If you fix the mentioned issue all starts to work as expected: http://plnkr.co/edit/9e1NPFtdnLbMsPPVlvCL?p=preview

Also please note that looking at the generated HTML is not much use in debugging, and especially here since:
* you should be looking at the `id` generated at a panel level, not panel's header level;
* in this very case headers get id of `panel's id + "-header"`: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/accordion/accordion.ts#L100.

I'm going to close this one as a support request since all things seem to work as designed.

**Closed by pkozlowski-opensource** 2017-09-07 11:46 UTC

**Comment by boltex** [comment] 2020-01-21 18:28
Great product overall, but a small quirk here : I just tested :  this does not work if the active IDs are generated programmatically and provided in an array. But on the other hand, it does work if the activeIds are given as a comma-separated string. Also, (no offense intended here) it's kind of weird that the "-header" suffix has to be added on activeIds list only when dynamically generating ngb-panels. 

Example: this is the attribute on my ngb-accordion tag :  
`[activeIds]="generateIds('type-', data.contractTypes.length)"`

and this is my generateIds function that works (if it returns as array, without the .join(),  it does not work) 

```
  public generateIds(p_prefix: string, p_qty: number): string {
    const w_refIds = [];
    for (let w_i = 0; w_i < p_qty; w_i++) {
      w_refIds.push(p_prefix + w_i);
    }
    return w_refIds.join();
  }
```

**Comment by vijayknu** [comment] 2023-08-04 05:03
@boltex - Thanks! This is good. I tried in another way and thought of mentioning the same. Had a look at the [api](https://ng-bootstrap.github.io/releases/9.x/#/components/accordion/api) - expandAll() method. In ts file, I had ViewChild for accordian and in html I had set activeIds static. Ex: "1-header". And doing expandAll() in afterViewInit() opens all panels. I done this to avoid having a method in HTML (generateIds()).
