### ISSUE TITLE
Button still highlighted after tooltip was hidden (Edge)

### ISSUE THREAD

**Issue by Yura13** [ng-bootstrap/ng-bootstrap#2341] opened 2018-04-24 11:42 UTC
### Link to minimally-working plunker that reproduces the issue:
Move cursor over the button. The tooltip is shown. Then move cursor up through the tooltip.
Actual result: Button is highlighted
Expected result: Button isn't highlighted

Reproduced only in Edge.

Printscreen made from https://ng-bootstrap.github.io/#/components/tooltip/examples
![image](https://user-images.githubusercontent.com/17030431/39184643-d7b2e5fa-47cc-11e8-8a2d-d0dd6b6aa712.png)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2.9
ng-bootstrap: 1.1.1
Bootstrap: 4.0.0

**Comment by pkozlowski-opensource** [comment] 2018-05-03 08:44
@divdavem could you please check this on the latest version of the demo page and latest Edge if you can reproduce? If you can, could you please try to dig into it? Don't hesitate to ask if you need any info / help!

**Comment by divdavem** [comment] 2018-05-03 08:54
@pkozlowski-opensource yes I can reproduce the issue in Edge. It looks like a bug (Edge does not seem to trigger the end of the ":hover" CSS state when the mouse leaves the button through the tooltip), I will investigate deeper to find a workaround.

**Comment by pkozlowski-opensource** [comment] 2018-05-03 08:59
@divdavem oh, great. When you say:

> It looks like a bug (Edge does not seem to trigger the end of the ":hover" CSS state when the mouse leaves the button through the tooltip)

do you mean a bug in Edge, Bootstrap CSS or our side? Depending on the root cause we should report / fix it in the proper place. 

Curious if it also happens in https://getbootstrap.com/docs/4.1/components/tooltips/ ?
Or maybe we can reproduce it in Edge without Bootstrap CSS ?

If it turns out a bug in Bootstrap CSS / Edge we should just open an issue in the target repo, I'm not too keen on work-around here (unless those are very small / simple / obvious). 

Thnx!

**Comment by divdavem** [comment] 2018-05-03 09:10
I am talking about a bug in Edge.
It does not happen in https://getbootstrap.com/docs/4.1/components/tooltips/.
It seems to be linked to the timing (how quickly the mouse goes out of the button, and how quickly the tooltip disappears).
There seems to be an issue on the bug tracker of Edge for a similar case: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5381673/

**Comment by divdavem** [comment] 2018-05-03 09:51
Adding a setTimeout before closing the tooltip seems to solve the issue.
@pkozlowski-opensource Do you think that it is small / simple / obvious enough to be integrated in ng-bootstrap?

**Comment by pkozlowski-opensource** [comment] 2018-05-03 09:54
> Adding a setTimeout before closing the tooltip seems to solve the issue.

I would work very hard to try _not_ to add `setTimeout` as it messes up things on several levels:
* will cause another cycle of JS / repaint etc.
* will make all the tests async

I wonder if using the `container`: `body` option is working-around the issue (it should create tooltip elements in a different place in the DOM, maybe it is enough to trick Edge?)

**Comment by divdavem** [comment] 2018-05-03 11:32
For info, I have reproduced the issue in the following simple page (without either ng-bootstrap or Bootstrap CSS), showing that the problem comes from a bug in Edge: https://divdavem.github.io/hoverIssueEdge/

**Comment by pkozlowski-opensource** [comment] 2018-05-03 11:40
Awesome @divdavem - this proves that the bug is indeed the Edge problem. Maybe it would be a good idea to add your reproduce scenario to https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5381673/ ?

If I understand correctly the issue will be either fixed in Edge or adding any delay will act as a work-around. Given that this is a bug in a browser and we plan to add delays through animations and / or #1052 I think that we can close it here.

Thnx for the detailed investigation @divdavem !

**Closed by pkozlowski-opensource** 2018-05-03 11:40 UTC
Labels: component: tooltip, needs: investigation

**Comment by divdavem** [comment] 2018-05-03 12:02
@pkozlowski-opensource You're welcome. I have added our specific use case to the Edge ticket.
