### ISSUE TITLE
Slider in ng-bootstrap

### ISSUE THREAD

**Issue by DouglasLapsley** [ng-bootstrap/ng-bootstrap#4149] opened 2021-08-25 02:34 UTC
Is there any chance of an ng-bootstrap slider please? I keep finding that I need it and having to go elsewhere for an implementation. Thanks!

**Comment by pkozlowski-opensource** [comment] 2021-08-25 10:17
This was discussed in the past, see #1350 - generally speaking the biggest problem here is that if there is no Bootstrap CSS widget than things get complicated. The primary reason for this project existence is to implement widgets corresponding to Bootstrap CSS.

As far as I can tell Bootstrap has only CSS for a standard `type="range"` input and there is no need for any specific widget here.

So my questions is - when you say "finding that I need it" - what do you need _exactly_ and what widgets you download when you need a "slider"?

**Comment by DouglasLapsley** [comment] 2021-08-25 11:37
Thanks for getting back to me. That's interesting.

I quite often have a client ask me specifically for a slider as an input mechanism.  Normally for a percentage selection in a survey system or similar.  Most times I end up using [Angular Material](https://material.angular.io/), but clearly that's a sledgehammer to crack a nut and complicates things.  It's the only component that I feel is really lacking from the library as it's quite a well-used one.

Thank you.

**Comment by pkozlowski-opensource** [comment] 2021-08-25 11:41
> clearly that's a sledgehammer to crack a nut and complicates things

yeh - the main problem I see that you need to re-do the whole accessibility and loose native look & feel / behaviour. 

An interesting question here would be: "what is really missing from `type="range"` input"?

As far as ng-bootstrap goes - the biggest issue for us is that there is no corresponding Bootstrap markup / CSS and we would have invent and maintain it on our side. This is non-trivial amount of work and great source of bugs (jugging from our experience dealing with datepicker and other widgets that are not part of Bootstrap)

**Comment by DouglasLapsley** [comment] 2021-08-25 11:45
OMGoodness!  25 years coding and I didn't know about type="range".  That will work nicely thank you.  Cannot believe I didn't know about that!!!  Just shows that I should revisit the documentation for the basics once in a while to refresh!  Thank you.

**Comment by pkozlowski-opensource** [comment] 2021-08-25 11:50
Ha, ha, glad that this helps. For the record, this is how Bootstrap "does sliders": https://getbootstrap.com/docs/5.0/forms/range/

**Comment by DouglasLapsley** [comment] 2021-08-25 11:55
Thank you, I am humbled and grateful for your informative responses.  Much appreciated.

**Comment by maxokorokov** [comment] 2022-04-05 08:45
Duplicate of #1350

**Closed by maxokorokov** 2022-04-05 08:45 UTC
Labels: type: feature, resolution: support
