### ISSUE TITLE
Modal: Scrolling with arrow buttons (Up/Down) doesn't work

### ISSUE THREAD

**Issue by andrii-oleksyshyn** [ng-bootstrap/ng-bootstrap#2689] opened 2018-09-06 09:21 UTC
### Bug description:
Scrolling with arrow buttons doesnt work when you set fixed height of the modal with overflow-y: auto to scroll the content that doen't fit the height of the modal. By the way scroll with mouse wheel works fine.
### Link to minimally-working plunker that reproduces the issue:
http://next.plnkr.co/edit/jsVH3nDWO2XvxSbV

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6.1.0

ng-bootstrap: 3.2.0

Bootstrap: 4.0.0

**Comment by aakash1401** [comment] 2018-09-07 13:32
I am still stuck with above issue. No comment from team side ?

**Comment by maxokorokov** [comment] 2018-09-10 14:16
To me looks like native bootstrap supports scrolling of the long content in the following way: https://getbootstrap.com/docs/4.1/components/modal/#scrolling-long-content. 

If you limit the height with 
```css
.modal-body {
  height: 250px;
  overflow-y: auto;
}
```
 it behaves in exactly the same way as ng-bootstrap.

For the problem you raise, I think it works as designed. Unless you have a focusable element in the modal content, why would it scroll with the keyboard?

**Comment by pkozlowski-opensource** [comment] 2018-09-16 06:32
Closing based on @maxokorokov comment.

**Closed by pkozlowski-opensource** 2018-09-16 06:32 UTC
Labels: component: modal
