### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError when using ngbModal from nbgRadioGroup click

### ISSUE THREAD

**Issue by mohamedmansour** [ng-bootstrap/ng-bootstrap#2612] opened 2018-08-14 17:41 UTC
### Bug description:

When launching a NgbModal from a ngbRadioGroup click, produces consistent always reproducible errors  ExpressionChangedAfterItHasBeenCheckedError

### Link to minimally-working plunker that reproduces the issue:

https://stackblitz.com/edit/angular-feikur

The "This works" button shows the correct behaviour, no errors in console.
When clicking on radio button "Custom range" the bug exists:

```
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'focus: true'. Current value: 'focus: false'.
    at viewDebugError (errors.ts:35)
    at expressionChangedAfterItHasBeenCheckedError (errors.ts:21)
    at checkBindingNoChanges (util.ts:102)
    at checkNoChangesNodeInline (view.ts:476)
    at checkNoChangesNode (view.ts:461)
    at debugCheckNoChangesNode (services.ts:464)
    at debugCheckRenderNodeFn (services.ts:416)
    at Object.eval [as updateRenderer] (RadialSelectorComponent.html:3)
    at Object.debugUpdateRenderer [as updateRenderer] (services.ts:408)
    at checkNoChangesView (view.ts:343)
```

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:  v6.1.0

ng-bootstrap: v3.0.0

Bootstrap: v4.1.3

**Comment by pkozlowski-opensource** [comment] 2018-08-15 06:30
This is a duplicate of https://github.com/ng-bootstrap/ng-bootstrap/issues/1252 - we are aware of the problem but not sure what to do about it... I guess the only option is to move focus to the modal asynchronously... 

Let's continue the discussion in #1252

**Closed by pkozlowski-opensource** 2018-08-15 06:30 UTC
