### ISSUE TITLE
Custom Time Adapter accept invalid valid in HH and MM fields

### ISSUE THREAD

**Issue by yasiryc** [ng-bootstrap/ng-bootstrap#3566] opened 2020-01-27 16:32 UTC
### Bug description:
When entering hour value in HH field, it accepts more than allowed. For example, we were able to enter 23-99 values in 24 hours format control. The same goes for MM field as well. 

The issue is repeatable in one of the demos on the ng-bootstrap time picker page

https://stackblitz.com/run?file=app/timepicker-adapter.ts

To recreate the issue, enter a value greater than 23 in HH field, navigate away you will see the value adjust fine, click back to HH field again enter the same value and then click away, you will notice invalid value stays in the control. The same is repeatable in MM field too. The model has correct value but the view is invalid.

![invalid time issue](https://user-images.githubusercontent.com/13417952/73194404-2a114d00-40fa-11ea-9f64-1b1f76da454a.png)

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/run?file=app/timepicker-adapter.ts

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.2.4

ng-bootstrap: 5.2.1

**Comment by benouat** [comment] 2020-02-07 10:28
Thanks for reporting this issue, but I'll close it as a duplicate of #3548

**Closed by benouat** 2020-02-07 10:28 UTC
Labels: component: timepicker
