### ISSUE TITLE
How to cancel typeahead

### ISSUE THREAD

**Issue by dereklin** [ng-bootstrap/ng-bootstrap#1382] opened 2017-03-16 21:29 UTC
I have an input field.  When you type something and hit enter, and when the value is correct, it will update some UI.

I have added typeahead to it to help the users find correct input values.

When I type slowly the suggested values comes back.  I select the correct value.  I hit Enter.  Everything works nicely.

However, when I type really fast and hit Enter before seeing any suggestions/popup.  My UI updates.  But after that, the suggestion popup shows up.

I don't want to see the popup anymore.  Is there an easy way to cancel the typeahead search in the this case so that it will not show up?

**Comment by dereklin** [comment] 2017-03-16 23:33
For now, I invoke this function to make the popup go away:
```
  private resetNgbTypeahead(input) {
    input.value = '';
    let event = document.createEvent('KeyboardEvent');
    event.initKeyboardEvent('input', true, true, null, '', 0, '', false, '');
    input.dispatchEvent(event);
    input.focus();
  }

```

**Comment by pkozlowski-opensource** [comment] 2017-03-17 06:45
This is duplicate of #723

**Closed by pkozlowski-opensource** 2017-03-17 06:45 UTC
