### ISSUE TITLE
Feature request: Assign custom class for navs

### ISSUE THREAD

**Issue by ysds** [ng-bootstrap/ng-bootstrap#2061] opened 2017-12-28 00:43 UTC
Please add the feature to apply custom class (e.g. `.nav-bordered`) other than `.nav-pills`, ` .nav-tabs` to `.nav`.

I would like to use an additional custom style nav like included in the bootstrap official theme:
https://bootstrap-themes.github.io/dashboard/docs/index.html#nav-bordered

![image](https://user-images.githubusercontent.com/4065765/34396814-6431f758-ebb3-11e7-8096-99e583d9734c.png)

**Comment by pkozlowski-opensource** [comment] 2018-01-02 10:20
Duplicate of #1567

**Closed by pkozlowski-opensource** 2018-01-02 10:20 UTC

**Comment by bastienmoulia** [comment] 2018-01-02 12:21
Not sure it is a duplicate.

Have you try to add `type="bordered"` in your `<ngb-tabset>`? It's not documented but it should add the class `nav-bordered`.

http://plnkr.co/edit/2wTWD6HTslDHLc606t5Y?p=preview

**Comment by ysds** [comment] 2018-01-11 02:11
@bastienmoulia Thanks a lot! `type="my-custom-class"` seems to work well.
