### ISSUE TITLE
ng-template should be used 

### ISSUE THREAD

**Issue by daBishMan** [ng-bootstrap/ng-bootstrap#1496] opened 2017-04-14 22:33 UTC
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
Brand new application using angular CLI 1.0.0

`@angular/cli: 1.0.0
node: 7.7.4
os: win32 x64
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/core: 4.0.2
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/router: 4.0.2
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.2
`

I added 1.0.0-alpha.23, and bootstrap 4.0.0-alpha.6 when I do a prod build I see 

> Template parse warnings: The 'template' element is deprecated. Use 'ng-template' instead (
> div class="card"
> WARNING  template ngFor let-panel [ngForOf]="panels"
>       div role="tab" id="{{panel.id}}-header"
>         "): ng:///NgbAccordionModule/NgbAccordion.html@2:4

### Link to minimally-working plunker that reproduces the issue:
nothing
You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.0.2

ng-bootstrap: 1.0.0-alpha.23

Bootstrap: 4.0.0-alpha.6

**Comment by jnizet** [comment] 2017-04-14 22:37
This is a known issue, and isn't really an issue. We want to keep supporting Angular 2 for a while, and Angular 2 doesn't have ng-template. So we can't avoid this warning. template is deprecated, but still working in Angular 4, so it's not a big issue, and we plan to us ng-template when we decide to drop support for Angular 2.

It's in our plans already.

Closing as duplicate of #1439

**Closed by jnizet** 2017-04-14 22:37 UTC
