### ISSUE TITLE
ng-bootstrap does'nt support by angular 15.0.0

### ISSUE THREAD

**Issue by Ali-Azizi** [ng-bootstrap/ng-bootstrap#4436] opened 2022-11-30 09:19 UTC
Hi,

I've tried to install ng-bootstrap on my project with angular 15.0.0 by I caught below error:

```

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: automation@0.0.0
npm ERR! Found: @angular/core@15.0.0
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"15.0.0" from @angular/animations@15.0.0
npm ERR!   node_modules/@angular/animations
npm ERR!     peerOptional @angular/animations@"15.0.0" from @angular/platform-browser@15.0.0
npm ERR!     node_modules/@angular/platform-browser
npm ERR!       peer @angular/platform-browser@"15.0.0" from @angular/forms@15.0.0
npm ERR!       node_modules/@angular/forms
npm ERR!         @angular/forms@"^15.0.0" from the root project
npm ERR!       3 more (@angular/platform-browser-dynamic, @angular/router, the root project)
npm ERR!     @angular/animations@"^15.0.0" from the root project
npm ERR!   peer @angular/core@"15.0.0" from @angular/common@15.0.0
npm ERR!   node_modules/@angular/common
npm ERR!     peer @angular/common@"15.0.0" from @angular/forms@15.0.0
npm ERR!     node_modules/@angular/forms
npm ERR!       @angular/forms@"^15.0.0" from the root project
npm ERR!     peer @angular/common@"15.0.0" from @angular/platform-browser@15.0.0
npm ERR!     node_modules/@angular/platform-browser
npm ERR!       peer @angular/platform-browser@"15.0.0" from @angular/forms@15.0.0
npm ERR!       node_modules/@angular/forms
npm ERR!         @angular/forms@"^15.0.0" from the root project
npm ERR!       3 more (@angular/platform-browser-dynamic, @angular/router, the root project)
npm ERR!     4 more (@angular/platform-browser-dynamic, @angular/router, ...)
npm ERR!   7 more (@angular/compiler, @angular/forms, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! @ng-bootstrap/ng-bootstrap@"14.0.0-rc.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @angular/core@15.0.1
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"15.0.1" from @angular/forms@15.0.1
npm ERR!   node_modules/@angular/forms
npm ERR!     @angular/forms@"^15.0.0" from the root project
npm ERR!     peer @angular/forms@"^15.0.0" from @ng-bootstrap/ng-bootstrap@14.0.0-rc.0
npm ERR!     node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!       @ng-bootstrap/ng-bootstrap@"14.0.0-rc.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

My ng version result is:
```
Angular CLI: 15.0.0
Node: 18.12.1
Package Manager: npm 8.19.2
OS: darwin x64

Angular: 15.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.0
@angular-devkit/build-angular   15.0.0
@angular-devkit/core            15.0.0
@angular-devkit/schematics      15.0.0
@schematics/angular             15.0.0
rxjs                            7.5.7
typescript                      4.8.4

```

Thank you for your attention...

**Comment by pkozlowski-opensource** [comment] 2022-11-30 09:51
Duplicate of #4419

**Closed by pkozlowski-opensource** 2022-11-30 09:51 UTC
