### ISSUE TITLE
Apply css to tooltip

### ISSUE THREAD

**Issue by maritogaleano** [ng-bootstrap/ng-bootstrap#4375] opened 2022-08-10 14:37 UTC
### Bug description:
I tried to apply css to the tooltip, however it is not applying, I did it directly like the example, however it does not accept me to inject on the existing selector

![image](https://user-images.githubusercontent.com/57814047/183926250-fd81b6a5-b71b-419f-ae72-29e1ee788b00.png)

I also tried to add the style directly, however it doesn't work either

![image](https://user-images.githubusercontent.com/57814047/183929396-20634605-98ce-4de5-b252-6bc65f8f4d8a.png)

![image](https://user-images.githubusercontent.com/57814047/183929201-dbe4bf3d-e807-4a0d-b028-9dccd4877020.png)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular:   13.3.7

ng-bootstrap: 12.1.2

Bootstrap: 5.2.0-beta1

**Comment by jnizet** [comment] 2022-08-10 14:59
The example in the documentation uses ViewEncapsulation.NONE. Yours doesn't. If you want to keep the default encapsulation, you need to add `::ng-deep ` before all your CSS selectors.

**Comment by maritogaleano** [comment] 2022-08-10 15:39
> 

Should it look like this in my css selectors?

`.my-custom-class .tooltip-inner {
    background-color: darkgreen;
    font-size: 125%;
}

.my-custom-class.bs-tooltip-end .tooltip-arrow::ng-deep {
    border-right-color: darkgreen;
}

.my-custom-class.bs-tooltip-start .tooltip-arrow::ng-deep {
    border-left-color: darkgreen;
}

.my-custom-class.bs-tooltip-top .tooltip-arrow::ng-deep {
    border-top-color: darkgreen;
}`

**Comment by maxokorokov** [comment] 2022-08-11 08:06
You can also apply a custom CSS class if it helps → https://ng-bootstrap.github.io/#/components/tooltip/examples#customclass

**Comment by jnizet** [comment] 2022-08-11 14:24
@maritogaleano no. As I said, add `::ng-deep` **before** the css selectors:

https://stackblitz.com/edit/angular-jmvsej?file=src%2Fapp%2Ftooltip-customclass.ts

```css
    ::ng-deep .my-custom-class .tooltip-inner {
      background-color: darkgreen;
      font-size: 125%;
    }
    ::ng-deep .my-custom-class.bs-tooltip-end .tooltip-arrow::before {
      border-right-color: darkgreen;
    }
    ::ng-deep .my-custom-class.bs-tooltip-start .tooltip-arrow::before {
      border-left-color: darkgreen;
    }
    ::ng-deep .my-custom-class.bs-tooltip-top .tooltip-arrow::before {
      border-top-color: darkgreen;
    }
    ::ng-deep .my-custom-class.bs-tooltip-bottom .tooltip-arrow::before {
      border-bottom-color: darkgreen;
    } 
```

**Comment by maritogaleano** [comment] 2022-08-11 15:25
> 

I made the change, however it still doesn't apply the style to the tooltip

![image](https://user-images.githubusercontent.com/57814047/184169425-26bdfdf9-3937-4546-b313-047bde0d106a.png)

In the example you sent me, I see that the style is applied from the component, that is, in this way:

@Component({
  selector: 'ngbd-tooltip-customclass',
  templateUrl: './tooltip-customclass.html',
  styles: [
    `
    ::ng-deep .my-custom-class .tooltip-inner {
      background-color: darkgreen;
      font-size: 125%;
    }
    ::ng-deep .my-custom-class.bs-tooltip-end .tooltip-arrow::before {
      border-right-color: darkgreen;
    }
    ::ng-deep .my-custom-class.bs-tooltip-start .tooltip-arrow::before {
      border-left-color: darkgreen;
    }
    ::ng-deep .my-custom-class.bs-tooltip-top .tooltip-arrow::before {
      border-top-color: darkgreen;
    }
    ::ng-deep .my-custom-class.bs-tooltip-bottom .tooltip-arrow::before {
      border-bottom-color: darkgreen;
    }
  `,
  ],
})

In my case, I have my own style file, how does the example apply in that case?


![image](https://user-images.githubusercontent.com/57814047/184170316-45637169-d2b8-445d-9d26-8808fa5275e3.png)

**Comment by jnizet** [comment] 2022-08-11 16:40
It should work the same way. Post a repro on stackblitz.

**Comment by maritogaleano** [comment] 2022-08-11 18:37
> It should work the same way. Post a repro on stackblitz.

There I replicated my case in stackblitz https://stackblitz.com/edit/angular-jmvsej?file=src%2Fapp%2Ftooltip-customclass.ts,src%2Fapp%2Ftooltip-custom-class.css

**Comment by jnizet** [comment] 2022-08-11 19:17
The stackblitz you posted is the one I posted above. And it displays a tooltip with a green background.

**Comment by maritogaleano** [comment] 2022-08-11 20:43
> The stackblitz you posted is the one I posted above. And it displays a tooltip with a green background.

I apologize, I copied the link wrong, this is the correct one: https://stackblitz.com/edit/angular-jmvsej-bzpz9y?file=src%2Fapp%2Ftooltip-customclass.css,src%2Fapp%2Ftooltip-customclass.ts

**Comment by jnizet** [comment] 2022-08-11 21:45
You made two mistakes:
1. the property must be named `styleUrls`, not `styles`
2. The array must contain the path of the **css** file, not the path of the **ts** file.

**Comment by maritogaleano** [comment] 2022-08-11 22:14
> You made two mistakes:
> 
> 1. the property must be named `styleUrls`, not `styles`
> 2. The array must contain the path of the **css** file, not the path of the **ts** file.

I made the change and in stackblitz it works, however in my project it doesn't 


![image](https://user-images.githubusercontent.com/57814047/184251484-f4291b5a-0937-4f7c-b04a-7994b24d1573.png)


![image](https://user-images.githubusercontent.com/57814047/184251548-f703433c-5c05-4733-a480-2e513dee6167.png)


![image](https://user-images.githubusercontent.com/57814047/184251601-bcf31581-76ae-4b95-8fbd-67055fd97cb9.png)

**Comment by jnizet** [comment] 2022-08-12 06:27
You put the CSS in mis-cuentas.css, which is probably not the CSS file for the component whose template is in mis-vehiculos.html. 

I think it's time to close this issue now. The problem is in your code, and ng-bootstrap github issues is not a good place to debug your code.

**Closed by jnizet** 2022-08-12 06:27 UTC
Labels: component: tooltip, type: customization
