### ISSUE TITLE
Typehead fixed height keyboard item selection not scrolling dropdown

### ISSUE THREAD

**Issue by shabbir-dhangot** [ng-bootstrap/ng-bootstrap#2379] opened 2018-05-15 05:57 UTC
### Bug description:

Dropdown not scrolling with keyboad event. I have more than 20 suggestion and I want to display 5 at a time. I fixed height of dropdown menu and all work fine except keyborad up/down not scrolling dropdown.

### Link to minimally-working plunker that reproduces the issue:
search for in
https://stackblitz.com/edit/angular-umjktm?file=app/typeahead-template.ts

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
5.2.5
ng-bootstrap:
1.1.2
Bootstrap:
latest

**Comment by pkozlowski-opensource** [comment] 2018-05-15 07:59
Duplicate of #1119

**Closed by pkozlowski-opensource** 2018-05-15 07:59 UTC
