### ISSUE TITLE
NgbPopover should have similar option like 'Dismissible popover' as bootstrap

### ISSUE THREAD

**Issue by simon-cha** [ng-bootstrap/ng-bootstrap#1629] opened 2017-06-21 17:34 UTC
NgbPopover should have an option to close on clicking else where, something like bootstrap's 'Dismissible popover'. 

Popover window is remain opened on clicking some link or button and need to call the close function to dismiss it.

Same feature like:
https://v4-alpha.getbootstrap.com/components/popovers/#dismiss-on-next-click

Thanks.

**Comment by pkozlowski-opensource** [comment] 2017-06-21 17:42
Duplicate of #933

**Closed by pkozlowski-opensource** 2017-06-21 17:42 UTC
