### ISSUE TITLE
Problem with Custom Date Adapter in DatePicker

### ISSUE THREAD

**Issue by leofiore99** [ng-bootstrap/ng-bootstrap#2098] opened 2018-01-18 17:25 UTC
The Custom Date Adapter example in the documentation contain an error... If you open the console and select a date on the input, will see ""ERROR RangeError: Maximum call stack size exceeded. 

It keeps calling fromModel and toModel with no stop, until get an limit error.

How can I fix it? Thanks!

**Comment by mslosarek** [comment] 2018-01-19 04:10
This appear to be an issue with the datepicker in a popup. This is happening on the demo page: 
https://ng-bootstrap.github.io/#/components/datepicker/examples 
https://ng-bootstrap.github.io/app/components/datepicker/demos/adapter/plnkr.html

**Comment by maxokorokov** [comment] 2018-01-19 10:58
I can't reproduce it on Mac OS Chrome, Safari, Firefox. Timezone GMT+1

What does "select date on the input" mean?
Any more info?

**Comment by leofiore99** [comment] 2018-01-19 11:28
@mslosarek Yes, exactly, I need to fix it for my project

@maxokorokov When I choose a date from popup datepicker, I receive this error in console:

See: [](https://ng-bootstrap.github.io/app/components/datepicker/demos/adapter/plnkr.html)

Choose a date in the popup on the right, and open console, or just put a console.log in those methods fromModel and toModel

**Comment by pkozlowski-opensource** [comment] 2018-01-19 13:06
As @maxokorokov I can't reproduce either... What is your exact environment (OS, browser and its version etc. ...)? Can you try in the incognito mode of your browser to rule-out extension(s) interference?

**Comment by maxokorokov** [comment] 2018-01-19 13:28
Most likely a timezone issue with South America. 
Duplicate of #2060, PR #2071 opened for this one.

**Closed** 2018-01-19 13:35 UTC
Labels: component: datepicker, needs: info

**Comment by mslosarek** [comment] 2018-01-19 13:49
Thanks for the help on this. I have confirmed that changing the toModel resolves the issue
```
  toModel(date: NgbDateStruct): Date {
    return date ? new Date(date.year, date.month - 1, date.day) : null;
  }
```
