### ISSUE TITLE
Feature request for typeahead

### ISSUE THREAD

**Issue by gregbown** [ng-bootstrap/ng-bootstrap#1336] opened 2017-02-24 18:24 UTC
There are cases where a user wants to submit a form with unmatched auto complete input or the UI designer thinks people want to see partial match results.  This is currently not possible as the enter key will submit the selected unless focusFirst is false or editable is true, in which case it will not emit the select item event. If the key event switch Key.Enter was altered as below it would allow both matched or unmatched.  A separate or new config parameter may be needed to be backwards compatible.
```
                case Key.Enter:
                  var result = this._windowRef.instance.getActive();
                  if(!this.focusFirst) {
                    if( !isDefined(result) ) {
                      result = this._userInput;
                    }
                  }
                  if (isDefined(result)) {
                    event.preventDefault();
                    event.stopPropagation();
                    this._selectResult(result);
                  }
                  this._closePopup();
                  break;
```

Versions:
Angular 2.4.8,
ng-bootstrap 1.0.0-alpha.20,
Bootstrap 4.0.0-alpha.6:

**Comment by gregbown** [comment] 2017-02-25 03:47
Revising slightly because if you arrow down to a search result and then hit enter, my initial post code will introduce a bug.  The following solves that but can possibly be cleaned up?
`                case Key.Enter:
                  var result = this._windowRef.instance.getActive();
                  if(!this.focusFirst) {
                    if( !isDefined(result) ) {
                      result = this._userInput;
                    }
                  }
                  if (isDefined(result)) {
                    event.preventDefault();
                    event.stopPropagation();
                    this._selectResult(result);
                  }
                  this._closePopup();
                  break;`

**Comment by deeg** [comment] 2017-02-28 17:36
This should already be possible by adding a keypress event to the input.

See discussion in #877. I believe this ticket can be closed.

**Comment by pkozlowski-opensource** [comment] 2017-03-01 12:36
@gregbown I must say that I'm having hard time following your use-case and the corresponding proposal. It would be much easier to understand the current vs. desired behavior with a plunker (which we systematically require in the issue template).

I'm going to close this one as an approximate duplicate of #877 but feel free to add more info to this issue (with a plunker) if you believe that the solution proposed in #877 isn't working for you.

**Closed by pkozlowski-opensource** 2017-03-01 12:36 UTC

**Comment by gregbown** [comment] 2017-03-01 16:38
@pkozlowski-opensource The request was driven by a decision made by someone who wants to see partial match search results.  It is not an issue because I can handle the enter key as described by @deeg without a change in the code.  Thank you both, great work from everyone on this project btw!  I really like how open the components are to adding functionality, less is more.
