### ISSUE TITLE
Auto placement of Tooltips not going to the left when needed

### ISSUE THREAD

**Issue by bluecaret** [ng-bootstrap/ng-bootstrap#2465] opened 2018-06-19 21:47 UTC
### Bug description:

Scenario: Tooltip is added to a button near the top right of the screen. The tooltip has a lot of text inside it.

Bug: When you view the page with a tall window, the tooltip displays below the button, in a skinny container (not the bug I'm referring to, but still not ideal), if you then view the page in a shorter window, that tooltip no longer fits below, so it goes back to its default position on the right, instead of following the next available space which is on the left.

### Link to minimally-working plunker that reproduces the issue:

https://stackblitz.com/edit/angular-fneazi?file=app/app.component.html

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6.0.0

ng-bootstrap: 2.1.1

Bootstrap: 4.0.0

**Comment by pkozlowski-opensource** [comment] 2018-06-20 07:43
So, what is going on here is a combination of 2 things:
* what you call "skinny container" is the default max width of 200px (if I'm not mistaken) defined in Bootstrap CSS. You can override this value if it is too small for you: https://github.com/twbs/bootstrap/blob/7b2372f35319ce392cb3f6ddab7c2de879a8a354/scss/_tooltip.scss#L107-L115
* with the max width of 200px and the amount of text you are trying to fit there is not enough space when trying to put tooltip on the left (in fact there is not enough space on top, see: https://stackblitz.com/edit/angular-fneazi-bmnssj?file=app/tooltip-basic.html

All in all everything works as designed here. I understand that you are not getting results you expect. To "solve it" you need to either:
* shorten the amount of text to show (good UX imo)
* override `$tooltip-max-width` variable in Bootstrap's scss.

Closing this one as a support request since there is nothing to fix on our side.

**Closed by pkozlowski-opensource** 2018-06-20 07:43 UTC

**Comment by bluecaret** [comment] 2018-06-20 14:45
Thanks for taking a look. What I was seeing was actually less than 200px wide, but I have realized what that actually is then, because I'm floating the element, there is no room to place the element to the left because of the float, I added container="body" and now it works as I would expect! Fairly sure that is what I am doing in my project where I noticed the issue already but that does show I am missing something. 

So to anyone else that might see this, check to make sure your tooltip can actually fit in the container, the container may be smaller than you think! :)

(For the record, I agree with keeping the text in a tooltip smaller, but that is an argument I did not win...)
