### ISSUE TITLE
Transition Effect Parameter

### ISSUE THREAD

**Issue by lasharela** [ng-bootstrap/ng-bootstrap#1554] opened 2017-05-18 08:33 UTC
It will be grate to have opportunity to configure transition effect parameter.

I' want to use the same effect as it is in [normal bootstrap](https://v4-alpha.getbootstrap.com/components/carousel/) and I cant.

**Comment by pkozlowski-opensource** [comment] 2017-05-18 10:04
Duplicate of #295

**Closed by pkozlowski-opensource** 2017-05-18 10:04 UTC
