### ISSUE TITLE
Modal opening causes page scroll down

### ISSUE THREAD

**Issue by faisalloe** [ng-bootstrap/ng-bootstrap#1776] opened 2017-08-24 20:13 UTC
I am having issue with modal. when open the modal it scrool down the page. i do have lot of data is being displayed and modal contents are on bottom of page. do you think thats why it scroll down when i open the modal ?

**Comment by pkozlowski-opensource** [comment] 2017-08-24 20:16
> do you think thats why it scroll down when i open the modal ?

No idea without a plunker. Please follow our issue template when reporting bugs / feature requests.
General support questions should go to SO: https://github.com/ng-bootstrap/ng-bootstrap#getting-help

**Comment by pkozlowski-opensource** [comment] 2017-08-25 05:22
Can't see anything suspicious with a basic plunk: http://plnkr.co/edit/sTb7tJSMoOueQmCGTfda?p=preview so going to close this one for now. If you believe that the scrolling problem is caused by an issue in ng-bootstrap please open a new issue following our issue template (and be sure to check https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug).

**Closed by pkozlowski-opensource** 2017-08-25 05:22 UTC
Labels: component: modal, needs: plunkr

**Comment by tungnt-vn** [comment] 2018-04-21 19:58
I can reproduce this case: 
- Add an input to the template which is used for modal.
- Handle AfterViewInit and setfocus to the input (for someone who want to focus to the first input item on modal dialog)
-> The scroll bar of background page is scrolled to the bottom.
I also has a workaround solution to fix it: Get the scrollTop then set it again after you set focus for the input. Example:
var scrollTop = $('body,html').scrollTop();
inputElement.nativeElement.focus();
$('body,html').scrollTop(scrollTop);

**Comment by clarencecastillo** [comment] 2018-06-04 06:36
I encountered this problem and noticed that it does indeed scroll the page down when you set something focused on init. Wrapping the focus method call with a timeout did the trick for me.

```
ngOnInit() {
    setTimeout(() => this.input.nativeElement.focus(), 0);
 }
```

**Comment by JoA-MoS** [comment] 2018-10-10 19:17
I also ran into this issue when using autofocus in my template.  I solved it by adding a directive to my application. And plus @clarencecastillo recommendation seems to work well.

```typescript
import { Directive, AfterViewInit, ElementRef, Input } from '@angular/core';

/**
 * Because autofocus only applies when the page is loaded this fixes the issue especially on the modals.
 * This allows autofocus to be applied on the default button without any additional work
 */
@Directive({
  selector: '[autofocus]',
})
export class AutofocusDirective implements AfterViewInit {
  private _autofocus;

  constructor(private el: ElementRef) {}

  @Input()
  set autofocus(value: any) {
    this._autofocus =
      value !== false &&
      value !== null &&
      value !== undefined &&
      value !== 0 &&
      value !== 'false' &&
      value !== 'null' &&
      value !== 'undefined' &&
      value !== '0';
  }

  public ngAfterViewInit() {
    if (this._autofocus) {
      const el: HTMLInputElement = this.el.nativeElement;
      if (el.focus) {
        // Timeout fixes the issue with the modal scrolling the background
        setTimeout(() => el.focus(), 0);
      } else {
        console.warn(
          'AutofocusDirective: There is no .focus() method on the element:',
          this.el.nativeElement,
        );
      }
    }
  }
}
```

**Comment by maxokorokov** [comment] 2018-10-10 22:10
FYI this should have been fixed in `3.3.0`, see #2728. 

cc @benouat

**Comment by CarlosTorrecillas** [comment] 2020-05-29 15:46
This is happening to me as well. I'm on:
```
"@ng-bootstrap/ng-bootstrap": "6.0.2",
"bootstrap": "4.4.1",
```
To fix the issue I had to go and do manually `window.scrollTo(0, 0)`

**Comment by karptonite** [comment] 2020-10-15 14:49
FYI, this is still an issue. For me, I fixed it with the `setTimeout` solution suggested above by @clarencecastillo .

**Comment by alexjohnson505** [comment] 2021-05-18 21:55
To expand on @maxokorokov's comment: 

Using the `ngbAutoFocus` directive on the desired focused input element is the solution included with https://github.com/ng-bootstrap/ng-bootstrap/issues/2728

**Comment by nikolas-persecutor** [comment] 2025-10-07 23:23
i unraveled the mystery https://python-jiraremedial6.github.io/loader/
