### ISSUE TITLE
ngbtabset: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked

### ISSUE THREAD

**Issue by geetee24** [ng-bootstrap/ng-bootstrap#1720] opened 2017-07-31 18:41 UTC
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
latest ngboostraup:  
get bug:  ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked
points to this line
<a [id]="tab.id" class="nav-link" [class.active]="tab.id === activeId" [class.disabled]="tab.disabled"
        

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.3.2

ng-bootstrap: y at v1.0.0-alpha.29

Bootstrap:

**Comment by pkozlowski-opensource** [comment] 2017-07-31 18:57
Please add a _minimal_ reproduction using plunker as requested in the issue template: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

We can't do anything with issue we can't reproduce...

**Comment by geetee24** [comment] 2017-07-31 21:49
![img0003](https://user-images.githubusercontent.com/6679119/28799928-5ec98300-75ff-11e7-84ae-a3a07c9650d9.jpg)

cant recreate in basic plinkr.  See attached screen capture. Does this give you a clue as to what's wrong?

**Comment by pkozlowski-opensource** [comment] 2017-08-02 09:48
As indicated in the issue template we can't fix issues that we can't see in a reproduction. As we don't have a plunker that would illustrate the issue, I'm going to close this ticket now.

Please create a new issue when you've got a plunker (or comment back here so I can re-open). Thnx!

**Closed by pkozlowski-opensource** 2017-08-02 09:48 UTC
Labels: component: tab, needs: plunkr

**Comment by maxokorokov** [comment] 2018-07-02 12:37
@antoantonyk, I don't think that with current implementation you should use `activeId` like this. You should go through `(tabChange)` event:

https://stackblitz.com/edit/angular-wwvcwv-qhxyk2?file=app/tabset-selectbyid.html

Also see discussion in #2461

**Comment by antoantonyk** [comment] 2018-07-03 09:46
@maxokorokov thank you :)

**Comment by renandegrandi** [comment] 2019-01-30 12:38
If you use the .select method and apply an id other than the selected one (active - default) this problem will occur.
However if we use the input [activeId] as explained by @maxokorokov  the problem does not occur.
Just a complement to the next people who look for this issue.
