### ISSUE TITLE
Need custom CSS class for tooltip Component: ngbTooltip type:Feature

### ISSUE THREAD

**Issue by VirajNimbalkar** [ng-bootstrap/ng-bootstrap#1641] opened 2017-06-29 05:20 UTC
### Need custom CSS class for tool tip [Feature]

When we use default config which render to parent HTML element, here we can wrap with other 
HTML element and then we can override default CSS simply like below.
```
.myuserinfo {
  .tooltip {}
}
```
This is fine.
-----------------------------------------------------------------------------------
But when we modify rendering to body, above CSS option doesn't work, To overcome this problem we have direct option which will override all tooltip CSS just by using 
`.tooltip {}`

This is not right solution , So my request is , Can you add option in ngbTooltip to accept CSS class name as input, so it will allow to have different custom CSS for each pop up.

**Comment by pkozlowski-opensource** [comment] 2017-06-29 06:31
Duplicate of #1349

**Closed by pkozlowski-opensource** 2017-06-29 06:31 UTC

**Comment by lroura** [comment] 2021-06-30 13:10
https://stackoverflow.com/a/58709863/1998483
