### ISSUE TITLE
Timepicker popup just like Datepicker Popup

### ISSUE THREAD

**Issue by RaphiStein** [ng-bootstrap/ng-bootstrap#1933] opened 2017-11-02 21:20 UTC
NgInputDatePicker is a great directive that appends a little calendar icon to an input box and displays a calendar popup on click.

There should be a matching directive for time selection, i.e. NgInputTimePicker that displays a little time picker popup.

What do you guys think?

**Comment by pkozlowski-opensource** [comment] 2017-11-03 09:15
Duplicate of #512. Please vote on existing issues (using Github reactions).

**Closed by pkozlowski-opensource** 2017-11-03 09:15 UTC
