### ISSUE TITLE
Accordion group used 1 card, Bootstrap 4 uses separate cards

### ISSUE THREAD

**Issue by smlombardi** [ng-bootstrap/ng-bootstrap#1671] opened 2017-07-10 15:06 UTC
Styling the standard Bootstrap 4 accordions and NGB Accordions  is not consistent.

I noticed that with Bootstrap 4, every accordion pane is a card, whereas NGB uses one card:

### NG Bootstap
![screen shot 2017-07-10 at 10 58 16 am](https://user-images.githubusercontent.com/835148/28024537-fde87268-655e-11e7-9a74-0e0a1425d214.png)

### Bootstrap 4:

![screen shot 2017-07-10 at 11 00 49 am](https://user-images.githubusercontent.com/835148/28024562-19153062-655f-11e7-9c6d-dd1606d23dfd.png)

This leads to issues of having a border around each card.  Bootstrap has a border, but NGB does not, as there is no card there.

![screen shot 2017-07-10 at 10 58 44 am](https://user-images.githubusercontent.com/835148/28024677-64877de8-655f-11e7-8659-818535cc936f.png)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.2.3

ng-bootstrap: 1.0.0 alpha 26

Bootstrap: 4.0 alpha 6

**Comment by pkozlowski-opensource** [comment] 2017-07-10 15:29
Duplicate of #1050

**Closed by pkozlowski-opensource** 2017-07-10 15:29 UTC
