### ISSUE TITLE
modal window template customizing

### ISSUE THREAD

**Issue by sbelodon** [ng-bootstrap/ng-bootstrap#4299] opened 2022-03-31 08:46 UTC
Hello!
I want to use drag directives like https://github.com/xieziyu/angular2-draggable with modal window
but I need to add ngDraggable directive to <div "modal-content"> which situated inside component template

Can you allow such changes? 
Or there is a workaround?

Version with data-target + separate template is not suitable, we are calling NgbModal.open with our component(not templateRef) from angular typescript code

**Comment by maxokorokov** [comment] 2022-03-31 10:11
Duplicate of #3201

**Closed by maxokorokov** 2022-03-31 10:11 UTC
Labels: component: modal, resolution: duplicate
