### ISSUE TITLE
Tooltip gets stuck when element becomes disabled

### ISSUE THREAD

**Issue by Spodii** [ng-bootstrap/ng-bootstrap#2547] opened 2018-07-24 18:51 UTC
### Bug description:

When an element (eg button) is showing a tooltip, if that element becomes disabled, the tooltip won't go away.

Tested in latest Chrome

### Link to minimally-working plunker that reproduces the issue:

http://next.plnkr.co/edit/04De866kd6xbciXd

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6.0.0
ng-bootstrap: 2.2.0

**Comment by pkozlowski-opensource** [comment] 2018-07-24 19:05
Duplicate of #1250. tl;dr;:
* DOM events don't fire on disabled elements;
* since DOM events don't fire we are not aware of mouse events so can't show / hide tooltip;
* there is nothing we can do about it in this lib, this is how browsers work;
* there are work-arounds (more or less hacky)

**Closed by pkozlowski-opensource** 2018-07-24 19:05 UTC
