### ISSUE TITLE
Typeahead does not cancel all previous request when start a new one

### ISSUE THREAD

**Issue by changLiuUNSW** [ng-bootstrap/ng-bootstrap#1548] opened 2017-05-12 22:54 UTC
When dealing with out-of-order responses,  ```switchMap``` operator should automatically unsubscribes from previous subscriptions as soon as the outer Observable emits new values, but it does not work in NgBootstrap Typeagead. 

You can replicate in [Wikipedia search](https://ng-bootstrap.github.io/#/components/typeahead) example by setting network throttling to ```5 kb/s```(download and upload) and ```2000ms``` latency in chrome Dev tool.

<img width="959" alt="typeahead" src="https://cloud.githubusercontent.com/assets/7379922/26019649/4e4d3892-37ba-11e7-865a-bbf0b6c97267.PNG">

**Comment by pkozlowski-opensource** [comment] 2017-05-14 18:50
Yes... This is (approximate) duplicate of #723 - I'm aware of the issue and we've got a PR (#1244) - just need to review it.

Closing as a duplicate of #723

**Closed by pkozlowski-opensource** 2017-05-14 18:50 UTC
