### ISSUE TITLE
Tooltip placement incorrect when element is near edge

### ISSUE THREAD

**Issue by randspy** [ng-bootstrap/ng-bootstrap#2914] opened 2018-12-07 14:09 UTC
### Bug description:
The tooltip is not positioned properly when button is located near the edge. It is also flickering(this problem does not appear in my project, just in StackBlitz) in chrome. In firefox I can see most of the time flickering pointer icon.

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-fneazi-fzgupq

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.1.1

ng-bootstrap: 4.0.0

Bootstrap: 4.1.3

**Comment by pkozlowski-opensource** [comment] 2018-12-11 13:39
What your stackblitz reproduces is a duplicate of #2775 - it flickers since a tooltip showing up covers the button which a browser interprets as mouse being moved out of tooltip, so it closes, but then the mouse is again over the button and the whole process repeats. 

When I change to `placement="bottom"` then the flickering goes away (again, this is a separate problem) but we can see the "wrong" positioning then: https://stackblitz.com/edit/angular-fneazi-fk9cqa?file=app/tooltip-basic.html

Is this the same issue that you see in your project? I would really like to see reproduce scenario that corresponds to your project, otherwise we might be fixing the wrong thing... In any case it seems like the issue in the stackblitz linked above is due to `float: right;`

**Comment by randspy** [comment] 2018-12-12 09:22
Hi,

Thanks to your response. I am not 100% sure as in my project the tooltip moves above the button, in the stackblitz I have sent bellow. I was not able to reproduce the exact situation. But when I change in my project placement to bottom then it is displayed as in the stackblitz you send. For the issue itself when I replace the ```float: right``` with ```margin-left: 130px``` the problem still occurs (https://stackblitz.com/edit/angular-fneazi-fh7q5e?file=app/tooltip-basic.scss)

BR

**Closed** 2019-02-07 09:37 UTC
Labels: component: tooltip, needs: info

**Comment by maxokorokov** [comment] 2019-02-07 09:39
This should be fixed in `4.0.3`, but please see this → https://github.com/ng-bootstrap/ng-bootstrap/pull/2972#issuecomment-460641793. Feel free to reopen if you're still having issues.
