### ISSUE TITLE
Datepicker's `minDate` attribute is not validating keyboard input.

### ISSUE THREAD

**Issue by saiy2k** [ng-bootstrap/ng-bootstrap#1657] opened 2017-07-05 13:52 UTC
### Bug description:
Datepicker's `minDate` attribute is not validating keyboard input.
Say, I set minDate to 2017-7-20.
- Through calendar control, I am not able to set any date below 2017-7-20, which is good as intended.
- But I can type in the date 2017-7-10 through Keyboard. No validation errors happening. The date is being accepted

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/cGmJA2A0pQh6eukD1kb3?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.0.3

ng-bootstrap: 1.0.0-alpha.27

Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment] 2017-07-08 20:37
Not sure what you mean by "No validation errors happening. The date is being accepted" but if I use the plunk you've linked and I enter "2017-7-10" the field is well marked as invalid.

Could you please elaborate on expected vs. observed behaviour?

**Comment by saiy2k** [comment] 2017-07-09 08:32
> and I enter "2017-7-10" the field is well marked as invalid.
How do you know it's marked as Invalid?

Anyways, here is what I expect:
 * Since the minDate is set to `2017-7-20`, the control should never allow me to set any date below, either through the Calendar control nor through Keyboard.
 * Ideally what should happen is
   * All dates below minDate should be disabled in Calendar control, which is happening.
   * When I enter the date below minDate via Keyboard, on lost focus, it should throw some error in (ngModelChange) or something and reset to previous valid date or reset to null.
   * So the developers can catch the error and handle properly.

What I observe
 * Assuming my expectation is right, this is not happening, I can enter `2017-7-10` via Keyboard and everything works good,
 * Like the date is accepted, (ngModelChange) triggers with no problem, when I click on Calendar control, date 10 is selected, though it's disabled in the Calendar control.

Hope the explanation helps.

**Comment by pkozlowski-opensource** [comment] 2017-07-09 09:31
> How do you know it's marked as Invalid?

Just inspect the DOM and see that Angular validation CSS classes (ex.: `ng-invalid`) are added properly. This proves that the control is marked as invalid.

> When I enter the date below minDate via Keyboard, on lost focus, it should throw some error in (ngModelChange) or something and reset to previous valid date or reset to null.

The Angular way of "throw some error" is to mark control as invalid. We want to follow what is happening in Angular forms and not to invent datepicker-specific way of handing invalid input.

> So the developers can catch the error and handle properly.

Once again, you should use control's validity state to provide adequate feedback to the users.

I'm going to close this one as it works as intended.

**Closed by pkozlowski-opensource** 2017-07-09 09:31 UTC
Labels: component: datepicker, needs: info
