### ISSUE TITLE
Feature: Navigation Bar

### ISSUE THREAD

**Issue by weechong-ong** [ng-bootstrap/ng-bootstrap#1260] opened 2017-01-26 03:46 UTC
Is the navigation bar available in ng-bootstrap?
 https://v4-alpha.getbootstrap.com/examples/navbars/

**Comment by pkozlowski-opensource** [comment] 2017-01-26 13:57
Nope, as it is not needed - all you need is standard Bootstrap CSS and the collapse directive. See more details in #738.

Closing as a duplicate of #738.

**Closed by pkozlowski-opensource** 2017-01-26 13:57 UTC
Labels: resolution: duplicate
