### ISSUE TITLE
Add please .dismissAll()

### ISSUE THREAD

**Issue by peteichuk** [ng-bootstrap/ng-bootstrap#2151] opened 2018-02-09 14:52 UTC
Add, please method dismissAll()

**Comment by bastienmoulia** [comment] 2018-02-09 15:49
If it's for modal, there is already #1963.

**Comment by pkozlowski-opensource** [comment] 2018-02-10 12:51
Yes, I assume this is a duplicate of #1963

**Closed by pkozlowski-opensource** 2018-02-10 12:51 UTC

**Comment by peteichuk** [comment] 2018-02-11 10:02
Thank you!
