### ISSUE TITLE
Modal won't open correctly with ChangeDetectionStrategy.OnPush applied to root component

### ISSUE THREAD

**Issue by dmitrysteblyuk** [ng-bootstrap/ng-bootstrap#1335] opened 2017-02-24 14:30 UTC
If modal is being opened on button click, everything's alright though. But when I try to open modal on click after some delay (or for example in AfterViewInit) then it doesn't open correctly:

http://plnkr.co/edit/B9XnNV5F6VjTRrzPUZyF?p=preview

P.S. I just took basic modal example from Plunker and added changeDetection to app component

**Comment by brcpar** [comment] 2017-02-26 02:00
According to this article: https://blog.thoughtram.io/angular/2016/02/22/angular-2-change-detection-explained.html the issue is the object reference isn't changing and since you are using Push strategy, if you want it to detect non-reference changes, you have to include ChangeDetectorRef in some way.  It looks like just DI that into your component and calling the markForCheck() function, it works correctly.  Here's your example forked: http://plnkr.co/edit/LqUUcO3OroYIXPSxe7or?p=preview  I have it in a setTimeout for an example which I feel is a hack.

This appears to be much easier for observables since you can just call the markForCheck() in the subscribe.  I'm not sure of a non-hacky way other than the timeout, but maybe that can be workaround for you for now?

**Comment by dmitrysteblyuk** [comment] 2017-02-26 07:29
@brcpar, thank you! I tried to use ChangeDetectorRef.markForCheck before but wasn't so clever as to call it in setTimeout.

**Comment by pkozlowski-opensource** [comment] 2017-02-27 07:48
Sounds like a support request that got resolved so closing this one.

**Closed by pkozlowski-opensource** 2017-02-27 07:48 UTC
