### ISSUE TITLE
Modal - Error when not providing an onRejectedCb to modalRef.result

### ISSUE THREAD

**Issue by vratojr** [ng-bootstrap/ng-bootstrap#1116] opened 2016-12-06 10:02 UTC
Hello,

- Open a modal
- attach event handlers to the returned promise
- If you attach both succes and reject handlers, it's ok
- If you attach only success handler, the _first time_ that you reject the dialog (by clicking outside or pressing ESC) you got an error message: 

> core.umd.js:3462 EXCEPTION: Uncaught (in promise): 0

Example code:
```
open(content) {
    this.modalService.open(content).result.then((result) => {
      this.closeResult = `Closed with: ${result}`;
    });
  }
```

See [Plunker](http://plnkr.co/edit/kfBBgOjEbEveB6TACU4j?p=preview) example

Angular: 2.2.0
ng-bootstrap: 1.0.0.alpha-14
Bootstrap: v4-alpha

**Comment by pkozlowski-opensource** [comment] 2016-12-06 12:53
This is how promises behave in browsers (or at least in Chrome) - you can reproduce the same "issue" in pure JS - without Angular nor ng-bootstrap: http://plnkr.co/edit/o4WAcw2dwWRpmdDGggFc?p=preview

Closing as invalid.

**Closed by pkozlowski-opensource** 2016-12-06 12:53 UTC

**Comment by JohannesRudolph** [comment] 2018-03-11 17:33
Just hit the same bug and I am not sure I agree with this assesment. The typescript typing is misleading (onRejected parameter is marked as optional, when it will fail at runtime). Since ngBootstrap is meant to be an angular specific implementation, would there be a chance to make it return an Observable instead?

**Comment by tplk** [comment] 2018-04-02 14:35
Don't really understand why stick to promises when angular already uses rxjs heavily. I don't think pulling additional dependencies is going to be an issue here.

**Comment by michaeljota** [comment] 2018-05-10 20:39
I don't think that using promises is a good idea for this, or at least, the promise should not be rejected because the user dismiss the modal, I mean, this is a really weir and unexpected behavior.
