### ISSUE TITLE
Close datepicker on click outside

### ISSUE THREAD

**Issue by smartHasmukh** [ng-bootstrap/ng-bootstrap#1623] opened 2017-06-20 12:10 UTC
I have to try hide datepicker on outside click but doesn't work on my end

**Comment by pkozlowski-opensource** [comment] 2017-06-20 12:15
Duplicate of #783

**Closed by pkozlowski-opensource** 2017-06-20 12:15 UTC

**Comment by smartHasmukh** [comment] 2017-06-22 03:22
@pkozlowski-opensource 
Here is proper solutions of Datepicker hide on click outside

[Plnkr Demo](https://plnkr.co/edit/nRCpS4?p=preview)

**Comment by SagarJagodra** [comment] 2017-07-19 11:51
@smartHasmukh 
In this plunker demo if you open both the datepicker by clicking on calendar icon one by one without clicking anywhere else and then if you click outside only one calendar will be closed leaving other calendar open and you have to close it by clicking calendar icon of that calendar.
