### ISSUE TITLE
(bug, blocking) Add nullability to in NgbDateStruct, NgbDateParserFormatter, NgbDateAdapter, NgbDateNativeAdapter classes

### ISSUE THREAD

**Issue by AbakumovAlexandr** [ng-bootstrap/ng-bootstrap#2629] opened 2018-08-20 20:02 UTC
### Bug description:
The [declaration](https://github.com/ng-bootstrap/ng-bootstrap/blob/88e5e984e1b2f530aaa36b2f70f55aef393d8163/src/datepicker/ngb-date-parser-formatter.ts#L21) is as follows:
```
abstract parse(value: string): NgbDateStruct;
```
But JsDoc says:
```
They must return null if the value can't be parsed.
```
So, you just cannot implement this method in the strict mode (TS won't allow you to return a `null` from it) and you cannot add `| null` to the return type of your implementation, since you get:

> ERROR in src/app/ngb/ditat-date-parser-formatter.ts(9,12): error TS2416: Property 'parse' in type 'MyDateParserFormatter' is not assignable to the same property in base type 'NgbDateParserFormatter'.
>   Type '(value: string) => NgbDateStruct | null' is not assignable to type '(value: string) => NgbDateStruct'.
>     Type 'NgbDateStruct | null' is not assignable to type 'NgbDateStruct'.
>       Type 'null' is not assignable to type 'NgbDateStruct'.
> 

### Version of Angular, ng-bootstrap, and Bootstrap:

ng-bootstrap: 3.0.0

**Comment by pkozlowski-opensource** [comment] 2018-08-20 20:41
Thnx for reporting, will fix for the next release (to be cut this week).

**Comment by pkozlowski-opensource** [comment] 2018-08-20 20:42
BTW, we should activate strict null checks on this project...

**Comment by AbakumovAlexandr** [comment] 2018-08-20 20:48
@pkozlowski-opensource , in addition (just experienced it) nullability should be added to the types of all properties of `NgbDateStruct`, since in `NgbDateISOParserFormatter.parse()` there is code like this:
```
return {year: toInteger(dateParts[0]), month: null, day: null};
```

**Comment by AbakumovAlexandr** [comment] 2018-08-20 20:58
@pkozlowski-opensource , what do you think on activating not just `--strictNullChecks` option, but even `--strict` one?

**Comment by maxokorokov** [comment] 2018-08-24 14:54
Looks like a duplicate of #1544 and it's not only the datepicker.

**Comment by pkozlowski-opensource** [comment] 2018-08-24 14:59
Oh yes, indeed this is a duplicate of #1544. Looks like it harder than I was initially assuming...

Closing as a duplicate.

**Closed by pkozlowski-opensource** 2018-08-24 14:59 UTC
Labels: component: datepicker, type: bug
