### ISSUE TITLE
Feature request: Navbar

### ISSUE THREAD

**Issue by rolandoldengarm** [ng-bootstrap/ng-bootstrap#907] opened 2016-10-19 02:36 UTC
Navbar has not been implemented yet. Right now it requires adding jQuery, bootstrap, and tether js to get it working. Would be cool if ng-bootstrap would support it.

**Comment by pkozlowski-opensource** [comment] 2016-10-19 07:02
I believe that this is a duplicate of #738 - let's move the discussion in there (but I believe that BS4 don't have any JS logic for navbars and we are already having all the functionality needed).

Please provide more info if you believe that this is not a duplicate.

**Closed by pkozlowski-opensource** 2016-10-19 07:02 UTC

**Comment by rolandoldengarm** [comment] 2016-10-19 07:39
@pkozlowski-opensource thanks for the reply! I think the collapse is exactly what I need. Will test tomorrow morning, but it looks good.
Maybe good to add that somewhere to the documentation?
