### ISSUE TITLE
NgbModalStack dismissAll function is missing

### ISSUE THREAD

**Issue by omprakash9** [ng-bootstrap/ng-bootstrap#1245] opened 2017-01-24 03:09 UTC
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:In ui-bootstrap we use to have a $uibModalStack.dismissAll(); method to close all the opened modals throught out the application. Whereas, in ng-boostrap i didn't came across that functionality. 
Can you please make sure is it available in ng-bootstrap.

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.2.4

ng-bootstrap: 1.0.0-alpha.13

Bootstrap: 4.0.0-alpha.4

**Comment by pkozlowski-opensource** [comment] 2017-01-24 09:12
We are currently _not_ supporting stacked modals, see #643

**Comment by pkozlowski-opensource** [comment] 2017-01-24 09:12
Closing as a duplicate of #643

**Closed by pkozlowski-opensource** 2017-01-24 09:12 UTC

**Comment by CD-UNCC** [comment] 2017-11-16 19:17
what is the preferred method of closing all modals. For example when a user is logged out from being idle and still has modals open?

**Comment by omprakash9** [comment] 2017-11-16 21:41
@CD-UNCC 

I think the best way is to create a singleton service, in which use a array of object to store all the ngb modal references(in your entire application)
and create a other metod to clear all the stored modal references (like by passing/assiging an empty array) call this method on signout/logout or which ever the method you were using at the time of timeout/logout
