### ISSUE TITLE
Animation on accordian and more

### ISSUE THREAD

**Issue by vushu** [ng-bootstrap/ng-bootstrap#1385] opened 2017-03-17 14:35 UTC
This is kind of an issue since, we in our team want to use your library and give the end-user a good experience, is there future hopes of animations being available throughout this library?

**Comment by pkozlowski-opensource** [comment] 2017-03-17 14:49
Duplicate of #295. Animations are on the roadmap.

**Closed by pkozlowski-opensource** 2017-03-17 14:49 UTC
