### ISSUE TITLE
Timepicker in meridian mode not correctly display time

### ISSUE THREAD

**Issue by Yura13** [ng-bootstrap/ng-bootstrap#2123] opened 2018-01-26 18:25 UTC
### Bug description:
Inputs and model change value to correct after first entering not valid hours and minutes. But its not working after the second, third trying and so on.
This issue also related to clicking the button AM/PM.

### Link to minimally-working plunker that reproduces the issue:
![timepicker_issue](https://user-images.githubusercontent.com/17030431/35454149-87e86f90-02d5-11e8-8315-99e9414f7abc.gif)

![timepicker_issue_2](https://user-images.githubusercontent.com/17030431/35454503-fa1d35ea-02d6-11e8-8863-bb4dbe93ce71.gif)

**Comment by bastienmoulia** [comment] 2018-01-27 08:55
This bug is on all timepicker, not just for Meridian Mode.
 
This appears when the value changes to another value which is a modulo of 24 (or 12 in meridian mode)

I'm looking at this issue.

**Comment by pkozlowski-opensource** [comment] 2018-01-27 10:22
@bastienmoulia if I'm not mistaken, it is the same as #1644
@Yura13 could you please attach a plunker as well? Much easier to debug than a screencast :-)

This is a tough one since we change the display value but Angular still "tracks" old value on the binding level. Essentially we can't update binding so for Angular a value never changes.

I might be wrong here, but I can definitivelly help getting to the bottom of it, don't hesitate to ping me @bastienmoulia if needed.

**Comment by Yura13** [comment] 2018-01-27 11:51
@pkozlowski-opensource this screencasts made on the page with examples (https://ng-bootstrap.github.io/#/components/timepicker/examples)

You can use your example plunker:
https://ng-bootstrap.github.io/app/components/timepicker/demos/meridian/plnkr.html

**Comment by bastienmoulia** [comment] 2018-01-27 13:18
@pkozlowski-opensource Definitely the same as #1644

**Comment by pkozlowski-opensource** [comment] 2018-01-27 13:20
@bastienmoulia thnx for confirming. Let's close this one as a duplicate of #1644 and continue the discussion in there.

**Closed by pkozlowski-opensource** 2018-01-27 13:20 UTC
Labels: component: timepicker
