### ISSUE TITLE
Add possibility to resolve data before opening modal window

### ISSUE THREAD

**Issue by Yura13** [ng-bootstrap/ng-bootstrap#1834] opened 2017-09-08 08:45 UTC
### Bug description:

Pure angular has resolve data before changing routing.
It will be a good idea to implement this feature

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.3.6

ng-bootstrap: 1.0.0-beta.4

Bootstrap: 4.0.0-beta

**Comment by pkozlowski-opensource** [comment] 2017-09-08 08:49
> It will be a good idea to implement this feature

Why? What would be the advantage of resolving data inside a modal service as opposed to doing so in the component / service that opens up modal?

As things stand today it seems to me that moving this logic to modal would make it heavier and less flexible at the same time. So, if you believe that something should be added / changed in the modal, please provide solid arguments with real-life use-cases.

**Comment by Yura13** [comment] 2017-09-08 09:24
If you reuse modal dialogs, you need to implement getting data in every component. As for me, this logic better put into the modal dialog and you don't need to duplicate code in differents components.

**Comment by pkozlowski-opensource** [comment] 2017-09-08 09:45
> As for me, this logic better put into the modal dialog service and you don't need to duplicate code in differents components.

Then why not wrapping `NgbModalService` into your own service that would fetch data as you need? The problem with moving this (application-specific) logic to the `NgbModalService` is that you need to decide what should happen while the resolution is going on and modal is delayed. There are several options here:
* delay modal display (but then the problem is that user has no feedback after clicking on modal open as nothing happens);
* delay modal display but show some kind of progress indicator (but then a progress indicator would be application dependent);
* open a modal but don't instantiate its content (but then a user would be looking at a blank modal window);
*  open a modal, instantiate its content and provide reference to data being resolved - this would cause flickering of the modal's content.

As you can see there are many possibilities here (and I'm sure people would easily come up with even more!) and several of those possibilities are application-dependent. As such I'm not sure how we could accommodate enough flexibility in the generic `NgbModalService` service.

If you can come up with the API / design that would cover the points I'm raising here we can see what can be done on the ng-bootstrap side. But for now my feeling is that it should be handled on an application side.

**Comment by lsilva-kununu** [comment] 2017-09-13 15:28
News?

**Comment by pkozlowski-opensource** [comment] 2017-09-19 13:49
@isaacplmann I'm not sure what type of news you would expect given that my [latest comment](https://github.com/ng-bootstrap/ng-bootstrap/issues/1834#issuecomment-328057982) was left without an answer from @Yura13 .

My current position is that, based on the info I've got on my hands, the use-case initially described in this issue would be best handled in the application code and not in ng-bootstrap. Without having more elements / info I've got no choice but close this issue for now.

If you've got a similar / same use-case and you still believe that something should be added to the modals implementation on our side, please open a new issue with the clear problem description.

**Closed by pkozlowski-opensource** 2017-09-19 13:49 UTC
Labels: component: modal, needs: info, type: feature
