### ISSUE TITLE
build custom library based on ng-bootstrap with ng g library command

### ISSUE THREAD

**Issue by ycj1905** [ng-bootstrap/ng-bootstrap#2862] opened 2018-11-12 06:37 UTC
### Motivation
I am trying to build own component library based on ng-bootstrap to make others can npm install it. And I do the things as follow for new project.

1. ng g library matt, then created projects/matt
2. copy all source code from ng-bootstrap/src to projects/matt/
3. And I'll build something custom component like the demo component : NgbdModalContent 

### Bug description:
It work all well for importing the project library on my project.
`import { NgbModalModule, NgbDatepickerModule } from 'projects/matt/src/public_api';`

However, after ng build matt, then import as follow
`import { NgbModalModule, NgbDatepickerModule } from 'matt';`

will consloe errot following error
```
ERROR Error: No component factory found for NgbModalBackdrop. Did you add it to @NgModule.entryComponents?
    at noComponentFactoryError (core.js:3256)
    at CodegenComponentFactoryResolver.push../node_modules/@angular/core/fesm5/core.js.CodegenComponentFactoryResolver.resolveComponentFactory (core.js:3291)
    at NgbModalStack.push../projects/matt/src/lib/modal/modal-stack.ts.NgbModalStack._attachBackdrop (modal-stack.ts:89)
    at NgbModalStack.push../projects/matt/src/lib/modal/modal-stack.ts.NgbModalStack.open (modal-stack.ts:62)
    at NgbModal.push../projects/matt/src/lib/modal/modal.ts.NgbModal.open (modal.ts:25)
    at AppComponent.push../src/app/app.component.ts.AppComponent.open (app.component.ts:16)
    at Object.eval [as handleEvent] (AppComponent.html:26)
    at handleEvent (core.js:10251)
    at callWithDebugContext (core.js:11344)
    at Object.debugHandleEvent [as handleEvent] (core.js:11047)
```

### My Issued sourcecode Link
https://github.com/ycj1905/ng-bootstrap-issue

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 6.1.0

ng-bootstrap: 3.3.1

Bootstrap: 4.0.0

**Comment by pkozlowski-opensource** [comment] 2018-11-12 12:59
I'm sorry but this is a support question beyond the scope of what we can reasonably support here. If you building a library on top of ng-bootstrap we are expecting you to act as a fellow developer and be able to investigate issues like this.

We are happy to fix any bugs / add flex points to ng-bootstrap but you would have to be much more precise in root cause analysis. I'm going to close this issue due to the above but feel free to open more focused / dedicated questions.

**Closed by pkozlowski-opensource** 2018-11-12 12:59 UTC
