### ISSUE TITLE
NgbTimepicker - When meridian is true: error Cannot read property 'hour' of undefined

### ISSUE THREAD

**Issue by jchewitt** [ng-bootstrap/ng-bootstrap#1106] opened 2016-12-02 07:08 UTC
Under timepicker.ts you'll see that **model** isn't initialized, only declared. Model is essentially undefined until angular2 initiates the binding with ControlValueAccessor and writeValue() is called.

```
export class NgbTimepicker implements ControlValueAccessor,
    OnChanges {
  disabled: boolean;
  model: NgbTime;
```

I'm not sure why it's working in your demo, however I can only assume that something has changed between versions and this fix will be needed as I'm on the latest (2.2.0) Also doesn't work with (2.0.2).

If you'll notice below that we don't hold model accountable when trying to access parameters from it until we get to checking if meridian is true.

```
            <input type="text" class="form-control" maxlength="2" size="2" placeholder="MM"
              [value]="formatMinSec(model?.minute)" (change)="updateMinute($event.target.value)" 
              [readonly]="readonlyInputs" [disabled]="disabled">
          </td>
          <template [ngIf]="seconds">
            <td>&nbsp;:&nbsp;</td>
            <input type="text" class="form-control" maxlength="2" size="2" placeholder="SS"
              [value]="formatMinSec(model?.second)" (change)="updateSecond($event.target.value)" 
              [readonly]="readonlyInputs" [disabled]="disabled">
          </template>
          <template [ngIf]="meridian">
            <td>&nbsp;&nbsp;</td>
            <td>
              <button type="button" class="btn btn-outline-primary" (click)="toggleMeridian()">{{model.hour >= 12 ? 'PM' : 'AM'}}</button>
```

I believe we need to soak up the undefined reference by treating the model as possibly undefined if the meridian is set to true. Currently we're expecting there to be an hour key on a possibly defined object and that doesn't work since model isn't set on class initiation, only when a change to the model is made and detected through controlvalueaccessor.

**Comment by alex321** [comment] 2016-12-02 12:06
@jchewitt  Could you please submit a minimal plnkr demonstrating what is going wrong. It is hard to replicate and understand what exactly the problem is. I believe that `writeValue` is called by angular on initialisation as well.

**Comment by pkozlowski-opensource** [comment] 2016-12-02 17:42
@jchewitt as commented by @alex321 please provide a plunker with a minimal reproduction scenario, otherwise this one is hardly actionable. Here is why: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

**Comment by dudleycodes** [comment] 2016-12-09 03:42
I'm having the same issue with Angular 2.2.3.

Cannot provide a plunker as they do not support anything above Angular 2.0.0.

**Comment by pkozlowski-opensource** [comment] 2016-12-14 14:12
@jchewitt I can't reproduce this in plunker with the latest Angular 2.3.0: http://plnkr.co/edit/X5SRmhv1zU1yHVdYxeJE?p=preview please modify this plunker to expose the issue if you still see it in your application.

@dudleycodes not sure what / who you mean by "they" in your comment:

> Cannot provide a plunker as they do not support anything above Angular 2.0.0.

In any case you _can_ create a plunker with _any_ version of Angular. Here is one using 2.2.3 where I can't reproduce the issue either: http://plnkr.co/edit/pj0R7Uv41O3qsPsI0X3Z?p=preview

I'm going to close this one as "can't reproduce" but if you guys still hit problems in your apps please use one of the above plunkers to reproduce this issue. Unfortunately we can't fix things we can't reproduce: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

**Closed by pkozlowski-opensource** 2016-12-14 14:12 UTC
Labels: component: timepicker, needs: investigation, needs: plunkr

**Comment by shibulijack** [comment] 2017-01-08 17:25
I'm facing the same issue, but not able to reproduce it in plunker. Weird. 

For what it's worth, here's the error log:
```
Error: Uncaught (in promise): Error: Error in ./NgbTimepicker class NgbTimepicker - inline template:52:95 caused by: Cannot read property 'hour' of undefined
TypeError: Cannot read property 'hour' of undefined
    at View_NgbTimepicker5.detectChangesInternal (component.ngfactory.js:751)
    at View_NgbTimepicker5.AppView.detectChanges (view.js:425)
    at View_NgbTimepicker5.DebugAppView.detectChanges (view.js:620)
    at ViewContainer.detectChangesInNestedViews (view_container.js:67)
```

**Comment by zszep** [comment] 2017-02-03 13:35
I can confirm the above mentioned problem. When meridian is set to true, I get the following message: " Uncaught (in promise): Error: Error in ./NgbTimepicker class NgbTimepicker - inline template:55:43 caused by: Cannot read property 'hour' of undefined". When setting meridian to false, the error is gone. I am using angular 2.4.6 and ng bootstrap 1.0.0-alpha.19.

**Comment by zszep** [comment] 2017-02-03 14:22
Setting the meridian to false in the html and then setting it to true in the OnInit method is a workaround for the problem that works.

**Comment by pkozlowski-opensource** [comment] 2017-02-03 14:25
@zszep there must be a way of reproducing it, I can't imagine that such obvious bug is slipping in here... Maybe it is a very specific version of Angular? Or usage of another 3rd party library? We want to fix a bug if there is one here but without a reproduce we are stabbing in the dark and can't fix it properly (as we can't write an associated test...).

So, the best way of having it resolved fast would be to really try to narrow it down and reproduce in a plunker...

**Comment by kumarlalapet** [comment] 2017-04-26 05:26
I started facing the same error under the following conditions

1) Component is under a form tag hence provided name attribute for the ngb-timepicker
2) Meridian is true

Worked for me when meridian is true and NOT under form tag and no name attribute was provided in the ngb-timepicker component. Not sure if this helps.

My workaround now is using [ngModelOptions]="{standalone: true}" so this is not processed by form.

**Comment by pkozlowski-opensource** [comment] 2017-04-26 06:33
@kumarlalapet we _really_ need a plunker: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by esistgut** [comment] 2017-07-21 17:25
Can anyone provide a working workaround for this?

**Comment by pkozlowski-opensource** [comment] 2017-07-21 17:49
@esistgut sure, I would _love_ to "fix" it: just please open a new issue with a _minimal_ reproduce scenario so we can understand the issue, fix it and add a test that would prevent the issue in the future. Thnx!

**Comment by esistgut** [comment] 2017-07-21 17:55
http://plnkr.co/edit/5pQE9DcqgcpJDmpPUI0f this plunker seems to correctly show the issue.

**Comment by pkozlowski-opensource** [comment] 2017-07-21 18:01
@esistgut yes, please, open a new issue as I for me it looks like a different from the one initially discussed here.

**Comment by jchewitt** [comment] 2017-07-21 19:27
It's the same issue :)
