### ISSUE TITLE
Bug: Iphone Datepicker in a popup select year/month

### ISSUE THREAD

**Issue by ronjb04** [ng-bootstrap/ng-bootstrap#3091] opened 2019-03-28 11:03 UTC
Simply open https://stackblitz.com/angular/degedjrgvok in any iphone device and try selecting the year or month select option.. it doesn't open the default select in iphone. In android the select works fine.

**Comment by maxokorokov** [comment] 2019-03-28 11:33
@ronjb04 thanks for reporting it, duplicate of #3079, should be fixed in `4.1.1` hopefully this week.

**Closed by maxokorokov** 2019-03-28 11:33 UTC
Labels: component: datepicker, resolution: duplicate
