### ISSUE TITLE
Let developers choose their own date format

### ISSUE THREAD

**Issue by bb128b** [ng-bootstrap/ng-bootstrap#2150] opened 2018-02-09 10:48 UTC
### Bug description:

Currently, there is no way to set the format of the date stored in the object without writing some kind of custom date parsing function and applying it to the model as it is a form control and cannot use pipes. It currently saves the date as {year:2000,month:1:day:6}. I don't know why it is done this way as most libraries store the date as a Date() object or just a string with "2000-01-06" which is easy to convert using moment() and send off to a back-end API. It seems un-natural to store a date as a 3-keyed JSON object.

Could somebody please write a pull-request to let users choose a date format that isn't just a display value but also as the ngModel value.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/pvV83A649HbzonGQdOa5?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.1.3
ng-bootstrap: 1.0.0-beta.9
Bootstrap: 4.0.0

**Comment by nkm8** [comment] 2018-02-14 17:10
I think this request closely relates (if not duplicates) several other open issues:
https://github.com/ng-bootstrap/ng-bootstrap/issues/1977
https://github.com/ng-bootstrap/ng-bootstrap/issues/1979
https://github.com/ng-bootstrap/ng-bootstrap/issues/2140
https://github.com/ng-bootstrap/ng-bootstrap/issues/754
https://github.com/ng-bootstrap/ng-bootstrap/issues/545

A feature was recently added to cover most of these requests.  See https://ng-bootstrap.github.io/#/components/datepicker/examples under 'Custom date adapter'

However, my question is why require custom code?  Using a native JS Date model is an arguably common use case.  Instead of requiring everyone to copy/paste the code from the example into their respective code bases, this should be integrated directly into ng-bootstrap.

As an alternative, I am currently using native HTML5 date inputs combined with https://github.com/JohannesHoppe/angular-date-value-accessor to achieve the same end result.  I like this approach because it only requires a single attribute on the input field. 

If/when this is added as a native feature in ng-boostrap, it will be extremely nice to get the added styling and functional sugar that ngb-datepicker adds.

**Comment by maxokorokov** [comment] 2018-02-22 13:47
@nkm8, that's exactly the plan to use native date by default and be able to change it if necessary

Duplicate of #754, #1977

**Closed by maxokorokov** 2018-02-22 13:47 UTC
Labels: resolution: duplicate
