### ISSUE TITLE
Stacked modal - Closing child modal closes parent modal.

### ISSUE THREAD

**Issue by kevinkhagan** [ng-bootstrap/ng-bootstrap#3642] opened 2020-03-10 19:53 UTC
When using stacked modals, closing child modal automatically closes parent modal. tried the example in the doc but still getting same behaviour

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 9+

ng-bootstrap: 6.0.0

Bootstrap:4.4.1

**Comment by benouat** [comment] 2020-03-13 15:43
Hey @kevinkhagan what do yo mean by

> tried the example in the doc but still getting same behaviour

Do you mean that demo -> https://ng-bootstrap.github.io/#/components/modal/examples#stacked

Because if it's the case, I can't reproduce what you describe. Closing child only closes the child...

**Comment by benouat** [comment] 2020-03-16 16:03
According to our documentation [You think you've found a bug](
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug) could you please reproduce your scenario in a minimalist Stackblitz in order for us to start working on it ?

**Comment by benouat** [comment] 2020-04-15 08:45
Closing as no StackBlitz. Don't hesitate to re-open, with a StackBlitz this time 😉

**Closed by benouat** 2020-04-15 08:45 UTC
Labels: component: modal, needs: stackblitz
