### ISSUE TITLE
Problems using accordion inside accordion with Angular 4

### ISSUE THREAD

**Issue by JoseDRojasA** [ng-bootstrap/ng-bootstrap#1433] opened 2017-04-04 12:49 UTC
I need to use an accordion with other accordions inside. When i was using Angular 2, i worked perfect but when i update to angular 4 using angular-cli 1.0, It stops working.

Here is the code:

```

<ngb-accordion>
    <ngb-panel title="First panel">
        <template ngbPanelContent>
            <ngb-accordion>
                <ngb-panel id="1" title="First panel">
                    <template ngbPanelContent>
                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird
                        on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table,
                        raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                    </template>
                </ngb-panel>
            </ngb-accordion>
        </template>
    </ngb-panel>
</ngb-accordion>

```

**Comment by mohammedzamakhan** [comment] 2017-04-04 13:02
Try to use ng-template instead of template.

**Comment by pkozlowski-opensource** [comment] 2017-04-04 13:10
Please provide a minimal reproduce scenario using plunker as requested in the issue template, otherwise this one is not actionable and will be closed: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by readme42** [comment] 2017-04-04 14:55
This problem is not restricted to nested accordions, it occurs here with non nested accordions with angular 4.0.1 and ng-bootstrap alpha 22

@mohammedzamakhan sadly it does not fix it - it breaks everything. It seems that ngbPanelTitle / ngbPanelContent is not working with "ng-template".

**Comment by readme42** [comment] 2017-04-04 15:12
@mohammedzamakhan 
First Plunkr showing accordion not working with ng-template. http://plnkr.co/edit/EBUBLPGNxXAlw9KWrXQD?p=preview

In this plunkr are two accordion panels, one with template, another with ng-template. Only the "template"-one is working.

**Comment by readme42** [comment] 2017-04-04 15:37
I've "purged" ;) my comments a little. At the first moment i thougt i ran into the same issue, but now it seems different.
I will investigate more time tomorrow and will open another issue. In short: when placing a custom component into an accordion and the custom component is doing something like "throw new Error(...)", angular crashes without and console output.

**Comment by readme42** [comment] 2017-04-04 15:45
@JoseDRojasA i created a plunkr for you which shows nested accordions in angular2.4.1. I cant get them to work, the nested panel title disappears after clicking: 
http://plnkr.co/edit/1cZzIEulupwmXBtshP5u?p=preview

**Comment by pkozlowski-opensource** [comment] 2017-04-04 15:48
I guess we should update [selectors](https://github.com/ng-bootstrap/ng-bootstrap/blob/3ec38c42465f15118898d2f1523b5476207509f4/src/accordion/accordion.ts#L31) to allow `<ng-template>` as well. But I wonder if this makes sense at this point as we are planning to move to Angular 4.x soon (in the next-next-alpha) so I'm not sure it is worth to support both forms.

I'm going to tentatively mark it as an approximate duplicate of #1337

**Comment by pkozlowski-opensource** [comment] 2017-04-04 15:49
As a work-around please keep using `<template>` for now.

**Comment by pkozlowski-opensource** [comment] 2017-04-05 15:50
Plan for the complete switch to Angular 4 here: #1439

**Comment by JoseDRojasA** [comment] 2017-04-27 03:35
I updated my project to Angular 4.1.0 and ng-bootstrap 1.0.0-alpha.25. I changed all templates to ng-template but when i tried to use an accordion with another accordion inside again, the issue persisted.

**Comment by alexandernst** [comment] 2017-05-01 12:16
Pretty much the same things happens with nested tabs: http://plnkr.co/edit/Gu36tzIlg35DNikjR8kt?p=preview

**Comment by pankajparkar** [comment] 2017-05-02 16:37
Here is work around for nested tab by using extra template http://stackoverflow.com/a/43720470/2435473

**Comment by pkozlowski-opensource** [comment] 2017-05-05 08:11
OK, so yesterday I've spent some time with Tobias from the Angular team debugging this issue. It turns out that the root cause is a bug in Angular's handling of queries. I've opened an issue to track resolution of Angular's bug here: https://github.com/angular/angular/issues/16568

Ultimately the solution for this problem will come from https://github.com/angular/angular/issues/16568 but till it is fixed on the Angular side you can use a work-around from http://stackoverflow.com/a/43720470/2435473 (thnx @pankajparkar)

**Comment by JrPribs** [comment] 2017-05-31 16:44
Another solution I found is to wrap the inner accordion in another component, which would essentially do behind the scenes what the previous workaround does.

**Comment by pkozlowski-opensource** [comment] 2017-07-26 07:54
This should be fixed on the Angular side via https://github.com/angular/angular/pull/18326

**Comment by pkozlowski-opensource** [comment] 2017-08-22 14:57
This just got fixed in Angular via https://github.com/angular/angular/pull/18326 so closing it here.

**Closed by pkozlowski-opensource** 2017-08-22 14:57 UTC
Labels: blocked: Angular issue, component: accordion, component: tab, type: bug

**Comment by pkozlowski-opensource** [comment] 2017-08-26 08:47
Angular `4.3.6` contains a fix for this issue.
