### ISSUE TITLE
Tooltip still showing when button becomes disabled

### ISSUE THREAD

**Issue by Yura13** [ng-bootstrap/ng-bootstrap#1975] opened 2017-11-20 16:46 UTC
### Bug description:
Tooltip still showing when the button becomes disabled after clicking on this button. 
If tooltip will close automatically, it will be great, because i need manually close this tooltip after clicking on the button.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/UH4bAK?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.3.6

ng-bootstrap: 1.0.0-beta.5

Bootstrap: 4.0.0-beta

**Comment by pkozlowski-opensource** [comment] 2017-11-20 18:33
Duplicate of #1250 
If you've got ideas on how to work-around it in this library, please continue the discussion in #1250

**Closed by pkozlowski-opensource** 2017-11-20 18:33 UTC
