### ISSUE TITLE
NPM Shrinkwrap Fails with Angular 5 (peer dependencies)

### ISSUE THREAD

**Issue by justin-ruffin** [ng-bootstrap/ng-bootstrap#1985] opened 2017-11-23 23:54 UTC
### Bug description:

NPM Shrinkwrap fails because of the following peer dependencies.

<pre>
<code>
npm WARN @ng-bootstrap/ng-bootstrap@1.0.0-beta.5 requires a peer of @angular/core@^4.0.3 but none was installed.
npm WARN @ng-bootstrap/ng-bootstrap@1.0.0-beta.5 requires a peer of @angular/common@^4.0.3 but none was installed.
npm WARN @ng-bootstrap/ng-bootstrap@1.0.0-beta.5 requires a peer of @angular/forms@^4.0.3 but none was installed.
</code>
</pre>

### Link to minimally-working plunker that reproduces the issue:

N/A

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.0.2

ng-bootstrap: 1.0.0-beta.5

Bootstrap: 4.0.0-beta.2

**Comment by pkozlowski-opensource** [comment] 2017-11-24 09:20
Duplicate of #1938 - we will be releasing an updated version this week.

**Closed by pkozlowski-opensource** 2017-11-24 09:20 UTC
