### ISSUE TITLE
 [destroyOnHide]="false" load only selected tab at a time and load every tab only one 

### ISSUE THREAD

**Issue by dhavalsolanki** [ng-bootstrap/ng-bootstrap#3511] opened 2019-12-09 13:51 UTC
Hello, 
I am using ngb-tabset  i have a requirement that every tab should be loaded only one. So for that i got a solution of  [destroyOnHide]="false", but when i am using that option all tabs are loading when page is loaded. I want a functionality that when particular tab is selected only that time tab must me loaded and once a tab is loaded it wont be loaded second time.

**Comment by maxokorokov** [comment] 2019-12-12 15:51
Thanks for the suggestion, it looks like a duplicate of #2154 to me though.

**Closed** 2019-12-12 15:52 UTC
Labels: component: tab, resolution: duplicate
