### ISSUE TITLE
angular 4 compatibility

### ISSUE THREAD

**Issue by eddy-geek** [ng-bootstrap/ng-bootstrap#1392] opened 2017-03-21 13:55 UTC
### Bug description:

See *how to reproduce* below. The issue is that currently the generated package.json has:

    "peerDependencies": {
      "@angular/common": "^2.0.0",
      "@angular/compiler": "^2.0.0",
      "@angular/core": "^2.0.0",
      "@angular/forms": "^2.0.0"
    },

which is too restrictive - according to the [official docs](https://nodejs.org/en/blog/npm/peer-dependencies/) :

> One piece of advice: peer dependency requirements, unlike those for regular dependencies, should be lenient

*Note*: this is a follow-up to https://github.com/ng-bootstrap/ng-bootstrap/pull/1390 which is indeed wrong - I didn't know the package.json was autogenerated and changed the actual dependencies (because I was looking at using the fork directly as a dependency of my project), but the issue remains.

*Note2*: by using `"^2.0.0 || >=4.0.0-beta <5.0.0",` you would still be supporting 2.x.

### How to reproduce the issue:

```bash
npm install -g @angular/cli
ng new ngcli-ng4 --ng4
cd ngcli-ng4
npm install --save ng-bootstrap
```
output
```
ngcli-ng4@0.0.0 /ything/projects/tmk/tmp/ngcli-ng4
├── UNMET PEER DEPENDENCY @angular/common@4.0.0-rc.5
├── UNMET PEER DEPENDENCY @angular/compiler@4.0.0-rc.5
├── UNMET PEER DEPENDENCY @angular/core@4.0.0-rc.5
├── UNMET PEER DEPENDENCY @angular/forms@4.0.0-rc.5
├─┬ ng-bootstrap@1.1.16-1
│ └── moment@2.15.1
└── UNMET PEER DEPENDENCY zone.js@0.7.8

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @angular/core@4.0.0-rc.5 requires a peer of zone.js@^0.8.4 but none was installed.
npm WARN ng-bootstrap@1.1.16-1 requires a peer of @angular/common@^2.0.0 but none was installed.
npm WARN ng-bootstrap@1.1.16-1 requires a peer of @angular/compiler@^2.0.0 but none was installed.
npm WARN ng-bootstrap@1.1.16-1 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN ng-bootstrap@1.1.16-1 requires a peer of @angular/forms@^2.0.0 but none was installed.
```

### Versions

* npm 3.10.10
* Angular: 4.0.0-rc.5
* ng-bootstrap: 1.1.16

**Comment by pkozlowski-opensource** [comment] 2017-03-21 14:07
Yep, we should relax this range. Will do it in the upcoming release.

**Comment by pkozlowski-opensource** [comment] 2017-03-21 15:47
Detailed list of tasks:
- [ ] - bump up node.js version - #1393
- [ ] - fix rating widget to be compatible with Angular 4.x - this requires investigation as it seems to be a regression in the Angular 4.x itself
- [ ] - fix the "critical dependency" warning in core-js / WebPack
- [ ] - argue about removing warnings when using the `<template>` element
- [ ] - make `peerDependencies` compatible with 4.x

**Comment by maxokorokov** [comment] 2017-03-23 17:06
@pkozlowski-opensource I'm also getting a very strange issue with AoT build in a project with 

```
node: 6.10.0
typescript: 2.1.6
@angular/cli: 1.0.0-rc.4
@angular: 4.0.0-rc.6
```

Webpack fails with a strange error about `toString()` function from `utils.ts`

```
Could not resolve module 'function toString() { [native code] }' relative to file /Users/mokorokov/Dev/ng2/quickstart/node_modules/@ng-bootstrap/ng-bootstrap/util/util.d.ts

... 

ERROR in m.replace is not a function

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory'
```

**Comment by pkozlowski-opensource** [comment] 2017-03-24 08:47
OK, seems like all the issues on the Angular side are fixed in the 4.0.0 final, I got ng-bootstrap working perfectly fine with 2.3.1+ and 4.0.0 locally (both JIT and AOT). Cutting a release that will relax peer dependencies range right now.

**Closed** 2017-03-24 09:20 UTC
Labels: type: build

**Comment by eddy-geek** [comment] 2017-03-24 13:09
confirmed working on my side. right on time for final ;-)

**Comment by pkozlowski-opensource** [comment] 2017-03-24 13:57
> confirmed working on my side. right on time for final

Yup, there were few regressions in RCs so we've helped track it down and fix on the Angular side. All good in final :-)
