### ISSUE TITLE
beta 6 release not fixed warning with peer dependencies in angular 5.

### ISSUE THREAD

**Issue by rocky6** [ng-bootstrap/ng-bootstrap#2006] opened 2017-12-01 17:36 UTC
### Bug description:

beta 6 release not fixed warning with peer dependencies in angular 5.

npm WARN @ng-bootstrap/ng-bootstrap@1.0.0-beta.6 requires a peer of @angular/core@^4.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-bootstrap/ng-bootstrap@1.0.0-beta.6 requires a peer of @angular/common@^4.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-bootstrap/ng-bootstrap@1.0.0-beta.6 requires a peer of @angular/forms@^4.0.3 but none is installed. You must install peer dependencies yourself.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.0.4

ng-bootstrap: 1.0.0-beta.6

Bootstrap: 4.0.0-beta.2

**Comment by pkozlowski-opensource** [comment] 2017-12-01 18:32
> beta 6 release not fixed warning with peer dependencies in angular 5.

Of course not, as it wasn't the intention. This will be part of beta.7 (via 01e8690c2958575ae4f23599a158e7fff83dde28).

Closing as a duplicate of #1938 (fixed in master but not released yet).

**Closed by pkozlowski-opensource** 2017-12-01 18:32 UTC
