### ISSUE TITLE
ngbDatepicker loads 28th April 2018 when field gets focus with mouse click!

### ISSUE THREAD

**Issue by dotNetAthlete** [ng-bootstrap/ng-bootstrap#2866] opened 2018-11-12 17:11 UTC
Could someone please explain where on earth this date is coming from ???

**Comment by pkozlowski-opensource** [comment] 2018-11-13 15:21
> Could someone please explain where on earth this date is coming from ???

Sure, as soon as we've got a minimal reproduce scenario: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by dotNetAthlete** [comment] 2018-11-13 15:45
If you are sure what is causing this bug, then why do I need a reproduce scanario?

**Comment by pkozlowski-opensource** [comment] 2018-11-13 15:57
> If you are sure what is causing this bug, then why do I need a reproduce scanario?

* I'm definitively not sure if this is a bug;
* I'm not sure what is the scenario;
* we systematically require reproduce scenario to be able to help you and other users in a meaningful way.

I'm really sorry but we really can't do much without a minimal reproduce scenario for the reasons explained in  https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by benouat** [comment] 2018-11-19 12:58
It's been 6 days and as mentioned by @pkozlowski-opensource previously, without a reproducible scenario, we can't investigate.

So closing for now. Feel free to reopen with a corresponding stackblitz.

**Closed by benouat** 2018-11-19 12:58 UTC
Labels: component: datepicker, needs: info, needs: stackblitz
