### ISSUE TITLE
Compile errors while enabled strictNullChecks 

### ISSUE THREAD

**Issue by schwitin** [ng-bootstrap/ng-bootstrap#3365] opened 2019-09-16 08:11 UTC
### Bug description:
The following code doesn't compile if the compiler option strictNullChecks is true:

`
export class MyDateParserFormatter extends NgbDateParserFormatter {
  format(date: NgbDateStruct): string {
    return '';
  }

  parse(value: string): NgbDateStruct {
    return null;
  }
}

`

ERROR in src/app/shared/components/date-picker/my-date-parser-formatter.ts:46:5 - error TS2322: Type 'null' is not assignable to type 'NgbDateStruct'.

Angular: 8.2.3

ng-bootstrap: "@ng-bootstrap/ng-bootstrap": "^5.1.0",

Bootstrap: "bootstrap-scss": "^4.3.1",

**Comment by peterblazejewicz** [comment] 2019-09-23 20:14
seems to be an old issue, nor only related to NgbDateStruct:
#1544

Here is a quick workaround you could use with strict null type checks here (and with any other 3rd party lib). It applies to .ts files, this cannot be applied to .html error in external libraries:

- in your `src` app create `@types` directory
- create a file to augment defintion, here `ngb-date-parser-formatter.d.ts`
- override source defintions with:

```ts
import { NgbDateStruct } from '@ng-bootstrap/ng-bootstrap';

declare module '@ng-bootstrap/ng-bootstrap' {
  export abstract class NgbDateParserFormatter {
    parse(value: string): NgbDateStruct | null;
    format(date: NgbDateStruct): string | null;
  }
}
```
This assumes you're using default `tsconfig.app.json`.
After this change you should have no erros, including aot production code :)

**Comment by maxokorokov** [comment] 2019-11-15 21:49
Duplicate of #1544

**Closed by maxokorokov** 2019-11-15 21:49 UTC
Labels: component: datepicker, resolution: duplicate
