### ISSUE TITLE
Add html content to bottom of DatePicker

### ISSUE THREAD

**Issue by skendrot** [ng-bootstrap/ng-bootstrap#1387] opened 2017-03-19 04:28 UTC
### Feature description: Add ability to add content to bottom of calendar view

Would be great to allow the capability to add content to the bottom of the calendar view.

Example:
Add a checkbox to override the minimum date:
![image](https://cloud.githubusercontent.com/assets/1594689/24078126/2309cbca-0c2a-11e7-8c5f-b252d9c29c21.png)

**Comment by pkozlowski-opensource** [comment] 2017-03-19 17:59
This is an "approximate duplicate" of #1197 in the sense that #1197 talks about adding new functionality to datepicker's footer. We just don't want to add a separate config option for each and every button that could be added to the footer - this would quickly "explode" public API.

What we would like to do instead is to provide people with ability to provide a template that would be inserted as a custom footer.

I'm going to close this one as a duplicate of  #1197 - could you please comment in there with your precise use-case (I'm not sure what you would like to achieve via "Override minimum date" exactly). I'm also going to move parts of this comment over to #1197

**Closed by pkozlowski-opensource** 2017-03-19 17:59 UTC

**Comment by skendrot** [comment] 2017-03-20 02:21
This request is a broad request to allow any content to the bottom. The example given is just an example of adding some content to the bottom. This example would allow for removing the minimum date on the DatePicker by triggering a method in your angular code that would clear the MinDate.
