### ISSUE TITLE
ngb-datepicker-navigation button styling

### ISSUE THREAD

**Issue by gergely-kovacs** [ng-bootstrap/ng-bootstrap#1928] opened 2017-11-01 13:48 UTC
### Bug description:

The 'btn' class is missing on the navigation buttons in the ngb-datepicker-navigation component.
So the classes shoul be 'btn btn-link' instead of just 'btn-link' in my opinion. This makes it looks like it's a windows 95 button.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.2.4

ng-bootstrap: ^1.0.0-beta.5

Bootstrap: ^4.0.0-beta.2

**Comment by pkozlowski-opensource** [comment] 2017-11-02 14:11
Duplicate of #1925, already fixed in master, will be part of the next release.

**Closed by pkozlowski-opensource** 2017-11-02 14:11 UTC
