### ISSUE TITLE
Datepicker bug in firefox browser

### ISSUE THREAD

**Issue by Tolitech** [ng-bootstrap/ng-bootstrap#1615] opened 2017-06-12 23:49 UTC
Hello.
I found a bug when using the datepicker component.

Using the firefox version, the month of October is displayed with the incorrect days.

I've tested on Edge and Chrome and both are working properly.
My version of Firefox is Developer Edition.

I created a Plunker with the reproduction that occurs in Firefox and also has the image of the problem.
[https://embed.plnkr.co/4WvupnKyZQ8t5oFn1G4l/](https://embed.plnkr.co/4WvupnKyZQ8t5oFn1G4l/)

Image:
[http://www.codegenerator.com.br/images/error.png](http://www.codegenerator.com.br/images/error.png)

**Comment by maxokorokov** [comment] 2017-06-15 13:40
Hey, @Tolitech.

Unfortunately you're plunkr is not working (anymore?) for me

However the demos from the site https://ng-bootstrap.github.io/#/components/datepicker are opening fine in plunker for me with Firefox Developer 55.0b1 on MacOS

Could you please check your plunker?

**Comment by Tolitech** [comment] 2017-06-15 20:06
Hi, @maxokorokov.
Thanks for the answer.

Unfortunately the bug also occurs on the demo site.
I am using windows 10.

I downloaded now the latest version of firefox (54.0) and the problem is the same.
In October the days are incorrect.

Image of the demo site:
[http://www.codegenerator.com.br/images/ff-error.png](http://www.codegenerator.com.br/images/ff-error.png)

Thank you.

**Comment by pkozlowski-opensource** [comment] 2017-06-15 20:18
I can't reproduce despite trying several OSX machines:
<img width="1440" alt="screen shot 2017-06-15 at 22 16 21" src="https://user-images.githubusercontent.com/973550/27200023-718fd53a-5218-11e7-876a-b2f117e933d5.png">

@Tolitech are you sure that you are not having any FFox extensions installed? Did you try to reproduce in the incognito mode?

Also, what is your timezone setting?

**Comment by Tolitech** [comment] 2017-06-15 21:07
@pkozlowski-opensource
 
I believe it's only in Firefox versions of Windows.
I have a virtual machine on Azure and I just installed Firefox again.
There was only Chrome.

I installed 64-bit version.
Same problem as 32 bit version on my machine.

I'm in São Paulo, Brazil, UTC -3:00
The virtual machine I tested is in the United States, but I can not remember exactly which region.

I'm trying to figure out some website that will emulate firefox in MacOS and Windows to know if the problem only occurs in Windows.

I do not have any extensions installed.

I'm going to try to find out something else to help, but for all indications, for now it would be the windows version.

![sem titulo](https://user-images.githubusercontent.com/20425889/27201798-619feb24-51f5-11e7-80c0-3d5294e8e2cb.png)

**Comment by maxokorokov** [comment] 2017-06-16 08:15
Took a look in different VMs with FF Dev 54.0a2 32-bit on SauceLabs. 
All Windows 7, 8.1 and 10 look OK.
Machines are in GMT.

So still can't reproduce for now...

**Comment by ymeine** [comment] 2017-06-30 15:21
So, I tested with several configurations, and here's __where I reproduced__ the bug: 

|               |Windows 10 (VM)|Window 7 (real)|
|:---------:|:-----------------:|:---------------:|
|UTC-3:00|:heavy_check_mark:|:x:                   |
|UTC        |:x:                         |:x:                      |

I didn't investigate further yet, but the result lets think it seems to be a bug linked to the implementation of time on Windows 10 (maybe 8 too).

## Procedure to reproduce the test

- launch a Windows machine with the proper Firefox installed
- configure the timezone
    - either using the OS settings
    - or by setting the environment variable `TZ` to the value `GMT+3:00` (__syntax and inverted sign are important__)
- launch Firefox
- check in the Dev Tools that the timezone offset is `180` by running the code `(new Date()).getTimezoneOffset()`
- then check the DatePicker normally

Sources: 

- [Time and time zone settings - MozillaZine Knowledge Base](http://kb.mozillazine.org/Time_and_time_zone_settings#A_Windows_bug)
- [Article: How to set TZ variable in UNIX?](http://knowledgebase.progress.com/articles/Article/000044163)

## Some tips to test on SauceLabs

Since the VM launches with Firefox already started, and that there is no shortcut to launch it again nor access to the disks in the file explorer, do the following: 

- open the Task Manager
- check the path of the running Firefox executable
- open a terminal and go to that folder

You'll be able to launch Firefox again from there after closing the previous instance. Even better, with this technique it's straightforward to apply the timezone without having to change OS settings using the procedure above.

**Comment by maxokorokov** [comment] 2017-07-10 08:02
Reproduced it locally. Using `getUTCDate()` instead of `getDate()` in the datepicker service seems to fix it. Will fix right after #1551 lands

**Closed** 2017-07-11 14:21 UTC
Labels: component: datepicker, type: bug

**Comment by shyamal890** [comment] 2019-10-06 14:10
@maxokorokov @pkozlowski-opensource  Most of the UI tools out there have 12 AM as the default. Any idea on when the behavior would reverted back to 12 AM instead of 12 PM?
