### ISSUE TITLE
Compilation error for v5.1.1 when >>ng build --prod

### ISSUE THREAD

**Issue by shaneGoose** [ng-bootstrap/ng-bootstrap#3373] opened 2019-09-20 13:14 UTC
### Bug description:
ERROR in node_modules/@ng-bootstrap/ng-bootstrap/accordion/accordion.d.ts.NgbAccordion.html(6,42): An expression of type 'void' cannot be tested for truthiness
node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker-navigation.d.ts.NgbDatepickerNavigation.html(3,67): An expression of type 'void' cannot be tested for truthiness
node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker-navigation.d.ts.NgbDatepickerNavigation.html(25,67): An expression of type 'void' cannot be tested for truthiness
node_modules/@ng-bootstrap/ng-bootstrap/pagination/pagination.d.ts.NgbPagination.html(6,11): An expression of type 'void' cannot be tested for truthiness
node_modules/@ng-bootstrap/ng-bootstrap/pagination/pagination.d.ts.NgbPagination.html(14,11): An expression of type 'void' cannot be tested for truthiness
node_modules/@ng-bootstrap/ng-bootstrap/pagination/pagination.d.ts.NgbPagination.html(21,67): An expression of type 'void' cannot be tested for truthiness
node_modules/@ng-bootstrap/ng-bootstrap/pagination/pagination.d.ts.NgbPagination.html(28,11): An expression of type 'void' cannot be tested for truthiness
node_modules/@ng-bootstrap/ng-bootstrap/pagination/pagination.d.ts.NgbPagination.html(35,11): An expression of type 'void' cannot be tested for truthiness
node_modules/@ng-bootstrap/ng-bootstrap/tabset/tabset.d.ts.NgbTabset.html(5,16): An expression of type 'void' cannot be tested for truthiness

### Link to minimally-working StackBlitz that reproduces the issue:
N/A, not using any of the components indicated in the error message. 

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 
cli: 8.3.4
core: 8.2.5

ng-bootstrap: 5.1.1

Bootstrap: 4.0.0

"typescript": "~3.5.3"

**Comment by maxokorokov** [comment] 2019-09-26 08:48
@shaneGoose might be your typescript version, you haven't reported it.
Everything works fine on my side after creating a new cli project and adding ng-bootstrap. Please, compare your deps with CLI ones.

**Comment by shaneGoose** [comment] 2019-09-27 12:52
@maxokorokov I updated the description to include the Typescript version

**Comment by maxokorokov** [comment] 2019-09-27 13:43
Oh, actually it looks like it's a duplicate of #2755 !
Check it and try clearing everything.

**Closed by maxokorokov** 2019-09-27 13:43 UTC
Labels: needs: info
