### ISSUE TITLE
Prevent body from scrolling when a modal is open

### ISSUE THREAD

**Issue by sergeu90** [ng-bootstrap/ng-bootstrap#2009] opened 2017-12-04 22:30 UTC
Hello everyone.You forgot a part of bootstrap code for fix scroll bar issue 
https://github.com/twbs/bootstrap/blob/v4-dev/js/src/modal.js#L136
https://github.com/twbs/bootstrap/blob/v4-dev/js/src/modal.js#L137

**Comment by pkozlowski-opensource** [comment] 2017-12-05 16:48
I believe that this is a duplicate of #641. If you trying to report a different issue, please provide more details. Closing for now.

**Closed by pkozlowski-opensource** 2017-12-05 16:48 UTC
