### ISSUE TITLE
Can't resolve all parameters for NgbModalStack:

### ISSUE THREAD

**Issue by aykutyararbas** [ng-bootstrap/ng-bootstrap#2212] opened 2018-03-09 23:58 UTC
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:

{code}
Error: Can't resolve all parameters for NgbModalStack: ([object Object], [object Object], [object Object], ?).
app2_main_bundle-4fb55a73a5.js:22295:17
syntaxError
https://truesight-staging.bmc.com/intelligence/scripts/app2_main_bundle-4fb55a73a5.js:22295:17
CompileMetadataResolver</CompileMetadataResolver.prototype._getDependenciesMetadata
https://truesight-staging.bmc.com/intelligence/scripts/app2_main_bundle-4fb55a73a5.js:31043:29
CompileMetadataResolver</CompileMetadataResolver.prototype._getTypeMetadata
https://truesight-staging.bmc.com/intelligence/scripts/app2_main_bundle-4fb55a73a5.js:30937:17
CompileMetadataResolver</CompileMetadataResolver.prototype._getInjectableMetadata
https://truesight-staging.bmc.com/intelligence/scripts/app2_main_bundle-4fb55a73a5.js:30925:14
CompileMetadataResolver</CompileMetadataResolver.prototype.getProviderMetadata
https://truesight-staging.bmc.com/intelligence/scripts/app2_main_bundle-4fb55a73a5.js:31155:31
CompileMetadataResolver</CompileMetadataResolver.prototype._getProvidersMetadata/<
https://truesight-staging.bmc.com/intelligence/scripts/app2_main_bundle-4fb55a73a5.js:31094:35
forEach self-hosted:271:13 
### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
 4.0.0
ng-bootstrap:
 1.0.1
Bootstrap:
 3.3.6

**Comment by aykutyararbas** [comment] 2018-03-10 00:00
I'd like to prepare sample plunker if I have time. But I assume this is a very generic Bootstrapping issue.

**Comment by pkozlowski-opensource** [comment] 2018-03-10 12:10
You are using unsupported versions of Angular _and_ Bootstrap CSS with this library. You need the following, minimal versions of:
* Angular: `5.0.2`
* Bootstrap: `4.0.0`

Here is a plunker demonstrating that things work correctly when required versions of dependencies are used: http://plnkr.co/edit/Uy5QUK0uI0LOTurylLar?p=preview

I'm going to close this one as the error is caused by incorrect Angular version. Happy to re-open if you can reproduce the problem with Angular 5.x (you can use a plunker I've linked here as a starting point)

**Closed by pkozlowski-opensource** 2018-03-10 12:10 UTC

**Comment by aykutyararbas** [comment] 2018-03-12 20:51
Thank you very much. 
I'd assume backward compatibility is not the case in this situation.
