### ISSUE TITLE
NgbModal feature request - Please add size: 'md' for modal

### ISSUE THREAD

**Issue by AlexA-1976** [ng-bootstrap/ng-bootstrap#3839] opened 2020-08-15 19:31 UTC
This is a necessary size between small and large. Otherwise you have to do custom CSS.

**Comment by jnizet** [comment] 2020-08-16 07:38
Duplicate of https://github.com/ng-bootstrap/ng-bootstrap/issues/3088

There is no 'md' size in Bootstrap. If you want the default size for modals, don't pass any size at all.

**Comment by maxokorokov** [comment] 2020-08-20 08:56
Also `NgbModalOptions` supports any string, so feel free to pass `size: 'md'` if necessary, https://ng-bootstrap.github.io/#/components/modal/api#NgbModalOptions.

![Screenshot 2020-08-20 at 10 56 17](https://user-images.githubusercontent.com/8074436/90749479-c8057880-e2d3-11ea-9332-567a58f40500.jpg)

**Closed by maxokorokov** 2020-08-20 08:56 UTC
Labels: component: modal
