### ISSUE TITLE
"XX.ngfactory.js is missing from the TypeScript  compilation" when ng build

### ISSUE THREAD

**Issue by blackredscarf** [ng-bootstrap/ng-bootstrap#2283] opened 2018-04-06 13:01 UTC
I build my project use `ng build --prod`.

throw these error:
```
ERROR in ./node_modules/_@ng-bootstrap_ng-bootstrap@1.1.1@@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory.js
Module build failed: Error: D:\Angular\video-server\node_modules\_@ng-bootstrap_ng-bootstrap@1.1.1@@ng-bootstrap\ng-bootstrap\alert\alert.ngfactory.js is missing from the TypeScript
 compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library reposit
ory to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (D:\Angular\video-server\node_modules\_@ngtools_webpack@1.9.5@@ngtools\webpack\src\angular_compiler_plugin.js:656:23)
    at plugin.done.then (D:\Angular\video-server\node_modules\_@ngtools_webpack@1.9.5@@ngtools\webpack\src\loader.js:467:39)
 @ ./src/app/app.module.ngfactory.js 12:0-90
 @ ./src/main.ts
 @ multi ./src/main.ts
```
Also there are popover.ngfactory.js, modal-window.ngfactory.js ...

And my tsconfig.json:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  }
}
```

Version:
angular-cli: 1.6.5
angular: ^5.2.0
ng-bootstrap: 1.1.1

**Comment by pkozlowski-opensource** [comment] 2018-04-06 13:07
Sorry, but there is not enough info here, we need versions of the dependencies used, build used etc.:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by pkozlowski-opensource** [comment] 2018-04-09 20:28
I've just tried to reproduce with the specified versions and can not. We also haven't had any other users reporting similar problems, even given several thousands downloads a day. We can't do much without a reproduce scenario so I'm going to close this issue for now.

Happy to re-open if / when you can provide us with a minimal reproduce scenario (share a minimal github repository)

**Closed by pkozlowski-opensource** 2018-04-09 20:28 UTC
Labels: needs: info

**Comment by JulioJu** [comment] 2018-04-19 15:59
@pkozlowski-opensource  and @blackredscarf 

I've the same problem

### Steps to reproduce. 

1. `git clone https://github.com/jhipster/jhipster-sample-app` official example of the famous https://www.jhipster.tech/. 
2. `yarn install`
3. `mv node_modules ../`
4. `ln -s ../node_modules .`
5. `node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js --config webpack/webpack.prod.js --profile`

Without step 3 and 4, all work fine. 
### Error message produced
```
ERROR in ../node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory.js
Module build failed: Error: /home/user/node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory.js is missing from the TypeScript compilation. Plea
se make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue
in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/user/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:685:23)
    at plugin.done.then (/home/user/node_modules/@ngtools/webpack/src/loader.js:28:31)
    at <anonymous>
 @ ./src/main/webapp/app/app.module.ngfactory.js 12:0-96 198:294-314
 @ ./src/main/webapp/app/app.main.ts

ERROR in ../node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.ngfactory.js
Module build failed: Error: /home/user/node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.ngfactory.js is missing from the TypeScript compila
tion. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue
in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/user/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:685:23)
    at plugin.done.then (/home/user/node_modules/@ngtools/webpack/src/loader.js:28:31)
    at <anonymous>
 @ ./src/main/webapp/app/app.module.ngfactory.js 15:0-106 198:378-403
 @ ./src/main/webapp/app/app.main.ts

ERROR in ../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-backdrop.ngfactory.js
Module build failed: Error: /home/user/node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-backdrop.ngfactory.js is missing from the TypeScript compilat
ion. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue
in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/user/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:685:23)
    at plugin.done.then (/home/user/node_modules/@ngtools/webpack/src/loader.js:28:31)
    at <anonymous>
 @ ./src/main/webapp/app/app.module.ngfactory.js 16:0-105 198:405-433
 @ ./src/main/webapp/app/app.main.ts

ERROR in ../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-window.ngfactory.js
Module build failed: Error: /home/user/node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-window.ngfactory.js is missing from the TypeScript compilatio
n. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue
in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/user/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:685:23)
    at plugin.done.then (/home/user/node_modules/@ngtools/webpack/src/loader.js:28:31)
    at <anonymous>
 @ ./src/main/webapp/app/app.module.ngfactory.js 17:0-104 198:435-462
 @ ./src/main/webapp/app/app.main.ts

ERROR in ../node_modules/@ng-bootstrap/ng-bootstrap/pagination/pagination.ngfactory.js
Module build failed: Error: /home/user/node_modules/@ng-bootstrap/ng-bootstrap/pagination/pagination.ngfactory.js is missing from the TypeScript compila
tion. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue
in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/user/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:685:23)
    at plugin.done.then (/home/user/node_modules/@ngtools/webpack/src/loader.js:28:31)
    at <anonymous>
 @ ./src/main/webapp/app/admin/user-management/user-management.component.ngfactory.js 17:0-113 88:20-44 88:46-74
 @ ./src/main/webapp/app/app.module.ngfactory.js
 @ ./src/main/webapp/app/app.main.ts

ERROR in ../node_modules/@ng-bootstrap/ng-bootstrap/popover/popover.ngfactory.js
Module build failed: Error: /home/user/node_modules/@ng-bootstrap/ng-bootstrap/popover/popover.ngfactory.js is missing from the TypeScript compilation.
Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue
in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/user/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:685:23)
    at plugin.done.then (/home/user/node_modules/@ngtools/webpack/src/loader.js:28:31)
    at <anonymous>
 @ ./src/main/webapp/app/app.module.ngfactory.js 18:0-101 198:464-493
 @ ./src/main/webapp/app/app.main.ts

ERROR in ../node_modules/@ng-bootstrap/ng-bootstrap/progressbar/progressbar.ngfactory.js
Module build failed: Error: /home/user/node_modules/@ng-bootstrap/ng-bootstrap/progressbar/progressbar.ngfactory.js is missing from the TypeScript compi
lation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue
in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/user/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:685:23)
    at plugin.done.then (/home/user/node_modules/@ngtools/webpack/src/loader.js:28:31)
    at <anonymous>
 @ ./src/main/webapp/app/admin/metrics/metrics.component.ngfactory.js 10:0-114 25:1338-1362 25:1364-1392 25:2460-2484 25:2486-2514 25:3589-3613 25:3615-3643 28
:763-787 28:789-817 28:1855-1879 28:1881-1909 28:2937-2961 28:2963-2991 28:4027-4051 28:4053-4081 31:4178-4202 31:4204-4232 31:6218-6242 31:6244-6272 31:8274-8
298 31:8300-8328 37:4863-4887 37:4889-4917
 @ ./src/main/webapp/app/app.module.ngfactory.js
 @ ./src/main/webapp/app/app.main.ts

ERROR in ../node_modules/@ng-bootstrap/ng-bootstrap/tooltip/tooltip.ngfactory.js
Module build failed: Error: /home/user/node_modules/@ng-bootstrap/ng-bootstrap/tooltip/tooltip.ngfactory.js is missing from the TypeScript compilation.
Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue
in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/user/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:685:23)
    at plugin.done.then (/home/user/node_modules/@ngtools/webpack/src/loader.js:28:31)
    at <anonymous>
 @ ./src/main/webapp/app/app.module.ngfactory.js 13:0-100 198:316-344
 @ ./src/main/webapp/app/app.main.ts

ERROR in ../node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead-window.ngfactory.js
Module build failed: Error: /home/user/node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead-window.ngfactory.js is missing from the TypeScript co
mpilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue
in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/user/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:685:23)
    at plugin.done.then (/home/user/node_modules/@ngtools/webpack/src/loader.js:28:31)
    at <anonymous>
 @ ./src/main/webapp/app/app.module.ngfactory.js 14:0-111 198:346-376
 @ ./src/main/webapp/app/app.main.ts
```

**Comment by RajPack** [comment] 2018-05-27 06:43
I had the same problem, with  "@ng-bootstrap/ng-bootstrap": "^1.1.2" version
The symlink of 'node_modules' was causing this issue as stated by @JulioJu 

Resolved the issue by adding the below in .angular-cli.json, within the `defaults` key.
`
 "build": {
      "preserveSymlinks": true
    }
`
Things started to work fine after this addition..

**Comment by JulioJu** [comment] 2018-06-05 11:49
@RajPack,
I've tested, but doesn't t work. As JHipster use Angular 6, the syntax is a little bit different that you said. The syntax should be instead (see https://github.com/angular/angular-cli/issues/10896 and https://github.com/angular/angular-cli/wiki/angular-workspace) :
```json
"architect": {
  "build": {
    "builder": "@angular-devkit/build-angular:browser",
    "options": {
      "preserveSymlinks": true
    }
  }
}
```
As the problem is with command `./mvn verify` (trigger packaging of the application), I've tried also with https://webpack.js.org/configuration/resolve/#resolve-symlinks, without more success. Have you an idea ? 

It's strange, because some of ngx-bootstrap modules are founded, like :
```log
[INFO]  [67] ../node_modules-cache-angular-sample/node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.module.js + 7 modules 39.1 KiB {1} [built]
[INFO]       |    8 modules
[INFO]  [82] ../node_modules-cache-angular-sample/node_modules/@ng-bootstrap/ng-bootstrap/accordion/accordion.module.js + 1 modules 8.5 KiB {1} [built]
[INFO]       |    2 modules
[INFO]  [83] ../node_modules-cache-angular-sample/node_modules/@ng-bootstrap/ng-bootstrap/tabset/tabset.module.js + 1 modules 8.3 KiB {1} [built]
[INFO]       |    2 modules
[INFO]  [93] ../node_modules-cache-angular-sample/node_modules/@ng-bootstrap/ng-bootstrap/carousel/carousel.module.js + 1 modules 9.79 KiB {1} [built]
[INFO]       |    2 modules
[INFO]  [94] ../node_modules-cache-angular-sample/node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead.module.js + 3 modules 20.1 KiB {1} [built]
[INFO]       |    4 modules
[INFO]  [96] ../node_modules-cache-angular-sample/node_modules/@ng-bootstrap/ng-bootstrap/tooltip/tooltip.module.js + 1 modules 10.1 KiB {1} [built]
[INFO]       |    2 modules
[INFO]       [] 274859ms -> [] 7438ms -> [0] 8302ms -> [310] 10565ms -> [305] 147ms -> factory:15330ms building:616ms dependencies:1969ms = 319226ms
[INFO] [101] ../node_modules-cache-angular-sample/node_modules/@ng-bootstrap/ng-bootstrap/popover/popover.module.js + 1 modules 10 KiB {1} [built]
[INFO]       |    2 modules
```
But not :
```log
[INFO] ERROR in ../node_modules-cache-angular-sample/node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory.js
[INFO] ERROR in ../node_modules-cache-angular-sample/node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.ngfactory.js
[INFO] ERROR in ../node_modules-cache-angular-sample/node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-backdrop.ngfactory.js
[INFO] ERROR in ../node_modules-cache-angular-sample/node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-window.ngfactory.js
[INFO] ERROR in ../node_modules-cache-angular-sample/node_modules/@ng-bootstrap/ng-bootstrap/pagination/pagination.ngfactory.js
[INFO] ERROR in ../node_modules-cache-angular-sample/node_modules/@ng-bootstrap/ng-bootstrap/popover/popover.ngfactory.js
[INFO] ERROR in ../node_modules-cache-angular-sample/node_modules/@ng-bootstrap/ng-bootstrap/progressbar/progressbar.ngfactory.js
[INFO] ERROR in ../node_modules-cache-angular-sample/node_modules/@ng-bootstrap/ng-bootstrap/tooltip/tooltip.ngfactory.js
[INFO] ERROR in ../node_modules-cache-angular-sample/node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead-window.ngfactory.js
```

Please, what do you think about that @pkozlowski-opensource ?
