### ISSUE TITLE
Not able to right align dropdown menu 

### ISSUE THREAD

**Issue by vivek-kumar-gupt** [ng-bootstrap/ng-bootstrap#1748] opened 2017-08-12 10:53 UTC
description:
In beta.1 "dropdown-menu-right" class has no effect on the alignment of the dropdown menu. Seems related to #1747 

plunker:
http://plnkr.co/edit/0TqTSKinhqv4xi5b9RNj?p=preview

Angular: 4.3.4
ng-bootstrap: 1.0.0-beta.1
Bootstrap: 4.0.0-beta

**Comment by pkozlowski-opensource** [comment] 2017-08-12 12:43
Yep, this is the same as #1747 and will be solved by using the positioning service. Closing as a duplicate of #1747

**Closed by pkozlowski-opensource** 2017-08-12 12:43 UTC
