### ISSUE TITLE
Name clash in ngbDropdown between a template input variable and a public var of ngbDropdownToggle

### ISSUE THREAD

**Issue by karptonite** [ng-bootstrap/ng-bootstrap#813] opened 2016-09-28 19:03 UTC
### Bug description:
In the plunker, you'll see a "menu" rendered using `*ngFor` for a set of dropdowns. The problem is the choice of the name `dropdown` for the template input variable in the `*ngFor`. That `dropdown` appears to conflict with the public variable `dropdown` of ngbDropdownToggle, causing both cryptic errors in the console and broken dropdowns. If you change the var name in the ngFor to anything other than `dropdown`, it works fine. 

This showed up in a real project (it broke between Alpha 5 and 6), and was pretty unexpected and difficult do debug. It is a problem even if you don't try to use the `dropdown` from the for loop in the label inside of the ngbDropdownToggle. 

I'm not actually sure whether this counts as an ngBootstrap problem or an Angular bug, or neither. This could be fixed, in part, by prefixing the `dropdown` var in ngbDropdownToggle, but I'm not sure what is the best practice here. I've never heard a suggestion that we should prefix our own local vars in, for example, an *ngFor--I never would have thought that such a local var name was at risk of clashing with anything, which makes me wonder if this is some problem on Angular's end.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/R0HJDJZd6DoZgmKTnz9f?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.0

ng-bootstrap: alpha 6

Bootstrap: 4.0.0 beta 4

**Comment by pkozlowski-opensource** [comment] 2016-09-29 10:35
> I'm not actually sure whether this counts as an ngBootstrap problem or an Angular bug, or neither. 

This definitively looks like a bug in the Angular itself (generated code seems to be confusing different variable scopes). I will try to reduce this further and will report / fix issue in the Angular.

> This could be fixed, in part, by prefixing the dropdown var in ngbDropdownToggle, but I'm not sure what is the best practice here.

No, let's fix it upstream. Thnx for reporting.

**Comment by karptonite** [comment] 2016-09-29 14:29
Thanks! When you report to Angular, please link back here--I'm curious to see what the issue is.

**Comment by pkozlowski-opensource** [comment] 2016-09-30 13:35
This is reproduction of the issue without ng-bootstrap: https://plnkr.co/edit/AgysQsIPMd81W37ON5Ux?p=preview

Relevant bug report for the Angular itself: https://github.com/angular/angular/issues/12004

I'm going to close it here as this is clearly Angular bug and should be fixed upstream.

**Closed by pkozlowski-opensource** 2016-09-30 13:35 UTC
Labels: blocked: ng2 issue, component: dropdown, needs: investigation, type: bug
