### ISSUE TITLE
Typeahead sets the input as undefined when focus is given to input and no value is selected 

### ISSUE THREAD

**Issue by curious29** [ng-bootstrap/ng-bootstrap#2145] opened 2018-02-06 10:47 UTC
I have binded typeahead search method to an object of list.
When User clicks on the input to which typeahead is bound a list appears. If user doe snot selects anything from the list and clicks outside the input shows undefined

**Comment by pherklotz** [comment] 2018-02-06 14:27
Hello, 
i struggled with the same problem. The bug appears because the input-Field-model from the typeahead component is not initialized. The following dirty workaround helped me:
```typescript
@ViewChild('typeahead')
typeahead: NgbTypeahead;

ngOnInit() {
  this.typeahead['_userInput'] = '';
}
```

I use ng-bootstrap 1.0.0-beta.6. **The property name has changed in the current version to "_inputValueBackup"!** 

As a fix i would suggest to initialize `NgbTypeahead._inputValueBackup` with an empty string.

**Comment by pkozlowski-opensource** [comment] 2018-03-01 14:08
@curious29 @pherklotz I'm having hard time to reproduce issue that you are reporting. I don't know what is the exact config that you are using, scenario etc. Please add a minimal reproduce scenario in a plunker with exact steps to reproduce.

We need a plunker as otherwise is too hard to understand under which conditions a problem appears: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by pherklotz** [comment] 2018-03-02 10:45
Sorry about your circumstances. I also could not reproduce the bug in version 1.0.0.

**Comment by pkozlowski-opensource** [comment] 2018-03-02 10:59
> I also could not reproduce the bug in version 1.0.0.

Thnx for coming back to with this info @pherklotz - I'm going to close this issue for now. Happy to re-open if / when we've got a reproduce scenario.

**Closed by pkozlowski-opensource** 2018-03-02 10:59 UTC
Labels: component: typeahead, needs: investigation, type: bug
