### ISSUE TITLE
Can't resolve all parameters for NgbModalRef 

### ISSUE THREAD

**Issue by Procaseycash** [ng-bootstrap/ng-bootstrap#1840] opened 2017-09-11 12:59 UTC
While building  on oracle Linux for production with ng build -prod, I encountered this error: 

 "Can't resolve all parameters for NgbModalRef in /var/www/html/checkout/node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-ref.d.ts: ([object Object], [object Object], [object Object], ?). This will become an error in Angular v5.x
Warning: Can't resolve all parameters for NgbModalRef in /var/www/html/checkout/node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-ref.d.ts: ([object Object], [object Object], [object Object], ?). This will become an error in Angular v5.x
"

After the production built was completed, this was now shown after the aforementioned warning: 

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/var/www/html/checkout/src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts

Any workaround on this? #

**Comment by pkozlowski-opensource** [comment] 2017-09-11 13:30
* this is not an error, but a _warning_ (your build should still work just fine);
* it is already fixed in master, see 0bf798dcab74a577511c5cc38473e1ad3c14ba55 and the fix will be part of a next release.

Closing as a duplicate of #1832

**Closed by pkozlowski-opensource** 2017-09-11 13:30 UTC

**Comment by pkozlowski-opensource** [comment] 2017-09-14 20:35
FYI, just released 1.0.0-beta.5 that removes the mentioned warning.

**Comment by DumanBi** [comment] 2017-09-25 04:27
me too
