### ISSUE TITLE
Modal's backdrop fills the whole page

### ISSUE THREAD

**Issue by natcohen** [ng-bootstrap/ng-bootstrap#652] opened 2016-09-01 11:31 UTC
Wherever I put the `ngbModalContainer`, the backdrop will take the whole page.

It should in fact only fill the parents' container.

**Comment by pkozlowski-opensource** [comment] 2016-09-01 11:39
> It should in fact only fill the parents' container.

Nope, this is not the intention nor how Bootstap's modal works: http://v4-alpha.getbootstrap.com/components/modal/

We _want_ to fill the whole page, this is by design and won't change, at least not in this library. Closing as "won't fix".

**Comment by natcohen** [comment] 2016-09-01 12:03
@pkozlowski-opensource I can't find what you referenced... anyway, it is extremely disappointing (uibootstrap was supporting it) especially because we won't be able to use modals with layout libraries ([golden-layout](https://www.golden-layout.com/) for example)!

There are hundreds of use case where the modal has to fill the container.

**Comment by pkozlowski-opensource** [comment] 2016-09-01 12:12
> I can't find what you referenced.

Huh? If you check http://v4-alpha.getbootstrap.com/components/modal/#options than you are going to see that there is no way of specifying container option in the original Bootstrap.

> uibootstrap was supporting it and angular material as well

Are you referring to the `appendTo` option in http://angular-ui.github.io/bootstrap/#/modal or sth else?
The problem is that as far as I understand Bootstrap 4 markup we might have hard time to restricting modal element to a particular container.

 > There are hundreds of use case where the modal has to fill the container. 
> it is extremely disappointing especially because we won't be able to use modals with layout libraries (golden-layout for example)!

If you are willing to share 3 killer use-cases and work with us on adding proper support for container-scoped modals I'm would be more than happy to re-open / re-consider.

**Comment by natcohen** [comment] 2016-09-01 12:31
> Are you referring to the appendTo

Yes

> If you are willing to share 3 killer use-cases and work with us on adding proper support for container-scoped modals I'm would be more than happy to re-open / re-consider.

- Mimic browser's tabs within electron or nwJS (note that most layouts don't support iframe)
- Mimic 'multi-task' inside your app for smartphone and tablets (by using layouts)
- Navigate within your app while a modal is open (to consult something if you have to fill a form inside the modal and some information is somewhere else)

I might not be the best person to help you do that... I'm not an expert and started web development only recently (I'm not a software engineer)

**Comment by pkozlowski-opensource** [comment] 2016-09-01 12:47
I'm re-opening this as a feature request, although I'm not sure it is technically possible.

> I might not be the best person to help you do that... I'm not an expert and started web development only recently (I'm not a software engineer)

That's fine. Just keep in mind that it has low priority for us so it won't happen soon if there is not enough interest / no one steps in to help out.

**Comment by natcohen** [comment] 2016-10-13 12:21
@pkozlowski-opensource BTW I've succeeded to do that by setting `position:absolute` to `.modal` and `.modal-backdrop` and by adding `position: relative` to the parent of `template(ngbModalContainer)`

**Comment by pkozlowski-opensource** [comment] 2016-10-13 14:57
Glad to hear this @natcohen as I wasn't too keen on supporting this (as you could gather from my previous comments).

**Closed by pkozlowski-opensource** 2016-10-13 14:57 UTC
Labels: component: modal, type: feature
