### ISSUE TITLE
Modal Animations Missing

### ISSUE THREAD

**Issue by jayoungers** [ng-bootstrap/ng-bootstrap#1407] opened 2017-03-25 19:34 UTC
### Bug description:

Modals are not animated on transition in/out (in Chrome 56 anyway); I just added the project, so I'm not sure if it was working earlier.

I tried to see if there was an easy solution, but since it opens with both classes (fade/show) already added, I'm not sure how you could get the browser to acknowledge the transitions.  I noticed 'modal-open' gets added at a body level and tried to key off of that, but my initial attempt didn't work.  I'll give it another shot tomorrow

### Link to minimally-working plunker that reproduces the issue:

The ng-bootstrap demo page: https://ng-bootstrap.github.io/#/components/modal

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.0.0

ng-bootstrap: 1.0.0-alpha.22

Bootstrap: v3.3.7 (w/ v4 modal styles shimmed in)

**Comment by pkozlowski-opensource** [comment] 2017-03-25 20:12
Duplicate of #295

**Closed by pkozlowski-opensource** 2017-03-25 20:12 UTC
