### ISSUE TITLE
bug: auto-open modal: ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by mixalbl4-127** [ng-bootstrap/ng-bootstrap#1775] opened 2017-08-24 17:51 UTC
Demo: http://plnkr.co/edit/DeDNcY6GYinSrDqg6RRQ?p=preview
Like I say here (https://github.com/ng-bootstrap/ng-bootstrap/issues/1774): all manipulation with components in "init" makes ExpressionChangedAfterItHasBeenCheckedError.
How to work with elements without this error in console?

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.3.3

ng-bootstrap: v1.0.0-beta.2

Bootstrap: 4.0.0-beta

**Comment by pkozlowski-opensource** [comment] 2017-08-24 18:08
What you are facing here is a bug in Angular itself, see https://github.com/angular/angular/issues/15634 (you can also check impact of this issue on modals in #1384).

Till the bug in Angular is fixed you can use a work-around with `setTimeout` as shown in the following plunker: http://plnkr.co/edit/Cf4Do8CucVbt5P95KvyW?p=preview

Closing as a duplicate of https://github.com/angular/angular/issues/15634 / #1384

**Closed by pkozlowski-opensource** 2017-08-24 18:08 UTC

**Comment by kukac7** [comment] 2017-11-30 11:05
🇷🇴
