### ISSUE TITLE
Generating index html...1 rules skipped due to selector errors:   legend+* -> Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by mrgauravchaudhari** [ng-bootstrap/ng-bootstrap#4527] opened 2023-06-14 04:57 UTC
Bug description:

When building angular using the production configuration, the step Generating index html... produces following warning:
Generating index html...1 rules skipped due to selector errors: legend+* -> Cannot read properties of undefined (reading 'type')

![image](https://github.com/ng-bootstrap/ng-bootstrap/assets/47390633/43afc630-f203-4b57-a910-74ac760d1808)

Angular CLI: 15.1.6
Node: v18.14.1
OS: win 10 x64

Package                         Version
---------------------------------------------------------
"dependencies": {
    "@angular/animations": "^15.1.0",
    "@angular/cdk": "^15.1.2",
    "@angular/common": "^15.1.0",
    "@angular/compiler": "^15.1.0",
    "@angular/core": "^15.1.0",
    "@angular/forms": "^15.1.0",
    "@angular/material": "^15.1.2",
    "@angular/platform-browser": "^15.1.0",
    "@angular/platform-browser-dynamic": "^15.1.0",
    "@angular/router": "^15.1.0",
    "@ng-select/ng-select": "^10.0.4",
    "@nguniversal/express-engine": "^15.2.0",
    "bootstrap": "^5.2.3",
    "file-saver-es": "^2.0.5",
    "moment": "^2.29.4",
    "ng-otp-input": "^1.8.5",
    "ng2-pdf-viewer": "^9.1.3",
    "ngx-device-detector": "^5.0.1",
    "ngx-pagination": "^6.0.3",
    "rxjs": "~7.8.0",
    "sha.js": "^2.4.11",
    "tslib": "^2.3.0",
    "xlsx": "^0.18.5",
    "zone.js": "~0.12.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.1.3",
    "@angular-eslint/builder": "^15.2.0",
    "@angular-eslint/eslint-plugin": "15.2.0",
    "@angular-eslint/eslint-plugin-template": "15.2.0",
    "@angular-eslint/schematics": "15.2.0",
    "@angular-eslint/template-parser": "15.2.0",
    "@angular/cli": "~15.1.3",
    "@angular/compiler-cli": "^15.1.0",
    "@types/jasmine": "~4.3.0",
    "@types/node": "^20.2.5",
    "@typescript-eslint/eslint-plugin": "5.48.1",
    "@typescript-eslint/parser": "5.48.1",
    "eslint": "^8.31.0",
    "jasmine-core": "~4.5.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "typescript": "~4.9.4"
  }

**Comment by maxokorokov** [comment] 2023-06-26 12:31
Duplicate of #4306

**Closed by maxokorokov** 2023-06-26 12:31 UTC
Labels: type: ssr, type: CSS
