### ISSUE TITLE
calendar's model should work with both strings and numbers

### ISSUE THREAD

**Issue by fxck** [ng-bootstrap/ng-bootstrap#1112] opened 2016-12-05 16:15 UTC
When values of `NgbDateStruct` are strings, it doesn't complain, but doesn't select the selected day either http://plnkr.co/edit/1gscdlkc8UkblG0XmeMy?p=preview

It should either accept both or throw a warning, especially given the fact that momentjs'(which I suppose quite a few people use) `.format()` method returns a string instead of a number.

I almost jumped out of the window before I figured out what was be the problem.

**Comment by pkozlowski-opensource** [comment] 2016-12-05 18:24
So there are 2 items to be tackled here:
* support for model formats other than `NgbDateStruct` - this is duplicate of https://github.com/ng-bootstrap/ng-bootstrap/issues/754#issuecomment-247767027 - the ultimate solution here must come from Angular itself (https://github.com/angular/angular/issues/11097)
* what should happen on invalid model - right now we've decided to handle invalid model value as `undefined`. We could throw but I'm not sure....

Going to keep this one open so we can discuss: "what to do on invalid model". cc. @maxokorokov

**Comment by fxck** [comment] 2016-12-05 19:45
It has come full circle lol https://github.com/angular/angular/issues/3009#issuecomment-227150544

**Comment by pkozlowski-opensource** [comment] 2016-12-05 20:02
> It has come full circle lol angular/angular#3009 (comment)

Indeed! IMO this is one of the top features needed for forms and Kara is fully aware of if (well, I was trying to make her aware of this issue :-))

**Comment by pkozlowski-opensource** [comment] 2016-12-13 10:39
Closing as a duplicate of #754

**Closed by pkozlowski-opensource** 2016-12-13 10:39 UTC
Labels: component: datepicker
