### ISSUE TITLE
[discussion] Typeahead multiple selection

### ISSUE THREAD

**Issue by tinchou** [ng-bootstrap/ng-bootstrap#893] opened 2016-10-15 00:35 UTC
Hi!

I'd like to discuss the possibility of extending the Typeahead component to include multiple selections, like when you fill the `to` or `cc` fields when writing an email in GMail. Or maybe like the labels selection when you add labels to a GitHub issue. This can also be another component, and leave Typeahead alone.

There're also other issues I have with the component that I would like to discuss, but maybe I can open new issues:

- `[ngbTypeahead]` doesn't bind to `this`, you need to do it manually if you want to access attributes: `[ngbTypeahead]="search.bind(this)"`
- It seems that if you're using Reactive Forms you need to use `[formControl]` instead of `[(ngModel)]`. Why not have our own property and be independent from the `forms` module?

**Comment by pkozlowski-opensource** [comment] 2016-10-15 06:44
> I'd like to discuss the possibility of extending the Typeahead component to include multiple selections, like when you fill the to or cc fields when writing an email in GMail. Or maybe like the labels selection when you add labels to a GitHub issue. This can also be another component, and leave Typeahead alone.

I believe that this is a duplicate of #532

> There're also other issues I have with the component that I would like to discuss, but maybe I can open new issues

Yes, having small, focused issues is always preferable. Just short comments here (but let's not continue the discussion in here, let's open new, focused issues if more details are needed).

> [ngbTypeahead] doesn't bind to this, you need to do it manually if you want to access attributes: [ngbTypeahead]="search.bind(this)"

We don't have access to the component instance in the typeahead directive so we can't bind `this`. But you can use ES6 fat-arrow syntax to do it effectively, like in our demos: https://ng-bootstrap.github.io/#/components/typeahead

> It seems that if you're using Reactive Forms you need to use [formControl] instead of [(ngModel)]. 

Yes, both template-driven and reactive forms use different directives.

> Why not have our own property and be independent from the forms module?

Because we want to play well with the entire ng-ecosystem.  Replacing integration with forms with our own properties would kill all the forms goodies like validation, indicators of pristine / touched etc. Having integration with forms was a conscious design decision and one we are not willing to review at this point.

**Closed by pkozlowski-opensource** 2016-10-15 06:44 UTC

**Comment by tinchou** [comment] 2016-10-15 14:24
Thanks for your input!
