### ISSUE TITLE
Feature Request: Option to make NgbModal Draggable

### ISSUE THREAD

**Issue by nre4ma** [ng-bootstrap/ng-bootstrap#1766] opened 2017-08-22 20:29 UTC
Hi,

Any chance this feature is in the backlog? Would be nice if this is a boolean option that you can pass in. Does anyone have a suggested workaround or example on how to do this with the current version? Any suggestion is appreciated. Thanks.

**Comment by pkozlowski-opensource** [comment] 2017-08-23 05:32
This is duplicate of #1378. There is _really_ no point in opening duplicates...

Draggable modal windows are not top priority for us since Bootstrap 4 doesn't support those, we would have to probably introduce a dependency on 3rd party code. Not to mention that it results in questionable UX.

If you truly care about draggable modals you can definitively suggest a technical solution in #1378 or, why not, propose a PR!

Closing as a duplicate of #1378

**Closed by pkozlowski-opensource** 2017-08-23 05:32 UTC

**Comment by nre4ma** [comment] 2017-08-29 19:39
Sorry, I did not see the #1378 while searching initially. I will take a look at that thread.
