### ISSUE TITLE
ng 19 compatibility

### ISSUE THREAD

**Issue by guypes** [ng-bootstrap/ng-bootstrap#4783] opened 2024-12-06 12:53 UTC
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
As the title the 17.0.1 version is incompatible with the new released ng 19
Just try to do ng update

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 19.0.x
ng-bootstrap: 17.0.1

Bootstrap: 5.3.3

**Comment by exequiel09** [comment] 2024-12-07 02:31
Dupe of #4779

**Comment by maxokorokov** [comment] 2024-12-09 08:44
Duplicate of #4779

**Closed** 2024-12-09 08:44 UTC
Labels: resolution: duplicate
