### ISSUE TITLE
How to access a child component inside ngbTabContent template

### ISSUE THREAD

**Issue by akram1905** [ng-bootstrap/ng-bootstrap#689] opened 2016-09-06 13:25 UTC
I asked this Question on SO:

[Tabs question](http://stackoverflow.com/questions/39341691/how-to-access-child-component-inside-ngb-tab-for-validation-purposes).

Here are some points (question/requests):

- Is there an option to make all tabs loaded (hidden and not removed from DOM)?
- Is there a way to make the child component (inside `ngbTabContent`) visible in the parent component?

----
notes:
- I tried to subscribe to the form `valueChanges` inside the child component, something like this:
```
    this.form1.valueChanges.subscribe((data) => {
      this.isValid= this.form1.valid;
    });
```
Suppose tab1(with `form1` inside it) is the active, when I change the tab, the `valueChanges` of `form1` is being called multiple times with a different `data` param passed each time, and I think last call with empty `data` param, which will make `form1` is valid.
 _I don't know if it's related to the fact it's inside a tab or not!_

**Comment by masaanli** [comment] 2016-09-06 13:26
I'm also struggling on this one, can't get it to work. 

Anyone?

**Comment by wesleycho** [comment] 2016-09-06 14:48
GitHub is not the place for support questions to be answered - if you would like us to take a look & think it may be a library deficiency, please set up a basic Plunker of the situation showing the problem and we can then investigate if it is a library issue.

**Comment by masaanli** [comment] 2016-09-06 15:58
I'm having it when i'm having a form inside a tab.

And in my component I got:
`@ViewChild('organisationNewForm, {read: NgForm}') organisationNewForm;`

But then the organisationNewForm stays undefined everytime, when it's moved outside the Template it's working.

**Comment by pkozlowski-opensource** [comment] 2016-09-07 13:33
@akram1905 

> Is there an option to make all tabs loaded (hidden and not removed from DOM)?

Not in the current version. We could make it configurable although I'm reluctant to do so since instantiating all the tabs at once would mean creation of unnecessary elements, more change detection etc. In short - perf penalty. 

> Is there a way to make the child component (inside ngbTabContent) visible in the parent component

Not sure I understand your use-case. Please provide a minimal (and I mean truly minimal) plunker if you need further assistance.

@masaanli - see above - we can't help without a minimal plunker.

**Comment by pkozlowski-opensource** [comment] 2016-09-07 13:34
I'm going to close this one till we've got a reproduce scenario.

**Closed by pkozlowski-opensource** 2016-09-07 13:34 UTC
Labels: component: tab, needs: plunkr
