### ISSUE TITLE
Datepicker: First day of month gets gray highlight upon opening

### ISSUE THREAD

**Issue by umerali523** [ng-bootstrap/ng-bootstrap#2680] opened 2018-09-01 21:09 UTC
Hello everyone. Can you help me . How can i remove first day of month gets gray highlight upon opening? I did not find this issue on version 2 but as soon as i moved to ng bootstrap v3.0.0 this issue starts appearing and it really very disturbing,

![33368428-b94ef06e-d502-11e7-9743-b710e632aaca](https://user-images.githubusercontent.com/33350607/44949930-1c985a80-ae55-11e8-810d-665b208e09b4.png)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6.1.6

ng-bootstrap: 3.0.0

Bootstrap: 4
@pkozlowski-opensource  @maxokorokov

**Comment by maxokorokov** [comment] 2018-09-10 13:01
@umerali523 I'm not sure which version you're on... We don't focus the whole popup, but only 1 day since 2.0.0  (it seems like the whole popup is focused in your example).

Ex. it looks like this now in FF:

![screen shot 2018-09-10 at 14 59 23](https://user-images.githubusercontent.com/8074436/45298932-46631880-b50a-11e8-88b6-5adfdb0774fc.png)

Looks like a duplicate of #2000 to me and doesn't look like a bug. 
That's the keyboard focus that you can hide easily with CSS if not needed.

I'd say, that if you want to suggest a better alternative of handling this, please open a feature request with description/demos of how you want it to be handled.

**Closed by maxokorokov** 2018-09-10 13:01 UTC
Labels: component: datepicker, needs: plunkr / stackblitz, resolution: support
