### ISSUE TITLE
Datepicker causing crash with model-driven forms

### ISSUE THREAD

**Issue by Palacios95** [ng-bootstrap/ng-bootstrap#1134] opened 2016-12-09 19:07 UTC
### Bug description:

There is a problem where when I set a default value to the formControlName the datepicker is bound to, it gives the text 'undefined--'. The only way to fix this is by setting the default value to an empty string, but there are many cases where that may not be an option (trying to edit information, for example).

### Link to minimally-working plunker that reproduces the issue:

WARNING: Clicking the button will crash your browser when the text is set to undefined--

http://plnkr.co/edit/APKpeTkAkxq9JW0WqBaG?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.3.0

ng-bootstrap: 1.0.0-alpha.14

bootstrap:

**Comment by pkozlowski-opensource** [comment] 2016-12-09 22:06
This is duplicate of #1062 and we've got already a PR that fixes it. The fix will be part of the next release. Closing as a duplicate.

**Closed by pkozlowski-opensource** 2016-12-09 22:06 UTC
