### ISSUE TITLE
Dropdown: when you click "document" CD triggers once per dropdown on the page

### ISSUE THREAD

**Issue by Denhai** [ng-bootstrap/ng-bootstrap#2528] opened 2018-07-17 10:38 UTC
https://stackblitz.com/edit/angular-1ceag2
This stackblitz has 5 dropdowns. Open the console and click anywhere outside the dropdowns. Should see "ngDoCheck" logged 5 times.

![image](https://user-images.githubusercontent.com/10227167/42812344-81404ede-89fc-11e8-86aa-5f7e5f600d58.png)

I think there is an issue with the way dropdown "outside" clicks are registered `(document:click)`. https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/dropdown/dropdown.ts#L110

Related? https://github.com/angular/angular/issues/22566

**Comment by pkozlowski-opensource** [comment] 2018-07-17 11:44
Duplicate of #900, will be fixed in a next release(s) via #2518

**Closed by pkozlowski-opensource** 2018-07-17 11:44 UTC
