### ISSUE TITLE
Uncaught (in promise) when dismiss Modal Dialog

### ISSUE THREAD

**Issue by changhuixu** [ng-bootstrap/ng-bootstrap#2116] opened 2018-01-24 22:08 UTC
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
In the Example for "Components as content",
if remove code 
```typescript
(reason) => {
      this.closeResult = `Dismissed ${this.getDismissReason(reason)}`;
    }
```
Then there's an error for dismiss event, because the promise is not caught.

Since "onrejected" is an optional call back for Promise, the error in console should be avoided.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/kg9mDRjTEREndbPZVDOl?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2.1

ng-bootstrap: 1.0.0-beta.9

Bootstrap: 4.0.0

**Comment by pkozlowski-opensource** [comment] 2018-01-24 22:41
Duplicate of #1116

**Closed by pkozlowski-opensource** 2018-01-24 22:41 UTC
