### ISSUE TITLE
Arrow Keys Do Not Work With Dropdowns

### ISSUE THREAD

**Issue by jrovny** [ng-bootstrap/ng-bootstrap#2162] opened 2018-02-14 02:33 UTC
The NG Bootstrap dropdown does not allow arrow keys to change selections in the dropdown list. This is an important feature for usability. The native Bootstrap dropdown does allow the arrow keys to select different items in the dropdown list. Whenever the user presses the arrow keys the screen is scrolled instead of individual items in the dropdown being selected.

**Comment by pkozlowski-opensource** [comment] 2018-02-27 10:35
Duplicate of #1998

**Closed by pkozlowski-opensource** 2018-02-27 10:35 UTC
