### ISSUE TITLE
(NgbPopover) Cannot control popover placement when it is open manually

### ISSUE THREAD

**Issue by changLiuUNSW** [ng-bootstrap/ng-bootstrap#1590] opened 2017-05-27 13:35 UTC
I need dynamic control the ```popover``` placement based on the calculation of space.
For example, if there is no enough space for ```popover``` to open at ```right``` placement, I need to open it at ```left```.  Same as open at ```top``` if no enough space at ```bottom``` and vice versa
Current ```open``` function of ```NgbPopover``` does not allow user to pass placement.
It would be better to expose an option to allow use to control placement.

**Comment by pkozlowski-opensource** [comment] 2017-05-29 09:02
I don't think we want to more arguments to the `open()` method as the placement is already controlled by the `placement` option and the `open()` method will take it into account.

More generally I think that you are looking for what is described in #992

Closing as a duplicate of #992

**Closed by pkozlowski-opensource** 2017-05-29 09:02 UTC
