### ISSUE TITLE
Feature Request(Carousel): Enable/Disable pause() on (mouseenter)

### ISSUE THREAD

**Issue by jodhman** [ng-bootstrap/ng-bootstrap#2132] opened 2018-01-30 10:30 UTC
The title is self-explanatory.
Might be my lack of understanding, but why would you put (mouseenter) under the Directives' host.
Perhaps bind the config to accept a function tied to the (mouseenter) host, or just not have (mouseenter) here at all.
Below is the code snippet in question:
`
@Component({
  selector: 'ngb-carousel',
  exportAs: 'ngbCarousel',
  host: {
    'class': 'carousel slide',
    '[style.display]': '"block"',
    'tabIndex': '0',
    '(mouseenter)': 'pause()',
    '(mouseleave)': 'cycle()',
    '(keydown.arrowLeft)': 'keyPrev()',
    '(keydown.arrowRight)': 'keyNext()'
  },
`

**Comment by pkozlowski-opensource** [comment] 2018-01-30 14:26
Duplicate of #1163
Please vote on the existing issues (GitHub reaction) instead of opening new ones - this helps us prioritise work.

**Closed by pkozlowski-opensource** 2018-01-30 14:26 UTC
