### ISSUE TITLE
positionElements function not available since v3.0.0

### ISSUE THREAD

**Issue by jingzhang** [ng-bootstrap/ng-bootstrap#2632] opened 2018-08-21 03:47 UTC
### Bug description:

Prior to 3.0.0, we can use positionElements like this:

```typescript
import { positionElements } from '@ng-bootstrap/ng-bootstrap/util/positioning';
```

But now it causes build error:

```text

Module not found: Error: Can't resolve '@ng-bootstrap/ng-bootstrap/util/positioning' in '......'

```

Seems it's because this function is not exported in @ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.umd.js

Is it by design to not export it? If not it would be nice to have it back.

Thanks.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6.1.3

ng-bootstrap: 3.0.0

Bootstrap: 4.1.3

**Comment by pkozlowski-opensource** [comment] 2018-08-21 07:55
Sorry, we are not ready to open it up as the public API hence it is not exported. So it is by design. 
We can consider opening it up in the future, but this is not priority right now. As such your best option is to copy this service over to your project. I know that this is not ideal, but this is the best option now.

I'm going to close this issue here but I'm still interested why you need access to the positioning service directly?

**Closed by pkozlowski-opensource** 2018-08-21 07:55 UTC

**Comment by jingzhang** [comment] 2018-08-21 09:12
Thank you @pkozlowski-opensource for the quick response!

I'll try your suggestion. 

The reason I need it is because it's used in this dropdown menu workaround https://github.com/ng-bootstrap/ng-bootstrap/issues/1012#issuecomment-365036589
