### ISSUE TITLE
Feature request - Add noCaret prop to DropdownButton

### ISSUE THREAD

**Issue by Pr0b** [ng-bootstrap/ng-bootstrap#2939] opened 2018-12-20 09:31 UTC
Add a noCaret  prop to DropdownButton that will prevent a caret from being rendered next to the button's title. 

Or this feature can be added as caretOrientation prop. With values: up,down,left, right,notRendered.

According to the [documentation](https://ng-bootstrap.github.io/#/components/dropdown/examples ) it's not currently possible to hide a caret for the dropDown button.

**Comment by Pr0b** [comment] 2018-12-20 09:32
Similar feature was already [added](https://github.com/react-bootstrap/react-bootstrap/pull/343) for react framework

**Comment by pkozlowski-opensource** [comment] 2018-12-20 10:42
Duplicate of #2560

**Closed by pkozlowski-opensource** 2018-12-20 10:42 UTC
Labels: component: dropdown

**Comment by pavinduLakshan** [comment] 2019-07-21 10:55
But this doesn't work in the following code

```
<DropdownButton bsStyle="default" title="No caret" noCaret>                  
          <Dropdown.Item eventKey="1">Action</Dropdown.Item>
          <Dropdown.Item eventKey="2">Another action</Dropdown.Item>
          <Dropdown.Item eventKey="3">Something else here</Dropdown.Item>
          <Dropdown.Item divider />
          <Dropdown.Item eventKey="4">Separated link</Dropdown.Item>
</DropdownButton>
```
Result: 
http://imgur.com/a/5d5LDhk

**Comment by toinhao1** [comment] 2019-08-27 07:13
This does not work as the documentation suggests it does.
