### ISSUE TITLE
"@ng-bootstrap/ng-bootstrap": "12.0.0" ngbPopover is mispositioned when page has scrollbar and position is top

### ISSUE THREAD

**Issue by mivanyna** [ng-bootstrap/ng-bootstrap#4347] opened 2022-07-08 15:10 UTC
### Bug description:
Starting from "@ng-bootstrap/ng-bootstrap": "12.0.0" ngbPopover is mispositioned when **page has scrollbar and position is top**
For version v11 all works well.
Positions right, left, bottom works well.

v12
![image](https://user-images.githubusercontent.com/10868397/178012239-6f5cbbf2-a147-46f8-9b13-611378564f1b.png)

v11
![image](https://user-images.githubusercontent.com/10868397/178010926-7c71827f-8af0-44b2-b541-253313fb6908.png)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 13 or 14 (doesn't matter)

ng-bootstrap: 12.0.0 and later

Bootstrap: 5.0.0 or 5.1.3 (doesn't matter)

**Comment by fbasso** [comment] 2022-07-27 09:44
Hi @mivanyna, thanks you for reporting an issue

I'm not able to reproduce the issue from the demo site (https://ng-bootstrap.github.io/#/components/popover/examples#basic), even with the scrollbar, so I would need more information.

- What is the popper version that you use (since the version 12, we use it for the positioning, so it's a dependency you need to add),
- Is there some specific parameters/inputs that you use for your popover ?

The best would be to have a Stackblitz with the issue.

**Comment by mivanyna** [comment] 2022-07-27 12:39
Hi @fbasso , 
"@popperjs/core": "2.11.5", 

I have a separate component wrapper for tooltip, but the same behavior if I use:
```
<img src="./icon.svg"
                   class="info-icon"
                   container="body"
                   autoClose="outside"
                   ngbPopover="Some text here"
                   triggers="mouseenter:mouseleave"
                   placement="top">
```
I have sticky navigation on the left side of the page, but haven't found the root cause

**Comment by fbasso** [comment] 2022-07-27 14:27
I don't know if it's the case, but the 'sticky' navigation let me think that it's similar to #4345 (see the comment).

In this case, it should be solved by overriding the popper configuration once #4323 will be released.

**Comment by mivanyna** [comment] 2022-07-27 15:16
I have different styles for html tag 
<img width="271" alt="image" src="https://user-images.githubusercontent.com/10868397/181284289-645898ef-90f9-4dcc-adcf-7f1bda5144dd.png">

Do you know when that config option will be released?

**Comment by mivanyna** [comment] 2022-07-27 16:46
BTW, the strange thing about the issue is that bottom placement works well

**Comment by maxokorokov** [comment] 2022-08-11 08:57
> Do you know when that config option will be released?

`13.1.0` should be out this or next week

**Closed as completed** 2022-10-24 09:30 UTC
Labels: type: positioning
