### ISSUE TITLE
Pagination Based On Offset Value

### ISSUE THREAD

**Issue by laijuthomas** [ng-bootstrap/ng-bootstrap#2607] opened 2018-08-14 03:33 UTC
I have a list of data shown in a table with pagination and limit filter. I use ng bootstrap pagination component for the pagination. The issue I am facing is, If for example I have 51 entries and I show 15 entries per page, the total page count will be 4. If I navigate to second page the result will show from 16-30. And If I change the row limit to 30 from the second page, the result is showing from 16-45 and the paging updates to two pages. I am not able to move to see result from 46-51

**Comment by pkozlowski-opensource** [comment] 2018-08-14 06:25
Sorry, it is not clear from the description what is going on and I can't reproduce here: https://stackblitz.com/edit/angular-zppemp?file=app%2Fpagination-basic.html

But generally speaking it sounds like your calculations are a bit off: you should be taking items with indexes 15-29 for the second page (instead of 16-30);

> And If I change the row limit to 30 from the second page, the result is showing from 16-45 and the paging updates to two pages

Again, this sounds like a calculation hiccup, I can't see this in stackblitz.

Please provide a minimal reproduce scenario in stackblitz, otherwise it is not actionable. So far I can't see any fault in `<ngb-pagination>`

**Comment by laijuthomas** [comment] 2018-08-14 06:38
In the stackblitz provided you can see when we navigate to page 2 and change rows to 30, the results show from 30- 60. My requirement is when I am in page 1 the result show from 0-15 and when I navigate to page 2 it will show from 15-30 and if i change entries per page to 30 it should show from 15-45 as the page started from 15

**Comment by pkozlowski-opensource** [comment] 2018-08-14 08:34
> and if i change entries per page to 30 it should show from 15-45 as the page started from 15

Sorry, this is not how we designed it and it is not how it works. What you are asking for is to be on the page 1/2 which is not what we intend to support.

Closing as won't fix.

**Closed by pkozlowski-opensource** 2018-08-14 08:34 UTC
Labels: component: pagination, needs: plunkr / stackblitz

**Comment by laijuthomas** [comment] 2018-08-14 08:39
Thank you
