### ISSUE TITLE
can't use 'window' in NgbModal

### ISSUE THREAD

**Issue by JimWang1995** [ng-bootstrap/ng-bootstrap#2438] opened 2018-06-07 02:51 UTC
modalService : NgbModal
this.modalService.open(ComponentOne);
in ComponentOne   this.modalService.open(ComponentTwo);

in ComponentTwo console.log('window',window)

window ƒ window(windowBoundaries) {     return Object(__WEBPACK_IMPORTED_MODULE_0__operators_window__["a" /* window */])(windowBoundaries)(this); }

**Comment by pkozlowski-opensource** [comment] 2018-06-07 09:54
I'm sorry but there is not enough info here for anyone to understand what this issue is about and how we could help.  Here is a small stackblitz (forked from our [demo page](https://ng-bootstrap.github.io/#/components/modal/examples)) showing that window is defined and available: 
https://stackblitz.com/edit/angular-mf9m3u?file=app/modal-component.ts

Please try to modify this stackblitz to reproduce the issue you are facing - otherwise this issue is not actionable and will be closed per our issue template.

**Comment by JimWang1995** [comment] 2018-06-08 03:46
I can't reproduce this bug too.
![img](https://raw.githubusercontent.com/JimWang1995/pic/master/3.png)
The real cause of the problem has not yet been found.
What advice?

**Comment by pkozlowski-opensource** [comment] 2018-06-08 12:42
> What advice?

I'm sorry but I don't see how we could assist you without _seeing_ and _understanding_ the error. I'm afraid that at this point  you've got more context to figure out the root cause of the issue.

I'm going to close this issue for now as we don't have any reproduce scenario. Feel free to re-open whn / if you manage to reproduce in isolation.

**Closed by pkozlowski-opensource** 2018-06-08 12:42 UTC
Labels: component: modal, needs: info, needs: plunkr
