### ISSUE TITLE
Upgrade dependencies to Bootstrap 4 beta 3

### ISSUE THREAD

**Issue by bastienmoulia** [ng-bootstrap/ng-bootstrap#2062] opened 2017-12-29 14:38 UTC
With the release of [Bootstrap 4 beta 3](https://blog.getbootstrap.com/2017/12/28/bootstrap-4-beta-3/) we should fix some problems.

- [x] Remove checkbox / radio in Buttons
<img width="383" alt="capture d ecran 2017-12-29 a 15 20 21" src="https://user-images.githubusercontent.com/686196/34439094-d7afe4a8-ecab-11e7-8ec9-e41230a5b0d4.png">

- [x] Fix Datepicker in a popup
<img width="242" alt="capture d ecran 2017-12-29 a 15 23 52" src="https://user-images.githubusercontent.com/686196/34439171-4c77a96a-ecac-11e7-8d94-7b702ef05f1a.png">

- [x] Fix arrow margin in button group with nested dropdown
<img width="189" alt="capture d ecran 2017-12-29 a 15 30 26" src="https://user-images.githubusercontent.com/686196/34439311-3a32f1dc-ecad-11e7-9e9d-01d87ea21622.png">

I start to work on this, if you see another issue feel free to add it to this post.

**Comment by pkozlowski-opensource** [comment] 2017-12-29 16:23
> I start to work on this, if you see another issue feel free to add it to this post.

@bastienmoulia awesome! From over changelog it seems like checkbox / radios are indeed the most impacted ones. The good news that the styling was improved for those buttons so we will no longer require `data-*` for styling. 

The other note: not a bug, but a feature we will be able to offer from beta.3 - center modals vertically.

**Comment by bastienmoulia** [comment] 2017-12-29 16:37
@pkozlowski-opensource Yes, for now I focus on the fix, but modals vertically centered and dropleft / dropright could be next if i can.

**Comment by jnizet** [comment] 2017-12-29 23:30
I just migrated an app to beta.3, and had to make the following changes related to ng-bootstrap components:

 - add `btn-group-toggle` to `.btn-group`. Not sure if ng-bootstrap should add this class for us or not. It should however not add `data-toggle="buttons"` anymore.
 - add a custom CSS rule to fix the datepicker navigation selects: when inside a `.input-group` (i.e. every time we use a datepicker in a popup), their width is set to 1%. I worked around it by adding the following rule, but it should be fixed in the component: 
```
.input-group ngb-datepicker-navigation-select .custom-select {
  width: 50%;
}
```

**Comment by bastienmoulia** [comment] 2017-12-30 09:12
@jnizet 
- In my PR I add `.btn-group-toggle` manualy.
- I also changed the CSS of the datepicker-navigation-select component [here](https://github.com/bastienmoulia/ng-bootstrap/blob/404db7bc19a37815ef0bae130d4b6fb09940b2df/src/datepicker/datepicker-navigation-select.ts#L11) but there is still a little difference due to the parent class `.input-group`.

Without a popup:
<img width="224" alt="capture d ecran 2017-12-30 a 10 07 39" src="https://user-images.githubusercontent.com/686196/34452885-7592c968-ed49-11e7-870c-0f4f7e497ede.png">

With a popup:
<img width="227" alt="capture d ecran 2017-12-30 a 10 07 48" src="https://user-images.githubusercontent.com/686196/34452884-757b425c-ed49-11e7-85e5-3b279d733db1.png">

One solution is to add the class `.input-group` around the 2 `<select>`. Another is to force the CSS in the component. Will try later.

**Closed** 2018-01-05 10:03 UTC

**Comment by pkozlowski-opensource** [comment] 2018-01-08 14:39
@achimha users are expected to add the `.btn-group-toggle` manually for now, check the required markup at: https://ng-bootstrap.github.io/#/components/buttons/examples

We could add this class automatically for radios but not for checkboxes, which would create strange inconsistency.
