### ISSUE TITLE
Template parse warnings Browser log

### ISSUE THREAD

**Issue by lafama** [ng-bootstrap/ng-bootstrap#1354] opened 2017-03-02 09:09 UTC
### Bug description:

```
core.es5.js:231Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("[ERROR ->]<template ngFor [ngForOf]="parts" let-part let-isOdd="odd"><span *ngIf="isOdd" class="{{highlightClas"): NgbHighlight@0:0
The <template> element is deprecated. Use <ng-template> instead ("rOf]="parts" let-part let-isOdd="odd"><span *ngIf="isOdd" class="{{highlightClass}}">{{part}}</span>[ERROR ->]<template [ngIf]="!isOdd">{{part}}</template></template>"): NgbHighlight@0:121
_warn @ core.es5.js:231
warn @ core.es5.js:3474
parse @ compiler.es5.js:14236
_compileTemplate @ compiler.es5.js:29087
(anonymous) @ compiler.es5.js:28988
_compileComponents @ compiler.es5.js:28987
createResult @ compiler.es5.js:28860
ZoneDelegate.invoke @ zone.js:330
Zone.run @ zone.js:126
(anonymous) @ zone.js:679
ZoneDelegate.invokeTask @ zone.js:363
Zone.runTask @ zone.js:166
drainMicroTaskQueue @ zone.js:529
core.es5.js:231Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("
    [ERROR ->]<template #rt let-result="result" let-term="term" let-formatter="formatter">
      <ngb-highlight [re"): NgbTypeaheadWindow@1:4
The <template> element is deprecated. Use <ng-template> instead ("     <ngb-highlight [result]="formatter(result)" [term]="term"></ngb-highlight>
    </template>
    [ERROR ->]<template ngFor [ngForOf]="results" let-result let-idx="index">
      <button type="button" class="dr"): NgbTypeaheadWindow@4:4
The <template> element is deprecated. Use <ng-template> instead ("
        (mouseenter)="markActive(idx)" 
        (click)="select(result)">
          [ERROR ->]<template [ngTemplateOutlet]="resultTemplate || rt" 
          [ngOutletContext]="{result: result, te"): NgbTypeaheadWindow@8:10
_warn @ core.es5.js:231
warn @ core.es5.js:3474
parse @ compiler.es5.js:14236
_compileTemplate @ compiler.es5.js:29087
(anonymous) @ compiler.es5.js:28988
_compileComponents @ compiler.es5.js:28987
createResult @ compiler.es5.js:28860
ZoneDelegate.invoke @ zone.js:330
Zone.run @ zone.js:126
(anonymous) @ zone.js:679
ZoneDelegate.invokeTask @ zone.js:363
Zone.runTask @ zone.js:166
drainMicroTaskQueue @ zone.js:529
core.es5.js:231Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("
  <div class="card">
    [ERROR ->]<template ngFor let-panel [ngForOf]="panels">
      <div role="tab" id="{{panel.id}}-header" [attr.ar"): NgbAccordion@2:4
The <template> element is deprecated. Use <ng-template> instead ("  [attr.aria-expanded]="isOpen(panel.id)" [attr.aria-controls]="panel.id">
          {{panel.title}}[ERROR ->]<template [ngTemplateOutlet]="panel.titleTpl?.templateRef"></template>
        </a>
      </div>
"): NgbAccordion@8:25
The <template> element is deprecated. Use <ng-template> instead (" [attr.aria-labelledby]="panel.id + '-header'" class="card-block" *ngIf="isOpen(panel.id)">
        [ERROR ->]<template [ngTemplateOutlet]="panel.contentTpl.templateRef"></template>
      </div>
    </template>
"): NgbAccordion@12:8
_warn @ core.es5.js:231
warn @ core.es5.js:3474
parse @ compiler.es5.js:14236
_compileTemplate @ compiler.es5.js:29087
(anonymous) @ compiler.es5.js:28988
_compileComponents @ compiler.es5.js:28987
createResult @ compiler.es5.js:28860
ZoneDelegate.invoke @ zone.js:330
Zone.run @ zone.js:126
(anonymous) @ zone.js:679
ZoneDelegate.invokeTask @ zone.js:363
Zone.runTask @ zone.js:166
drainMicroTaskQueue @ zone.js:529
core.es5.js:231Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead (" *ngFor="let slide of slides" class="carousel-item" [class.active]="slide.id === activeId">
        [ERROR ->]<template [ngTemplateOutlet]="slide.tplRef"></template>
      </div>
    </div>
"): NgbCarousel@6:8
_warn @ core.es5.js:231
warn @ core.es5.js:3474
parse @ compiler.es5.js:14236
_compileTemplate @ compiler.es5.js:29087
(anonymous) @ compiler.es5.js:28988
_compileComponents @ compiler.es5.js:28987
createResult @ compiler.es5.js:28860
ZoneDelegate.invoke @ zone.js:330
Zone.run @ zone.js:126
(anonymous) @ zone.js:679
ZoneDelegate.invokeTask @ zone.js:363
Zone.runTask @ zone.js:166
drainMicroTaskQueue @ zone.js:529
core.es5.js:231Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("
    [ERROR ->]<template #dt let-date="date" let-currentMonth="currentMonth" let-selected="selected" let-disabled="d"): NgbDatepicker@1:4
The <template> element is deprecated. Use <ng-template> instead ("

    <div class="ngb-dp-months d-flex px-1 pb-1">
      [ERROR ->]<template ngFor let-month [ngForOf]="months" let-i="index">
        <div class="ngb-dp-month d-block "): NgbDatepicker@21:6
_warn @ core.es5.js:231
warn @ core.es5.js:3474
parse @ compiler.es5.js:14236
_compileTemplate @ compiler.es5.js:29087
(anonymous) @ compiler.es5.js:28988
_compileComponents @ compiler.es5.js:28987
createResult @ compiler.es5.js:28860
ZoneDelegate.invoke @ zone.js:330
Zone.run @ zone.js:126
(anonymous) @ zone.js:679
ZoneDelegate.invokeTask @ zone.js:363
Zone.runTask @ zone.js:166
drainMicroTaskQueue @ zone.js:529
core.es5.js:231Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("Disabled(day)"
      [class.collapsed]="isCollapsed(day)" [class.hidden]="isHidden(day)">
          [ERROR ->]<template [ngTemplateOutlet]="dayTemplate"
          [ngOutletContext]="{date: {year: day.date.year, "): NgbDatepickerMonthView@11:10
_warn @ core.es5.js:231
warn @ core.es5.js:3474
parse @ compiler.es5.js:14236
_compileTemplate @ compiler.es5.js:29087
(anonymous) @ compiler.es5.js:28988
_compileComponents @ compiler.es5.js:28987
createResult @ compiler.es5.js:28860
ZoneDelegate.invoke @ zone.js:330
Zone.run @ zone.js:126
(anonymous) @ zone.js:679
ZoneDelegate.invokeTask @ zone.js:363
Zone.runTask @ zone.js:166
drainMicroTaskQueue @ zone.js:529
core.es5.js:231 Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("
    [ERROR ->]<template #t let-fill="fill">{{ fill === 100 ? '&#9733;' : '&#9734;' }}</template>
    <span tabindex"): NgbRating@1:4
The <template> element is deprecated. Use <ng-template> instead ("ttr.aria-valuemax]="max" [attr.aria-valuenow]="rate" [attr.aria-valuetext]="ariaValueText()">
      [ERROR ->]<template ngFor [ngForOf]="range" let-index="index">
        <span class="sr-only">({{ index < rate ?"): NgbRating@4:6
The <template> element is deprecated. Use <ng-template> instead ("" (click)="update(index + 1)" 
        [style.cursor]="readonly ? 'default' : 'pointer'">
          [ERROR ->]<template [ngTemplateOutlet]="starTemplate || t" [ngOutletContext]="{fill: getFillValue(index)}"></te"): NgbRating@8:10
_warn @ core.es5.js:231
warn @ core.es5.js:3474
parse @ compiler.es5.js:14236
_compileTemplate @ compiler.es5.js:29087
(anonymous) @ compiler.es5.js:28988
_compileComponents @ compiler.es5.js:28987
createResult @ compiler.es5.js:28860
ZoneDelegate.invoke @ zone.js:330
Zone.run @ zone.js:126
(anonymous) @ zone.js:679
ZoneDelegate.invokeTask @ zone.js:363
Zone.runTask @ zone.js:166
drainMicroTaskQueue @ zone.js:529
core.es5.js:231 Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("ia-controls]="tab.id + '-panel'" [attr.aria-expanded]="tab.id === activeId">
          {{tab.title}}[ERROR ->]<template [ngTemplateOutlet]="tab.titleTpl?.templateRef"></template>
        </a>
      </li>
"): NgbTabset@5:23
The <template> element is deprecated. Use <ng-template> instead ("
    </ul>
    <div class="tab-content">
      [ERROR ->]<template ngFor let-tab [ngForOf]="tabs">
        <div class="tab-pane active" *ngIf="tab.id === acti"): NgbTabset@10:6
The <template> element is deprecated. Use <ng-template> instead ("b.id === activeId" role="tabpanel" [attr.aria-labelledby]="tab.id" id="{{tab.id}}-panel">
          [ERROR ->]<template [ngTemplateOutlet]="tab.contentTpl.templateRef"></template>
        </div>
      </template"): NgbTabset@12:10
_warn @ core.es5.js:231
warn @ core.es5.js:3474
parse @ compiler.es5.js:14236
_compileTemplate @ compiler.es5.js:29087
(anonymous) @ compiler.es5.js:28988
_compileComponents @ compiler.es5.js:28987
createResult @ compiler.es5.js:28860
ZoneDelegate.invoke @ zone.js:330
Zone.run @ zone.js:126
(anonymous) @ zone.js:679
ZoneDelegate.invokeTask @ zone.js:363
Zone.runTask @ zone.js:166
drainMicroTaskQueue @ zone.js:529
core.es5.js:231 Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("
            </button>
          </td>
          [ERROR ->]<template [ngIf]="seconds">
            <td>&nbsp;</td>
            <td class="text-center">
"): NgbTimepicker@17:10
The <template> element is deprecated. Use <ng-template> instead ("
            </td>
          </template>
          [ERROR ->]<template [ngIf]="meridian">
            <td>&nbsp;</td>
            <td>&nbsp;</td>
"): NgbTimepicker@26:10
The <template> element is deprecated. Use <ng-template> instead ("
              [readonly]="readonlyInputs" [disabled]="disabled">
          </td>
          [ERROR ->]<template [ngIf]="seconds">
            <td>&nbsp;:&nbsp;</td>
            <td>
"): NgbTimepicker@43:10
The <template> element is deprecated. Use <ng-template> instead ("
            </td>
          </template>
          [ERROR ->]<template [ngIf]="meridian">
            <td>&nbsp;&nbsp;</td>
            <td>
"): NgbTimepicker@51:10
The <template> element is deprecated. Use <ng-template> instead ("
            </button>
          </td>
          [ERROR ->]<template [ngIf]="seconds">
            <td>&nbsp;</td>
            <td class="text-center">
"): NgbTimepicker@73:10
The <template> element is deprecated. Use <ng-template> instead ("
            </td>
          </template>
          [ERROR ->]<template [ngIf]="meridian">
            <td>&nbsp;</td>
            <td>&nbsp;</td>
"): NgbTimepicker@82:10

```
### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:4.0.0-rc.2

ng-bootstrap:1.0.0-alpha.20

Bootstrap:

**Comment by pkozlowski-opensource** [comment] 2017-03-02 09:11
Duplicate of #1337 - we will move to `<ng-template>` and dependency on Angular 4.0.x as soon as a stable version is released.

**Closed by pkozlowski-opensource** 2017-03-02 09:11 UTC
