### ISSUE TITLE
ngbTooltip placement issue when inside other text

### ISSUE THREAD

**Issue by dereklin** [ng-bootstrap/ng-bootstrap#1896] opened 2017-10-12 20:11 UTC
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
When using ngbTooltip inside other text, the tooltip placement is not stable
### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/mqliRNfHFvFVi7W160Q7?p=preview

When you resize the window, making it smaller and larger, you might see different placement issues

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.3.5 and above

ng-bootstrap: 1.0.0-beta.5

Bootstrap: 4.0.0-beta

**Comment by mschoudry** [comment] 2017-10-18 13:20
The problem is with the max-width specified inside .tooltip-inner. remove it and the tooltip will be ok.

Regards,

**Comment by pkozlowski-opensource** [comment] 2018-03-02 11:25
This is fixed in the latest version of this library (1.0.0) and Bootstrap CSS 4.0.0: http://plnkr.co/edit/3dUpcB0IWH9wBEBUaAEX?p=preview

**Closed by pkozlowski-opensource** 2018-03-02 11:25 UTC
Labels: component: tooltip, needs: investigation
