### ISSUE TITLE
Typeahead - Showing conditionally the list

### ISSUE THREAD

**Issue by abelardolg** [ng-bootstrap/ng-bootstrap#2327] opened 2018-04-19 11:43 UTC
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

[x] Feature request

### Bug description:
I would like to show conditionally the list when the typeahead gets the focus. It could be passed a flag to indicate if show, or not, the list of items on focus.

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2.10

ng-bootstrap: last version.

Bootstrap: 4.1.0

**Comment by pkozlowski-opensource** [comment] 2018-04-19 12:02
* check the "Open on focus" example at https://ng-bootstrap.github.io/#/components/typeahead/examples
* we plan to make it easier in the future via #2318

Closing as a duplicate of #2318

**Closed by pkozlowski-opensource** 2018-04-19 12:02 UTC
