### ISSUE TITLE
Tab caption not updates from dynamically created tab content component

### ISSUE THREAD

**Issue by AbakumovAlexandr** [ng-bootstrap/ng-bootstrap#2428] opened 2018-06-01 16:26 UTC
### Bug description:
I have an app with all components being `ChangeDetectionStrategy.OnPush` and it has the following parts:

- tab service holding current tabs
- menu component which adds new tabs to current tabs array
- tabset component which holds layout necessary for `ngb-tabset`
- bunch of tab content components that are created dynamically via `ngComponentOutlet` in tabset component

Tab content components are supposed to change tab caption however they want. But it doesn't work with `ngb-tabset`. When I model `ngb-tabset` layout with simple `div`s everything works fine.

### Link to minimally-working plunker that reproduces the issue:
https://stackblitz.com/edit/ng-bootstrap-tab-caption-test
You can check it by commenting `ngb-tabset`-based implementation and uncommenting the one based on `div`s in `tabset.component.html`. Captions would become `Caption from component` instead of `Default caption`.

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular: 6.0.3
ng-bootstrap: 2.0.0
Bootstrap: 4.1.1

**Comment by benouat** [comment] 2018-06-20 09:36
I just add a look at your stackblitz trying to understand how things are happening.

To me the issue is not coming from `ngb-tabset` but from the usage of `ng-template` made by `ngb-tabset`

When you are using `ng-template` inside a component, by the time this template is used (ie. by the time the underlying embeddedView is created and used) it is directly changed detected, way before the component using the `ngb-tabset` is changed detected itself. This is why it looks like it's always 1 or 2 change detections behind.

So you _think_ your example is working without using `ngb-tabset`, but it is actually not if you do what `ngb-tabset` would be doing. It is using `ng-template` and you're not.

Simply update your example like so:

```html
<div *ngFor="let tab of tabService.tabs | async" class="tabset">
  
  <!-- wrap to emulate what ngb-tabset would do -->
  <ng-template [ngIf]="true">
    <div class="tab-caption">{{ tab.caption | async }}</div>
  </ng-template>

  <!-- wrap to emulate what ngb-tabset would do -->
  <ng-template [ngIf]="true">
    <div *ngComponentOutlet="DynamicComponent; injector: tab.componentInjector" class="tab-content"></div>
  </ng-template>
</div>
```

and you'll start to see it is **not** working as well.

Thus I would say that this is not an `ngb-tabset` related issue. Actually there is no issue at all here, Angular things are occurring like this by design.

So, regarding what you want to achieve, you should probably try to implement it differently, sorry for that... 😞

Hope it'll help!

**Comment by pkozlowski-opensource** [comment] 2018-06-20 12:20
@benouat explanation is spot-on here, thnx! In short - it has nothing to do with `OnPush` but rather with order of change detection for dynamically created views.

@AbakumovAlexandr it is not super-clear what you are trying to achieve but our _feeling_ is that you are trying to set tab title from a dynamically created component. If this is the case the approach you are trying to employ here won't and can't work: tabs are meant to be created lazily (and destroyed when not used). A given tab content will be created _only_ when switching to a said tab. With your approach you couldn't display title till actually switching to a tab which doesn't make sense from a user point of view.

Again, I'm not sure if I understand your desired result correctly but it feels like you might have specific needs that are not covered in the design / implementation of the current tabset. You might consider rolling out a specific widget for your particular needs.

Going to close this one as everything works as expected / designed (still, acknowledging that it might not be what you are looking for...).

**Closed by pkozlowski-opensource** 2018-06-20 12:20 UTC

**Comment by AbakumovAlexandr** [comment] 2018-06-20 21:38
@benouat and @pkozlowski-opensource , thank you so much, guys, for the detailed explanations.

I've created another [Stackblitz](https://stackblitz.com/edit/ng-template-update-parent?file=app%2Fapp.component.ts) without the NGB involvement to reproduce my use case and based my SO [question](https://stackoverflow.com/q/50957041/3345644) on it. I now know it's out of scope of this project, but I'd appreciate if you could an idea of what is the cleanest Angular-ish way to update tab title from tab content.

@pkozlowski-opensource, you've spotted it correctly: I'm trying to update a tab title from a tab content. However, I'd like to comment on your point:

> If this is the case the approach you are trying to employ here won't and can't work: tabs are meant to be created lazily (and destroyed when not used). A given tab content will be created only when switching to a said tab. With your approach you couldn't display title till actually switching to a tab which doesn't make sense from a user point of view.

I realize that tab content is lazily created and that's why my tabs have a default title :) But after tab content is created (and any time later), the tab content should be able to change its tab title however it likes. This is what my use case looks like.

I also updated my first Stackblitz to exclude dynamic tab content creation with `ngComponentOutlet` since it turned out it's irrelevant to the problem:
```
        <ng-template ngbTabContent>
            <dynamic-component [tab]="tab"></dynamic-component>
            <!-- <ng-container *ngComponentOutlet="DynamicComponent; injector: tab.componentInjector"></ng-container> -->
        </ng-template>
```
