### ISSUE TITLE
ngbCollapse not working because of display property being overriden

### ISSUE THREAD

**Issue by Qi-Z** [ng-bootstrap/ng-bootstrap#2172] opened 2018-02-16 20:53 UTC
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
`<div id="collapseExample" [ngbCollapse]="isCollapsed" class="block">`
When `ngbCollapse` is applied on an element with `display` property, say, `block`, toggle for collapse or expand won't work.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/vqSn7njQVA5dJasW1XBv?p=info

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.0.2

ng-bootstrap: 1.0.0

Bootstrap: 4.0.0

**Comment by gorkemerdogann** [comment] 2018-02-21 14:39
Yes, it doesn't work if set `display: block` or add class with contains `display: block`. Because it only add `show` class for show element and remove that class for collapse.`show` class work with display property. I tested with #1839 PR changes locally and works perfectly. When they are merge #1839 PR, this issue will fix. 😊

**Comment by Qi-Z** [comment] 2018-02-21 20:23
Nice to see ngbCollapse become powerful 👍

**Comment by pkozlowski-opensource** [comment] 2018-03-02 15:13
Of course, it won't work since Bootstrap CSS uses the `show` class that flips `display: none` <=> `display: block`. If you force it to `block` you will never see the collapsing effect.

I'm going to close this issue here as the problem steams from the Bootstrap CSS and the same issue could be reproduced with pure Bootstrap, without using this library.

**Closed by pkozlowski-opensource** 2018-03-02 15:13 UTC
Labels: component: collapse, needs: investigation
