### ISSUE TITLE
Typeahead zero min length in Angular2

### ISSUE THREAD

**Issue by michalkopula** [ng-bootstrap/ng-bootstrap#1333] opened 2017-02-24 07:37 UTC
Is it possible (or planned) to have similar functionality like the library had in Angular1 which allows to open typeahead on focus? typeahead-min-length="0" parameter assured that before.

**Comment by pkozlowski-opensource** [comment] 2017-02-24 11:48
Duplicate of #698

**Closed by pkozlowski-opensource** 2017-02-24 11:48 UTC
