### ISSUE TITLE
is there any animation feature available in ng-carousel to left to right transition or how to do that for this library,please help

### ISSUE THREAD

**Issue by hemanthsp** [ng-bootstrap/ng-bootstrap#2176] opened 2018-02-19 10:27 UTC

**Comment by cristianmartinez** [comment] 2018-02-20 04:11
Hey @hemanthsp, I just looked into the code and there are not options for animations.
But I think you can play with the css3 animation and the DOM class.

The active item always have the `.carousel-item.active` class. The `.active` part is removed when a different item is the active one. So, you can try something like this:

.carousel-item {
  /* Force to always be block */
  display: block !important;
  z-index: 1;
  position: absolute;
  transform: translateX(100%);
  opacity: 0;
  transition:all  0.2s;
  visibility: hidden;
}

.carousel-item.active {
  position: relative;
  transform: translateX(0);
  visibility: visible ;
  opacity: 1;
}

The animation is pretty simple, but you can play with it.

Hope this help.

**Comment by hemanthsp** [comment] 2018-02-20 04:30
bro  your code is super but according to your code animation is like " when i click arrows of the slider the images start from right and gone in right place for both arrows" but i need to do like rotate left to right when click on right arrows and vice verse please, i am just kid in animation css

**Comment by pkozlowski-opensource** [comment] 2018-02-25 15:49
Duplicate of #1823

**Closed by pkozlowski-opensource** 2018-02-25 15:49 UTC

**Comment by hemanthsp** [comment] 2018-02-26 07:58
my issues solved in #1823

**Comment by foo-baar** [comment] 2020-05-04 23:19
@hemanthsp Wondering how did you achieved it finally? #1823 doesn't have much details

**Comment by kabrender** [comment] 2020-07-03 08:52
Hello @foo-baar,
you can define your own class attribute and your own event listener.
Than you can differantiate it in the CSS file.

**class attribute:**
 <ngb-carousel  [ngClass]="direction" (slide)="sliderOn($event)" ...>

**event listener:**
sliderOn(event) {
   this.direction = event.direction;
}

**CSS**
.left .carousel-item.active {
animation-name: slideLeftIn;
 }

.left .carousel-item.active {
animation-name: slideRightIn; 
}

**Comment by foo-baar** [comment] 2020-07-05 00:48
@kabrender No it doesn't work unless you are missing some piece of information above, are intending to add these classes anywhere? .left and .right ?

**Comment by fbasso** [comment] 2020-07-06 07:25
For information, animations are now actively developed. See #2817 and the dedicated branch https://github.com/ng-bootstrap/ng-bootstrap/tree/animations.
