### ISSUE TITLE
feature(typeahead): Be able to format before calling _onChange

### ISSUE THREAD

**Issue by marcalj** [ng-bootstrap/ng-bootstrap#1226] opened 2017-01-18 19:37 UTC
Use case for Typeahead. Take the flags example from docs:
https://ng-bootstrap.github.io/app/components/typeahead/demos/template/plnkr.html

When selected "Colorado", the ```model``` variable contains: 

```json
Model: {
  "name": "Colorado",
  "flag": "4/46/Flag_of_Colorado.svg/45px-Flag_of_Colorado.svg.png"
}
```

But I want this variable to contain the ```name``` property, "Colorado".

Maybe with another formatter function. It's strange to have a string when typing another option:

Typings: "colorado 222", ```model : "colorado 222"```. A different representation.

Noting that I want to access the complete object properties in templates and formatters. Just to parse the value passed to ```this._onChange(value);```

Thanks!

**Comment by pkozlowski-opensource** [comment] 2017-01-18 20:01
Duplicate of #611

**Closed by pkozlowski-opensource** 2017-01-18 20:01 UTC

**Comment by marcalj** [comment] 2017-01-19 09:48
@pkozlowski-opensource Any news from the core team about this use cases for ngModel? :)
Thanks!
