### ISSUE TITLE
NgbPopover - Opening popover in AfterViewInit throws ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by wclaibor** [ng-bootstrap/ng-bootstrap#3242] opened 2019-06-18 22:07 UTC
### Bug description:
When you try to open a NgbPopover using the manual trigger inside of the ngAfterViewInit angular lifecycle hook, the ExpressionChangedAfterItHasBeenCheckedError is thrown. 

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/ngb-popover-expression-changed-after-checked?file=app%2Fpopover-triggers.ts

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.0.0

ng-bootstrap: 4.2.1

Bootstrap: 4.1.2

**Comment by IAfanasov** [comment] 2019-06-19 05:37
feels like expected behavior. take a look into [the article](https://blog.angularindepth.com/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error-e3fd9ce7dbb4) to better understand it.
Popover need to modify DOM and ngAfterViewInit not a suitable place for such operation

**Comment by benouat** [comment] 2019-06-19 06:54
Unfortunately, as mentioned by @IAfanasov, this lifecycle hook is not suitable for that.

It occurs for any widget mutating the DOM: NgbModal, NgbPopover, NgbTooltip... it would also occur with a simple NgbDropdown or NgbDatepicker. Literally anything that would create dynamically some DOM nodes using bindings.

It's an Angular issue and I'm afraid that we don't have any great solution here - your best option for now is to wrap popover opening logic into `setTimeout(...)` ...

Closing as duplicate of https://github.com/angular/angular/issues/15634

**Closed by benouat** 2019-06-19 06:54 UTC
Labels: blocked: Angular issue, resolution: Angular issue, type: bug
