### ISSUE TITLE
Indextab="-1" on Bootstrap modals not works

### ISSUE THREAD

**Issue by CarlosTenorio** [ng-bootstrap/ng-bootstrap#1647] opened 2017-06-30 08:06 UTC
### Bug description:
When the bootstrap modal has tabindex="-1", tabbing does not return focus to the first element in the modal. It puts focus onto the background elements. With Bootstrap works fine but with the ng-bootstrap fails

## Minimal reproduction of the problem with instructions
https://embed.plnkr.co/zPlXP3DNlKkM17H590i3/

## Environment
Browser:
- Chrome (desktop) version 59.0.3071.115

Platform: 
- Windows

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.1.0

ng-bootstrap: 1.0.0-alpha.26

Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment] 2017-06-30 08:58
Duplicate of #642

**Closed by pkozlowski-opensource** 2017-06-30 08:58 UTC
