### ISSUE TITLE
Make full ng-panel header clickable to collapse/uncollapse content.

### ISSUE THREAD

**Issue by dgpuranik** [ng-bootstrap/ng-bootstrap#2337] opened 2018-04-22 07:59 UTC
This is a feature request. 

I will give you a scenario, I am displaying a menu of the restaurant with diffetent categories. The ngb-panel title is category name. In the current implementation, I have to click the category name to collapse and uncollapse menu items in that particular category. If I click anywhere else in the header nothing happens.

Angular: 5.2.9

ng-bootstrap: 1.1.2

Bootstrap: 4.1.0

**Comment by pkozlowski-opensource** [comment] 2018-04-22 14:04
This is a duplicate of the existing issues #465 and #717

**Closed by pkozlowski-opensource** 2018-04-22 14:04 UTC

**Comment by rmvanmeeuwen** [comment] 2018-10-19 08:08
I just use the following css styling, which worked ok for me:
`span.card-header-link {
    width: 100% !important;
}`

**Comment by Jagan555** [comment] 2019-03-22 05:44
The above methods are not working. Please follow mine to get a desired result.
I found the solution after some digging.

In the angular-cli.json file was the following:
`"apps": [
{
  "root": "src",
  "outDir": "dist",
  "assets": [
    "assets",
    "favicon.ico"
  ],
  "index": "index.html",
  "main": "main.ts",
  "test": "test.ts",
  "tsconfig": "tsconfig.json",
  "prefix": "app",
  "mobile": false,
  "styles": [
    "styles.css",
    "../node_modules/bootstrap/dist/css/bootstrap.min.css"
  ],
  "scripts": [],
  "environments": {
    "source": "environments/environment.ts",
    "dev": "environments/environment.ts",
    "prod": "environments/environment.prod.ts"
  }
}`

I just needed to switch the order of the styles
`"styles": [
    "../node_modules/bootstrap/dist/css/bootstrap.min.css",
    "styles.css"
  ],`

Originally decribed @ https://stackoverflow.com/questions/41101685/how-to-override-twitter-bootstrap-styles-in-angular2-with-ng2-bootstrap

**Comment by mtpultz** [comment] 2019-04-09 00:38
CSS solution still works, but requires the use of a button instead of an anchor

```
ngb-accordion .card-header > button {
  text-align: left;
  width: 100%;
  height: 100%;
}
```
