### ISSUE TITLE
popover positioning problem for Mobiles

### ISSUE THREAD

**Issue by sateesh2020** [ng-bootstrap/ng-bootstrap#1036] opened 2016-11-13 14:12 UTC
### Bug description:
The Positioning of the popover in mobile devices are not perfect. Half of the popover is hiding from the screen due to negative left px values.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/qJy83oAoRhC8GI8adqOl?p=preview

Open the above link in Mobile view.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.1.0

ng-bootstrap: v1.0.0-alpha.11

Bootstrap: v4-alpha

**Comment by pkozlowski-opensource** [comment] 2016-11-13 14:26
* it is not specific to mobile
* a proper solution will be delivered via #992

Closing as a duplicate of #992

**Closed by pkozlowski-opensource** 2016-11-13 14:26 UTC

**Comment by Bala-BUI0011** [comment] 2024-08-27 07:20
#@
```

``` ### 

- [ ] ![inspection_files_1683117349988](https://github.com/user-attachments/assets/e763acc5-3b96-4089-8f3f-86e0787821e4)
