### ISSUE TITLE
Bug: ngbDatePicker always ngInvalid with any smart validators in Reactive Form

### ISSUE THREAD

**Issue by mixalbl4-127** [ng-bootstrap/ng-bootstrap#1773] opened 2017-08-24 14:33 UTC
I've fount a bug with validator and ngbDatePicker.
ngbDatePicker convert **string** value to object like { "year": 2011, "month": 10, "day": 22 } and validator can't work with it, because it expect string "2011-10-22" instead of object

bug demo: http://plnkr.co/edit/9iTmp8WoC8jJv4pTMNeS?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.3.3

ng-bootstrap: 1.0.0-beta.2

Bootstrap: 4.0.0-beta

**Comment by pkozlowski-opensource** [comment] 2017-08-24 14:42
> ngbDatePicker convert string value to object like { "year": 2011, "month": 10, "day": 22 }

This is by design and _might_ eventually change, see #1753

>  and validator can't work with it, because it expect string "2011-10-22" instead of object

As of today you would have to adapt your validator to work with the structure returned by the datepicker. Please note that currently datepicker _has_ build in validation:
* will fail if invalid date is entered
* will fail if a date outside of a specified range (min / max) is entered
* it will also fail validation if a disable date is entered manually. 

I'm not sure what you are trying to validate _exactly_ but just trying to match string entered by a user is not a proper way of going about things. You validation should be happening on the model (in this case, a structure propagated by a datepicker).

Closing as invalid.

**Closed by pkozlowski-opensource** 2017-08-24 14:42 UTC

**Comment by winstonma** [comment] 2017-08-31 12:23
Hi, the only validation problem I faced is I used the following code.

```
                    <div class="input-group">
                        <input class="form-control"
                               placeholder="Please use the calendar button to select the date"
                               name="dob" [(ngModel)]="dob"
                               ngbDatepicker #d="ngbDatepicker"
                               required #dob="ngModel"
                               pattern="[0-9]{4}-(0[1-9]|1[012])-(0[1-9]|1[0-9]|2[0-9]|3[01])"
                               disabled
                               [ngClass]="{'is-invalid': dob.invalid && (dob.dirty || dob.touched)}"/>
                        <div class="input-group-addon" (click)="d.toggle()">
                            <i class="fa fa-calendar" aria-hidden="true"></i>
                        </div>
                    </div>
```

I currently disabled the user input and forced the user to select the date from the calendar. My question is

1. The submit button of the form should be enabled when the date is being picked. But in my case the submit button is shown even if the user didn't select any date from the calendar. How could it be fixed?
2. Based on your answer above, should I remove the pattern check?

Thanks a lot
