### ISSUE TITLE
Undependent Modal Component

### ISSUE THREAD

**Issue by kolkov** [ng-bootstrap/ng-bootstrap#712] opened 2016-09-09 18:57 UTC
Hi!
Is it possible to use Modal as separately component or module with any settings, params and with embedded templates as in Angular 1 like below?

App module:

```
'use strict';
angular
    .module('app', ['common.modal'])
    .config(Config)
```

Controller or Service:
```
function showModal() {
            var formData = {id: "1", name: "Ivan", };            
            var modalInstance = $uibModal.open({
                animation: true,
                templateUrl: 'app/private/base/person/new.html',
                controller: 'ModalInstanceCtrl',
                controllerAs: "vm",
                size: size,
                resolve: {
                    data: function () {
                        return formData;
                    }
                }
            });
            modalInstance.result.then(function (resultFrom) {
                var result = resultFrom;
                result.uid = AuthService.getUID();
                result.characterId = parseInt(result.characterId);
                save(result)
                    .then(function(data){
                        $log.info(data);
                        $rootScope.$emit('newPerson', true);
                    })
                    .catch(function () {
                        $rootScope.$emit('newPerson', false);
                    });
            });
        }
```

ModalInstance controller:

```
'use strict';

ModalInstanceController.$inject = ["$uibModalInstance", "data"];

export default function ModalInstanceController($uibModalInstance, data) {
    var vm = this;
    vm.formData = data;

    vm.ok = function (modalData, modalForm) {
        if(modalForm.$valid) {
            $uibModalInstance.close(modalData);
        }
    };

    vm.cancel = function () {
        $uibModalInstance.dismiss('cancel');
    };
}
```

Modal module:

```
import ModalInstanceController from './modal.controller'

'use strict';
    angular
        .module('common.modal', [])
        .controller('ModalInstanceCtrl', ModalInstanceController);

```

**Comment by pkozlowski-opensource** [comment] 2016-09-10 05:16
Duplicate of #680

**Closed by pkozlowski-opensource** 2016-09-10 05:16 UTC
