### ISSUE TITLE
Datepicker's Month Arrows Styled Differently in Bootstrap Beta 2

### ISSUE THREAD

**Issue by jacroe** [ng-bootstrap/ng-bootstrap#1925] opened 2017-10-31 18:39 UTC
### Bug description:

Datepicker's arrow buttons to switch months lost/gained some additional styles in moving to Bootstrap v4 Beta 2.

### Link to minimally-working plunker that reproduces the issue:

Forked from the Plunker from the website: http://plnkr.co/edit/qWgqIau2Mc0Dx7XXOQ7Y?p=preview

Only edit was changing the Bootstrap version to the 2nd beta.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.0.3 (from the fork), 4.4.6 (locally)

ng-bootstrap: 1.0.0-beta.5 (from the fork)

Bootstrap: v4 Beta 2

**Comment by maxokorokov** [comment] 2017-10-31 18:42
Duplicate of #1851. Should de fixed in `beta.6`

**Closed by maxokorokov** 2017-10-31 18:42 UTC
Labels: component: datepicker, resolution: duplicate
