### ISSUE TITLE
Cannot use the router outlet inside of a tab

### ISSUE THREAD

**Issue by mattlewis92** [ng-bootstrap/ng-bootstrap#1167] opened 2016-12-29 16:18 UTC
### Bug description:
Placing a router-outlet inside of an ngbTab works on the first load, but then if you change the tab and then switch the tab back again the outlet content is gone.

The issue appears to be related to the ngIf used [here](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/tabset/tabset.ts#L92) which by design is incompatible with the router: https://github.com/angular/angular/issues/11100

The only obvious solution I can see to this is an option to use `[hidden]="true"` instead of the ngIf i.e. by default the ngIf will still be used to preserve backwards compatibility (and keep the performance benefit), but the new option would only hide the content e.g.

`*ngIf="!keepInDom && tab.id === activeId" [hidden]="keepInDom && tab.id !== activeId"`

The `[keepInDom]="true"` option could probably use some bikeshedding.

If you're happy with the implementation, I will send a PR that implements it.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/7uYe1ymKOGJ4OHV3JpJa?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.4.1

ng-bootstrap: 1.0.0-alpha.15

Bootstrap: 4

**Comment by pkozlowski-opensource** [comment] 2016-12-29 16:21
This is roughly duplicate of #1161 (that is, #1161 is about hiding DOM of panels instead of destroying).

TBH I'm on the fence when it comes to this feature request - for sure it would require design, Let's centralize discussion in  #1161

**Closed by pkozlowski-opensource** 2016-12-29 16:21 UTC
