### ISSUE TITLE
Error when opening modal in ngOnChanges

### ISSUE THREAD

**Issue by jspizziri** [ng-bootstrap/ng-bootstrap#1604] opened 2017-06-03 12:01 UTC
### Bug description:
Attempting to open a modal as the result of a change via `ngOnChanges` results in an:

```
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'modal fade show'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?
```

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/svQOUKKRvyWlioopFTjy?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:
- Angular: `angular@4.0.3`
- ng-bootstrap: `ng-bootstrap@1.0.0-alpha.26`
- Bootstrap: `bootstrap@4.0.0-alpha.6`

**Comment by wesleycho** [comment] 2017-06-03 17:56
This Plunker is a bit artificial - can you give a little more context as to what you are trying to accomplish exactly so we could maybe better figure out what the intensions are?

**Comment by pkozlowski-opensource** [comment] 2017-06-03 19:58
This is Angular's limitation, see: https://github.com/angular/angular/issues/15634

More details in https://github.com/ng-bootstrap/ng-bootstrap/issues/1384

Closing as a duplicate of https://github.com/angular/angular/issues/15634

**Closed by pkozlowski-opensource** 2017-06-03 19:58 UTC
Labels: component: modal, needs: info

**Comment by abnersouza** [comment] 2018-01-22 13:37
I found a workaround in my case, where i have a login form then pressing key enter i open a NgbModal.

I did the following:
1. Added the #formElement to the my <form>
2. Then in the ts I added @ViewChild('formElement') formElement: ElementRef;
3. On the Submit event i do the following:
this.formElement.nativeElement.ownerDocument.activeElement.blur();

Solved :)

Tried all the other ways like setTimeout and no success

**Comment by envil** [comment] 2018-04-20 09:04
@abnersouza ab
After 2 days of wandering on the internet, your solution finally fixed my problem!

**Comment by SandeepThomas** [comment] 2018-12-06 05:43
> I found a workaround in my case, where i have a login form then pressing key enter i open a NgbModal.
> 
> I did the following:
> 
> 1. Added the #formElement to the my form html tag
> 2. Then in the ts I added @ViewChild('formElement') formElement: ElementRef;
> 3. On the Submit event i do the following:
>    this.formElement.nativeElement.ownerDocument.activeElement.blur();
> 
> Solved :)
> 
> Tried all the other ways like setTimeout and no success

A better solution from Stackoverflow:

Inject a Renderer into your component/directive.

Get a hold of any elementRef (for example your button or link).

constructor(private elRef: ElementRef, private renderer: Renderer){
}
then in your handler function:

this.renderer.invokeElementMethod(this.elRef.nativeElement.ownerDocument.activeElement, 'blur');

https://stackoverflow.com/a/40368311/10293213
