### ISSUE TITLE
Alert: No 'close' event when the alert is self-closed

### ISSUE THREAD

**Issue by kennotek** [ng-bootstrap/ng-bootstrap#705] opened 2016-09-08 16:32 UTC
When 'dismissible' I get a 'close' event so I can remove the alert from the alert array.
A 'close' event is not received when the alert is self-closed.

Angular: 2-rc.5

ng-bootstrap: 1.0.0-alpha.4

Bootstrap: 4.0.0-alpha.4

**Comment by pkozlowski-opensource** [comment] 2016-09-08 16:42
@kennotek I'm sorry but it is not clear what you are saying. Please provide a minimal reproduce scenario.

Generally speaking you do _not_ want to use self-closable alerts if you control their visibility based on some model entires.

**Comment by kennotek** [comment] 2016-09-08 16:55
In your self-closing alert example you have a button that adds alerts to an array.
This array is displayed and as the alerts timeout they are no longer seen.
But, in the html, the <p> elements still exist because the alerts are still in the array.
If there a lot of alerts that go up in an application, that array could get large.

If the alert is closable and the close button is selected, the close event can be used
to remove the alert from the array (see closable alert example). This also works
in a self-closable scenario if it is dismissible and the close button is selected.

I would like to remove the messages that are closed, either by selecting the close
button or by a timeout.

**Comment by Quinn-L** [comment] 2016-09-09 05:14
Yep, there's an issue here. Self-closing alerts still need to be cleaned up in the back-end like the 'Closable Alert' does (ie. remove the alert object from the array on the `close` event), otherwise the element in the `*ngFor` that contains the template remains in the browser since the object still exists in the array (the alert itself gets removed, though).

The self-closing alert does have a `close` event, however this doesn't get triggered since both the code and documentation state it's only called when the close button is clicked (which doesn't exist).
The `close` event needs to be called so the user can remove the alert object from the array, unless there's there's some alternative way to inject the alert template into the page and hold no reference to it in the back-end.

**Comment by jnizet** [comment] 2016-09-10 13:23
Frankly, the more I think about it, the less I find NgbSelfClosingAlert useful. As said above, the only example given in the demo leaks, because the array entries are never cleared.

It can be trivially fixed by emitting an event when the alert self-closes, and removing the alert from the array when this event is fired.

But even then, I don't really understand the real use-case behind this component. I can see two use-cases for self-closing alerts:
1. you want to display a self-closing message, that disappears after 5 seconds. The next success message replaces the previous one, and restarts the counter. I don't see how to implement this cleanly and easily with NgbSelfClosingAlert.
2. you want a stack of short-lived messages, that disappear after 5 seconds. This is the use-case shown in the demo, but it leaks.

Both these scenarios can be easily implemented using just NgbAlert, and a tiny piece of TypeScript code, with the help of RxJS. See [this plunkr](http://plnkr.co/edit/bVjPFXNeMVoVnMPWIEJY?p=preview) for example.

Do we really need NgbSelfClosingAlert? Which use-case does it solve that isn't as easily solved by NgbAlert combined with RxJS?

**Comment by pkozlowski-opensource** [comment] 2016-09-10 13:35
I think that our demo is wrong / illustrates wrong use-case.

The _only_ use case I can see for self-closing alerts is this: a message in the HTML that should be easily to close / disappear after some time. Real-life example would be a message like "Hey, check our new website version <link>". All in all there are very limited use-cases for this.

If we drop self-closing alerts we essentially need:

```html
<ngb-alert *ngIf="closed" (close)="closed=true">...content goes here...</ngb-alert>
```
which is slightly more code as compared to:

 ```html
<template ngbAlert>...content goes here...</template>
```

But given all the confusion that 2 version of alerts bring it might be a good idea to drop self-closable ones. I'm good with any approach.

**Comment by jnizet** [comment] 2016-09-10 13:52
OK. I see now. I have the feeling that the use-case you described (i.e. if I understand correctly, a static, not model-driven, self-closing alert) is not very frequent.

Pros of keeping self-closing alerts:
- makes the UI code a bit simpler for this use-case
- avoids having a setTimeout in the component code for this use-case

Cons of keeping self-closing alerts:
- makes it more confusing: users, including myself, tend to think it can be used for other use-cases where the alert is driven by the model
- using it wrong, as in the demo, causes leaks, or convoluted solutions
- makes the library heavier, although the use-case it solves can be implemented easily with NgbAlert alone, and is not, I think, very frequent

My preference, since we're still in alpha, would be to remove this component, but keep a demo to show how to implement, with NgbAlert, your use-case and mine (i.e. a self-closing success message that can be displayed and replaced programmatically, as in the above plunkr).

@kennotek, @pkozlowski-opensource, @Quinn-L what do you think?

**Comment by pkozlowski-opensource** [comment] 2016-09-10 13:56
I'm good with removing self-closing flavour of alerts, unless anyone objects with good use-case.

**Comment by Quinn-L** [comment] 2016-09-10 14:52
I'm trying to think how much user code could be saved if the `dismissOnTimeout` function could go on `ngb-alert`... Probably not much, since the user has to clean up anyway, but not having a need to discriminate between user clicking the close button or it timing out, and self cleaning up the dismiss timeout, would be nice features to have (but not required).

I personally don't might if the self-closing version gets removed. I'm not that great at coding, I can't really see how the self-closing one is suppose to be used properly anyway since an alert object needs to be referenced _somewhere_ for Angular to display it, or the user injects it into the DOM directly.

**Comment by jnizet** [comment] 2016-09-10 15:05
If we removed self-closing alerts, here is what the demo for self-closing alerts (but using just NgbAlert), could look like: https://gist.github.com/jnizet/8043943eec2e2bc79436e846d36b9cbc

**Comment by kennotek** [comment] 2016-09-12 14:22
When I found this alert I was satisfied with the stacked messages but was looking for this:
1. Display an alert with timeout and type.
2. On arrival a new alert, replace the current alert and display the new alert with its timeout and type.
3. On timeout, clear the current alert.
It is fine to remove the self-closing alert and I can implement the above functionality in my code.

**Comment by pkozlowski-opensource** [comment] 2016-09-17 16:22
Self-closing alerts are gone now: 79e393dc740b2f26daffe8eba7d25ab6e1671828

**Closed by pkozlowski-opensource** 2016-09-17 16:22 UTC
Labels: component: alert, needs: info, needs: plunkr
