### ISSUE TITLE
fix dropups and add positioning

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#1747] opened 2017-08-11 18:04 UTC
dropdowns are not dropping up with Bootstrap 4.beta. The fix is not trivial as we need to use the positioning service.

**Comment by achimha** [comment] 2017-08-13 16:29
Is there any workaround for the time being?

**Comment by mcescalante** [comment] 2017-08-15 15:45
@achimha this is my temporary workaround for 4.0.0-beta. It uses the default [example from the docs](https://getbootstrap.com/docs/4.0/components/dropdowns/#menu-alignment) and adds `[ngbCollapse]` in a couple places to make it work.

```
<div class="btn-group">
  <button type="button" (click)="isMenuCollapsed = !isMenuCollapsed" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    This dropdown's menu is right-aligned
  </button>
  <div [ngbCollapse]="!isMenuCollapsed" class="dropdown-menu dropdown-menu-right">
    <button class="dropdown-item" type="button">Action</button>
    <button class="dropdown-item" type="button">Another action</button>
    <button class="dropdown-item" type="button">Something else here</button>
  </div>
</div>
```

**Comment by bgaillard** [comment] 2017-08-16 07:21
Hi, as @achimha we also need to quickly fix this, is their a simple workaround ?

**Comment by pkozlowski-opensource** [comment] 2017-08-16 08:05
@achimha @bgaillard I'm not aware of any work-around but we are going to release a patch (beta.2) this week with a fix. If you really need it urgently please consider sending a PR. Thnx!

**Comment by bgaillard** [comment] 2017-08-16 08:09
Hi @pkozlowski-opensource, releasing a patch this week would be perfect for us. 

Thanks a lot for your reactivity !

**Comment by pkozlowski-opensource** [comment] 2017-08-16 14:00
@achimha  @bgaillard please review #1752 if you want to see it fixed faster :-)

**Comment by bgaillard** [comment] 2017-08-18 07:37
Hi @pkozlowski-opensource, thanks a lot for this PR. 

After testing I'm think I do not encounter the same bug as @achimha. 

In my case the problem is that the Dropdown is placed outside the screen. I initially though the bug was the same because #1748 was marked as a duplicate of this case and was is positioning problems.

The following screenshots shows the problem I currently encounter with `beta.1` version at left (the dropdown is placed outside the screen). 

At right this is a screenshot of what I had with the last alpha version (this is the expected behavior).

On those screenshots the border of my screen is at right of the "grey scroll bar".

![dropdown-bug](https://user-images.githubusercontent.com/1327782/29448546-734a9c00-83f7-11e7-80fc-f108184f0796.jpg)

Do you know if its an ng-bootstrap bug or a Twitter Bootstrap 4 bug ?

I'm in holidays tonight so i do not have any time to test if this bug comes from Twitter Bootstrap or ng-bootstrap. During my holidays my co-worker @simonbaudry will be able to respond you I he has not too much work :).

**Comment by achimha** [comment] 2017-08-18 07:41
@bgaillard that's exactly the problem I'm seeing, `dropdown-menu-right` doesn't work with beta 1 because Bootstrap 4 switched to a Javascript positioning service.

**Comment by pkozlowski-opensource** [comment] 2017-08-18 07:45
> dropdown-menu-right doesn't work with beta 1 because Bootstrap 4 switched to a Javascript positioning service.

Exactly. Since Bootstrap moved away from CSS and switched to JS we need to do the same. The first step is to use JS to position things and this is what #1752 does. #1752 will restore dropups but won't help with cropping and auto-positioning - this will be handled in #1171 (but in order to make it work we need to beef up our positioning service).

**Closed** 2017-08-22 12:30 UTC
Labels: component: dropdown, required for RC, type: bug

**Comment by bgaillard** [comment] 2017-09-04 17:38
Hi, thanks for your work on this, my co-worker @simonbaudry fixed our problems thanks to your comments and other issues linked to it.
