### ISSUE TITLE
Modal should not close on mouseup outside

### ISSUE THREAD

**Issue by devel112** [ng-bootstrap/ng-bootstrap#3330] opened 2019-08-13 15:55 UTC
### Bug description:
Of course the modal should close on a complete click outside when not using static option.
But, I argue that a single mouseup is not a complete user action "click" outside the modal.

Reasoning: Try to highlight som text in the modal. You will find it extremely annoying that the modal just closed because you released the mouse barely outside the modal.

Solution: I would create a PR but i do not know the code as well as others. Only a mouse down + mouse up should qualify as a "click" outside the modal

**Comment by benouat** [comment] 2019-08-22 14:44
Hey @devel112! Thanks to report this issue, but I will close it as duplicate.

Duplicate of #1950

**Closed by benouat** 2019-08-22 14:44 UTC
