### ISSUE TITLE
Feature request: Arbitrary classes to control elements

### ISSUE THREAD

**Issue by Dan203** [ng-bootstrap/ng-bootstrap#2196] opened 2018-02-28 00:14 UTC
I would like to be able to add my own classes to the individual elements of a control. For example I'd like to be able to add custom class that would override the color of a tab. Right now I'm having to use unique IDs and then use CSS selectors like....

.nav-item a.nav-link[id^="queuedTab"] {
    background-color: #375a7f;
}

which works, but it would be a lot easier if I could just use the class bg-primary instead.

**Comment by pkozlowski-opensource** [comment] 2018-02-28 08:53
Duplicate of the existing issues about custom styling: #1436, #1567, #2186

**Closed by pkozlowski-opensource** 2018-02-28 08:53 UTC
