### ISSUE TITLE
Autofocus on input type="number" field in Modal causes error on Firefox

### ISSUE THREAD

**Issue by MeMeMax** [ng-bootstrap/ng-bootstrap#3184] opened 2019-05-09 11:58 UTC
### Bug description:
Hi, Firefox raises a "ExpressionChangedAfterItHasBeenCheckedError" if there is a input with type="number" in the modal and this input has autoFocus on it or gets autoFocus from anything else.

I am using reactive forms to bind my input to the ts class.

Chrome and IE works perfectly well.

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-8mwgbc

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular:
"@angular/core": "~7.2.0",
ng-bootstrap:
"@ng-bootstrap/ng-bootstrap": "^4.1.0",
Bootstrap:
"bootstrap": "^4.3.1",

**Comment by benouat** [comment] 2019-05-13 06:55
Hey @MeMeMax !

Thanks for reporting that ! Could you please confirm which kind of autofocus are you using ? I assume you would be talking about the native one ?

Could you please try with the one we provide `ngbAutofocus` as referred in the documentation [here](https://ng-bootstrap.github.io/#/components/modal/examples#focus). Is the error still present with that one ?

**Comment by MeMeMax** [comment] 2019-05-13 07:38
@benouat Thanks for your response. I am already using the ngbAutoFocus in the stackblitz. The native autofocus doesn´t have any effect (field is not focussed).

**Comment by benouat** [comment] 2019-05-13 10:33
oh sorry.. I should have checked the SB. I got confused by your bug description.
I'll have a deeper look, but it sounds like a bug on our side. We probably focus the element synchronously instead of asynchronously.

**Comment by maxokorokov** [comment] 2019-05-13 15:15
@MeMeMax, you should be using `ngbAutofocus`, no `tabindex` and `autofocus`

```html
<input ngbAutofocus type="number" class="form-control" formControlName="testNumber">
```

However this is still broken with `ExpressionChanged...` exception. 

Some notes:
- it works fine with input `type=text`
- There is a bug in Firefox for the input `type=number` that is explicitly the cause of this issue → https://bugzilla.mozilla.org/show_bug.cgi?id=1057858, should be fixed in FF 68 :)
- we do focus synchronously with `element.focus()`

---

So I'd say on the one hand it's not our issue :) 
On the other hand if we do `setTimeout(() => element.focus())` we get just `focus` in Firefox instead of `blur-focus-focus`...

@benouat you decide :)

**Comment by MeMeMax** [comment] 2019-05-14 13:15
@maxokorokov thanks for the clarification. In my real example I might have more inputs and I need to use tabindex to define tabsequence.

Imho `setTimeout(() => element.focus())` is not that nice...Firefox should fix this.

**Comment by benouat** [comment] 2019-06-19 07:10
Sorry to come late to discussion! Here are my final thoughts on the topic.

Knowing that → 
+ it will be fixed in FF68 (landing as stable on July 9th according to their [roadmap](https://wiki.mozilla.org/Firefox/Roadmap/Updates))
+ `ExpressionChanged...` exception only occurs in DEV mode. So it should not crash anything in PROD mode until the FF patch.

My decision is → **not to fix it**. I won't add the `setTimeout()` fix.

@MeMeMax are you fine with that so we can close the issue, and move on ?

**Comment by maxokorokov** [comment] 2019-11-08 18:32
This was fixed in FF, closing

**Closed by maxokorokov** 2019-11-08 18:32 UTC
Labels: component: modal, resolution: browser issue, type: bug
