### ISSUE TITLE
Range Date picker get hides on first click

### ISSUE THREAD

**Issue by Santoshah** [ng-bootstrap/ng-bootstrap#2087] opened 2018-01-15 22:33 UTC
I am trying to create range date picker where I can open the 2 months datepicker at once and select from date and to Date. However, the date picker gets hides on the first click and for to-Date selection, I have to open again.

`<form class="form-inline">
  <div class="form-group">
    <div class="input-group">
      <input class="form-control" #dp ngModel (ngModelChange)="onDateChange($event)"  placeholder="yyyy-mm-dd" name="dp" [displayMonths]="displayMonths" [dayTemplate]="t" [navigation]="navigation" ngbDatepicker #d="ngbDatepicker">

		<ng-template #t let-date="date" let-focused="focused">
		  <span class="custom-day"
		        [class.focused]="focused"
		        [class.range]="isFrom(date) || isTo(date) || isInside(date) || isHovered(date)"
		        [class.faded]="isHovered(date) || isInside(date)"
		        (mouseenter)="hoveredDate = date"
		        (mouseleave)="hoveredDate = null">
		    {{ date.day }}
		  </span>
		</ng-template>
			<br>

      <div class="input-group-append">
        <button class="btn btn-info" (click)="d.toggle()" type="button">
          <img src="img/calendar-icon.svg" style="width: 1.2rem; height: 1rem; cursor: pointer;"/>
        </button>
      </div>
    </div>
  </div>
</form>
<pre>From: {{ fromDate | json }} </pre>
<pre>To: {{ toDate | json }} </pre>  `

**Comment by maxokorokov** [comment] 2018-01-19 09:38
Thanks for reporting, though looks like a duplicate of #1984

**Closed by maxokorokov** 2018-01-19 09:38 UTC
Labels: component: datepicker, resolution: duplicate
