### ISSUE TITLE
Typeahead - Show a scroll in the list

### ISSUE THREAD

**Issue by abelardolg** [ng-bootstrap/ng-bootstrap#2331] opened 2018-04-20 11:08 UTC
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

[x]  Requesting new feature

### New Feature description:
Show a scroll when the number of items to be displayed is not specified.

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2.10

ng-bootstrap: latest version

Bootstrap: 4.0.0.

**Comment by pkozlowski-opensource** [comment] 2018-04-22 14:07
Duplicate of #1119

**Closed by pkozlowski-opensource** 2018-04-22 14:07 UTC
