### ISSUE TITLE
 Modal meet very weird scene on Window system and the latest Chrome 

### ISSUE THREAD

**Issue by xiehongyang** [ng-bootstrap/ng-bootstrap#1889] opened 2017-10-08 13:15 UTC
Question:
I am using [ng2-admin](http://akveo.com/ng2-admin/#/pages/ui/modals) to build system for my company, and recently I met a very weird question on modal, because i develop under Mac, everything is fine, but on **Windows**, When I open modal, found **a very weird white shadow** on backdrop of modal, I don't know what's going on here, and whether it's belong to a bug. See picture below.
![shadow](http://images2017.cnblogs.com/blog/749201/201710/749201-20171008211149309-441211070.png)
version:
```
"ng-bootstrap": "^1.0.0-alpha.26",
"@angular/all": "4.1.3",
```
Chrome: 61.0.3163.100

Could anyone met this in before? Thanks for author build this great component.Could anyone help me? Thanks very much!

**Comment by xiehongyang** [comment] 2017-10-10 02:59
I also see this bug in your demo page [modal](https://ng-bootstrap.github.io/#/components/modal/examples). See picture below
![modal](http://images2017.cnblogs.com/blog/749201/201710/749201-20171010104813090-961813555.png)

**Comment by carloswbarros** [comment] 2017-10-13 13:10
This is not a ng-bootstrap problem, neither is a bootstrap problem, this is problem with chrome. Check this: https://github.com/twbs/bootstrap/issues/24233 . They have a simple workaround there, but it's not the way to be fixed.

**Comment by pkozlowski-opensource** [comment] 2017-10-13 13:32
@carloswbarros thnx so much for pointing this out. I'm going to close this issue as a duplicate of https://github.com/twbs/bootstrap/issues/24233 then as Bootstrap folks will either decide to work-around it or will chase a bug in Chrome.

Once again, thnx for taking time to report back here, much appreciated!

**Closed** 2017-10-13 13:32 UTC
Labels: blocked: bs4 issue
