### ISSUE TITLE
Issue with package in angular universal

### ISSUE THREAD

**Issue by JinnaBalu** [ng-bootstrap/ng-bootstrap#2017] opened 2017-12-06 19:12 UTC
### Bug description:
Error 1:
No component factory found for NgbModalBackdrop. Did you add it to @NgModule.entryComponents?
Error 2:
Error: No component factory found for NgbTypeaheadWindow. Did you add it to @NgModule.entryComponents?

I am running application with angular univeral for serverside rendering.  

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.0.0

ng-bootstrap: 1.0.0-beta.5

Bootstrap: 4.0.0-beta.2

**Comment by pkozlowski-opensource** [comment] 2017-12-06 19:42
Duplicate of #858

**Closed by pkozlowski-opensource** 2017-12-06 19:42 UTC
