### ISSUE TITLE
How make change in accordion component in header

### ISSUE THREAD

**Issue by natec0240** [ng-bootstrap/ng-bootstrap#2585] opened 2018-08-08 23:33 UTC
Just wanted to know if there anyway is it possible to do it ????

### Bug description:
i am trying to modify the accordion as click on 6 selected as described in the picture it should show and hide but right next to it i have an <pipe> and Edit as link as both are in header of accordion when the user clicks on the 6selected or edit link it will expand and collapse so i want to know is there anyway to control the behavior of the edit link as it should not do expand or collapse  

### Link to minimally-working plunker that reproduces the issue:
r. Here is why:
![nm007f_1533578403060](https://user-images.githubusercontent.com/40182128/43869389-e1c4d10c-9b37-11e8-8dc2-d73146215257.png)

Angular: 1

ng-bootstrap:

Bootstrap:

**Comment by benouat** [comment] 2018-08-09 08:11
Hello, as it is clearly stated in the [Readme](
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug) and also in the [Issue Template](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/.github/ISSUE_TEMPLATE.md) without a minimal reproductible stackblitz/plunker we can't do much.

On top you edited the Angular version to `1` which is suspicious. This repository is providing a widget library meant to be used with Angular 2+

**Comment by pkozlowski-opensource** [comment] 2018-08-10 17:52
This is duplicate of the existing feature request #717

**Closed by pkozlowski-opensource** 2018-08-10 17:52 UTC
Labels: component: accordion, needs: plunkr / stackblitz
