### ISSUE TITLE
Building with the -p flag breaks Modals.

### ISSUE THREAD

**Issue by iammikecohen** [ng-bootstrap/ng-bootstrap#1502] opened 2017-04-19 00:05 UTC
Sorry, I can't provide a plnkr for this issue because it only happens when building for production. I have dug into the code a little and have isolated the issue to `modal-window.metadata.json` and/or `modal-window.js`

The problem is when I build with the "`-p`" flag the `<ngb-modal-window>` element and the div directly under it don't get class names. 
When I change the code in the `.json` file to not be binding to the element's class attribute the problem is fixed. (I passed static class names to the class attribute)

Something in there must be failing silently. There are no error at build or when I pull up the app in my browser.

**Comment by pkozlowski-opensource** [comment] 2017-04-19 07:39
I'm sorry but there is just not enough details here. Even if you can't reproduce in a plunker you could always create a minimal project generated with the CLI and put it somewhere on GitHub. Without a reproduce scenario (hey, we don't even know what the error is!) there is no way of investigating.

Please create a minimal reproduce scenario.

**Comment by pkozlowski-opensource** [comment] 2017-04-20 15:54
@iammikecohen I've just:
* created a brand new project with the latest CLI version;
* installed the latest `@ng-bootstrap/ng-bootstrap` version;
* added modal to the application
* run `ng build -prod -aot`

and didn't get any errors. Also verified that a modal properly opens when application runs.

I'm going to close this one given that:
* I can't reproduce;
* we don't have any reproduce scenario / error message from you.

Happy to re-open / investigate when you've got a minimal reproduce scenario.

**Closed by pkozlowski-opensource** 2017-04-20 15:54 UTC
Labels: component: modal, needs: info
