### ISSUE TITLE
hamburger menu not working

### ISSUE THREAD

**Issue by GuitarHero1969** [ng-bootstrap/ng-bootstrap#2919] opened 2018-12-10 21:53 UTC
Angular version = 7.1.2
Bootstrap version = 4.1.3
ng-bootstrap version 4.0.0

When I collapse the browser to test the responsive layout the burger appears but clicking it doesn't expand its content.

Your site tells everyone not to use popper or jquery if using ng-bootstrap as it can interfere - I quote:

"Should I add bootstrap.js or bootstrap.min.js to my project?

No, the goal of ng-bootstrap is to completely replace JavaScript implementation for components. Nor should you include other dependencies like jQuery or popper.js. It is not necessary and might interfere with ng-bootstrap code."

But the dropdown wasn't working, so I used ngbDropdown, ngbDropdownToggle and ngbDropdownMenu and now that's working.

But, jquery and popper to make drop-downs work and ng-bootstrap doesn't have the navbar stuff, so you can see the problem here !!!

Developers don't want to have to download windows updates only to be told that if there is a problem then go to the source code on github and hack it, so why do we have to do this with front end code !!??
Or have I missed something ?

`
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
          aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav mr-auto">

      <li [routerLinkActive]='["link-active"]' [routerLinkActiveOptions]='{ exact: true }'>
        <a class='nav-link' [routerLink]='["/"]' (click)='collapse()'>
          <span class="sr-only glyphicon glyphicon-home">(current)</span> Home
        </a>
      </li>

      <li [routerLinkActive]='["link-active"]'>
        <a class='nav-link' [routerLink]='["/counter"]' (click)='collapse()'>
          <span class='glyphicon glyphicon-education'></span> Counter
        </a>
      </li>

      <li [routerLinkActive]='["link-active"]'>
        <a class='nav-link' [routerLink]='["/fetch-data"]' (click)='collapse()'>
          <span class='glyphicon glyphicon-th-list'></span> Fetch data
        </a>
      </li>

      <li class="nav-item dropdown" ngbDropdown>

        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
           ngbDropdownToggle>
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown" ngbDropdownMenu>
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>

      </li>

      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>

    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    </form>
  </div>
</nav>`

**Comment by pkozlowski-opensource** [comment] 2018-12-11 14:45
I'm sorry but this is not clear from the provided description what is not working. We absolutely need a minimal reproduce scenario as requested in the issue template: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

**Comment by GuitarHero1969** [comment] 2018-12-11 15:19
What is "not working" is the compatibility between ngx-bootstrap, ng-bootstrap and twitter bootstrap.
And the fact that I didn't want to include jquery and popper but wanted to follow a 'leaner' pattern.

I have fixed this now anyway and am posting my index.html mark-up here to help anyone else that runs into bootstrap problems:

`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Angular Seven</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</head>
<body>
  <app-root>Loading...</app-root>
</body>
</html>`

**Comment by maxokorokov** [comment] 2018-12-13 14:22
Duplicate of #738 
However opened #2928 to update documentation on the demo site

**Closed by maxokorokov** 2018-12-13 14:22 UTC
Labels: component: dropdown, needs: stackblitz
