### ISSUE TITLE
Filtering table - filter and data combination stucks

### ISSUE THREAD

**Issue by gblack72** [ng-bootstrap/ng-bootstrap#4724] opened 2024-06-12 08:21 UTC
### Bug description:
Combination text in filter field and data causes into error. It stops whole browser.
In forked project write pp into search field.

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-yvhety?file=src%2Fmain.ts

### Versions of Angular, ng-bootstrap and Bootstrap:
Versions are as created your demo app. I have other and will write into brackets
Angular: 17.0.9 (17.3.5)

ng-bootstrap: 16.0.0 (16.0.0)

Bootstrap: idk (5.3.3)

**Comment by jnizet** [comment] 2024-06-20 19:45
Duplicate of #4705

This issue has been fixed in ng-bootstrap 17.

**Closed by jnizet** 2024-06-20 19:45 UTC
