### ISSUE TITLE
Transition for modals

### ISSUE THREAD

**Issue by JoseDRojasA** [ng-bootstrap/ng-bootstrap#1466] opened 2017-04-10 16:22 UTC
Hello, I need to have a transition on modal's open and modal's close but i can't find how to do this.

I'm looking for something like this: http://getbootstrap.com/javascript/#modals -> "Launch demo modal"

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.0.1

ng-bootstrap: 1.0.0-alpha.22

Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment] 2017-04-10 17:46
Duplicate of #295

**Closed by pkozlowski-opensource** 2017-04-10 17:46 UTC
