### ISSUE TITLE
Modal stopped to work in 1.0.0-alpha.16

### ISSUE THREAD

**Issue by karolisgrinkevicius** [ng-bootstrap/ng-bootstrap#1191] opened 2017-01-07 14:22 UTC
Modal window is no longer working in new release.

http://plnkr.co/edit/?p=preview

Angular: 2.2.1

ng-bootstrap: 1.0.0-alpha.16

Bootstrap: 4.0.0-alpha.6

**Comment by ASHFAQPATWARI** [comment] 2017-01-07 14:38
@karolisgrinkevicius This is not because of ng-bootstrap. This is because of new release of bootstrap (4.0.0-alpha.6)

**Comment by karolisgrinkevicius** [comment] 2017-01-07 14:58
Is it possible to make some temporary workaround for that?

**Comment by ASHFAQPATWARI** [comment] 2017-01-07 15:00
You can temporarily stick to bootstrap 4.0.0- alpha.5.

**Comment by jnizet** [comment] 2017-01-07 15:02
@karolisgrinkevicius the temporary workaround is to stay on bootstrap-4.0.0-alpha.5. 

alpha.6 was only released yesterday, and introduced a lot of breaking changes in the markup. So we need some time to catch up. But as you can see if you look at the pending pull requests, we already started working on it, so an alpha.6-compatible release should be out soon.

**Comment by jnizet** [comment] 2017-01-07 15:02
Closing as duplicate of #1178

**Closed by jnizet** 2017-01-07 15:02 UTC

**Comment by karolisgrinkevicius** [comment] 2017-01-07 15:17
@jnizet, @ASHFAQPATWARI thanks! Created an issue in bootstrap https://github.com/twbs/bootstrap/issues/21596. Let's stick to older bootstrap alpha release.

**Comment by jnizet** [comment] 2017-01-07 15:20
@karolisgrinkevicius you shouldn't have. The breaking change in twbs/bootstrap is intentional. Their own CSS and JS code for modal works fine, but we need to integrate this breaking change into our own code. This will be done soon.

**Comment by karolisgrinkevicius** [comment] 2017-01-07 15:24
As you're saying soon how much time it might take for you to solve it?

**Comment by jnizet** [comment] 2017-01-07 15:33
I'm not the one deciding when releases are done, so I can't give any number. All I can say is that we're releasing on a regular basis, and that many changes are done already, but need to be reviewed.

**Comment by RodolfoSilva** [comment] 2017-01-08 12:43
My temporary solution for this. @karolisgrinkevicius 

```css
.fade.in {
  opacity: 1;
}

.modal-backdrop.in {
  opacity: 0.5;
}

.modal.in .modal-dialog {
  -webkit-transform: translate(0, 0);
       -o-transform: translate(0, 0);
          transform: translate(0, 0);
}
```

**Comment by hackathon365** [comment] 2017-01-25 08:03
@RodolfoSilva Thank you for your solution,
I just had to change the 'in' to 'show' in my working environment.
```
.fade.show {
  opacity: 1;
}

.modal-backdrop.show {
  opacity: 0.5;
}

.modal.show .modal-dialog {
  -webkit-transform: translate(0, 0);
  -o-transform: translate(0, 0);
  transform: translate(0, 0);
}
```
