### ISSUE TITLE
ng-bootstrap breaks the basic functionality of assigning a value to a radio button (reactive forms)

### ISSUE THREAD

**Issue by javascrewpt** [ng-bootstrap/ng-bootstrap#1509] opened 2017-04-20 11:07 UTC
### Bug description:
ng-bootstrap breaks the basic functionality of assigning a value to a radio button (reactive forms).

### Link to minimally-working plunker that reproduces the issue:
Here's a working example that doesn't include ng-bootstrap (focus on radio buttons, one gets selected by default using the setValue): https://plnkr.co/edit/5Vd0HtLB1GH1EbOoBlM2?p=preview

Here's THE SAME CODE, but with ng-bootstrap enabled: the radio button is not initially set as in the example above: http://plnkr.co/edit/bkkRBHlOiCHSEHVYWjFi?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
"@angular/core": "^4.0.0",

ng-bootstrap:
"@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.20",

Bootstrap:
"bootstrap": "4.0.0-alpha.6",

**Comment by pkozlowski-opensource** [comment] 2017-04-20 11:42
We are tracking this already as part of #1125. This has rather high priority for us and will be resolved before releasing beta.

Closing as a duplicate of #1125

**Closed by pkozlowski-opensource** 2017-04-20 11:42 UTC
