### ISSUE TITLE
Date picker: Cannot scroll throug all years using ngbDatepicker

### ISSUE THREAD

**Issue by jadavpalak** [ng-bootstrap/ng-bootstrap#3709] opened 2020-04-29 11:36 UTC
**Expected behavior**

I want a user to be able to select all years in the year range in the date picker.

**Actual behavior**

A user can only choose 15 in the range. Say the range goes from 2010 -2020, the user would first have to click on 2010, and then he would click the list again and could now select down to 2010. How to I modify the code so a user can select from all years and don't have to click multiple times to get to the right year?

![image](https://user-images.githubusercontent.com/25167163/80591677-b1dd5f00-8a3b-11ea-8ffd-4734cbc7f023.png)

https://stackblitz.com/angular/xamnxlaknpgb?file=app%2Fdatepicker-range.ts

**Comment by pkozlowski-opensource** [comment] 2020-04-29 11:40
Have you tried setting `minDate` / `maxDate`? https://stackblitz.com/edit/angular-ruzpnd?file=app/datepicker-range.html

**Comment by jadavpalak** [comment] 2020-05-01 06:27
@pkozlowski-opensource in the stackblitz you have given also if you want to select year above 2030 you need to first select year 2030 then only you can select 2032 or etc. I want to scroll through all the years at one go.

**Comment by peterblazejewicz** [comment] 2020-05-01 08:17
@jadavpalak 
One needs to provide both, e.g. Linux epoch range:
```ts
<ngb-datepicker #dp (select)="onDateSelection($event)" [displayMonths]="2" [dayTemplate]="t" [minDate]="{year: 1970, month:1, day: 1}" [maxDate]="{year: 2038, month:1, day: 19}">
</ngb-datepicker>
```

**Comment by jadavpalak** [comment] 2020-05-04 04:46
@peterblazejewicz Why i needs to provide both? I don't need maxDate as per my requirement, there should be default behavior so we can scroll through all the years available.

**Comment by lslavkov** [comment] 2020-05-12 14:46
@jadavpalak at the documentation in **Api** tab there is default settings for _maxDate_ and _minDate_. Here is the picture of those params:

![image](https://user-images.githubusercontent.com/23018487/81706131-1e128680-9470-11ea-9a46-29cd874aa3dd.png)

**Comment by maxokorokov** [comment] 2020-05-13 13:08
@jadavpalak, what do you mean by "available"? All the years in the past and the future? When does the future end? :)

On a serious note, I understand that the API is most likely not flexible enough... We should probably allow customising the default `10` value or something.

You could also create any controls you want with this → https://ng-bootstrap.github.io/#/components/datepicker/examples#custommonth

**Comment by maxokorokov** [comment] 2020-05-18 14:44
By the way will close this as a duplicate of #2412

**Closed by maxokorokov** 2020-05-18 14:44 UTC
Labels: component: datepicker, needs: design, resolution: duplicate, type: feature
