### ISSUE TITLE
Feature request: "container"-property for Dropdowns

### ISSUE THREAD

**Issue by kirilmitev** [ng-bootstrap/ng-bootstrap#2164] opened 2018-02-14 10:27 UTC
Hello,

popovers have this "container"-property, and I think it will make the ng-bootstrap's dropdowns a lot more flexible. 

My application scenario:
------------------------------------------------
At the moment I have a **card**, that consists of a **card-header**, a **card-body** and a **card-footer**. In the card-body I have the dropdowns, but since the card-body is scrollable, there is no way to show the dropdown-menu over the card-header and card-body. This could be solved very easily by setting the container for the dropdown-menu.

Best regards
Kiril

**Comment by armandoxxx** [comment] 2018-02-25 09:03
this is achievable with css styles ...

**Comment by kirilmitev** [comment] 2018-02-25 09:12
Sadly, it‘s not achievable with pure css, since the card-body is both positioned relative and scrollable (overflow: scroll), and thus dropdown options will always stay within the card-body.

**Comment by armandoxxx** [comment] 2018-02-25 09:17
are you sure ? bucause .. I've managed to do just that ... 
![capture2](https://user-images.githubusercontent.com/2564372/36639839-18e445f4-1a15-11e8-9589-eadeee173851.PNG)
![capture1](https://user-images.githubusercontent.com/2564372/36639840-1900a0a0-1a15-11e8-9618-328b2808387b.PNG)

**Comment by pkozlowski-opensource** [comment] 2018-02-25 15:38
Duplicate of #1012

**Closed by pkozlowski-opensource** 2018-02-25 15:38 UTC

**Comment by kirilmitev** [comment] 2018-02-25 17:08
Yes, I am sure, and sorry, but you are wrong. The main problem is the stacking of the elements, you probably have a different HTML structure.
