### ISSUE TITLE
DatePicker - Show outside days of the month in disabled state on collapsed mode of "outsideDays"

### ISSUE THREAD

**Issue by jrajeshbritto** [ng-bootstrap/ng-bootstrap#2330] opened 2018-04-20 09:51 UTC
Hi,

Solution:

   Remove the **this.outsideDays === 'collapsed'** condition in the **isHidden** method.

**isHidden**(day: DayViewModel) {
    return (this.outsideDays === 'hidden' **|| this.outsideDays === 'collapsed'**) && this.month.number !== day.date.month;
  }

Thanks in Advance.

Regards,
Rajesh J

**Comment by pkozlowski-opensource** [comment] 2018-04-22 14:13
I believe that his is a duplicate of #2035 - can't be sure, though, as there is _very_ little info in this issue. Please open a new issue with more context if you believe that this is not a duplicate.

**Closed by pkozlowski-opensource** 2018-04-22 14:13 UTC
