### ISSUE TITLE
ngbTypeAhead result template group header display

### ISSUE THREAD

**Issue by patelshabana** [ng-bootstrap/ng-bootstrap#2531] opened 2018-07-18 19:40 UTC
We want to add group header name and it should not be clickable  in ngbtypeahead
e.g. see below US State Typeahead search result

**NorthEast**
New York
New Jersey

**SouthEast**
Florida

Can someone please help us to create above sample result template?

**Comment by pkozlowski-opensource** [comment] 2018-07-18 20:06
Duplicate of #1274

**Closed by pkozlowski-opensource** 2018-07-18 20:06 UTC
