### ISSUE TITLE
Carousel is not animated

### ISSUE THREAD

**Issue by SebastianSchenk** [ng-bootstrap/ng-bootstrap#1823] opened 2017-09-06 16:42 UTC
### Bug description:
The carousel transitions are not animated and therefore, are not sliding.
The slides are missing classes called `carousel-item-next`, `carousel-item-left/right`.
Due to the lack of these classes during transition, the slides are not animated. You can see this behaviour, while debugging the original carousel on the bootstrap documentation page https://getbootstrap.com/docs/4.0/components/carousel/#with-indicators

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/GXzJpDL0E5jF0wDYvvv2?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.0.3

ng-bootstrap: 1.0.0-beta.3

Bootstrap: 4.0.0-beta

**Comment by pkozlowski-opensource** [comment] 2017-09-06 17:09
Yep, we are _just_ adding animations right now, see #295 for the detailed discussion.

The tl;dr; is that we are adding animations support through Angular animations and were not planning on using Bootstrap CSS classes. Are you saying that a carousel could be animated by simply sticking appropriate CSS classes at a given time?

@mattlewis92 any thoughts on this?

**Comment by mattlewis92** [comment] 2017-09-06 21:36
I did have a go at the implementation for this the other day, but it got a bit tricky so I left it to loop back to last. I will take another go at it next time I have some free time (maybe this weekend).

**Comment by js-digital** [comment] 2017-09-18 11:41
Hello @mattlewis92,
Do you have any updates about current issue, some details, estimates ? 
Thank you

**Comment by mattlewis92** [comment] 2017-09-18 12:26
I'm afraid I haven't had the time to look at this, as with anything in open source though you are very welcome to have a go at implementing it yourself. Some resources that might help 😄 
* https://angular.io/guide/animations
* https://www.yearofmoo.com/2017/06/new-wave-of-animation-features.html

**Comment by js-digital** [comment] 2017-09-18 13:31
That's awesome )

**Comment by tstockwell** [comment] 2017-11-06 21:32
Hi All,

I'm new to Angular 2, and I'm not a very experienced web developer in general, but I'm working on an Angular 2 project and I would like to get the animation working on the carousel.  I've created a small Plunker that demonstrates animation for a carousel.  Before I waste my time attempting to apply my animations to the ng-bootstrap carousel, it would be great if someone would take a look at what I've done and tell me if my implementation is too naive to be used in ng-bootstrap.

Plunker:  [Angular 2 Carousel Animation Demo](https://embed.plnkr.co/nTrSDnYksdpkxC89dMue/)
Thanks...

PS:  I made the animation real slow for demo purposes

**Comment by linusbrolin** [comment] 2017-11-13 19:08
Hi,
I've made a pr for this: https://github.com/ng-bootstrap/ng-bootstrap/pull/1958
There is a Travis error, but it doesn't seem to be related to my code at all, it seems to be related to a failing ngb-datepicker test, so I don't think it's something that should be fixed in this pr.

**Comment by TonyTheTech** [comment] 2017-12-18 22:45
Is there a possible workaround for this? Or does it come down to, at the end of the day the carousel will not be animated when using it through ng-bootstrap at this point in time?

**Comment by linusbrolin** [comment] 2017-12-18 22:57
@TonyTheTech there is a pr to add animations for the carousel: https://github.com/ng-bootstrap/ng-bootstrap/pull/1958
They just havent reviewed and merged it yet.
But you can always fork it and add my pr yourself to get the animations.

**Comment by tolgaek** [comment] 2018-01-21 01:21
is there a workaround for this without using a forked version?

**Comment by hfournier** [comment] 2018-02-28 21:34
There's been a pr #1958 waiting for review for over 3 months now... when is this issue going to be resolved?

**Comment by pkozlowski-opensource** [comment] 2018-08-03 13:29
Going to close this as a duplicate of #295 where we track all initial animation related work - no need to have a separate issue per widget until the initial implementation is done.

**Closed by pkozlowski-opensource** 2018-08-03 13:29 UTC
Labels: component: carousel, type: animate

**Comment by foo-baar** [comment] 2020-05-04 23:31
> There's been a pr #1958 waiting for review for over 3 months now... when is this issue going to be resolved?

Hi @hfournier Wondering was it finally implemented ?

**Comment by hfournier** [comment] 2020-05-04 23:38
@foo-baar doesn't look like it. Follow #295, which leads to another PR.

I gave up. I'm using Angular Material instead and was able to easily implement my own animated carousel.

**Comment by foo-baar** [comment] 2020-05-04 23:47
> @foo-baar doesn't look like it. Follow #295, which leads to another PR.
> 
> I gave up. I'm using Angular Material instead and was able to easily implement my own animated carousel.

Thanks for replying @hfournier, even basic bootstrap handles it so well.

**Comment by fbasso** [comment] 2020-05-05 07:04
Hi @foo-baar.

FYI, animations are actively developed and is planned for the 7.0.0. 

Information on PR #2817.

**Comment by foo-baar** [comment] 2020-05-05 09:52
> Hi @foo-baar.
> 
> FYI, animations are actively developed and is planned for the 7.0.0.
> 
> Information on PR #2817.

Thanks @fbasso for replying, any idea on timelines ?

**Comment by fbasso** [comment] 2020-05-05 14:41
Unfortunately, it's not possible to give dates for now. We are working hard on this subject, and there is a lot to cover: test to be done, edge cases.

Now we are trying to go widget by widget. Just follow the different PRs to get some news about it.

**Comment by foo-baar** [comment] 2020-05-05 15:52
Understand @fbasso, Thanks for posting the update.
