### ISSUE TITLE
Link broken on homepage of Angular Bootstrap github.io

### ISSUE THREAD

**Issue by vivz753** [ng-bootstrap/ng-bootstrap#2584] opened 2018-08-08 19:26 UTC

**Comment by benouat** [comment] 2018-08-09 08:05
Thank you @vivz753 to report the issue !

Nonetheless I will close it as I can't reproduce it running master locally.

Maybe something has been fixed in `@angular/router` regarding the version we have in production (6.0) and next one (6.1), but I doubt.

I can't explain this.

**Comment by benouat** [comment] 2018-08-09 08:26
Thank to @maxokorokov that just had the idea to launch Webstorm, we figured out what was going on!!

`https:/getbootstrap.com` -> `https://getbootstrap.com` 😆 the missing `/`

So it is not fixed yet, but for whatever reason, Github Pages is probably doing some stuff that leads to the issue on github.io but not localhost.

**Closed** 2018-08-09 08:50 UTC
Labels: type: demo site
