### ISSUE TITLE
NgbTimepicker with undefined hour/minute and required property shouldn't return valid=true

### ISSUE THREAD

**Issue by esistgut** [ng-bootstrap/ng-bootstrap#1703] opened 2017-07-26 16:48 UTC
### Bug description:

A NgbTimepicker with time = {hour: undefined, minute: undefined} returns valid=true even if there is no input and the required property is in place.
Changing to time = undefined makes it correctly return valid=false.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/J4hrmdmT4pqgEVQx3zpl

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.3.1

ng-bootstrap: 1.0.0-alpha.29

Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment] 2017-07-26 16:50
This is a (aproximate) duplicate of #1328. #1328 is all about adding validation to timepicker (which is lacking today).

**Closed by pkozlowski-opensource** 2017-07-26 16:50 UTC
