### ISSUE TITLE
Timepicker : If giving incorrect value in Hour field like 33 continuously 2 times then it accept the invalid value 2nd time.

### ISSUE THREAD

**Issue by ShraddhaChandrakar** [ng-bootstrap/ng-bootstrap#2744] opened 2018-09-25 09:34 UTC
Timepicker : If giving incorrect value in Hour field like 33 continuously 2 times then it accept the invalid value 2nd time.Please find screen shot for same.
1st time if I gave 33 on HH field it will convert it to 09:
![screen shot 2018-09-25 at 3 06 40 pm](https://user-images.githubusercontent.com/38907956/46006234-a514be80-c0d4-11e8-9957-cbe74d4024ef.png)

2nd time if i gave 33 on HH field its not converting it to 09:
![screen shot 2018-09-25 at 3 02 48 pm](https://user-images.githubusercontent.com/38907956/46006025-30da1b00-c0d4-11e8-922e-a42d70638534.png)

**Comment by pkozlowski-opensource** [comment] 2018-09-25 12:10
Duplicate of #1644

**Closed by pkozlowski-opensource** 2018-09-25 12:10 UTC

**Comment by deepakgauda-dk** [comment] 2019-09-09 10:39
Hi, As shraddha I am also facing the same issue with ngb-timepicker.  I didn't find a solution in #1644 either. Any help ?
