### ISSUE TITLE
ng-bootstrap Datepicker defaulting the navigation year to 10 years before the current date

### ISSUE THREAD

**Issue by justincastlight** [ng-bootstrap/ng-bootstrap#4325] opened 2022-05-04 20:34 UTC
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
The ngbDatepicker was working fine for me, after Angular 12 upgrade i am seeing an issue . The selected date is   05-02-2022 but when i click on the calendar icon the popup is showing month as Jana and year is (current year - 10 years). Please refer the below screen shot. 

<img width="216" alt="Screen Shot 2022-05-04 at 1 29 49 PM" src="https://user-images.githubusercontent.com/52939731/166820903-1f14e05f-855e-42da-9ad8-1d8f88f4488a.png">

### Link to minimally-working StackBlitz that reproduces the issue:

You can fork a StackBlitz from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.

Please note that we can _not_ act on bug reports without a _minimal_ reproduction scenario in a StackBlitz. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 12

ng-bootstrap: 4.2.2

Bootstrap: 4.5.0

**Comment by jnizet** [comment] 2022-05-04 21:01
Hi @justincastlight.

You haven't provided a stackblitz as the issue template requires, and you're using ng-bootstrp 4.2.2, which is very old, and was supposed to be used with Angular 7 and Bootstrap 4.0.0.

Please check the compatibility matrix: https://ng-bootstrap.github.io/#/getting-started#dependencies, use correct and more recent versions, and if you still have an issue, provide a reproduction as requested in the issue template.

**Comment by maxokorokov** [comment] 2022-05-23 12:41
Indeed it defaults to 10 and not configurable. Unless you specify `minDate` and `maxDate`, then it will be in the specified range.

https://github.com/ng-bootstrap/ng-bootstrap/blob/d2f9a558649b8da7619676cd288f287e1cbb936b/src/datepicker/datepicker-tools.ts#L76-L77

**Comment by maxokorokov** [comment] 2022-05-23 12:44
This is however a duplicate of #2412

**Closed by maxokorokov** 2022-05-23 12:44 UTC
Labels: type: feature, component: datepicker
