### ISSUE TITLE
Button moves if mouse over in modal-footer

### ISSUE THREAD

**Issue by Yura13** [ng-bootstrap/ng-bootstrap#1864] opened 2017-09-21 10:05 UTC
### Bug description:
Tooltips added to buttons in the footer of a modal dialog. The last button moves to left if mouse over on this button.
This bug related to the next css styles:
```
.modal-footer > :not(:first-child) {
  margin-left: .25rem;
}

.modal-footer > :not(:last-child) {
  margin-right: .25rem;
}
```

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/lR5hiNA3MNVLBMQW0gGS?p=preview

**Comment by pkozlowski-opensource** [comment] 2017-09-21 10:23
The mentioned CSS comes from the Bootstrap itself and the HTML of the modal window is provided by a user so we can't fix anything on the ng-bootstrap side, I'm afraid. The good news is that the issue is super-easy to work-around, by either:
* wrapping `<button>` into a separate `<div>` element: http://plnkr.co/edit/A0gVIJcEop0PtAtPk9jD?p=preview
* appending tooltip to body: http://plnkr.co/edit/c80RPgKpfxLLaM4TnC28?p=preview

Going to close this issue here as the root cause is in Bootstrap CSS and we can't fix it / work-around it here. On top of this a trivial work-arounds exist on the user side. Still, you can try opening an issue on the Bootstrap side (https://github.com/twbs/bootstrap/issues) if you believe that the CSS should be fixed.

**Closed by pkozlowski-opensource** 2017-09-21 10:23 UTC
