### ISSUE TITLE
ngbDropdown has poor performance - Click handler & DOMRect layout thrashing

### ISSUE THREAD

**Issue by mboughaba** [ng-bootstrap/ng-bootstrap#2951] opened 2018-12-28 13:17 UTC
### Bug description:

ngbDropdown feels really slow. Opening the dropdown list take a noticeable amount of time, even if it contains only 5 items (built using ngFor).
Here is the results from the devtools performance measurement

![image](https://user-images.githubusercontent.com/3800584/50516401-edb08f00-0aaa-11e9-9114-3f1195932128.png)
![image](https://user-images.githubusercontent.com/3800584/50516403-f1dcac80-0aaa-11e9-846c-a8f6d2ccfb7a.png)

The Click handler is taking way too long and computer DOMRect which on its own triggers Layout Thrashing.

I still notice the poor performance even if several issues closed attempting to fix Dropdown perf issue:
https://github.com/ng-bootstrap/ng-bootstrap/pull/1863
https://github.com/ng-bootstrap/ng-bootstrap/issues/2342
https://github.com/ng-bootstrap/ng-bootstrap/issues/900
https://github.com/ng-bootstrap/ng-bootstrap/pull/2518

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.1.3

ng-bootstrap: 4.0.0

Bootstrap: 4.1.3

**Comment by maxokorokov** [comment] 2019-01-08 10:50
@mboughaba we'll gladly investigate the issue, but need more details.

200ms+ is obviously not normal. On the other hand on the demo site it takes < 10ms, so please provide a stackblitz.

You won't be able to avoid style recalculation / reflow, because you'll have to generate dropdown content and calculate its dimensions to position it correctly. But you should have only one, like on the demo site:

![screen shot 2019-01-08 at 11 49 53](https://user-images.githubusercontent.com/8074436/50826316-911b6280-133b-11e9-9817-2b2d440c6dfa.png)

**Comment by maxokorokov** [comment] 2019-01-29 16:13
Will close this as there are no news, feel free to reopen if you have reproduction scenario

**Closed by maxokorokov** 2019-01-29 16:13 UTC
Labels: component: dropdown, needs: info, needs: stackblitz, type: performance
