### ISSUE TITLE
datePicker: Is there a way to show Datepicker in a popup without template variable?

### ISSUE THREAD

**Issue by peterhe2000** [ng-bootstrap/ng-bootstrap#1401] opened 2017-03-24 02:15 UTC
Hi. I am trying to dynamic load datepicker from a *ngFor loop.
I am having trouble to reference datePicker in a popup since it's using template variable to link input-group-addon with datePicker input directive .
So is there a way to show Datepicker in a popup without template variable? Or is there any to bind template variable dynamically?

-------------------------------------------------------------------------------------
Angular:2.4.10

ng-bootstrap:1.0.0-alpha.21

Bootstrap:4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment] 2017-04-05 14:45
Not sure what you mean by "I am having trouble to reference datePicker in a popup since it's using template variable to link input-group-addon with datePicker input directive .". In any case:
* datepicker can work perfectly fine with ngFor: http://plnkr.co/edit/RiafSlkoLhet1sqkMzlx?p=preview
* support requests need to be asked using a dedicated channel: https://github.com/ng-bootstrap/ng-bootstrap#getting-help

If you believe that there is a bug in this library please open a new issue following the issue template and providing live, minimal reproduce scenario, see: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

Closing as a support request.

**Closed by pkozlowski-opensource** 2017-04-05 14:45 UTC
Labels: component: datepicker, needs: design
