### ISSUE TITLE
Ng-bootstrap not working with angular 7.2.15

### ISSUE THREAD

**Issue by andzejsw** [ng-bootstrap/ng-bootstrap#3238] opened 2019-06-14 14:39 UTC
### Bug description:
I have included bootstrap.scss in styles.scss.
Also have included NgbModule in app.module.ts imports section: NgbModule.forRoot();
When i try to use any of ng-bootstrap components (like ngb-alert), they don't work in components. There is only error like this: `'ngb-alert' is not a known element:`

### Versions of Angular, ng-bootstrap and Bootstrap:
Angular: 7.2.15
ng-bootstrap: 4.2.1
Bootstrap: 4.3.1

Am i missing something!?

**Comment by pkozlowski-opensource** [comment] 2019-06-14 14:48
> Angular: 7.3.9
Are you sure? The latest 7.x seem to be 7.2.15

Also, did you follow https://ng-bootstrap.github.io/#/getting-started#installation ? From the error it seems like you are missing ` imports: [NgbModule, ...]` in your application module. But hard to say for sure without a minimal reproduction scenario...

**Comment by andzejsw** [comment] 2019-06-17 09:43
Yes, i followed instructions. 
In package.json i have `"@angular/cli": "~7.3.9"`, and other angular packages with version `7.2.15`.
As i told, i have NgbModule import in my app.module.ts file: `
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
  imports: [
    NgbModule.forRoot(),
...
]
`

**Comment by andzejsw** [comment] 2019-06-17 10:02
> Yes, i followed instructions.
> In package.json i have `"@angular/cli": "~7.3.9"`, and other angular packages with version `7.2.15`.
> As i told, i have NgbModule import in my app.module.ts file: `import { NgbModule } from '@ng-bootstrap/ng-bootstrap'; imports: [ NgbModule.forRoot(), ... ]`

Angular: 7.2.15
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0

**Comment by andzejsw** [comment] 2019-06-17 11:10
Well. This is interesting. It works for me in root, but if ngb modules is used inside my custom widget, they don't work.

**Comment by andzejsw** [comment] 2019-06-17 11:13
Yeah, looks like NgbModule import is needed for each separate module. It doesn't work for me, if i import it in app.module.ts, like other 3rd party libs.

**Comment by benouat** [comment] 2019-06-18 06:38
> Yeah, looks like NgbModule import is needed for each separate module

Yes, this is how Angular is working. Each single module needs to be aware of everything you use inside.

Anytime you are in doubt, do not hesitate to refer back to the official documentation. [Here](https://angular.io/guide/ngmodules#angular-modularity), for example, it is stated that each `@NgModule()` directive needs to import other modules declaring the stuff you need:

> NgModule metadata does the following:
> + ...
> + Imports other modules with the components, directives, and pipes that components in the current module need.

---

Another point also, keep in mind that using `.forRoot()` is **deprecated** and will be removed very soon in `5.0.0`. Our [documentation](https://ng-bootstrap.github.io/#/getting-started#installation) does **not** mention to use it!

---

I will close the issue, as I can see, it seems to be a misconfiguration on your side.
Nonetheless, if you really think that there is something wrong, as stated in our [dedicated section](https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug) please re-open an issue with a minimal reproducible scenario inside a Stackblitz.

**Closed by benouat** 2019-06-18 06:38 UTC

**Comment by faisalzamankhan** [comment] 2020-03-26 07:57
i m getting ngb module error what to do with it i follow all the code in the documentation but still.If someone could explain me what to do with it in simple words as i m new to angular

**Comment by MrCartaaa** [comment] 2020-03-28 20:23
@faisalzamankhan did you resolve this yet? I believe I found a solution.

**Comment by MrCartaaa** [comment] 2020-03-28 20:29
@faisalzamankhan my solution...
1. stop all terminals from running.
2. open the application (oshop?) in your editor (vscode?).
3. open the terminal (CTRL + `)
4. `ng add @angular-localize` on the terminal.. wait for it to finish
5. `npm i @angular/cdk` on the terminal.. wait for it to finish
6. kill the terminal and open a fresh one...
7. `ng serve`
8. the application should be running on [localhost:4200](localhost:4200)

**Comment by faisalzamankhan** [comment] 2020-03-31 13:33
> @faisalzamankhan my solution...
> 
> 1. stop all terminals from running.
> 2. open the application (oshop?) in your editor (vscode?).
> 3. open the terminal (CTRL + `)
> 4. `ng add @angular-localize` on the terminal.. wait for it to finish
> 5. `npm i @angular/cdk` on the terminal.. wait for it to finish
> 6. kill the terminal and open a fresh one...
> 7. `ng serve`
> 8. the application should be running on localhost:4200

ng add @angular-localize
after running this command i got this error
Invalid tag name "@angular-localize": Tags may not have any characters that encodeURIComponent encodes.

**Comment by faisalzamankhan** [comment] 2020-03-31 13:34
ng add @angular-localize
after running this command i got this error
 Invalid tag name "@angular-localize": Tags may not have any characters
that encodeURIComponent encodes.
