### ISSUE TITLE
Issue with NgbModelBackdrop 

### ISSUE THREAD

**Issue by JinnaBalu** [ng-bootstrap/ng-bootstrap#2001] opened 2017-11-29 18:47 UTC
```bash
ERROR { Error: Uncaught (in promise): Error: No component factory found for NgbModalBackdrop. Did you add it to @NgModule.entryComponents?
Error: No component factory found for NgbModalBackdrop. Did you add it to @NgModule.entryComponents?
    at noComponentFactoryError (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:8581:34)
    at CodegenComponentFactoryResolver.resolveComponentFactory (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:8645:19)
    at new NgbModalStack (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:70536:59)
    at _createClass (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:15418:20)
    at _createProviderInstance$1 (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:15388:26)
    at resolveNgModuleDep (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:15373:17)
    at _createClass (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:15418:107)
    at _createProviderInstance$1 (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:15388:26)
    at resolveNgModuleDep (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:15373:17)
    at NgModuleRef_.get (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:16598:16)
    at resolvePromise (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:136092:31)
    at resolvePromise (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:136063:17)
    at /home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:136141:17
    at ZoneDelegate.invokeTask (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:135693:31)
    at Object.onInvokeTask (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:9412:33)
    at ZoneDelegate.invokeTask (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:135692:36)
    at Zone.runTask (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:135460:47)
    at drainMicroTaskQueue (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:135870:35)
    at ZoneTask.invokeTask (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:135771:21)
    at Server.ZoneTask.invoke (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:135756:48)
  rejection: 
   { Error: No component factory found for NgbModalBackdrop. Did you add it to @NgModule.entryComponents?
    at noComponentFactoryError (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:8581:34)
    at CodegenComponentFactoryResolver.resolveComponentFactory (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:8645:19)
    at new NgbModalStack (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:70536:59)
    at _createClass (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:15418:20)
    at _createProviderInstance$1 (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:15388:26)
    at resolveNgModuleDep (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:15373:17)
    at _createClass (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:15418:107)
    at _createProviderInstance$1 (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:15388:26)
    at resolveNgModuleDep (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:15373:17)
    at NgModuleRef_.get (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:16598:16)
     ngComponent: { [Function: NgbModalBackdrop] decorators: [Array], ctorParameters: [Function] },
     __zone_symbol__currentTask: 
      ZoneTask {
        _zone: [Object],
        runCount: 0,
        _zoneDelegates: null,
        _state: 'notScheduled',
        type: 'microTask',
        source: 'Promise.then',
        data: undefined,
        scheduleFn: undefined,
        cancelFn: null,
        callback: [Function],
        invoke: [Function] } },
  promise: 
   ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value: { Error: No component factory found for NgbModalBackdrop. Did you add it to @NgModule.entryComponents?
    at noComponentFactoryError (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:8581:34)
    at CodegenComponentFactoryResolver.resolveComponentFactory (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:8645:19)
    at new NgbModalStack (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:70536:59)
    at _createClass (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:15418:20)
    at _createProviderInstance$1 (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:15388:26)
    at resolveNgModuleDep (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:15373:17)
    at _createClass (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:15418:107)
    at _createProviderInstance$1 (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:15388:26)
    at resolveNgModuleDep (/home/jinna/JINNA-FOLDER/angular-cli/gluoed-app/gluoed/dist/server.js:15373:17)

```

Here is my app.module.ts

```ts
import { BrowserModule, BrowserTransferStateModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';

import { AppComponent } from './app.component';
import { FormsModule } from '@angular/forms';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { HeaderComponent } from './components/layouts/header/header.component';
import { FooterComponent } from './components/layouts/footer/footer.component';
import { MainComponent } from './components/layouts/main/main.component';
import { LoaderComponent } from './components/layouts/loader/loader.component';
import { NotFoundComponent } from './components/not-found/not-found.component';
import { YoutubeTrendingComponent, NgbdModalContentComponent } from './components/youtube-trending/youtube-trending.component';
import { TopHeadlinesComponent } from './components/top-headlines/top-headlines.component';
import { YoutubeService } from './shared/services/youtube.service';
import { GoogleHotTrendsService } from './shared/services/google-hot-trends.service';
import { TwitterHotTrendsService } from './shared/services/twitter-hot-trends.service';
import { InstagramHotTrendsService } from './shared/services/instagram-hot-trends.service';
import { NewsApiService } from './shared/services/news-api.service';
import { CountryService } from './shared/services/country.service';
import { NumaralsPipe } from './shared/pipes/numarals.pipe';
import { TruncatePipe } from './shared/pipes/truncate.pipe';
import { HttpClientModule } from '@angular/common/http';
import { HttpModule, JsonpModule } from '@angular/http';
import { NgbModalBackdrop } from '@ng-bootstrap/ng-bootstrap/modal/modal-backdrop';


@NgModule({
  declarations: [
    AppComponent,
    HeaderComponent,
    FooterComponent,
    MainComponent,
    LoaderComponent,
    NotFoundComponent,
    YoutubeTrendingComponent,
    TopHeadlinesComponent,
    NumaralsPipe,
    TruncatePipe,
    NgbdModalContentComponent
  ],
  imports: [
    BrowserModule.withServerTransition({ appId: 'gluoed-app' }),
    AppRoutingModule,
    NgbModule.forRoot(),
    BrowserModule.withServerTransition({ appId: 'gluoed' }),
    AppRoutingModule,
    HttpClientModule,
    BrowserTransferStateModule,
    HttpModule,
    JsonpModule,
    FormsModule
  ],
  providers: [
    NgbModalBackdrop,
    YoutubeService,
    GoogleHotTrendsService,
    TwitterHotTrendsService,
    InstagramHotTrendsService,
    NewsApiService,
    CountryService],
  bootstrap: [AppComponent],
  entryComponents: [
    HeaderComponent,
    FooterComponent,
    MainComponent,
    LoaderComponent,
    NotFoundComponent,
    YoutubeTrendingComponent,
    TopHeadlinesComponent,
    NgbdModalContentComponent,
    NgbModalBackdrop
  ],
})
export class AppModule { }

```

**Comment by Laragh** [comment] 2017-11-30 16:36
Same issue here, latest version installed, using Angular 5, same error , also same error

**Comment by pkozlowski-opensource** [comment] 2017-12-01 09:12
Hard to say more without a minimal reproduce scenario, but:
* you should _not_ be adding `NgbModalBackdrop` to `entryComponents` - not sure what made you do so...
* universal support is work in progress and is tracked in #858

Closing as a duplicate of #858 - please add a minimal reproduce scenario in there, when you've got it

**Closed by pkozlowski-opensource** 2017-12-01 09:12 UTC

**Comment by elSuperRiton** [comment] 2017-12-08 15:15
Same issue here on Universal 5 ( Updated from 4 ).

**Comment by cravter** [comment] 2017-12-20 20:27
+1

**Comment by CarlosTorrecillas** [comment] 2017-12-21 11:28
@pkozlowski-opensource I think the error / stacktrace suggests the addition to the entryComponents however that doesn't fix it.

`ERROR { Error: No component factory found for NgbModalBackdrop. Did you add it to @NgModule.entryComponents?
    at noComponentFactoryError (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:4169:34)
    at CodegenComponentFactoryResolver.resolveComponentFactory (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:4233:19)
    at new NgbModalStack (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:65744:59)
    at _createClass (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:11190:20)
    at _createProviderInstance$1 (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:11160:26)
    at resolveNgModuleDep (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:11145:17)
    at _createClass (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:11190:107)
    at _createProviderInstance$1 (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:11160:26)
    at resolveNgModuleDep (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:11145:17)
    at _createClass (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:11186:29)
  ngComponent: { [Function: NgbModalBackdrop] decorators: [ [Object] ], ctorParameters: [Function] },
  __zone_symbol__currentTask:
   ZoneTask {
     _zone:
      Zone {
        _properties: [Object],
        _parent: [Object],
        _name: 'angular',
        _zoneDelegate: [Object] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data: undefined,
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }
Unhandled Promise rejection: No component factory found for NgbModalBackdrop. Did you add it to @NgModule.entryComponents? ; Zone: <root> ; Task: Promise.then ; Value: { Error: No component factory found for NgbModalBackdrop. Did you add it to @NgModule.entryComponents?
    at noComponentFactoryError (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:4169:34)
    at CodegenComponentFactoryResolver.resolveComponentFactory (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:4233:19)
    at new NgbModalStack (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:65744:59)
    at _createClass (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:11190:20)
    at _createProviderInstance$1 (C:\Users\carlostorrecillas\Documents\git\jq.website\dist\server.js:11160:26)
    at resolveNgModuleDep (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:11145:17)
    at _createClass (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:11190:107)
    at _createProviderInstance$1 (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:11160:26)
    at resolveNgModuleDep (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:11145:17)
    at _createClass (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:11186:29)
  ngComponent: { [Function: NgbModalBackdrop] decorators: [ [Object] ], ctorParameters: [Function] },
  __zone_symbol__currentTask:
   ZoneTask {
     _zone:
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [Object] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data: undefined,
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } } Error: No component factory found for NgbModalBackdrop. Did you add it to @NgModule.entryComponents?
    at noComponentFactoryError (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:4169:34)
    at CodegenComponentFactoryResolver.resolveComponentFactory (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:4233:19)
    at new NgbModalStack (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:65744:59)
    at _createClass (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:11190:20)
    at _createProviderInstance$1 (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:11160:26)
    at resolveNgModuleDep (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:11145:17)
    at _createClass (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:11190:107)
    at _createProviderInstance$1 (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:11160:26)
    at resolveNgModuleDep (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:11145:17)
    at _createClass (C:\Users\carlostorrecillas\Documents\git\project\dist\server.js:11186:29)`

I've got Ngb integrated on another project and that works fine, however that project doesn't have the NgbModalModule.forRoot() imported. Maybe that's the root cause?

My packages:

"@angular/animations": "5.1.1",
    "@angular/common": "5.1.1",
    "@angular/compiler": "5.1.1",
    "@angular/core": "5.1.1",
    "@angular/forms": "5.1.1",
    "@angular/http": "5.1.1",
    "@angular/platform-browser": "5.1.1",
    "@angular/platform-browser-dynamic": "5.1.1",
    "@angular/platform-server": "5.1.1",
    "@angular/router": "5.1.1",
    "@ng-bootstrap/ng-bootstrap": "1.0.0-beta.8",
    "@nguniversal/express-engine": "5.0.0-beta.5",
    "@nguniversal/module-map-ngfactory-loader": "5.0.0-beta.5",
    "angular2-cookie": "1.2.6",
    "bootstrap": "4.0.0-beta.2",
    "core-js": "2.5.3",
    "font-awesome": "4.7.0",
    "rxjs": "5.5.5",
    "web-animations-js": "2.3.1",
    "zone.js": "0.8.18"

**Comment by cravter** [comment] 2017-12-21 22:04
guys, Injector saved my life. 
Inside your component change this:
<img width="285" alt="screen shot 2017-12-21 at 23 45 02" src="https://user-images.githubusercontent.com/2894896/34276283-5d2b65ca-e6a9-11e7-903f-241cb5df92a3.png">
to this:
<img width="460" alt="screen shot 2017-12-21 at 23 53 12" src="https://user-images.githubusercontent.com/2894896/34276693-2530b330-e6ab-11e7-8812-0e10430fdb35.png">
So NgbModal will be instantiated only for browser version and you wouldn't see error about NgbModalBackdrop

P.S. Angular 5.1.1

**Comment by maksimbykov** [comment] 2018-02-27 14:03
@cravter god bless you!

**Comment by harshbhardwajcsit** [comment] 2018-10-09 18:59
Add NgbModule.forRoot() in your imports, it solves the problem

**Comment by Fl0re** [comment] 2018-10-29 08:33
@harshbhardwajcsit  thx !!! :D

**Comment by var1ap** [comment] 2019-10-16 11:43
> Add NgbModule.forRoot() in your imports, it solves the problem
Thank you!
But now 2019,  import NgbModule without forRoot().

**Comment by AshotAleqs** [comment] 2020-01-29 18:35
In my case, the problem resolves by importing the `NgbModalModule` in the `AppModule`, I tested it it is working inside of all lazy modules. 
Here is my app module

![image](https://user-images.githubusercontent.com/48962964/73386001-91d8bb00-42e7-11ea-9000-b04bba6476fc.png)

**Comment by boopathisakthi** [comment] 2020-04-13 10:20
poda pundaingala

**Comment by gauravdasgupta** [comment] 2020-05-02 14:50
I was stuck in exactly the same problem this whole thread is about and then got rid of it by just following these steps-
1. If you're using Angular ≥ 9.0.0 and ng-bootstrap ≥ 6.0.0, you also have to install the @angular/localize polyfill:

`ng add @angular/localize`
2. import {NgbModule} from '@ng-bootstrap/ng-bootstrap';

```
@NgModule({
  imports: [NgbModule],
})
export class YourAppModule {
}
```

That's it !!
