### ISSUE TITLE
ngbAccordion ClickEvent in ngbPanelTitle not working in Firefox

### ISSUE THREAD

**Issue by stretau** [ng-bootstrap/ng-bootstrap#2757] opened 2018-10-01 15:36 UTC
### Bug description:
If you provide an clickEvent within an ngbPanelTitle template, this clickEvent is triggered in Chrome, Edge, Safari (in my opion correct) but not in Firefox.

Background:
I'm building a menu like accordion in an angular6 application. If the menu have children (submenu) than the accordion is supposed to open, if the menu item hasn't any children only the title is used with clickEvent to the page I want to open.

I saw that there were some accordion changes with version 3.1.0 of ng-bootstrap. You changed there some markup with buttons, etc.Please let me know if there is an another ways to make a special clickEvent on an accordion title and prevent the default to open up the content part.

### Link to minimally-working StackBlitz that reproduces the issue:
See console.log in both browsers. In Chrome "console.log" is set by menuClick(), in Firefox its not firing
https://stackblitz.com/edit/angular-n1rwaj?file=app%2Faccordion-basic.ts

### Versions of Angular, ng-bootstrap and Bootstrap:
Angular 6, ng-bootstrap 3.2.2, bootstrap 4

Thx and best regards

**Comment by giampierobono** [comment] 2018-10-02 09:28
In your example it seems you are using an <a> tag for ngbPanelTitle.

ngbPanelTitle creates a <button> and as its children interactive contents are not allowed, including the <a> tag, so probably the Firefox behaviour is the most standard compliant.  

Check this: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

**Comment by giampierobono** [comment] 2018-10-02 09:55
Why don't you use the `panelChange` event and call the `preventDefault` function if you don't want to expand it?

**Comment by pkozlowski-opensource** [comment] 2018-10-03 15:01
@stretau putting `<a>` tags in the title, as you are trying to do, would result in invalid HTML as you would end up with the `<a>` tag inside `<button>` tag. This is invalid HTML and can lead to unpredictable results.

We've got a number of tickets to improve markup flexibility for accordion titles (ex.: #465, #717) but we are not there yet. Hopefully @giampierobono suggestion will work for you in the meantime. 

Closing as s duplicate of #465 / #717

**Closed by pkozlowski-opensource** 2018-10-03 15:01 UTC

**Comment by pkozlowski-opensource** [comment] 2018-10-03 15:31
@giampierobono produced HTML would contain `<a>` inside `<button>` and this is not valid HTML:

> Permitted content: Phrasing content but **there must be no Interactive content**

Source:  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

> Interactive content includes elements that are specifically designed for user interaction. **Elements that belong to this category include: `<a>`**, ...

Source: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Interactive_content

**Comment by giampierobono** [comment] 2018-10-03 15:40
Yeah I totally agree with you and I was sure about this, but apparently in the phrasing content it's included also <a> with a condition:
> `<a>` if it contains only phrasing content

https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content

I mean, having something like:
`<button>
     <a>Test</a>
</button>`
can be considered as valid HTML because the `<a>` has just text inside and no other attribute?

**Comment by pkozlowski-opensource** [comment] 2018-10-03 15:45
> can be considered as valid HTML because the <a> has just text inside and no other attribute?

Maybe, depending on how you read the specs... In any case @stretau is trying to have an interactive element inside a title that is rendered using a `<button>` tag and I don't think we should recommend users to go down this path - it is just too easy to shoot yourself in a foot.

A proper solution will come from #465 / #717 hence closed as a duplicate.

**Comment by giampierobono** [comment] 2018-10-03 15:47
Yeah totally agree with avoiding using <a> inside <button>! Also because using <a> tag without any interaction would be semantically incorrect.

Thanks @pkozlowski-opensource

**Comment by sheikalthaf** [comment] 2018-12-27 09:20
@pkozlowski-opensource 

I have a requirment of opening the accordion tap on top of the screen on opening. so i need the title element to get `getBoundingClientRect()`. But i can able to do with directive but it is not working in FireFox. Any way to get the title element in `panelChange` event as a property

**Comment by giampierobono** [comment] 2019-01-17 11:12
@kernyden I think it has been changed to follow the Bootstrap accordion component structure. 

Moreover according to [w3c](https://www.w3.org/TR/wai-aria-practices/#accordion), accordion header has to be a button. The only missing part for accessibility is that it should be wrapped into an element with role='heading', but a part of that, this structure I think is correct.

**Comment by maxokorokov** [comment] 2019-01-17 11:34
@giampierobono @kernyden please see #2927 about accessibility

Also `h5` we had from trailing bootstrap docs was removed here → https://github.com/ng-bootstrap/ng-bootstrap/pull/2915/files#diff-72975e4cc867e9f92f930f8ad98b75a0R118

**Comment by giampierobono** [comment] 2019-01-17 11:48
@maxokorokov COOOL! :)

**Comment by kernyden** [comment] 2019-01-17 12:09
@maxokorokov and it doesnt solve our problem, right? How does title be the "multiclickable" in ngbacc?

**Comment by maxokorokov** [comment] 2019-01-17 13:21
@kernyden nope, I think https://github.com/ng-bootstrap/ng-bootstrap/issues/2757#issuecomment-426681685 stays valid and the open issues for this are #465 and #717

**Comment by kernyden** [comment] 2019-01-17 14:42
@maxokorokov glad to hear, now to fix my problem ive used my own ngb-accordion references to https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/accordion/accordion.ts
