### ISSUE TITLE
Missed bootstrap 'dropdown'/'dropup' classes on ngbDropdown host element

### ISSUE THREAD

**Issue by anastasiacrs** [ng-bootstrap/ng-bootstrap#1848] opened 2017-09-14 10:27 UTC
ngbDropdown component  do not have .dropdown/.dropup css class on host element in 1.0.0-beta.4. 
It's OK in beta.3

1.0.0-beta.4:: [http://plnkr.co/edit/vRf4bjLBPUVLDMX2x3At?p=preview](http://plnkr.co/edit/vRf4bjLBPUVLDMX2x3At?p=preview)
1.0.0-beta3:: [http://plnkr.co/edit/uLdQhu7KXCbHkh1GpEV6?p=preview](http://plnkr.co/edit/uLdQhu7KXCbHkh1GpEV6?p=preview)

Angular: 4.3.6

ng-bootstrap: 1.0.0-beta.4 

Bootstrap: 4.0.0-beta

**Comment by pkozlowski-opensource** [comment] 2017-09-14 11:43
* `dropdown` class is no longer needed with  the latest Bootstrap CSS
* `dropup` class is added dynamically when you open a menu (it needs to be added dynamically now since position of the menu can change dynamically with the new placement options)

From our point of view it works as intended. Yes, it is a change, but one that should be more in-line with what Bootstrap does _and_ should not cause any display issues.
Is it causing any display issues on your side?

**Comment by pkozlowski-opensource** [comment] 2017-09-14 12:09
Actually, this is a duplicate of #1847

**Closed by pkozlowski-opensource** 2017-09-14 12:09 UTC
Labels: component: dropdown, needs: info

**Comment by anastasiacrs** [comment] 2017-09-14 12:11
We just expect  to have it as it exists in bootstrap's dropdown.scss and use it to customize styles.  And now we unfortunately need to update our css rules.

**Comment by pkozlowski-opensource** [comment] 2017-09-14 12:16
We are going to add it back in #1847
