### ISSUE TITLE
Angular 4.rc6 and 1.0.0-alpha.21 fails when AOT building

### ISSUE THREAD

**Issue by leon** [ng-bootstrap/ng-bootstrap#1398] opened 2017-03-23 09:27 UTC
### Bug description:
https://github.com/leon/bug-ng-bootstrap-aot-build

# Developing works

```bash
yarn start
```

```
$ ng serve 
** NG Live Development Server is running on http://localhost:4200 **
Hash: 888ec32125e57675671c                                                              
Time: 8119ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 158 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 3.82 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 9.77 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.57 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
webpack: Compiled successfully.
```

# Build with AOT fails

```bash
yarn build
```

```
$ ng build --aot 
 10% building modules 3/3 modules 0 activeCould not resolve module 'function toString() { [native code] }' relative to file /Users/leon/Temp/bug-aot-build/node_modules/@ng-bootstrap/ng-bootstrap/util/util.d.ts
Hash: ffa896c7e882276dae4e                                                              
Time: 2665ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 158 kB {4} [initial] [rendered]
chunk    {1} styles.bundle.js, styles.bundle.js.map (styles) 9.77 kB {4} [initial] [rendered]
chunk    {2} main.bundle.js, main.bundle.js.map (main) 1.09 kB {3} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 805 kB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in m.replace is not a function

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/leon/Temp/bug-aot-build/src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts
error Command failed with exit code 1.
```

**Comment by pkozlowski-opensource** [comment] 2017-03-23 10:07
I can confirm this one. This is definitively a regression in rc.6 or `"@ngtools/webpack": "1.2.14"` as the same code works perfectly fine with rc.5 / "@ngtools/webpack": "1.2.13".

The root cause / error is:

> 10% building modules 3/3 modules 0 activeModuleNotFoundError: Module not found: Error: Can't resolve './../../$$_gendir/demo/src/app/app.module.ngfactory' in '/Users/pawelkozlowski/work/gitrepos/pkozlowski-opensource/core/demo/src'

I'm going to narrow it down and check with the rest of the Angular team to track it down / fix. At the moment it looks like an issue in the Angular. Thx for reporting.

**Comment by pkozlowski-opensource** [comment] 2017-03-23 11:49
OK, I can confirm now that this is a regression in Angular, see the details in https://github.com/angular/angular/issues/15420.

Depending on the team's feedback it will be either fixed today or I will work-around it here by renaming the offending util function. In any case I'm planning to cut a 4.0.0 compatible release today or tomorrow morning the latest.

**Comment by pkozlowski-opensource** [comment] 2017-03-24 08:45
Good news, it was fixed on the Angular side via https://github.com/angular/angular/pull/15430 - just tested it locally and things are fine now. Closing, please update Angular to 4.0.0 final to see it fixed on your side.

**Closed by pkozlowski-opensource** 2017-03-24 08:45 UTC
Labels: blocked: ng2 issue, type: bug

**Comment by rolandoldengarm** [comment] 2017-03-24 20:57
@pkozlowski-opensource are there any plans to upgrade the dependencies to Angular 4? Couldn't find an issue. Currently I get NPM warnings as ng-bootstrap requires Angular 2.x

**Comment by pkozlowski-opensource** [comment] 2017-03-24 21:48
@rolandoldengarm it is already done via c9212e72538052d1bb30c508430a52b5fbab8f07. Upgrade to alpha.22 and all works with 4.0.0 (and continue to work with 2.x)
