### ISSUE TITLE
ease in and out caoursel

### ISSUE THREAD

**Issue by AhadCove** [ng-bootstrap/ng-bootstrap#1351] opened 2017-03-01 19:02 UTC
I can't find any information on how to modify how the carousel changes slide. Typically I would like to have it either fade in and out or slide to the left

**Comment by pkozlowski-opensource** [comment] 2017-03-02 08:59
Duplicate of #295 - we don't support animations just yet.

**Closed by pkozlowski-opensource** 2017-03-02 08:59 UTC

**Comment by BaronChen** [comment] 2017-03-03 00:58
Just in case you need a work around, check this: http://stackoverflow.com/questions/42567906/animation-for-carousel-with-ng-boostrap-and-angular-2

**Comment by AhadCove** [comment] 2017-03-03 20:56
Thank you, this is exactly what I was looking for
