### ISSUE TITLE
Position tooltip / popover at nativeElement

### ISSUE THREAD

**Issue by MickL** [ng-bootstrap/ng-bootstrap#2134] opened 2018-01-30 13:11 UTC
Right now it seems like tooltips / popovers always need an Angular element with the directive `ngbTooltip` or a `ViewChild`. Is it possible to create a tooltip or popover programmatically and just position it at a native element we get from a third-party library (not Angular)?

E.g. on regular Boostrap you can just trigger it on any DOM element:
`$('#example').tooltip(options);`

I would like to do something like this:
```
const exampleNativeElement = document.getElementById('example');
const popoverRef = this.popoverService.open(MyPopoverContentComponent, exampleNativeElement);
popoverRef.componentInstance.name = 'World';
```

If yes, please add an example to the documentation. If no, please consider this as a feature request :)

**Comment by pkozlowski-opensource** [comment] 2018-01-30 14:31
This is an (approximate) duplicate of #870. I'm still on a fence if we want to implement it or not, having real-life use-cases would help to weight this way or another.

Could you please add your exact use-case in #870?

**Closed by pkozlowski-opensource** 2018-01-30 14:31 UTC
