### ISSUE TITLE
NgbAccordion - there is no way to change the default style.

### ISSUE THREAD

**Issue by bbehzadi** [ng-bootstrap/ng-bootstrap#1107] opened 2016-12-02 08:04 UTC
It is not possible to change the style of NgbAccordion, NgbPanel, NgbPanelTitle and NgbPanelContent.  e.g. If using 'type' is not desirable, there is no way to change the background color or remove the borders without studying the internals of the implementation and hacking up a solution.  The API should explicitly support changing all the styles for these elements.

**Comment by pkozlowski-opensource** [comment] 2016-12-14 14:39
@bbehzadi what would be your API proposal for this? We don't want to explode API surface either but if you can propose a reasonable solution we could look into implementing it. A PR with a super-nice implementation would be even better :-)

**Comment by pkozlowski-opensource** [comment] 2016-12-15 10:52
One thing we should probably do is to change classes used from "solid" to "outline" as using a custom type makes the accordion looks ... well, not very pretty....

**Comment by bbehzadi** [comment] 2016-12-17 23:05
Using Bootstrap .card, .card-header, .card-block and all other classes, can be extended and even overridden.  But they are all hidden here.

The problem is beyond this particular component. But to answer your question @pkozlowski-opensource, it is desirable to have everything about the component that can be styled or tweaked  exposed by the API - without any fear of 'API surface explosion'.

The Polymer project has done an excellent job on this front.  Every element in their [catalog](https://elements.polymer-project.org/) is documented in well structured subsections which include Styling, Properties, Events, Examples and comprehensive API Reference. And ALL that can be customized is exposed through the API properties and styling with ample examples and animation hints, etc.

**Comment by pkozlowski-opensource** [comment] 2016-12-21 11:17
@bbehzadi I'm sorry, but you would have to be more specific (that is - exact proposal not just a link to another impl) if you want to push it forward.... 

I've casually looked at https://elements.polymer-project.org/elements/paper-header-panel and honestly I'm not sure what you are proposing. I don't see any specific properties that would control styling. You have styles but so Bootstrap does so you can override Bootstrap classes if you don't like the default theme.

I've got the impression that we don't understand each other that why I'm insisting on _concrete_ examples. Try to prepare a plunk with what you are trying to do and what you believe is "hidden".

**Comment by bbehzadi** [comment] 2017-01-30 04:29
As an example, to customize ngb-accordion background color, I had to **dig in its source code** and find out that in order to achieve that I had to change the background-color and the border-color of the .card, .card-header and .card-block.  These 3 classes are internal to this component and if in some future version of ngb-accordion some other classes are used or simply these are renamed, I am screwed.

If these classes were officially part of the API, in package.json I'd set the version of ng-bootstrap so that the future versions which break the API will not be downloaded and used.  I will consider moving to the new versions if and when I change the app code to match the API change.

This was just a simple example.  If you want to have these components rigid and NOT customizable just close this case and I will have to find other ways.  But if you want these components to be of any use to a wider community please help out by finding a reasonable way to make the styling attributes of ngb-accordion (and for that matter the other components of ngb-bootstrap) customizable and protected by API contracts.  In the previous comments I suggested what the polymer folks have done but you may have better ideas.

Thanks in advance.

**Comment by Anirudh-Konduri** [comment] 2017-05-02 22:14
@bbehzadi How did you even achieve changing the styles by adding custom styles to .card, .card-header, .card-block. I tried to do the same thing but, my custom styles does not show up. All i could see is the default styles.

**Comment by bbehzadi** [comment] 2017-05-03 04:02
Looked under the hoods. Using Chrome DevTools identified the classes used internally and then customized them.  That is the wrong way to do things.  Next version those class names may change as they are not part of the API.  That's why I opened this case.

**Comment by wesleycho** [comment] 2017-05-25 11:53
I'm confused by the claims about concern over the class names changing - those are Bootstrap classes, so they would only change if they change in Bootstrap.

**Comment by Andrey-Pavlov** [comment] 2017-07-19 12:42
Good point here. I need this functionality too. I want to change styles in a component when I use an accordion.

**Comment by maxpark-jd** [comment] 2017-08-07 19:54
Does ::ng-deep work with ng-bootstrap? In my case, /deep/ works fine but I am out of luck using ::ng-deep. I was hoping ::ng-deep to work as A2 team said they will maintain ::ng-deep until the whole shadow dom matter settles in.

**Comment by vzR** [comment] 2017-09-26 10:29
this is what worked for me in Angular 4:
```
::ng-deep .card {
  border-radius: 0px;
}

```
As the tool is describing a use of Bootstrap 4 with Angular you can surely rely on the classes used by bootstrap [4] without any worries of them being changed?

**Comment by bbalvanera** [comment] 2017-11-06 08:00
I believe the idea behind all of these components is for them to use the bootstrap classes for styling. If you are looking to change styles you need to customize your bootstrap.css template instead of overriding or trying to change the classes used by the control itself.

**Comment by woolfred** [comment] 2018-01-27 14:08
Maybe it would help to reference in the documentation which Bootstrap classes are used and need to be overwritten?
`ngb-panel` will be a `card`, `ngbPanelTitle` = `card-header` and `ngbPanelContent` = `card-body`.

But overwriting wasn't a problem for me with an own __accordion.scss_:
```scss
ngb-accordion {
  .card {
    border: none;
    margin-top: -4px;
  }

  .card-header {
    @extend .h4;
    margin-bottom: 0;
    color: $primary-color;
    background-color: transparent;
  }

  .card-body{
    padding-top: 0.75rem;
    padding-bottom: 0.75rem;
  }
}
```

**Comment by manoj30dec** [comment] 2018-02-06 06:15
You need to make your component css file as public from "encapsulation: ViewEncapsulation.None" like
following.  Then it will work.  
@Component({
    selector: 'location-file',
    templateUrl: './location-file.component.html',
    styleUrls: ['./location-file.component.scss'],
    encapsulation: ViewEncapsulation.None
})

**Comment by codeherlife** [comment] 2018-08-24 16:17
Here's what has worked with me (using custom sass variables I created) to modify background colors, etc within the accordion:


::ng-deep div.card-header:hover {
    background-color: var(--subtle-gray);
}

::ng-deep div.card-header a {
    background-color: var(--accent);
    text-decoration: none !important;
}

::ng-deep div.card-body {
    background-color: var(--subtle-gray);
}

**Comment by dziugasmeskauskas** [comment] 2018-09-10 07:34
@codeherlife It should be avoided using ```::ng-deep``` pseudo selector as it will soon be deprecated  
https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep

**Comment by pkozlowski-opensource** [comment] 2018-09-21 09:51
After reading carefully again through this entire thread I think that we are confusing ng-bootstrap customizability with Bootstrap CSS customizability.

All ng-bootstrap widgets are based on Bootstrap CSS. This is the contract and it is already documented in the [Bootstrap pages](http://getbootstrap.com/docs/4.1/getting-started/introduction/). We strictly follow Bootstrap markup and CSS - if there is a discrepancy than it is a bug on our side and we will fix it asap. 

On top of this Bootstrap CSS is already fully customisable as seen in many [existing themes](https://themes.getbootstrap.com/) - you can create your own Bootstrap CSS theme to suit your needs and ng-bootstrap will be happily working with it as it is using standard Bootstrap CSS and markup.

I'm going to close this one since I think that we are all covered here. There is still needed work for covering widgets that have their custom (non-Bootstrap) CSS (ex. datepicker) but this will be handled in a separate issue.

Closing this one for now, if anyone has more precise use-cases that are not covered so far, please open a new issue with a minimal reproduce scenario in a stackblitz.

**Closed by pkozlowski-opensource** 2018-09-21 09:51 UTC
Labels: component: accordion, type: feature

**Comment by tannerturner** [comment] 2019-02-07 20:50
Here's what worked for me in the accordion (not perfect but it's a start):

::ng-deep ngb-accordion {
    .btn-link, .btn-link.collapsed {
        text-align: left;
        width: 100%;
        text-decoration: none !important;
    }
  
   .btn-link:hover {
        text-align: left;
        width: 100%;
        text-decoration: none !important;
    }

    .card-header {
        background-color: var(--light);
    }

    .card-header:hover {
        background-color: var(--subtle-gray);
    }

    .mb-0 {
        width: 103%;
        margin: -10px 0px 0px -20px;
        padding-top: 10px;
    }
}

**Comment by chr1soscl** [comment] 2019-10-21 19:20
any ideas to color the card-header dynamically? I want to paint the background green, red, gray or orange, depending of a section status. sometimes I want the panel green, sometimes red, any ideas?

**Comment by kapsrocks** [comment] 2020-02-19 14:05
Why this issue is closed?, still there is not a proper solution provided for writing custom scss for particular component.

As ng deep will be depricated in future

**Comment by neudesicinterviews** [comment] 2020-07-16 19:00
Check this out- https://ng-bootstrap.github.io/#/components/accordion/examples#config
This allows to pass a config object so as to customize it- but looks limited options are available

**Comment by redevill** [comment] 2021-05-21 17:36
Same reason they closed my Feature request... nothing been done on this problem for 5 years.
As it stands even trying to assign a custom class does not appear to work.

The closure claim was - you can use the "View Encapsulation Turned off" which is NOT a solution. Equivalent to saying you must use Global variables only! - Ridiculous. I have tried this route, and got all kinds of styling being applied where I did not want it.

If you used Css variable, users could re-assign the values to override styling they might want.
This - https://developers.google.com/web/updates/2016/02/css-variables-why-should-you-care?hl=en
