### ISSUE TITLE
NgbDropdown click event not working in Apple IOS  safari browser

### ISSUE THREAD

**Issue by jtan80813** [ng-bootstrap/ng-bootstrap#3510] opened 2019-12-08 09:11 UTC
Hi! I cannot able to perform the (click) function in the safari browser of apple IOS. 
I have `<div class="col col-12 col-sm-4"><button ngbDropdownItem (click)="testclick(1)">Action - 1</button>  </div>`. And it doesn't work

**Comment by maxokorokov** [comment] 2019-12-12 15:47
@jtan80813 could you please provide iOS and Safari versions, but most importantly a StackBlitz to reproduce the issue:

Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a **minimal** reproduction scenario in a StackBlitz

**Comment by benouat** [comment] 2019-12-20 13:56
I am closing this issue as no feedback from author, and also because I can't manage to reproduce.
Tested on iOS 13.3 Safari → Simple click is working.

**Closed by benouat** 2019-12-20 13:56 UTC
Labels: component: dropdown, needs: stackblitz

**Comment by AlekseySorokin** [comment] 2021-09-02 11:52
@benouat 
https://stackblitz.com/run?file=src%2Fapp%2Fdropdown-manual.html

Try to open the blue dropdown by clicking them in Safari.
