### ISSUE TITLE
Feature request/Question: Close other Popovers on new one being opened

### ISSUE THREAD

**Issue by SlimDogs** [ng-bootstrap/ng-bootstrap#1499] opened 2017-04-18 11:01 UTC
### Bug description:

When we have "Popover" triggered by "click" could we limit popover amount to 1? I mean if there is some Popover already open and we click to open another one - could we close the previous popover somehow?

I am not sure if this can be done now (if yes, please refer me to documentation or example). But if it's not done - it's for sure something may come handy in the future releases!

**Comment by pkozlowski-opensource** [comment] 2017-04-18 11:56
Duplicate of #933 - it is rather high priority for us so expect to see it in one of the future releases.

**Closed by pkozlowski-opensource** 2017-04-18 11:56 UTC
