### ISSUE TITLE
Dialogs stacks in incorrect order

### ISSUE THREAD

**Issue by amariniello** [ng-bootstrap/ng-bootstrap#902] opened 2016-10-18 09:33 UTC
### Bug description:

If you open multiple dialogs at the same time the last opened modal get's inserted before the others. 
Example:

--Open 1 dialog (dialog1)
--From  dialog1 open a second dialog (dialog2)-
--dialog2 is not visible as it's hidden under dialog1
--close dialog1 and you will see dialog2

Expected Behavior

dialog2 should be placed in front of dialog1

In my opinion the incriminated piece of code is in the 'master/src/modal/modal-container.ts'
    this._viewContainerRef.createComponent(this._windowFactory, 0, this._injector, contentRef.nodes);

this inserts the element at position 0 (behind)
i personally think the position should be undefined so that it will be inserted last(angular docs)

You can use this template as a starting point: http://plnkr.co/edit/IZ3ugtRbRYYoX0QketIV?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.0.1

ng-bootstrap: 1.0.0-alpha.8

Bootstrap: 4.0.0-alpha.4

**Comment by pkozlowski-opensource** [comment] 2016-10-18 09:37
This will be solved by #901 - merging it later today. Please note that just solving order of elements might not be enough to fully support stacked modals - this is tracked in #643

Closing as a duplicate of #901 and #643

**Closed by pkozlowski-opensource** 2016-10-18 09:37 UTC

**Comment by amariniello** [comment] 2016-10-18 09:39
Yes i understand the challenges. but it will work for simple cases. Thanks
