### ISSUE TITLE
Problems using ngb typeahead in ngb modal

### ISSUE THREAD

**Issue by dnovikov33** [ng-bootstrap/ng-bootstrap#2400] opened 2018-05-23 18:23 UTC
### Bug description:
Bug founded while using ngb modal with ngb tabs in it. On the first tab I tried to create ngb typeahead, however, this.instance is undefined, so I can't call it's method isPopupOpen(). Bug was recreated in pnkr below

### Link to minimally-working plunker that reproduces the issue:

Create a plnkr for founded bug. http://plnkr.co/edit/lyxEQnYMvn6GvsyrCmVB?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: ^5.2.0

ng-bootstrap: 1.1.1

Bootstrap: ^4.1.0

**Comment by pkozlowski-opensource** [comment] 2018-05-25 09:02
Yeh, we are aware that the current developer experience with opening a typeahead on focus isn't the greatest one. We are planning on making it easier in #2318.

Coming back to your issue - the root cause is in Angular queries and dynamically inserted views. We can't do much about it but there is a work-around that you could use for your case: http://plnkr.co/edit/05ACQO4lZDoRcIHisRV4?p=preview

Closing as a support request. We are planning on making it easier for users in #2318.

**Closed by pkozlowski-opensource** 2018-05-25 09:02 UTC

**Comment by dnovikov33** [comment] 2018-05-25 09:08
Thanks a lot!
