### ISSUE TITLE
Page refreshes when clicking on drop down menu

### ISSUE THREAD

**Issue by kolkov** [ng-bootstrap/ng-bootstrap#720] opened 2016-09-10 19:23 UTC
### Bug description:
When I click on dropdown menu my page with youtube videos in iframes refreshes.

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular 2 2.0.0-rc.6, ng-bootstrap 1.0.0-alpha.4, bootstrap 4.0.0-alpha.4

**Comment by pkozlowski-opensource** [comment] 2016-09-10 19:28
> Link to minimally-working plunker that reproduces the issue

This is essential. No reproduce = we can't do much about it.

**Comment by kolkov** [comment] 2016-09-10 19:52
@pkozlowski-opensource Where I can find working plunker with last ng-bootstrap? Thanks!

**Comment by jnizet** [comment] 2016-09-10 20:48
@kolkov You can start from this plunkr: http://plnkr.co/edit/Z23tWp?p=info

**Comment by kolkov** [comment] 2016-09-10 20:51
Thanks!
[plunker with dropdown navbar](https://plnkr.co/edit/jP2aDq83kDjENkvgL6M0)

**Comment by jnizet** [comment] 2016-09-10 21:39
I have no idea what is the root cause of this, but here's what I can tell:
- the problem only shows up when there is an ngb-dropdown, and is caused by the document click listener used to close dropdown when we click outside
- even if the listener does nothing, the problem happens
- the problem does happens for any URL, not just youtube
- the problem doesn not happen if `src="theUrl"` is used instead of `[src]="trustSrcUrl(theUrl)`

**Comment by kolkov** [comment] 2016-09-10 22:06
Maybe it somehow related with each other ...?
https://github.com/ng-bootstrap/ng-bootstrap/issues/687

**Comment by Quinn-L** [comment] 2016-09-11 05:07
I think this is a quirk with Angular2 not ng-bootstrap. In my experience, inlining functions with bindings do not play well together.
What's happening is the document click event causes Angular to do a full view check. Since binding a function is technically returning a "new" object, Angular decides to refresh/recreate the iframe (its actually only the iframe changing, not the full page in your example). 
In this [updated plunker](https://plnkr.co/edit/6gC282X4dVwGidb5n0FN?p=preview), I changed your iframe `src` binding to a cached property.

**Comment by kolkov** [comment] 2016-09-11 11:39
Аnd what are our next steps?

**Comment by pkozlowski-opensource** [comment] 2016-09-11 11:54
> Аnd what are our next steps?

What @kolkov says. The issue at hand is not specific to dropdown but can be demonstrated with _any_ binding that triggers Angular dirty check. Just don't use a function when binding to video URL.

Closing as not related to this project. Thnx for tracking this @Quinn-L !

**Closed by pkozlowski-opensource** 2016-09-11 11:54 UTC
Labels: component: dropdown, needs: plunkr

**Comment by kolkov** [comment] 2016-09-11 12:01
@pkozlowski-opensource Very good, but the problem remains. In the first version AngularJS everything worked as it should. Maybe you should open a new issue on the Angular 2?

**Comment by kolkov** [comment] 2016-09-11 17:29
@pkozlowski-opensource Thanks! I will raise the issue in the Angular 2.

**Comment by kolkov** [comment] 2016-09-11 22:46
This Solution from Angular 2:

> Use pure pipe instead

```
@Pipe({ name: 'safe' })
export class SafePipe implements PipeTransform {
  constructor(private sanitizer: DomSanitizer) {}
  transform(url) {
    return this.sanitizer.bypassSecurityTrustResourceUrl(url);
  }
}
```
https://plnkr.co/edit/9JPA5r0gjTwfVckohihp?p=preview

**Comment by jbistis** [comment] 2018-01-16 21:30
Does anyone have a fix for this?

**Comment by h0m36r0wn** [comment] 2018-09-12 17:08
It seems this issue haven't resolved yet, but for the sake of the others you could   try adding type="button" attribute in your button :)
