### ISSUE TITLE
</my-date-picker> using ngmodel how should i convert date format and send

### ISSUE THREAD

**Issue by chaitanyanadavati** [ng-bootstrap/ng-bootstrap#2140] opened 2018-02-02 02:51 UTC
I am getting date like this 2018-10-17T00:00:00.000Z i should convert to 17.10.18 and send through [(ngModel)] by using my date picker

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:2

ng-bootstrap:

Bootstrap:

**Comment by maxokorokov** [comment] 2018-02-22 14:09
Duplicate of #754, #1977

**Closed by maxokorokov** 2018-02-22 14:09 UTC
Labels: component: datepicker, resolution: duplicate
