### ISSUE TITLE
MinDate get error for yy-mm-dd format

### ISSUE THREAD

**Issue by froufe** [ng-bootstrap/ng-bootstrap#1580] opened 2017-05-25 14:47 UTC
1. If you set minDate with format yyyy-mm-dd (I tried 2017-05-25) 
2. Type in the input with format yy-mm-dd (I tried 17-05-25) 
3. Try to open the popup 

**ERROR Error: 'maxDate' 27-12-31 should be greater than 'minDate' 2017-5-25**

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4

ng-bootstrap: 2.26

Bootstrap: 4.alpha

**Comment by pkozlowski-opensource** [comment] 2017-05-25 14:55
It works as intended, you can't expect datepicker to figure out date format for you... If you want to support different date formats currently you need to implement your own date parser / formatter. See details in https://github.com/ng-bootstrap/ng-bootstrap/issues/754#issuecomment-247767027

Closing as a duplicate of #754

**Closed by pkozlowski-opensource** 2017-05-25 14:55 UTC

**Comment by froufe** [comment] 2017-05-25 15:34
I want to allow only the format yyyy-mm-dd for the input, Do you know how to set it?

Because by default the input accept yyyy-mm-dd and yy-mm-dd.

Thank you in advance

**Comment by pkozlowski-opensource** [comment] 2017-05-25 16:05
Specify `minDate` to a date equal to whatever makes sense in your case: https://ng-bootstrap.github.io/#/components/datepicker

**Comment by yangzhaohui89** [comment] 2017-07-24 07:24
why set a default value for datepicker is so so so so so harder ?..............................
