### ISSUE TITLE
ExpressionChanged error while opening a modal from button

### ISSUE THREAD

**Issue by WizardPC** [ng-bootstrap/ng-bootstrap#2772] opened 2018-10-09 14:24 UTC
### Bug description:

Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'focus: true'. Current value: 'focus: false'.

### Link to minimally-working StackBlitz that reproduces the issue:

[https://stackblitz.com/edit/ngb-error-focus](https://stackblitz.com/edit/ngb-error-focus)

### Versions of Angular, ng-bootstrap and Bootstrap:

See SB.

**Comment by pkozlowski-opensource** [comment] 2018-10-09 14:40
This is a duplicate of #1252. Unfortunately it is not easy to fix (if at all) and the only known work-around is to use `setTimeout` when opening a modal. More info in the linked issue.

**Closed by pkozlowski-opensource** 2018-10-09 14:40 UTC

**Comment by WizardPC** [comment] 2018-10-10 12:18
@pkozlowski-opensource thanks for the link. I update the stackblitz with the workaround.

The Error is thrown by "ngbButtonLabel"
![issue2](https://user-images.githubusercontent.com/11718892/46735662-28b6d980-cc97-11e8-9ef4-89057019583e.PNG)

Any workaround can be integrate to ngBoostrap directly ?
