### ISSUE TITLE
Pagination. Incorrect works with ellipses=true

### ISSUE THREAD

**Issue by tamtakoe** [ng-bootstrap/ng-bootstrap#1881] opened 2017-10-02 06:11 UTC
If we have `ellipses=true` and `maxSize + 2 == collectionSize` ellipses never has to be shown. But it is in most of cases

![1](https://image.prntscr.com/image/MCGecxi4StSDaXT67DrV-Q.png)
![2](https://image.prntscr.com/image/Gud1HNpdRwq6JaFYQN_olA.png)
![3](https://image.prntscr.com/image/Ffeys0ayS0_W5IjxS7UztQ.png)

ng-bootstrap: 1.0.0-beta.5

**Comment by pkozlowski-opensource** [comment] 2017-10-02 06:51
Duplicate of #1235

**Closed by pkozlowski-opensource** 2017-10-02 06:51 UTC
