### ISSUE TITLE
Demo: Collapse does not animate

### ISSUE THREAD

**Issue by rolandoldengarm** [ng-bootstrap/ng-bootstrap#922] opened 2016-10-19 23:08 UTC
The Collapse on the demo site does not animate, while the example on bootstrap.com does animate.

https://ng-bootstrap.github.io/#/components/collapse

I'm a noob at animations, but shouldn't the collapse animate by default? The demo only says "it's easy to add animations", but no guidance provided at all. Not sure how it's supposed to work?

**Comment by pkozlowski-opensource** [comment] 2016-10-20 08:29
We don't have support for animations yet, this is work in progress. Closing as a duplicate of #295

**Closed by pkozlowski-opensource** 2016-10-20 08:29 UTC
