### ISSUE TITLE
Datepicker event when value changes

### ISSUE THREAD

**Issue by MortenSkjoldager** [ng-bootstrap/ng-bootstrap#1531] opened 2017-05-02 08:28 UTC
Feature request:

When working with the datepicker and time picker, the format of the value is an object, however my expected model is just a string, so i want to convert said object into a proper date, and I want to combine it with the time picker as I'm selecting a date and a time. This means that i need to convert both objects into a proper string. So i want output methods on both the datepicker / timepicker that emits the selected value. 

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: ^4.0.0

ng-bootstrap: @ng-bootstrap/ng-bootstrap

Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment] 2017-05-02 09:06
You've got already such events from the `ngModel` directive - just use `(ngModelChange)="...."`. Or you could use getter / setter for your model.

In any case I understand what the issue is but we can't solve it properly right now since Angular is missing basic infrastructure to solve this use-case in an elegant way. We are already tracking this in #545 in this repository and as https://github.com/angular/angular/issues/11097 in the Angular repository.

Closing as a duplicate of the mentioned issues.

**Closed by pkozlowski-opensource** 2017-05-02 09:06 UTC

**Comment by MortenSkjoldager** [comment] 2017-05-02 09:49
I simply don't understand why you have events for when you navigate to another year and month, but not when a date changes. Care to elaborate?

**Comment by pkozlowski-opensource** [comment] 2017-05-02 09:54
> I simply don't understand why you have events for when you navigate to another year and month, but not when a date changes. Care to elaborate?

There is already `ngModelChange` so adding another datepicker-specific event would be pure duplication with no added value. 

Navigation does _not_ date selection so there is no equivalent in `ngModel` - hence presence of datepicker specific events.

**Comment by MortenSkjoldager** [comment] 2017-05-03 08:32
I see. Well. I do not agree. With the current solution i have to bind a temporary value on my input field and do ngModelChange just to get the value to bind to my actual model. In my opinion the added value is simply that your component will be easier and more clean to work with and the documentation is easier to read. To get the value i have to turn to a complete other solution that working with the API exposed by you. Even though you end up having multiple ways of solving the same problem, it's simply also a matter of communication and ease. This is just my opinion though. It works with ngModelChange as well.
