### ISSUE TITLE
modal inside another modal is having issue

### ISSUE THREAD

**Issue by iopossum** [ng-bootstrap/ng-bootstrap#2306] opened 2018-04-12 05:12 UTC
We have parent modal and child modal. When child modal will closed - body's class 'modal-open' will removed too. So we still have visible one modal(parent) and there is no 'modal-open' class.

Angular: 5.2

ng-bootstrap: 1.1.1

Bootstrap: 3.3.7

**Comment by pkozlowski-opensource** [comment] 2018-04-12 08:01
Duplicate of #643 - we are not supporting stacked modals and likely not adding support for stacked modals until it is not supported in the Bootstrap itself.

**Closed by pkozlowski-opensource** 2018-04-12 08:01 UTC
