### ISSUE TITLE
Loading ng-bootstrap causes interference with radio buttons using reactive forms

### ISSUE THREAD

**Issue by karptonite** [ng-bootstrap/ng-bootstrap#1653] opened 2017-06-30 21:19 UTC
### Bug description:
Simple importing `ngbModule` seems to break the initial display for forms with radio buttons using vanilla Angular with bootstrap styles, but not using `ngbRadioGroup`.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/Rs1ZSr4AsqqumgniSSLi?p=preview

When the form loads, the "bar" radio button should be shown as selected, according to the form data. It is not. Commenting out the import of `NgbModule.forRoot()` fixes this bug, and the form properly initializes.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: "current" for angular in the plunkr--currently 2.4.5, I guess.

ng-bootstrap: Alpha 27

Bootstrap: Bootstrap 4 alpha 6

**Comment by karptonite** [comment] 2017-07-01 03:03
Looking more closely, the culprit is definitely related to this: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/buttons/radio.ts#L94
Notice that the selector for NgbRadio is `input[type=radio]`. While I see that there is an awful lot of checking of `_group`, presumably to make sure that if there is no parent group, it has no effect, those host bindings are still being created, and presumably something there is interfering with angular forms proper.
I'm not sure of the solution, but perhaps some sort of prefixed selector for NgbRadio would be appropriate? Even if this bug is fixed, it doesn't seem ideal that this directive is getting applied everywhere.

**Comment by pkozlowski-opensource** [comment] 2017-07-04 08:02
Duplicate of #1125

**Closed by pkozlowski-opensource** 2017-07-04 08:02 UTC
