### ISSUE TITLE
Is there a way to show the current today a little bit dark so that user gets to know it

### ISSUE THREAD

**Issue by xyrintech** [ng-bootstrap/ng-bootstrap#2383] opened 2018-05-16 16:46 UTC
Is there a way to show the current today a little bit dark so that user gets to know it

**Comment by pkozlowski-opensource** [comment] 2018-05-16 17:37
Not sure what you mean by "current today" as you might have different things:
- currently _selected_ date in the model
- currently _focused_ date (when using keyboard navigation)
- today

Regardless of what you want to do, exactly, you can customise look & feel of a day's display by using a custom day template as shown in the [Custom day view example](https://ng-bootstrap.github.io/#/components/datepicker/examples#customday)

Also potential duplicate of #1470

There is not enough context here to say more - closing as a support request / duplicate.

**Closed by pkozlowski-opensource** 2018-05-16 17:37 UTC
