### ISSUE TITLE
(demo) Anchor links don't work

### ISSUE THREAD

**Issue by maxkorz** [ng-bootstrap/ng-bootstrap#2602] opened 2018-08-13 11:33 UTC
Example: https://ng-bootstrap.github.io/#/components/accordion/examples#preventchange

I expect the browser to jump to the heading `Prevent panel toggle`, but it does not happen. 

Windows 10, Google Chrome 68.

**Comment by pkozlowski-opensource** [comment] 2018-08-13 11:45
This is a duplicate of #2529

**Closed by pkozlowski-opensource** 2018-08-13 11:45 UTC
Labels: type: bug, type: demo site
