### ISSUE TITLE
Timepicker: Incorrect format of numbers

### ISSUE THREAD

**Issue by dzagaduroska** [ng-bootstrap/ng-bootstrap#2722] opened 2018-09-18 20:02 UTC
**Bug description**: Timepicker does not format the number when the same number is entered twice.

Steps to reproduce this bug:
1. Type a number without leading zeros in the hour field (or time) e.g 2
2. Click outside the component -> now the field should be filled with one leading zero e.g 02
3. Remove the value and enter the same value again ( in this case 2 ) -> the value remains 2 and a leading zero is not added.

**Link to minimally-working plunker that reproduces the issue**: http://plnkr.co/edit/QU3846?p=preview

**Version of Angular, ng-bootstrap, and Bootstrap**:

Angular: 6.1.3

ng-bootstrap: 3.2.0

Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment] 2018-09-18 20:37
Duplicate of #1644

**Closed by pkozlowski-opensource** 2018-09-18 20:37 UTC

**Comment by AmanJais0660** [comment] 2024-09-29 17:21
resolved work around with above 
https://stackblitz.com/~/github.com/AmanJais0660/stackblitz-starters-r2t2bn
![image](https://github.com/user-attachments/assets/ab20399e-2c6e-41bf-bf07-20cc988219fb)
