### ISSUE TITLE
Open Typeahead on click input

### ISSUE THREAD

**Issue by elioth010** [ng-bootstrap/ng-bootstrap#1586] opened 2017-05-26 16:01 UTC
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
Feature, not bug.
I want expand the Typeaead against when the input has a focus o was clicked.

### Link to minimally-working plunker that reproduces the issue:
You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
4.0.0
ng-bootstrap:
1.0.0-alpha.25
Bootstrap:
3.3.7

**Comment by pkozlowski-opensource** [comment] 2017-05-26 19:45
Duplicate of #698. Please check the existing issues before opening new ones.

**Closed by pkozlowski-opensource** 2017-05-26 19:45 UTC
