### ISSUE TITLE
(Tab) Create tabs inside another tab content is hiding parent tab and error

### ISSUE THREAD

**Issue by aniruddhadas9** [ng-bootstrap/ng-bootstrap#1630] opened 2017-06-21 18:29 UTC
### Bug description:

Tab inside another tab content is hiding parent tab and only showing child tabs

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/Nw9utaWLYwmbhQW2OMLb?p=preview

### Description
I have a requirement where I need to create bunch of tabs inside another tab content. When I put set of tabs inside a tab, it show wired behavior.

In the plunker the tabs inside the first tab content will not be visible until you click in the heading of the tab and if you will click another tab then the child tabs will not be visible any more.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.1.3
ng-bootstrap: 1.0.0-alpha.26
Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment] 2017-06-21 18:37
Duplicate of #1433

**Closed by pkozlowski-opensource** 2017-06-21 18:37 UTC

**Comment by aniruddhadas9** [comment] 2017-06-22 18:13
@pkozlowski-opensource  thanks for marking duplicate and the below stackoverflow link solution worked for me

Here is work around for nested tab by using extra template http://stackoverflow.com/a/43720470/2435473
