### ISSUE TITLE
Performance and Memory Leak when using ngbDropdown

### ISSUE THREAD

**Issue by carlos-algms** [ng-bootstrap/ng-bootstrap#2336] opened 2018-04-21 23:47 UTC
### Bug description:
Each ngbDropdown inserted in the HTML is binding global mouse events.
Those events are exponentially triggering changes detection to all components on the screen, causing application slowdown and, depending on number of components on the page, the app get freeze.

### Link to minimally-working plunker that reproduces the issue:
https://stackblitz.com/edit/angular-or5uez

One can just click on a blank area of the demo and look at the console to see logs growing. 
It is happening no mater where the click happens. 

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: All

ng-bootstrap: 1.1.2

Bootstrap: not relevant

**Comment by pkozlowski-opensource** [comment] 2018-04-22 13:58
Duplicate of #900

**Closed by pkozlowski-opensource** 2018-04-22 13:58 UTC
