### ISSUE TITLE
NgbInputDatepicker highjacks change detection on input field

### ISSUE THREAD

**Issue by phil-cap** [ng-bootstrap/ng-bootstrap#1225] opened 2017-01-18 15:27 UTC
The NgbInputDatepicker directive appears to highjack change detection capabilities of Angular 2 on input elements.
Once the directive is added to an input element, i do not receive any change events on keyup when changing the date directly in the input field. 
The changes are however detected once i click somewhere outside the input field.

**Comment by pkozlowski-opensource** [comment] 2017-01-18 15:32
Could you please provide a minimal plunker that demonstrates a difference with and without the datepicker directive. AFAIK the `change` event is executed on blur only so won't execute on keyup events - you might be looking for the `input` event (?).

What are you trying to achieve, exactly?

**Comment by phil-cap** [comment] 2017-01-19 09:01
@pkozlowski-opensource apologies for the lack of information. I was frustrated of multiple hours of failed attempts at resolving the issue and lacked the necessary patience.
Hiere is the plunk: [plunker](http://plnkr.co/edit/DIBD1Te1cXCj2RqssNOy?p=preview)

Essentially form validation, which is triggered by `keyup` events, stops working as expected once the `ngbDatePicker ` directive is applied. The event then switches to `on blur` from what i can tell.

I currently do not know how to enforce input validation to ensure content is valid before form submission.

**Comment by pkozlowski-opensource** [comment] 2017-01-19 09:46
@phil-cap thnx for the plunk. I think I see what you mean. My first knee-jerk reaction is that it works as expected. Looking at the validation constraints you've got in your plunk (`required`, `minlength` and `maxlength`) I would argue that:
* `required` should get valid only if a valid date is entered - making it valid on any character doesn't make sense IMO since for a datepicker an atomic entry is entire date;
`minlength`  and `maxlength` doesn't make sense at all in the context of picking date so I would not expect those validation constraints to have any effect. What was your intended behavior here?

Having said all the above I can see from where you are coming from. I'm planning to work on another issue around date validation this / next week so I will look into several use case. In the meantime I would ask you to:
* share more of your thoughts on `required`, `minlength`  and `maxlength`  validation constraints given my above comments;
* have a look at #1222 which also talks about date validation - maybe we should merge the 2 issues?

**Comment by phil-cap** [comment] 2017-01-19 10:14
@pkozlowski-opensource thanks for your speedy feedback. I must admit that the `minlength` and `maxlength` validations are unrealistic in this `date` context. I was using them as regular expression placeholders. I had trouble with Angular 2 concerning regexes before on a separate issue and hence picked something simpler.

So the general problem is as follows: with the `NgbInputDatepicker` directive dates can be entered via the pop-up date picker, or manually via the input field. There is a strong case for validating manually entered input on `keyup` using a Regex or even Date.parse(). The user is then immediately informed if the recently entered input is invalid, and, more importantly, reacting to `keyup` is necessary to prevent submission of the form if the input data is invalid. 

I personally implemented a directive that validates the said input field by running a RegExp over its contents, combined with a `Date.parse() !== NaN` check. The big issue is however, that the directive is only applied on `blur` from what i can tell. This means the user can enter a wrong date via the input field and click on the submit button without knowing that something went wrong.

I hope this somewhat clarifies the issue at hand. My plunker illustrates the problem, albeit with unrealistic validations. The minlength for example is not applied on `keyup`, so the form control is marked as valid albeit the data being invalid (e.g. too few characters).

This is somewhat related to #1222. In vague, abstract terms: the `ngbDatePicker` should *synchronize* with the underlying input field to a closer degree, validating on all changes to the input form. 

Do you perhaps have a workaround for the current dilemma? I am currently trying to use `_elRef.nativeElement.value` to somehow validate the input field.

**Comment by phil-cap** [comment] 2017-01-19 11:10
I have managed to come up with a partial solution, see here [plunker for manual form control validation](http://plnkr.co/edit/DIBD1Te1cXCj2RqssNOy?p=preview). Through the use of `elRef.nativeElement.value` to inspect the user's manual input, combined with Ang2's `setErrors(...)` method of the `FormControl` class, it is possible to manually validate the input. The downside is that the `ngbDatePicker` naturally clears the input field on `blur` or `submit`, since it cannot parse the contents into an `ngbDateStruct`. 

Ideally the invalid (manual) input content should remain on parse failure...

@pkozlowski-opensource what do you think of this? This all seems a bit of overkill. It is just that the reactive way is to provide feedback as soon as possible. my current view has validation on input fields that react on `keyup` throughout, and the `ngbDatePicker`'s approach collides with this.

**Comment by pkozlowski-opensource** [comment] 2017-01-24 11:04
@phil-cap I wanted to take some time thinking about various validation cases before rushing into any implementations and here is the resulting design doc: https://docs.google.com/document/d/1NmyKQjpmva62-Y8A-nfzJjD3p09fb-Q-UtS39HzFjTo/edit?usp=sharing

Regarding your input:

> There is a strong case for validating manually entered input on keyup using a Regex or even Date.parse(). The user is then immediately informed if the recently entered input is invalid, 

I would argue that the opposite makes more sense: if, as a user, I'm entering a date, I _know_ that it is invalid while I'm typing. See more info in the linked doc.

> more importantly, reacting to keyup is necessary to prevent submission of the form if the input data is invalid.

How is so? Submitting a form will result in a `blur` even on the datepicker first, no?

Anyway, would love to hear more input (comments here or in the doc). I will also check with the material team to gather their feedback.

**Comment by phil-cap** [comment] 2017-01-31 13:31
@pkozlowski-opensource Hi Pawel i just commented your insightful document. Apologies for the delay.
Here some comments on your response:

> I would argue that the opposite makes more sense: if, as a user, I'm entering a date, I know that it is invalid while I'm typing. See more info in the linked doc.

Very true.... You are right. And validating on every key is definitely overkill. However, validating with debouncing can lead to nice solutions.

Concerning my statement

> more importantly, reacting to keyup is necessary to prevent submission of the form if the input data is invalid.

This is indeed incorrect. However, the submit button associated with the form remains enabled since `blur` is only triggered after clicking the button. While this makes sense in most situations, it prevents achieving full validation before submission. Perhaps my suggestion in the document of exposing a `validate` function is good solution.

Hope the feedback is useful.

**Comment by PerfectPixel** [comment] 2017-02-28 14:37
Another _odd_ behaviour with parsing on `blur` or `change` is if you use the css classes like `ng-invalid` to add visual markers to your input, they are only updated on a `blur` or `change` event.

Once the user finished typing, you have a valid date visible in your input, however, it is marked as invalid as the user has not yet triggered a `change` or `blur` event.

Same goes with disabling the submit button if the form is invalid. You see a valid form but cannot send it unless you switch focus away from the input.

**Comment by critchie** [comment] 2017-04-21 18:16
I think if the Datepicker would fire a valueChanges event on every key press the Datepicker could do whatever it needed internally and still give the consuming code a chance to do whatever it wanted outside of the Datepicker, such as disable a Submit button.  But it doesn't appear the Datepicker fires a valueChanges on every key press, only on the blur.

[Plnkr](https://embed.plnkr.co/z0VPswkNSjerqQQ4ckB1/)

You receive no console output while typing in the Datepicker input like you do in the Event Name input.  You only get a console output on the blur from the Datepicker.

Firing a valueChanges event on every key press seems like the proper functionality for this.  The value after all has changed.  There should be no concerns about the value being valid.

**Comment by pkozlowski-opensource** [comment] 2017-04-22 11:19
@PerfectPixel @critchie OK, I think that you guys convinced me! Let's change the behaviour and listen to the `(input)` event instead of the `(change)` one. 

A PR would be awesome.

**Comment by eden91940** [comment] 2017-06-01 14:42
wainting this fix... :+1:

**Closed** 2017-08-02 09:43 UTC
Labels: component: datepicker, needs: design

**Comment by dotNetAthlete** [comment] 2018-11-15 18:22
The only way I have found so far to deal with this is (Reactive Forms)

this.reportForm.controls['dateFromPicker'].valueChanges.subscribe(data => {
...validation on data here, etc...
