### ISSUE TITLE
How change ngbDatepicker format to "dd-mm-yyyy" ?

### ISSUE THREAD

**Issue by Arpanx** [ng-bootstrap/ng-bootstrap#2072] opened 2018-01-04 15:57 UTC
Only please do not give a link to the past discussion. I re-read everything, there is no working solution.

**Comment by nicoabie** [comment] 2018-01-09 15:48
Create  custom parser formatter.

```javascript
import { NgbDateParserFormatter, NgbDateStruct } from '@ng-bootstrap/ng-bootstrap';
import { Injectable } from '@angular/core';
import { isNumber, toInteger, padNumber } from '@ng-bootstrap/ng-bootstrap/util/util';

@Injectable()
export class NgbDateCustomParserFormatter extends NgbDateParserFormatter {
  parse(value: string): NgbDateStruct {
    if (value) {
      const dateParts = value.trim().split('-');
      if (dateParts.length === 1 && isNumber(dateParts[0])) {
        return {day: toInteger(dateParts[0]), month: null, year: null};
      } else if (dateParts.length === 2 && isNumber(dateParts[0]) && isNumber(dateParts[1])) {
        return {day: toInteger(dateParts[0]), month: toInteger(dateParts[1]), year: null};
      } else if (dateParts.length === 3 && isNumber(dateParts[0]) && isNumber(dateParts[1]) && isNumber(dateParts[2])) {
        return {day: toInteger(dateParts[0]), month: toInteger(dateParts[1]), year: toInteger(dateParts[2])};
      }
    }
    return null;
  }

  format(date: NgbDateStruct): string {
    return date ?
        `${isNumber(date.day) ? padNumber(date.day) : ''}-${isNumber(date.month) ? padNumber(date.month) : ''}-${date.year}` :
        '';
  }
}
```
Set the provider for the custom parser formatter in the @NgModule.

```javascript
providers: [
    {provide: NgbDateParserFormatter, useClass: NgbDateCustomParserFormatter}
   ]
```
As described in the [api](https://ng-bootstrap.github.io/#/components/datepicker/api#NgbDateParserFormatter)

**Comment by maxokorokov** [comment] 2018-01-19 13:00
Opened a separate datepicker documentation issue: #2102 
Closing this one

**Closed by maxokorokov** 2018-01-19 13:00 UTC
Labels: component: datepicker, type: doc

**Comment by kotmatpockuh** [comment] 2018-01-31 11:03
@nicoabie your code won't work in case of keybord input in input

**Comment by nicoabie** [comment] 2018-01-31 13:51
@kotmatpockuh  feel free to submit an issue, my code does not handle that.

**Comment by astashko** [comment] 2018-02-05 10:46
@nicoabie your code handles that. He changed delimiter from '-' to '.' only for format.

**Comment by kotmatpockuh** [comment] 2018-02-05 11:13
@astashko it doesn't matter
any custom format won't work
even with - or .

**Comment by nicoabie** [comment] 2018-02-05 12:58
@astashko ???

> "your code won't work in case of keybord input in input-box"

how am I supposed to understand from that sentence the problem @kotmatpockuh was experiencing with underscores and colons?

**Comment by astashko** [comment] 2018-02-05 13:11
@nicoabie you don't need to. My reply is rather for anyone who finds this issue while searching for the ways to change the date format. After his comment this thread looked like your solution is only 50% working while in reality it's fully functional.

**Comment by Pinguinmann** [comment] 2018-02-16 13:48
In case you having issues.
You have to adapt @nicoabie s version slightly for using dots, even though for his case it was certainly right.
```
const dateParts = value.trim().split(/\./g);
 if (!this.isDateValid(value)) {
 return null;
}
```
// splitting by dots & additional validation function (next to parse & format in your custom DateParser)

I added a custom validation for the input field of the input datepicker, as the user could enter an invalid date in the input box like 29.02.2018. In theory javascript would "overflow" it and count it as the first day of march but the user would think the day is still in february.

```
isDateValid(value :string) :string {
const regexValid :boolean = value.match(/^(0[1-9]|1[0-9]|2[0-9]|3[0-1]){1}\.(0[1-9]|1[0-2]){1}\.\d\d\d\d$/g) === null ? false : true; // you get the idea.

if (!regexValid) { return null; } 
// if this doesnt match the date format is in wrong format (user made a syntax error).
// Next test must be done for semantics (e. g. 29.02.2018 is invalid) :

const dateItems :string[] = value.split(/\./g); 
// you can split the value like this as you have checked previously if user entered this format.

const isDateValid :boolean = regexValid && parseInt(dateItems[1], 10) <= new Date(parseInt(dateItems[2], 10), parseInt(dateItems[1], 10), 0).getDate();

return isDateValid;
}
```

And woooha everything works as expected.

FYI: 
With creating a Date Object with DayInMonth 0 you get the maximum days of last Month.
Important here is: as months start at 0 in js-Date you would normally pass `-1 + month` for the month parameter in the date constructor, but not this time, as you want to create a date in next month and get the max days of previous month

**Comment by LeonadoRivaldo** [comment] 2018-04-06 16:07
@nicoabie can u explain what this parse function is used for inside the component?

thx.

**Comment by korenb** [comment] 2018-10-23 13:07
I simply use moment.js for that
```ts
import { NgbDateParserFormatter, NgbDateStruct } from "@ng-bootstrap/ng-bootstrap";
import * as moment from 'moment';

export class MomentDateFormatter extends NgbDateParserFormatter {

    readonly DT_FORMAT = 'MM/DD/YYYY';

    parse(value: string): NgbDateStruct {
        if (value) {
            value = value.trim();
            let mdt = moment(value, this.DT_FORMAT)
        }
        return null;
    }
    format(date: NgbDateStruct): string {
        if (!date) return '';
        let mdt = moment([date.year, date.month - 1, date.day]);
        if (!mdt.isValid()) return '';
        return mdt.format(this.DT_FORMAT);
    }
}
```

**Comment by nicoabie** [comment] 2018-10-23 14:00
@korenb that is ok if you were already using **moment** in your application. Adding such a dependency for this is a waste of bytes.

**Comment by nicoabie** [comment] 2018-10-26 22:21
Hey @amitsbaghel, I wouldn't recommend copying those functions over when they are being exported. Probably the path was wrong but there is really no need to copy them.

**Comment by brent-langdon** [comment] 2018-10-31 19:32
@nicoabie: Copying seems needed to use utils, based on this: https://github.com/ng-bootstrap/ng-bootstrap/issues/2566

> Sorry, this will be a breaking change in 3.0.0 - we are migrating to Angular package format and as such you will not be able to use "deep" imports.
> 
> I know that this is not what you want to hear but we see this as a "good thing" since util is supposed to be our private implementation detail and not meant to be pubic API...
> 
> This is a very simple utility so feel free to copy it over to your project if you need it: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/util/util.ts
>

**Comment by nicoabie** [comment] 2018-10-31 20:58
@brent-langdon I was not aware of that, thanks!
I will add my opinion to see if they can change that a bit.

**Comment by amitsbaghel** [comment] 2018-10-31 23:56
Thank you very much @brent-langdon.
I spent a long time to figure out where I was wrong but I still believed that they are no more exporting those functions.

**Comment by gmac-softrax** [comment] 2019-03-18 17:26
Don't have time to monkey around with something that should be extremely simple for a control of this type: displaying the date in a format other than 2019-03-19.

Will find a suitable, working alternative. Can't waste any more time. It's March 2019, and this has been an issue for years. Unacceptable.

**Comment by wiadev** [comment] 2019-04-30 02:49
Isn't there an easy way to change the format? (e.g via props. format="mm/dd/yyyy")

I'm getting the format from the API and change it very frequently but with the ParserFormatter service, I don't have the flexibility to change it.

**Comment by jivan-supe** [comment] 2019-05-10 06:39
@nicoabie Worked for me! thanks a ton! :) :)

**Comment by jivansupe** [comment] 2019-05-10 06:41
@nicoabie Worked like charm!! Thanks a lot 💯 👍

**Comment by pauloantonelli** [comment] 2019-05-28 03:57
> I simply use moment.js for that
> 
> ```ts
> import { NgbDateParserFormatter, NgbDateStruct } from "@ng-bootstrap/ng-bootstrap";
> import * as moment from 'moment';
> 
> export class MomentDateFormatter extends NgbDateParserFormatter {
> 
>     readonly DT_FORMAT = 'MM/DD/YYYY';
> 
>     parse(value: string): NgbDateStruct {
>         if (value) {
>             value = value.trim();
>             let mdt = moment(value, this.DT_FORMAT)
>         }
>         return null;
>     }
>     format(date: NgbDateStruct): string {
>         if (!date) return '';
>         let mdt = moment([date.year, date.month - 1, date.day]);
>         if (!mdt.isValid()) return '';
>         return mdt.format(this.DT_FORMAT);
>     }
> }
> ```

Thanks Bro! You solution solved my problem! 

I was taking problems of: 
import { isNumber, toInteger, padNumber } from '@ng-bootstrap/ng-bootstrap/util/util';

but now i dont need it.

Many thanks!

**Comment by randym127** [comment] 2019-08-13 19:03
> I simply use moment.js for that
> 
> ```ts
> import { NgbDateParserFormatter, NgbDateStruct } from "@ng-bootstrap/ng-bootstrap";
> import * as moment from 'moment';
> 
> export class MomentDateFormatter extends NgbDateParserFormatter {
> 
>     readonly DT_FORMAT = 'MM/DD/YYYY';
> 
>     parse(value: string): NgbDateStruct {
>         if (value) {
>             value = value.trim();
>             let mdt = moment(value, this.DT_FORMAT)
>         }
>         return null;
>     }
>     format(date: NgbDateStruct): string {
>         if (!date) return '';
>         let mdt = moment([date.year, date.month - 1, date.day]);
>         if (!mdt.isValid()) return '';
>         return mdt.format(this.DT_FORMAT);
>     }
> }
> ```

Is there a way to make the date format more dynamic, I ended up with a solution very close to yours.  However I need to pass in the format, and I am just hitting road blocks in everything I try.

**Comment by nicoabie** [comment] 2019-08-13 20:12
@randym127  Your MomentDateFormatter is a class like any other.
Just declare a constructor for it and pass the format string.
Then

```
providers: [
    {provide: NgbDateParserFormatter, useValue: new MomentDateFormatter('MM/DD/YYYY')}
   ]
```

**Comment by randym127** [comment] 2019-08-13 20:45
> @randym127 Your MomentDateFormatter is a class like any other.
> Just declare a constructor for it and pass the format string.
> Then
> 
> ```
> providers: [
>     {provide: NgbDateParserFormatter, useValue: new MomentDateFormatter('MM/DD/YYYY')}
>    ]
> ```

I needed it to be a bit more dynamic than that, its a dynamic reactive form.  And each date component could have its own format.  I have it working through a service, and set the format on a focus event.

{provide: NgbDateParserFormatter, deps: [FormatService], useClass: FormDateFormatter}

I don't have the format until the form renders for each field.

**Comment by szymonworld** [comment] 2019-08-19 11:32
> @randym127 Your MomentDateFormatter is a class like any other.
> Just declare a constructor for it and pass the format string.
> Then
> 
> ```
> providers: [
>     {provide: NgbDateParserFormatter, useValue: new MomentDateFormatter('MM/DD/YYYY')}
>    ]
> ```

There is some kind of way to pass my service or just use my service inside extended NgbDateParserFormatter ?

I need to dynamic change format base on current language.

**Comment by randym127** [comment] 2019-08-19 14:07
I can post my code later, not in office today.  But I used a service as they mentioned above.  Injected it into the formatter, you need to depend on the service in the provider.  Then in my dynamic form I set the format on focus in each date component.  I used the formatting based on moment so nothing fancy there.   DOB format is always different but on same form.  Really poorly designed component and architecture.  Shouldn't be that hard to pass a value to the date picker.

**Comment by tibistibi** [comment] 2019-09-29 16:18
@korenb i noticed your parse always returns null. I changed it to this:

```import { NgbDateParserFormatter, NgbDateStruct } from '@ng-bootstrap/ng-bootstrap';
import * as moment from 'moment';

export class MomentDateFormatter extends NgbDateParserFormatter {
  readonly DT_FORMAT = 'DD-MM-YYYY';

  parse(value: string): NgbDateStruct {
    if (value) {
      const mdt = moment(value.trim(), this.DT_FORMAT);
      return { day: mdt.day(), month: mdt.months() + 1, year: mdt.year() };
    }
    return null;
  }
  format(date: NgbDateStruct): string {
    if (!date) {
      return '';
    }
    const mdt = moment([date.year, date.month - 1, date.day]);
    return mdt.isValid() ? mdt.format(this.DT_FORMAT) : '';
  }
}
```

**Comment by vidvidvid** [comment] 2019-10-07 13:48
@randym Could you post your code, please? I'm stuck with exactly the same issue. Would be super thankful!

**Comment by randym127** [comment] 2019-10-07 21:25
> @randym Could you post your code, please? I'm stuck with exactly the same issue. Would be super thankful!

Sorry totally forgot about this.  We display a few date pickers per form and can be different formats depending on the configuration of the form.  The main variance is between regular date entry and DOB date entry.  Actually had to write my own year only and month-year pickers as the date picker didn't work well with partial date formats.

**The module code, this is the tricky bit.**
`providers: [
    {provide: NgbDateAdapter, useClass: NgbDateNativeAdapter},
    {provide: NgbDateParserFormatter, deps: [FormatService], useClass: FormDateFormatter}
  ],`

**Formatter based off of code I got on here, thank you!**

`import { NgbDateParserFormatter, NgbDateStruct } from '@ng-bootstrap/ng-bootstrap';
import { FormatService } from './format.service';
import moment from 'moment';

export class FormDateFormatter extends NgbDateParserFormatter  {

    fail: string;

    constructor(private formatService: FormatService) {
        super();
    }

    parse(value: string): NgbDateStruct {
        if (value && this.formatService.format) {
            const d =  moment(value, this.formatService.format);
            return { year: d.year(), month: (d.month() + 1), day: d.date()};
        }
        return null;
    }

    format(date: NgbDateStruct): string {
        if (date && this.formatService.format) {
            const result = moment().year(date.year).month(date.month - 1).date(date.day).format(this.formatService.format);
            return result;
        }
        return null;
    }

}
`
**My Service**
`import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class FormatService {

  public format: string;

  constructor() { }
}`

**Component html**
`(focus)="setFormat()"`

**Component**
`setFormat() {
    this.formatService.format = this.config.format;
  }`

**Comment by vidvidvid** [comment] 2019-10-08 08:45
@randym127 Thank you so very much! However there is till one little detail missing - when my forms are loaded with data, how do I trigger the setFormat function on element initialization? I would like to pass the data about the format to the date formatter, however now the data is passed only on focus. I have tried the (onload) function and setting a directive as suggested in the answer by Dakota: https://stackoverflow.com/questions/48335720/angular-i-want-to-call-a-function-when-element-is-loaded?noredirect=1&lq=1 but it doesn't work. Do you have any suggestion on how I should try to fix this problem?

**Comment by randym127** [comment] 2019-10-08 17:14
@vidvidvid Sorry TBD over here on that.   I hope to get to the edit functionality of our Dynamic Form soon, next few sprints.   I would imagine that you need to call patchvalue or setvalue for your FormGroup after you have built the form somewhere.   I played with things for about 2 hours and could not get it to put an initial value...  let me know if you figure it out, this component pretty much blows but I am stuck at this point using it...

Good luck

**Comment by vidvidvid** [comment] 2019-10-09 11:51
@randym127 Yup, same here. Tried every single thing I could think of and find, but nothing works. A simple autocomplete dropdown with months and an input for the year would do. Good luck to you too.

**Comment by VigneshSAN** [comment] 2019-10-15 07:16
> @nicoabie I was getting an error stating there is no such module when importing "util". I copied the following code from Github into a new TS file and imported it.
> 
> https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/util/util.ts
> 
> I may be wrong but it worked for me.
> 
> ng-bootstrap | Angular | Bootstrap CSS
> 4.x.x | 7.0.0 | 4.0.0

I am also facing the same issue .. can u please clearly tell me how you imported the module.?

**Comment by rharari** [comment] 2019-10-28 20:05
> @korenb i noticed your parse always returns null. I changed it to this (and some small tweaks to make my compiler happier):
> 
> ```
> import * as moment from 'moment';
> 
> export class MomentDateFormatter extends NgbDateParserFormatter {
>   readonly DT_FORMAT = 'DD-MM-YYYY';
> 
>   parse(value: string): NgbDateStruct {
>     if (value) {
>       const mdt = moment(value.trim(), this.DT_FORMAT);
>       return { day: mdt.day(), month: mdt.months() + 1, year: mdt.year() };
>     }
>     return null;
>   }
>   format(date: NgbDateStruct): string {
>     if (!date) {
>       return '';
>     }
>     const mdt = moment([date.year, date.month - 1, date.day]);
>     return mdt.isValid() ? mdt.format(this.DT_FORMAT) : '';
>   }
> }
> ```

little correction -> ...return { day: mdt.`date()` ....

day() returns the day of the week.

I agree with @gmac-softrax - the display format is a basic feature for a date component. 
Also should improve the form validators according to angular spec.

**Comment by randym127** [comment] 2019-11-14 19:55
> @randym127 Thank you so very much! However there is still one little detail missing - when my forms are loaded with data, how do I trigger the setFormat function on element initialization? I would like to pass the data about the format to the date formatter, however now the data is passed only on focus. I have tried the (onload) function and setting a directive as suggested in the answer by Dakota: https://stackoverflow.com/questions/48335720/angular-i-want-to-call-a-function-when-element-is-loaded?noredirect=1&lq=1 but it doesn't work. Do you have any suggestion on how I should try to fix this problem?

So I finally got it loading values... what a pain.  So when I build the control on the form group I set the value initially when I am editing.  This was the tricky bit, it did not work when I set it as a NgbDateStruct and it did not work when I set is the formatted string which in my case was something like '2011/Apr/10'
```
const { validation } = config;
const disabled = config.disabled || !this.isFormAvailable || this.isFieldInitiallyDisabled(config.id);
const value = this.getValue(config);
return this.fb.control({ disabled, value }, validation, this.getAsyncValidators(config, disabled));
```

In the getValue its something like this:
```
getValue() {
   if (this.editMode) {
      let dateValue = '2011-04-10T10:20:30Z'
      return new Date(dateValue);
   }
   return null;
}
```

I had to do it this way as I have validations that trigger and expect it to be in Date, and when it was any other type it would fail.  However with just this change the value is set in the input but nothing is shown in the component, it is still blank.  So I need to add the following in the date component.

In the component.ts
```
getValue() {
    if (this.getControl().value) {
      const d =  moment(this.getControl().value, this.config.format);
      const date = { year: d.year(), month: (d.month() + 1), day: d.date()};
      return moment().year(date.year).month(date.month - 1).date(date.day).format(this.config.format);
    }
    return null;
  }
```

In the template (I added the [value]="getValue()"
```
<input class="form-control" [placeholder]="getPlaceHolder()" [formControlName]="config.id" [ngClass]="{ 'is-invalid': isFieldInvalid() }"
            name="d2" ngbDatepicker #d2="ngbDatepicker" (focus)="setFormat()" [id]="config.id" [value]="getValue()">
```

So after I added this the initial values were loaded.  I am going through it to see if I can simplify things as it seems weird you have to convert the value so much just to set things initially...

**Comment by randym127** [comment] 2019-11-19 18:50
> > @randym127 Thank you so very much! However there is still one little detail missing - when my forms are loaded with data, how do I trigger the setFormat function on element initialization? I would like to pass the data about the format to the date formatter, however now the data is passed only on focus. I have tried the (onload) function and setting a directive as suggested in the answer by Dakota: https://stackoverflow.com/questions/48335720/angular-i-want-to-call-a-function-when-element-is-loaded?noredirect=1&lq=1 but it doesn't work. Do you have any suggestion on how I should try to fix this problem?
> 
> So I finally got it loading values... what a pain. So when I build the control on the form group I set the value initially when I am editing. This was the tricky bit, it did not work when I set it as a NgbDateStruct and it did not work when I set is the formatted string which in my case was something like '2011/Apr/10'
> 
> ```
> const { validation } = config;
> const disabled = config.disabled || !this.isFormAvailable || this.isFieldInitiallyDisabled(config.id);
> const value = this.getValue(config);
> return this.fb.control({ disabled, value }, validation, this.getAsyncValidators(config, disabled));
> ```
> 
> In the getValue its something like this:
> 
> ```
> getValue() {
>    if (this.editMode) {
>       let dateValue = '2011-04-10T10:20:30Z'
>       return new Date(dateValue);
>    }
>    return null;
> }
> ```
> 
> I had to do it this way as I have validations that trigger and expect it to be in Date, and when it was any other type it would fail. However with just this change the value is set in the input but nothing is shown in the component, it is still blank. So I need to add the following in the date component.
> 
> In the component.ts
> 
> ```
> getValue() {
>     if (this.getControl().value) {
>       const d =  moment(this.getControl().value, this.config.format);
>       const date = { year: d.year(), month: (d.month() + 1), day: d.date()};
>       return moment().year(date.year).month(date.month - 1).date(date.day).format(this.config.format);
>     }
>     return null;
>   }
> ```
> 
> In the template I added the **[value]="getValue()"**
> 
> ```
> <input class="form-control" [placeholder]="getPlaceHolder()" [formControlName]="config.id" [ngClass]="{ 'is-invalid': isFieldInvalid() }"
>             name="d2" ngbDatepicker #d2="ngbDatepicker" (focus)="setFormat()" [id]="config.id" [value]="getValue()">
> ```
> 
> So after I added this the initial values were loaded. I am going through it to see if I can simplify things as it seems weird you have to convert the value so much just to set things initially...

FYI this is breaking the component when typing in a date.  Literally this component is the bane of my existence.  If you are reading this pick any other date picker component.  I am too far down the rabit hole...

**Comment by vidvidvid** [comment] 2019-11-20 10:17
@randym127 Hello! I switched jobs, so I won't have to deal with this anymore - something that simple should have been waaaaaay easier to implement. My idea was to just add a dropdown with months (full name or number, depending on how you configure it) and an input for the year (or a dropdown in case you are selecting only from a couple possible years) and I still think this is the simple solution. In case the input data needs to be sent somewhere in a certain format, even writing a 
parser shouldn't be too hard, ditto with setting the data upon form initialisation.

Good luck mate and thanks for your help and time!

**Comment by randym127** [comment] 2019-11-20 14:22
@vidvidvid I got no such luck.  I think the issues are just lack of support.  Doesn't seem many use this component library.

So I think I finally got the issue worked out in my component...  Early on I didn't like their model stuff and I saw the adapter that converts to js Date for you but that seems to be an issue with a custom formatter as the formatter always gets null.  I removed the following provider and just went with converting into their models:

My module went from:
``providers: [
    {provide: NgbDateAdapter, useClass: NgbDateNativeAdapter},
    {provide: NgbDateParserFormatter, deps: [FormatService], useClass: FormDateFormatter}
  ],``

to

``providers: [
    {provide: NgbDateParserFormatter, deps: [FormatService], useClass: FormDateFormatter}
  ],``

And now I just need to go fix all my custom validation to use their model now.

**Comment by Ismaestro** [comment] 2019-11-30 15:09
What do you think about this solution with **Luxon**. It shows the date-time in a specific format depending on locale (a complete list can be found [here](https://stackoverflow.com/a/9893752/1919749)):

**Bootstrap module**
```
...
declare const luxon;

export class LuxonDateFormatter extends NgbDateParserFormatter {

  constructor(private readonly translateService: TranslateService) {
    super();
  }

  parse(value: string): NgbDateStruct {
    if (value) {
      value = value.trim();
      return luxon.DateTime.fromFormat(value, UtilsHelperService.getLocaleDateString(this.translateService.currentLang));
    }
    return null;
  }

  format(date: NgbDateStruct): string {
    if (!date) {
      return '';
    }
    const mdt = luxon.DateTime.fromFormat(`${date.year}-${date.month - 1}-${date.day}`, 'yyyy-LL-dd');
    if (!mdt.isValid) {
      return '';
    }
    return mdt.toFormat(UtilsHelperService.getLocaleDateString(this.translateService.currentLang));
  }
}

@NgModule({
  ...
  providers: [
    {provide: NgbDateParserFormatter, useClass: LuxonDateFormatter, deps: [TranslateService]}
  ]
})
...
```

**Utils helper service**
```
static getLocaleDateString(lang) {

    const formats = {
      'ca': 'dd/LL/yyyy',
      'en': 'dd/LL/yyyy',
      'es': 'dd/LL/yyyy',
      'de': 'dd.LL.yyyy',
      'pl': 'yyyy-LL-dd',
      'pt': 'd/L/yyyy',
      'pt-BR': 'd/MLyyyy',
    };

    return formats[lang] || 'dd/MM/yyyy';
  }

  static getLocaleDateStringToShow(lang) {
    return UtilsHelperService.getLocaleDateString(lang).replace(/L/g, 'M');
  }
```

**Component ts**
```
...
ngOnInit(): void {
    this.dateFormat = UtilsHelperService.getLocaleDateStringToShow(this.translateService.currentLang);
    ...
  }
...
```

Component template
```
<div class="form-group">
              <div class="input-group">
                <input id="birthDate" class="form-control input datepicker-input pointer" autocomplete="false"
                       placeholder="{{dateFormat}}" formControlName="birthDate"
                       name="dp" ngbDatepicker #d="ngbDatepicker" (click)="d.toggle()"/>
                <div class="input-group-append">
                  <button class="btn btn-outline-secondary calendar" (click)="d.toggle()" type="button">
                    <span class="icon icon-calendar"></span>
                  </button>
                </div>
              </div>
            </div>
```

**Comment by TheMuyu** [comment] 2020-08-08 00:06
> I simply use moment.js for that
> 
> ```ts
> import { NgbDateParserFormatter, NgbDateStruct } from "@ng-bootstrap/ng-bootstrap";
> import * as moment from 'moment';
> 
> export class MomentDateFormatter extends NgbDateParserFormatter {
> 
>     readonly DT_FORMAT = 'MM/DD/YYYY';
> 
>     parse(value: string): NgbDateStruct {
>         if (value) {
>             value = value.trim();
>             let mdt = moment(value, this.DT_FORMAT)
>         }
>         return null;
>     }
>     format(date: NgbDateStruct): string {
>         if (!date) return '';
>         let mdt = moment([date.year, date.month - 1, date.day]);
>         if (!mdt.isValid()) return '';
>         return mdt.format(this.DT_FORMAT);
>     }
> }
> ```

Hello, How can i use this class in any component ?

**Comment by sayeed958** [comment] 2020-10-10 19:57
@TheMuyu 
save the above code in ` dateFormat.ts` file

On your component.ts(where you want to use) Change the below code

`import {NgbDateParserFormatter} from '@ng-bootstrap/ng-bootstrap';`
`import {MomentDateFormatter} from '../dateFormat';`
```
@Component({
  selector: 'app-component-name',
  templateUrl: '....'

  providers: [
    {provide: NgbDateParserFormatter, useClass: MomentDateFormatter}
  ]
```

**Comment by eran10** [comment] 2020-11-23 10:33
hi has anyone faced this error :
TypeError: Class constructor NgbDateParserFormatter cannot be invoked without 'new'
?

 I used it as describe above and it started when I upgrade to version 8.0 (in 7.0 it was working ok)

**Comment by cl-seshanmugam** [comment] 2021-04-07 22:14
@eran10 Most likely cause is the ng-bootstrap or bootstrap versions need to be upgraded to Angular 8 compatible versions.
The dependencies are listed here https://www.npmjs.com/package/@ng-bootstrap/ng-bootstrap

**Comment by pdoise** [comment] 2021-04-19 20:09
@eran10 any luck with that error? I believe its caused by using the keyword 'extends' in the custom date adaptor while targeting es5. I am using latest ng-bootstrap and latest angular versions in my application. Could really use a workaround.

**Comment by matanarbel** [comment] 2021-06-07 09:07
@pdoise I found 2 workarounds:
1. Remove the `Injectable()` from your formatter. Downside - you'll get a detraction notice from Angular, and it might not be supported in the future (I'm using Angular 11 and it works).
2. Compile using es2015 - but make sure it doesn't break something else in your app

**Comment by kishore-maria** [comment] 2021-07-05 10:40
```typescript
import { FormatWidth, getLocaleDateFormat } from '@angular/common';
import { Inject, Injectable, LOCALE_ID } from '@angular/core';
import { NgbDateParserFormatter, NgbDateStruct } from "@ng-bootstrap/ng-bootstrap";
import * as moment from 'moment';

@Injectable({
  providedIn: 'root'
})
export class CustomeNgbDatePickerService extends NgbDateParserFormatter {

  public placeholder = '';

  constructor(
    @Inject( LOCALE_ID ) private locale: string
  ) {
    super();
    const localeDateFormat = getLocaleDateFormat(this.locale, FormatWidth.Short);
    const splitedText = localeDateFormat.split('/');
    splitedText.map(text => {
      if (text.toLowerCase().includes('m')) {
        this.placeholder += this.placeholder.length > 0 ? '/MM' : 'MM';
      } else if (text.toLowerCase().includes('d')) {
        this.placeholder += this.placeholder.length > 0 ? '/DD' : 'DD';
      } else if (text.toLowerCase().includes('y')) {
        this.placeholder += this.placeholder.length > 0 ? '/YYYY' : 'YYYY';
      }
    })
  }

  parse(value: string): NgbDateStruct {
    if (value) {
      value = value.trim();
      let mdt = moment(value, this.placeholder)
    }
    return null;
  }

  format(date: NgbDateStruct): string {
    if (!date) return '';
    let mdt = moment([date.year, date.month - 1, date.day]);
    if (!mdt.isValid()) return '';
    return mdt.format(this.placeholder);
  }
}

```

To get dynamic locale date format as using **LOCALE_ID**

**Comment by edwinbustamanterodriguez** [comment] 2021-07-08 16:06
> Create custom parser formatter.
> 
> ```js
> import { NgbDateParserFormatter, NgbDateStruct } from '@ng-bootstrap/ng-bootstrap';
> import { Injectable } from '@angular/core';
> import { isNumber, toInteger, padNumber } from '@ng-bootstrap/ng-bootstrap/util/util';
> 
> @Injectable()
> export class NgbDateCustomParserFormatter extends NgbDateParserFormatter {
>   parse(value: string): NgbDateStruct {
>     if (value) {
>       const dateParts = value.trim().split('-');
>       if (dateParts.length === 1 && isNumber(dateParts[0])) {
>         return {day: toInteger(dateParts[0]), month: null, year: null};
>       } else if (dateParts.length === 2 && isNumber(dateParts[0]) && isNumber(dateParts[1])) {
>         return {day: toInteger(dateParts[0]), month: toInteger(dateParts[1]), year: null};
>       } else if (dateParts.length === 3 && isNumber(dateParts[0]) && isNumber(dateParts[1]) && isNumber(dateParts[2])) {
>         return {day: toInteger(dateParts[0]), month: toInteger(dateParts[1]), year: toInteger(dateParts[2])};
>       }
>     }
>     return null;
>   }
> 
>   format(date: NgbDateStruct): string {
>     return date ?
>         `${isNumber(date.day) ? padNumber(date.day) : ''}-${isNumber(date.month) ? padNumber(date.month) : ''}-${date.year}` :
>         '';
>   }
> }
> ```
> 
> Set the provider for the custom parser formatter in the @NgModule.
> 
> ```js
> providers: [
>     {provide: NgbDateParserFormatter, useClass: NgbDateCustomParserFormatter}
>    ]
> ```
> 
> As described in the [api](https://ng-bootstrap.github.io/#/components/datepicker/api#NgbDateParserFormatter)

other solution::
@Injectable()
export class CustomDateParserFormatter extends NgbDateParserFormatter {

  readonly DELIMITER = '/';

  parse(value: string): NgbDateStruct | null {
    if (value) {
      let date = value.split(this.DELIMITER);
      return {
        day : parseInt(date[0], 10),
        month : parseInt(date[1], 10),
        year : parseInt(date[2], 10)
      };
    }
    return null;
  }

  format(date: NgbDateStruct | null): string {
    return date ? date.day + this.DELIMITER + date.month + this.DELIMITER + date.year : '';
  }
}

**Comment by thahirkovai** [comment] 2023-02-03 07:35
Try this
[](https://stackblitz.com/run?file=src%2Fapp%2Fdatepicker-adapter.html,src%2Fapp%2Fdatepicker-adapter.ts)

**Comment by ivaancruzz** [comment] 2024-03-22 22:00
`export class CustomDateFormatter extends NgbDateParserFormatter {
  readonly DT_FORMAT = 'DD-MM-YYYY';

  parse(value: string): NgbDateStruct | null {
    if (value) {
      value = value.trim();
      let mdt = dayjs(value, this.DT_FORMAT);
    }
    return null;
  }
  format(date: NgbDateStruct): string {
    if (!date) return '';
    let mdt = dayjs(`${date.year}/${date.month - 1}/${date.day}`);
    if (!mdt.isValid()) return '';
    return mdt.format(this.DT_FORMAT);
  }
}
`

`providers: [
     { provide: NgbDateParserFormatter, useValue: new CustomDateFormatter() },
  ],`
