### ISSUE TITLE
Toggling variables inside dropdown closes the dropdown menu

### ISSUE THREAD

**Issue by Anirudh-Konduri** [ng-bootstrap/ng-bootstrap#2268] opened 2018-03-29 18:59 UTC
### Bug description:
When ever a dropdown have buttons that show/hide variables, it closes the dropdown menu when clicked on that button. 
Look for plunker link, dropdown menu has `No Show` button. Dropdown menu closes on clicking on it. 
### Link to minimally-working plunker that reproduces the issue:

https://stackblitz.com/edit/angular-vqxlki?file=app%2Fdropdown-config.ts

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2.8

ng-bootstrap: 1.0.4

Bootstrap: 4.0.0

**Comment by pkozlowski-opensource** [comment] 2018-03-29 19:14
Yep, this is by design. You can do one of 2 things:
* set `autoClose` to `false` or `outside` (but then you need to close the dropdown manually on menu items click);
* call `.stopPropagation()` on the click event of your button.

Closing as a support request.

**Closed by pkozlowski-opensource** 2018-03-29 19:14 UTC
Labels: component: dropdown, resolution: support

**Comment by Anirudh-Konduri** [comment] 2018-03-29 21:41
hi @pkozlowski-opensource 

Your second solution worked for me as a work around, thank you.  I still couldn't understand why would it be a feature to close the dropdown on changing the variable state.
