### ISSUE TITLE
Datepicker triggers valueChanges

### ISSUE THREAD

**Issue by VictorJuliani** [ng-bootstrap/ng-bootstrap#1982] opened 2017-11-22 10:51 UTC
### Bug description:
For a datepicker set as a FormControl, when any of it's properties gets updated, a valueChanges is triggered.

I have a parent component that passes to the child what are the max and min dates to be used on datepicker through @Input and listens to it's valueChanges to trigger some service action.
With multiple datepickers on the component, one valueChange is being triggered for each picker, causing the service to be ran multiple times before user has taken any action.

The following plunkr simulates an ngOnChanges and logs the valueChanges.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/SRUdhOyOcYAwPmsE6GiR?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.0.2

ng-bootstrap: 1.0.0-beta.5

Bootstrap: 4.0.0-beta.2

**Comment by pkozlowski-opensource** [comment] 2017-11-24 13:24
Right, this is a valid bug. Thnx for reporting!

**Comment by kharlamm** [comment] 2018-03-08 10:21
+1 Same problem here

**Comment by pkozlowski-opensource** [comment] 2018-08-30 13:38
Opened an issue on the Angular side: https://github.com/angular/angular/issues/25749. Will keep this issue open in here so we can bump up minimal Angular version when it gets fixed.

**Comment by pkozlowski-opensource** [comment] 2018-08-31 10:02
So, it looks like this is expected behaviour in Angular and a work-around exists (`distinctUntilChanged `), see: https://github.com/angular/angular/issues/25749

Closing it here as all the actions need to happen on the Angular side.

**Closed by pkozlowski-opensource** 2018-08-31 10:02 UTC
Labels: blocked: Angular issue, component: datepicker, type: bug
