### ISSUE TITLE
Uncaught TypeError: Cannot read property 'core' of undefined

### ISSUE THREAD

**Issue by heeyoun-song** [ng-bootstrap/ng-bootstrap#1529] opened 2017-05-01 12:26 UTC
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Link to minimally-working plunker that reproduces the issue: 

> https://github.com/heeyoun-song/angular-sample ( 1-add-bootstrap-module )

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 

>   ~>>> ninezero@songhuiyun-ui-MacBook-Air ~/D/w/m/angular-sample> npm angular-cli -v
>   ~>>> 4.2.0

ng-bootstrap: 

>  "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.25",

Bootstrap:

----------------------------------------------------------------------------------------------------

**1) Karama Log**

> ~>>> ninezero@songhuiyun-ui-MacBook-Air ~/D/w/m/angular-sample> karma start
> 01 05 2017 21:15:34.939:WARN [karma]: No captured browser, open http://localhost:9876/
> 01 05 2017 21:15:34.962:INFO [karma]: Karma v1.4.1 server started at http://0.0.0.0:9876/
> 01 05 2017 21:15:34.963:INFO [launcher]: Launching browser Chrome with unlimited concurrency
> 01 05 2017 21:15:34.972:INFO [launcher]: Starting browser Chrome
> 01 05 2017 21:15:36.633:INFO [Chrome 57.0.2987 (Mac OS X 10.12.4)]: Connected on socket CyKxHmRzOS9WVeWGAAAA with id 64103673
> Chrome 57.0.2987 (Mac OS X 10.12.4) ERROR
>   Uncaught TypeError: Cannot read property 'core' of undefined
>   at node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js:9
> 
> Chrome 57.0.2987 (Mac OS X 10.12.4) ERROR
>   Uncaught TypeError: Cannot read property 'core' of undefined
>   at node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js:9
> 
> Chrome 57.0.2987 (Mac OS X 10.12.4): Executed 0 of 3 SUCCESS (0 secs / 0 secs)
> Chrome 57.0.2987 (Mac OS X 10.12.4) ERROR
>   Disconnected, because no message in 10000 ms.
> Chrome 57.0.2987 (Mac OS X 10.12.4): Executed 0 of 3 DISCONNECTED (10.004 secs / 0 secs)
> Chrome 57.0.2987 (Mac OS X 10.12.4) ERROR
> Chrome 57.0.2987 (Mac OS X 10.12.4): Executed 0 of 3 DISCONNECTED (10.004 secs / 0 secs)

**2) Node version, and npm version**

> ~>>> ninezero@songhuiyun-ui-MacBook-Air ~/D/w/m/angular-sample> node --version
> v7.9.0
> ~>>> ninezero@songhuiyun-ui-MacBook-Air ~/D/w/m/angular-sample> npm -v
> 4.2.0

Please let me know if you need any more information.
Error in chrome developer console starting with ng serve.

**Comment by pkozlowski-opensource** [comment] 2017-05-01 14:24
Sorry, but it is not clear what the issue is. I check the repository and there is no ng-bootstrap being used in your project: https://github.com/heeyoun-song/angular-sample/blob/e2cfedbb61c35c818edf424332436f97211e64ab/package.json

The error log seems to be coming from karma tests but we don't know which command / option combination triggers this for you.

Looking at the error and the stack trace:

> Uncaught TypeError: Cannot read property 'core' of undefined
at node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js:9

It corresponds to the following code in our bundle (last line, alpha.25):

```
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory(require("@angular/core"), require("@angular/common"), require("@angular/forms"), require("rxjs/observable/fromEvent"), require("rxjs/operator/do"), require("rxjs/operator/let"));
	else if(typeof define === 'function' && define.amd)
		define(["@angular/core", "@angular/common", "@angular/forms", "rxjs/observable/fromEvent", "rxjs/operator/do", "rxjs/operator/let"], factory);
	else if(typeof exports === 'object')
		exports["ngb"] = factory(require("@angular/core"), require("@angular/common"), require("@angular/forms"), require("rxjs/observable/fromEvent"), require("rxjs/operator/do"), require("rxjs/operator/let"));
	else
		root["ngb"] = factory(root["ng"]["core"], root["ng"]["common"], root["ng"]["forms"], root["Rx"], root["Rx"], root["Rx"]);
```

So it seems like this fails for you: `root["ngb"] = factory(root["ng"]["core"], root["ng"]["common"], root["ng"]["forms"], root["Rx"], root["Rx"], root["Rx"]);` which doesn't make sense as it would indicate that there is no angular core defined.

For now I will assume that this is setup issue on your end, we need more info if you believe that there is a problem in this library.

**Comment by heeyoun-song** [comment] 2017-05-01 14:37
https://github.com/heeyoun-song/angular-sample/tree/1-add-bootstrap-module
branch : 1-add-bootstrap-module

[1-add-bootstrap-module] Can not verify usage on that branch?
I loaded my angle-cli.json> script into bootstrap

-------------------------------------------------------------------------------------------------------------------

{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "angular-sample"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        **"../node_modules/bootstrap/dist/css/bootstrap.css"**
      ],
      "scripts": [
        **"../node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js"**
      ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json"
    },
    {
      "project": "src/tsconfig.spec.json"
    },
    {
      "project": "e2e/tsconfig.e2e.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}

**Comment by pkozlowski-opensource** [comment] 2017-05-02 09:02
The problem is that you are putting the ng-bootstrap library inside `scripts` section of the CLI. This is not how it is meant to be used. You should rather import symbols from the `@ng-bootstrap/ng-bootstrap` namespace as described in our getting started page: https://ng-bootstrap.github.io/#/getting-started

Closing as a support request

**Closed by pkozlowski-opensource** 2017-05-02 09:02 UTC
Labels: needs: info

**Comment by heeyoun-song** [comment] 2017-05-02 09:29
angular-cli.json> scripts> This removes the bootstrap load so it works fine.
Thank you. :)

@pkozlowski-opensource 
Do you have permission to modify the guide?
now uses Webpack instead of SystemJS.However, there is still an explanation for SystemJS in the guide.Can you correct the guide accordingly?

**Comment by pkozlowski-opensource** [comment] 2017-05-02 09:44
> now uses Webpack instead of SystemJS.However, there is still an explanation for SystemJS in the guide.Can you correct the guide accordingly?

Some people might be still using SystemJS and the SystemJS-specific section clearly states:

> **If you are using SystemJS**, you should also adjust your configuration to point to the UMD bundle.

So not sure which corrections you would like to see, exactly... Feel free to send a PR if you would like to see particular changes, though.

**Comment by heeyoun-song** [comment] 2017-05-03 17:40
Thank you for @pkozlowski-opensource answer.
Have a nice day:)

**Comment by pulfabio** [comment] 2017-06-08 14:04
It would be nice if you added instructions for angular-cli, without removing the section for SystemJS, of course.

**Comment by xblader** [comment] 2017-06-21 12:09
there should be instructions for angular-cli, as pulFabio said.

**Comment by pulfabio** [comment] 2017-06-21 12:15
Thanks @xblader 
I'm pulfabio actually, all lowercase :)
