### ISSUE TITLE
Popover: close when click outside it

### ISSUE THREAD

**Issue by chrisbenseler** [ng-bootstrap/ng-bootstrap#1656] opened 2017-07-05 11:34 UTC
I didn't font in the docs if is possible, out-of-the-box, to close the Popover when the user clicks outside the popover. The only way to close it is clicking again in the element that calls it to open.
Is there this feature? Or the only way is binding an eventlistener on the body, via plain javascript, and handle this event?

**Comment by dhardtke** [comment] 2017-07-05 19:30
Dupe of https://github.com/ng-bootstrap/ng-bootstrap/issues/933

**Closed** 2017-07-06 08:57 UTC
