### ISSUE TITLE
ngDropdown changes ?

### ISSUE THREAD

**Issue by liyokuna** [ng-bootstrap/ng-bootstrap#2824] opened 2018-10-24 08:24 UTC
### Bug description:
Hello,

I am working on a framework that is based on ng-boostrap. I just release a new version by upgrading  ng-boostrap version from **_2.0.0_** to **_2.2.2_**. I have a component that uses `ngbDropdown` directive.
When I use this package, and implement an element that uses ngdropdown,  I am runnig into this error message in my angular project:

```
ERROR Error: StaticInjectorError(AppModule)[ODropdownComponent -> ElementRef]: 
  StaticInjectorError(Platform: core)[ODropdownComponent -> ElementRef]: 
    NullInjectorError: No provider for ElementRef!
```

I want to know if there is major changes made into the `ngbDropdown` directive ?
Here is the [link to the component](https://github.com/Orange-OpenSource/Orange-Boosted-Angular/blob/master/src/o-dropdown/o-dropdown.component.ts) and the project. 

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 6.1.0

ng-bootstrap: 2.2.2

Bootstrap: 4

**Comment by pkozlowski-opensource** [comment] 2018-10-24 08:39
> I want to know if there is major changes made into the ngbDropdown directive ?

You can see all the changes listed here:
* https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md
* https://github.com/ng-bootstrap/ng-bootstrap/commits/master/src/dropdown/dropdown.ts

Briefly looking at the changelog I can't see anything immediately obvious that could cause the error you are seeing. Did you update the Angular version at the same time?

**Comment by liyokuna** [comment] 2018-10-24 08:54
Ok thanks.
Yes I updated the angular version so as to match your project as we are using ng-bootstrap.
Angular 6.1

**Comment by pkozlowski-opensource** [comment] 2018-10-24 09:06
> Yes I updated the angular version so as to match your project as we are using ng-bootstrap.
Angular 6.1

ng-bootstrap 2.x doesn't require Angular 6.1, see: https://github.com/ng-bootstrap/ng-bootstrap#dependencies

Try to update one thing at a time to pin-point the root cause. 

BTW, I was trying to reproduce your error in a stackblitz taking your menu focus directive and didn't see the error (can't share stackblitz right now as it doesn't save for some reason...). So it looks like maybe something else is going on here?

**Comment by liyokuna** [comment] 2018-10-25 09:12
oh sorry , I mean angular 6.0.0.
oh ok that's weird.
[stackblitz](https://stackblitz.com/edit/angular-ctrqm3?file=src%2Fapp%2Fapp.module.ts) doesn't talk much.
Yeah, i just looked at my packages and i updated some of them. i don't know where that is coming from...

**Comment by pkozlowski-opensource** [comment] 2018-10-25 09:17
@liyokuna right, I also couldn't reproduce it in isolation in stackblitz... I would very much like to help here but you will have to isolate it further.

As a side note I would very much like to work closer with you guys so we can pull stuff like focus setting on dropdown items to `ng-bootstrap`. This way you wouldn't have to work-around things  like this. Also would be more than happy if you guys could contribute back to `ng-bootstrap` instead of maintaining work-around on your end. How does it sound?

**Comment by liyokuna** [comment] 2018-10-25 15:50
@pkozlowski-opensource 
After looking around for a solution and reading [angular documentation](https://angular.io/guide/attribute-directives#why-not-highlight) ( I was suspected that something new was made by Angular dev), I found out that a simple word was needed when you use directive inside your file.
So now the issue is solved, here is [the link to the documentation](https://angular.io/guide/attribute-directives#why-not-highlight)

for your answer, yes. I will be glad to help. Just let me know.

**Comment by pkozlowski-opensource** [comment] 2018-10-26 09:10
@liyokuna glad that the issue is solved!

I would very much like to get into closer contact with you guys so we can share workload on some of the issues:
- we could pull stuff you are missing in ng-bootstrap so you don't have to maintain it;
- you could PR us directly with the stuff you are missing from ng-bootstrap.

Could you think of:
- a list of items that you would like to push upstream to ng-bootstrap;
- top 3 features that you miss the most from ng-bootstrap;
- top 3 fixes that you would like to see in ng-bootstrap;

I'm going to close this issue as the problem is solved by we can continue the other discussion in here.

**Closed by pkozlowski-opensource** 2018-10-26 09:10 UTC
Labels: component: dropdown, needs: stackblitz

**Comment by liyokuna** [comment] 2018-10-26 16:03
@pkozlowski-opensource 
Yes. We can do that.
I will get back to you with the list of features.

**Comment by liyokuna** [comment] 2018-11-27 09:49
Hello @pkozlowski-opensource, I have some ideas, improvements and new components.

1. Tooltip, a colleague came up with an improvement to do on the tooltip. When the cursor is over a tooltip buttons, you have a text that pops up, when you move your cursor to that text, It disappears. The improvement here is to not closing the text when the cursor is upon the text displayed.
Here is a link to explain the [thing](https://a11y.nicolas-hoffmann.net/simple-tooltip/).

2. Tables component, I was considering to create a table component. It will based on that [example](https://material.angular.io/components/table/overview). I will focus more on the sorting ( and accessibility), a lot of user ask to have that on our framework.

3. Chips, It will be great to have a chip component too. Here is a [link to an example](https://material.angular.io/components/chips/overview).

What do you think ?

**Comment by liyokuna** [comment] 2018-12-04 14:11
I'll do some PR :)
