### ISSUE TITLE
Cannot set time to 12:00pm when using meridian

### ISSUE THREAD

**Issue by dan-lennox** [ng-bootstrap/ng-bootstrap#1071] opened 2016-11-22 01:15 UTC
### Bug description:

It's not possible to set the time to 12:00pm when [meridian]="true", even when using the "spinner" arrows. All attempts result in 00:00 am as the value set.

You can see this bug in the actual demo plnkr from the API docs.

### Link to minimally-working plunker that reproduces the issue:
#
https://ng-bootstrap.github.io/app/components/timepicker/demos/meridian/plnkr.html

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.0.0

ng-bootstrap: 1.0.0-alpha.13

Bootstrap: v4-alpha

**Comment by pkozlowski-opensource** [comment] 2016-11-22 09:04
This is a duplicate of #1031 and was already fixed in master via 91ca5186bfc435ead9f879569da8ac523a429b61. It will be part of the next release (alpha.14) to be cut later this week.

**Closed by pkozlowski-opensource** 2016-11-22 09:04 UTC

**Comment by dan-lennox** [comment] 2016-11-22 09:08
Thanks, apologies missed the dup.
