### ISSUE TITLE
Modal: consider supporting stacked modals

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#643] opened 2016-08-31 09:15 UTC
That is - modals that can be opened from modals. The current thinking is:
- we are very reluctant to support those as it is very, very bad UX
- "real life" sometimes "requires" those anyway....

Will try to resist us long as possible before implementing stacked modals, but let's have this issue to track interest / real-life usage scenarios.

**Comment by natcohen** [comment] 2016-08-31 21:21
I think it should be supported (for your record)

**Comment by Quinn-L** [comment] 2016-08-31 23:40
I use modal for yes/no confirmation dialogs.
However, if stacked modals aren't supported this means you can't have 'normal' modals with data entry which then uses modal confirmation dialogs. I guess one could argue data entry in modals are a bad UX?

**Comment by pkozlowski-opensource** [comment] 2016-09-01 11:54
Yeh, I'm kind of resigning to the reality of many projects and bracing for supporting this... But won't get to it before we land datepicker.

**Comment by pkozlowski-opensource** [comment] 2016-09-01 16:08
Voice in the discussion: https://github.com/twbs/bootstrap/issues/20607#issuecomment-244127770

**Comment by asadsahi** [comment] 2016-09-08 13:27
I also agree with @pkozlowski-opensource  stacked modal aren't good from UX perspective. Also, we had huge number of problems in one of large SPA build in Angular 1. Where there were confirmation dialogs, terms dialogs on top of existing dialogs, which caused more complexity, especially when in a web app reload happens, it is difficult to maintain state for those. We totally scrappeed the idea of having functional templates in modal. only for confirmation dialogs etc.

**Comment by tytskiy** [comment] 2016-12-29 15:58
Is there any plans to support backdrop position in between stacked modals? 
It turns that for each inner modal its backdrop doesn't cover previous modal.

There is quick reproduction: http://plnkr.co/edit/FG03lIbHjzM9wAZMoLWL?p=preview

**Comment by dneuer** [comment] 2017-01-05 16:56
@pkozlowski-opensource If this is considered by the team to be "very, very bad UX," what is the suggested alternative when several closely associated components need to operate on the same data? Especially with data that's already loaded? @ViewChild and direct subcomponent access? Child routes (and the terrible API of having to have a singleton service to pass references to in-memory data)?

**Comment by ASHFAQPATWARI** [comment] 2017-01-21 10:01
@pkozlowski-opensource  As you already said, sometimes we need stacked modals anyway. What is the alternative approach suggested by you till the library support stacked modals ?

**Comment by DocteurEz** [comment] 2017-02-08 00:38
@pkozlowski-opensource is there any progress on this matter?

**Comment by ravtakhar** [comment] 2017-02-12 00:40
When opening a modal(2) within a modal(1) it doesn't apply a backdrop to modal 1

**Comment by dguisinger** [comment] 2017-02-23 03:46
Not sure where you are at on this issue, but I agree multiple modals are needed. In my instance I'm working on an address component what when you click edit opens a modal (because the edit controls take up much more place than a read-only address displayed in the DOM), I don't want to limit the component to only working outside of modals.  In fact, I find it frustrating looking over the documentation that you are building an alternative implementation of Bootstrap.js, but treat modals so entirely different.  I don't understand why instead of using divs and modal classes, why we need to use templates and host it in a special tag somewhere in the modal.  From what I can tell, none of your other controls are imposing a different design than the standard Bootstrap.

I can understand you wanting to do it a particular way for ease of use for what you consider the common design pattern, but I can't see the justification for eliminating my ability to stick my modals anywhere in my HTML DOM that I chose and open them anyway I please.

**Comment by natcohen** [comment] 2017-05-03 13:35
There is also a problem when the first modal has a scroll bar... when you open a stacked modal over the first one and close it, it becomes impossible to scroll the first one.

Reproduce here: http://plnkr.co/edit/ZGYAbyJXwn8IWqz4sme8?p=preview

 - Open by clicking Launch demo
 - Scroll down and click on the stacked button
 - Close the small modal
 - Try to scroll again, it won't work...

**Comment by Vx2gas** [comment] 2017-05-26 17:14
Any updates on this?   I would like to have the first modal included in the backdrop when the second modal is opened.

**Comment by dmitrysteblyuk** [comment] 2017-06-05 08:01
@Vx2gas, z-index helps to some extent (the second modal backdrop is shown now over the first modal), but it doesn't fix the issue with scrolling:
http://plnkr.co/edit/3cISZTeEoqfb76KaC12z?p=preview

**Comment by Vx2gas** [comment] 2017-06-05 14:30
@dmitrysteblyuk, your right.

**Comment by dmitrysteblyuk** [comment] 2017-06-05 17:51
@Vx2gas the issue was that NgbModalRef removes modal-open class from body on destroy (despite that the first modal is still open). I added for myself this quick fix
```
modalRef.result.catch(() => {})
    .then(() => {
        if (document.querySelector('body > .modal')) {
            document.body.classList.add('modal-open');
        }
    });
```

**Comment by dmitrysteblyuk** [comment] 2017-06-05 18:08
It seems, adding z-index for modal backdrop and modal-open class for body fixes all the mentioned above issues. I tested only in browser platform though.

**Comment by natcohen** [comment] 2017-06-21 15:05
Anyone for a PR?

**Comment by ansorensen** [comment] 2017-08-21 01:02
An alternative to stacking modals would be the ability to switch between modals.

I attempted to do this manually: have a child component emit an event when it has a modal open. The parent (with it's own modal) could close the parent modal when the child is open, and reopen the parent modal when the child closes. However, calling modalRef.close on the parent appears to detach _all_ modal listeners. The child's modalRef.result.then never fires, so I can't emit an event when the child closes.

Looks like the windowCmptRef  gets nullified on close (modal-ref.ts line 98), and windowCmptRef is what is responsible for subscribing to close events (modal-ref.ts line 54). Is it possible that all modals are sharing the same windowCmptRef? It gets assigned at (modal-stack.ts line 52).

Plunkr of the issue [here](http://plnkr.co/edit/b8q6nDgA5Lq04NMr9tbT?p=preview).

**Comment by lyonzy** [comment] 2017-10-10 03:01
Just to add my 2c, when you say:

> it is very, very bad UX

Twitter themselves use stacked modals - try going to [a tweet](https://twitter.com/dog_rates/status/917172603026071553) and clicking on the picture.

**Comment by SoftCircuits** [comment] 2017-10-24 00:22
It's not a great UI/UX, but it's not *that* terrible. It's done all the times with desktop applications. I recognize that it might be problematic, and I don't know what's involved with the scrolling issue, but it would be nice if this were straight forward to do for situations that call for it.

**Comment by pbrain19** [comment] 2017-11-24 14:17
well...

**Comment by earle36** [comment] 2017-12-01 20:39
The team I'm on has support use cases for stacked modals regardless of whether its good UI/UX. We've been using ng-bootstrap and love it so far - this is the only issue holding us up right now. I really hope support gets added for this - would be a shame to have to use a different library just because of this one issue.

**Comment by Arman92** [comment] 2017-12-18 21:19
I need stacked modals too, any progress regarding this feature?

**Comment by ravtakhar** [comment] 2017-12-18 21:29
@Arman92 what I'm doing as a work around is hiding the parent modal upon open, and then using @dmitrysteblyuk's trick to bring the backdrop back.

**Comment by shyamal890** [comment] 2018-04-11 18:03
@pkozlowski-opensource Can you please update us on the status of this issue and what's stopping the team from implementing this feature?

**Comment by k-vekos** [comment] 2018-05-10 14:40
+1

**Comment by mglavall** [comment] 2018-05-29 12:50
@natcohen Also, there is a bug that when you close the stacked modal, the button that opened it stays focused. It can be seen in your plunkr also: http://plnkr.co/edit/ZGYAbyJXwn8IWqz4sme8?p=preview

**Comment by ashgibson** [comment] 2018-06-10 11:30
+1

**Comment by firou1925** [comment] 2018-06-27 16:53
@dmitrysteblyuk  please where to add this exactly?

```
modalRef.result.catch(() => {})
    .then(() => {
        if (document.querySelector('body > .modal')) {
            document.body.classList.add('modal-open');
        }
    });
```

**Comment by dmitrysteblyuk** [comment] 2018-06-27 19:33
@firou1925 you add it just after you opening a modal with “open” method (it returns modalRef).
I don’t know though if this workaround is still working

**Comment by nortain** [comment] 2018-07-09 06:37
I would also like to see a modal in modal support to be added to bootstrap.  Confirmation messages inside of modal are hardly a uncommon, or even bad IMO Ux design.   Ngb-alerts are too limited to handle this and using a native confirm is just an eye sore compared to a custom built confirmation component. :(

**Comment by kernyden** [comment] 2018-07-24 07:38
https://github.com/dmitrysteblyuk still works, thx for the answer

**Comment by tan9** [comment] 2018-08-03 07:07
If you tend not to apply the workaround provided by @dmitrysteblyuk everywhere, register a MutationObserver like:

https://gist.github.com/hyshan/ae791e420bbad1ffa31eafbbd350e290

**Comment by benouat** [comment] 2018-08-29 07:31
Stacked modals will land in 3.2.0

**Closed** 2018-08-29 07:30 UTC
Labels: component: modal, type: feature

**Comment by aldyson** [comment] 2018-08-30 13:03
@benouat Will the issue discussed by @Vx2gas and @dmitrysteblyuk be fixed as part of this? i.e. `.modal-open` being removed after closing a stacked modal, despite a modal still being open?

**Comment by benouat** [comment] 2018-08-30 13:06
@aldyson yes it will! We now have a test for this 😃

```typescript
it('should not remove "modal-open" class on body when closed modal is not last', async(() => {
```

**Comment by kernyden** [comment] 2018-11-02 08:38
@dmitrysteblyuk is there a solution for make parent modal scrolling(>100vh) when child modal is open?

**Comment by shrikantk3** [comment] 2019-09-24 08:19
$('body').on('click','a[data-toggle="modal"]', function(e){         
            setTimeout(function() {
                $('body').addClass('modal-open');                     
            },500);            
        });
Working perfectly try it.

**Comment by wildhart** [comment] 2021-12-12 16:54
I agree that stacked models have many valid use cases.  I've inherited a project which makes extensive use of it.  Rather than adding code to every `modalRef.result.catch` and `modalRef.result.then` (for modals which are closed instead of dismissed), I have created the following global intercepter for modalRef:

```
const checkIfOtherModalsOpen = () => {
	setTimeout(() => {
		if (document.querySelector('.modal.show')) {
			document.body.classList.add('modal-open');
		}
	});
}

const origModalOpen = this.modalService.open.bind(this.modalService);

this.modalService.open = (...args) => {
	const modalRef = origModalOpen(...args);
	const origPromise = modalRef.result;
	modalRef.result = new Promise((resolve, reject) => {
		origPromise.then(result => {
			resolve(result);
			checkIfOtherModalsOpen();
		}).catch((error) => {
			reject(error);
			checkIfOtherModalsOpen();
		})
	})
	return modalRef;
}
```

I've put this in the `ngOnInit()` in by app.component.ts
