### ISSUE TITLE
Add custom class to tooltips - ngbTooltipClass

### ISSUE THREAD

**Issue by ShakurOo** [ng-bootstrap/ng-bootstrap#1349] opened 2017-03-01 14:50 UTC
A great feature could making us able to set a custom class on tooltip for setting custom styles depending about this classe.

For example, in my case, I display a variable score in a `<i>` tag, and each tag have color depending of its score _(eg: 3/10 => .red class)_. 

It would be wonderfull if I could set a class by the way of interpolation : 

```
<ul>
    <template ngFor let-score [ngForOf]="scores | orderBy: ['label']">

        <template #tipScore>{{score.label}} : <strong>{{score.score}}</strong> /10</template>

        <li *ngIf="score.name != 'general'">
            <i [ngbTooltip]="tipScore" [ngbTooltipClass]="(score.note | colorScore)"></i>
        </li>
        
    </template>
</ul>
```

The class should set through a [ngbTooltipClass] _(in my case the classname would be returned by pipe colorScore)_.

**Edit :** 
There is a poor way to perform this, but which has its own limits and depends of the state of [container].

When the default behavior is running the container is the element where the [ngbTooltip] directive is attached. (in my case this is `<i>`), we could provide custom styles.

**Example :**

1) Attach a class to the element node which contains the tooltip :
`<i class="yellow" [ngbTooltip]="tipScore"></i>`

2) Then use this selector for cover the tooltip and setting some styles : 
```
[ng-reflect-ngb-tooltip].yellow + .tooltip {
    background-color: yellow;
}
```

But when the [container] is changes to _body_, I unknown a way to target the tooltip and apply a particular styles.

**Comment by StefanKern** [comment] 2017-05-26 11:46
Thanks for the example, if I read it completely I would have saved a lot of time :)

**Comment by Ismaestro** [comment] 2017-09-11 12:55
Any updates?? this is mandatory, not a feature!!

**Comment by bastienmoulia** [comment] 2017-11-04 11:45
Adding a class to a tooltip is easy, the problem is I can't find a way to declare the CSS inside the component, it has to be in the CSS of the app because the tooltip-window is outside the scope of the tooltip.

If it's ok to add the CSS to customize a tooltip at the app level, I can PR what I've done.

If not, other solution can be to replace the `ngbTooltipClass` by `ngbTooltipStyle` and to pass the style with `[ngStyle]`in the tooltip-window. But I'm not sure if the arrow can be customized with that.

Another solution is to specify directly `ngbTooltipBackgroundColor` and `ngbTooltipColor` if it's ok to just customize the color of the tooltip (with the arrow).

@pkozlowski-opensource Any idea?

**Comment by mfodor** [comment] 2018-03-26 10:32
Another use case is when you need to set container to body. Then you have no control in CSS since the element is appended to body not as a child element. Coloring tooltips e.g. when displaying error indicators and details are in tooltip. This is my case.

Any updates?

@bastienmoulia do you have plans to make your PR accepted (#1951)?

**Comment by pkozlowski-opensource** [comment] 2018-06-29 13:31
I've just merged a PR that adds this functionality to poovers. If anyone is up to a PR for tooltips you can prepare a PR by doing almost _exactly_ the same thing as was done for popovers in 483bd05e539badfbc544ad1eb4aa110e3745bb59

**Closed** 2018-08-28 07:15 UTC
Labels: PRs plz!, component: tooltip, type: feature
