### ISSUE TITLE
Allow option for accordion panel title to not be included in anchor tag

### ISSUE THREAD

**Issue by paustint** [ng-bootstrap/ng-bootstrap#1034] opened 2016-11-12 23:35 UTC
Feature Request:
Right now, the ngbPanel always wraps the title in an anchor tag even if the user is using a provided template ngbPanelTitle tag which limits the functionality and styling that can easily be provided.

Use case:
It would be great to be able to include other content, aside from just the title, in the header that will not expand the accordion when clicked (e.x. some icon with state, a button, etc..)

**Comment by pkozlowski-opensource** [comment] 2016-11-13 09:23
Duplicate of  #465 and #717. It is on the roadmap but we are not there yet. We want to add animations and keyboard navigation first to settle on the API.

**Closed by pkozlowski-opensource** 2016-11-13 09:23 UTC

**Comment by nagarjunveni** [comment] 2018-10-13 01:14
I also have similar requirement. Can you please let me know if this request was implemented?
