### ISSUE TITLE
Passing data to modal components (feature request)

### ISSUE THREAD

**Issue by kevin-madhu** [ng-bootstrap/ng-bootstrap#879] opened 2016-10-13 06:17 UTC
I'm using NgbModal service for creating modals passing components to it as content. One limitation I hit is that the components that we're passing might have @Input attributes where it expects input from the parent component, but currently I don't see any ways for passing on data. I request you to introduce a method to pass on such data.

Thanks!

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.0.0

ng-bootstrap: 1.0.0-alpha.7

Bootstrap: ng2-bootstrap(^1.1.5)

**Comment by pkozlowski-opensource** [comment] 2016-10-13 08:06
Duplicate of #861

**Closed by pkozlowski-opensource** 2016-10-13 08:06 UTC
