### ISSUE TITLE
Accordion type doesn't work

### ISSUE THREAD

**Issue by Dan203** [ng-bootstrap/ng-bootstrap#2195] opened 2018-02-27 23:54 UTC
The release version of Bootstrap 4 removed the card-[color] classes and says to to use the bg-[color] on the various card elements instead. When using the "type" input in your API it still assigns classes like "card-danger" which do nothing.

**Comment by pkozlowski-opensource** [comment] 2018-02-28 08:51
Duplicate of #1897

**Closed by pkozlowski-opensource** 2018-02-28 08:51 UTC
