### ISSUE TITLE
Modal broken after alpha-21 upgrade

### ISSUE THREAD

**Issue by sousarka** [ng-bootstrap/ng-bootstrap#1384] opened 2017-03-16 23:02 UTC
### Bug description:

I'm getting an "expression has changed after it was checked." error from a modal after I upgraded to alpha-21. 

### Link to minimally-working plunker that reproduces the issue:
Plunker with alpha-20 (working without any error)  - [http://plnkr.co/edit/POQliZvnstO6yeIAdhhX?p=preview](http://plnkr.co/edit/POQliZvnstO6yeIAdhhX?p=preview)

Plunker with alpha-21 (throwing error) - [http://plnkr.co/edit/SMl0IKXc4wEnERcfCsP7?p=preview](http://plnkr.co/edit/SMl0IKXc4wEnERcfCsP7?p=preview)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.3.1

ng-bootstrap: 1.0-alpha-21

Bootstrap: 4.0.0 alpha-6

**Comment by Thommas** [comment] 2017-03-17 03:06
Same problem here.

But also I have two more problems.

Using ngb-tabset inside the modal triggers 'query 1 dirty' error.

Using a ViewChild to access a child component in my modal returns undefined even after ChangeDetectorRef detectChange() is called after opening the modal.

**Comment by pkozlowski-opensource** [comment] 2017-03-17 07:07
> Same problem here.

@Thommas we can't confirm that this is the same problem without a plunker... Are you also opening a modal from `ngOnInit`?

> But also I have two more problems.
> Using ngb-tabset inside the modal triggers 'query 1 dirty' error.
> Using a ViewChild to access a child component in my modal returns undefined even after ChangeDetectorRef detectChange() is called after opening the modal.

@Thommas please open separate tickets for those issues following our issue template. Generally speaking we are _not_ going to investigate any issues without a live reproduce scenario and here is why: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by pkozlowski-opensource** [comment] 2017-03-19 18:12
OK, so looking a bit into this issue it seems like Angular disallows adding new views from any lifecycle hooks. I'm going to discuss this with Tobias / Misko and take appropriate actions afterwards.

For now my feeling is that we are unlikely to revert changes done in alpha.21 as the current code is "right". I would more expect that the fix will come from the framework itself. Let's see.

**Comment by sousarka** [comment] 2017-03-20 17:32
@pkozlowski-opensource : Understood your point. Refactored my code and it seems to work. So, for now, we have a workaround.

[http://plnkr.co/edit/SMl0IKXc4wEnERcfCsP7?p=preview](http://plnkr.co/edit/SMl0IKXc4wEnERcfCsP7?p=preview)

**Comment by pkozlowski-opensource** [comment] 2017-03-23 15:57
It looks like the original plunker have changed and I can no longer reproduce this issue with http://plnkr.co/edit/SMl0IKXc4wEnERcfCsP7?p=preview. I was also trying to isolate this particular scenario with the exact mechanics that modal is using: https://plnkr.co/edit/uh4oxxA3Yq6i45SA52SS?p=preview

I'm not sure if this is linked to the Angular version change (both plunkers are using 2.4.10) or sth else. In any case I no longer have a reproduce scenario so got no choice but close this issue. Happy to reopen if any new scenario surfaces.

**Comment by pkozlowski-opensource** [comment] 2017-03-23 16:25
Wait, actually I _can_ reproduce this without using modal - here is roughly what modal does: https://plnkr.co/edit/uh4oxxA3Yq6i45SA52SS?p=preview

I'm meeting with Misko today so will clarify if this should be supported or not.

**Comment by sousarka** [comment] 2017-03-23 16:27
Great.. In case you need another plunkr :)

[http://plnkr.co/edit/eQ5tZhfN4Ix90XvUjT3W?p=preview](http://plnkr.co/edit/eQ5tZhfN4Ix90XvUjT3W?p=preview)

**Comment by pkozlowski-opensource** [comment] 2017-03-30 18:56
I've discussed it with both Misko and Tobias from the angular team and opened https://github.com/angular/angular/issues/15634 as the result.

I'm going to close this issue here as the ultimate solution needs to come from the angular itself. Please track https://github.com/angular/angular/issues/15634 if you are facing pb described here.

**Closed by pkozlowski-opensource** 2017-03-30 18:56 UTC
Labels: component: modal, needs: investigation, required for beta

**Comment by JCarlosGarza** [comment] 2017-06-27 00:31
Same here, modal not working with *ngIf  bootstrap 4 angular 4.
