### ISSUE TITLE
Dependency Error after upgrate to angular 18

### ISSUE THREAD

**Issue by iferpaz7** [ng-bootstrap/ng-bootstrap#4706] opened 2024-05-27 21:38 UTC
I have trouble with some dependency's after upgrading to angular 18. 
![MicrosoftTeams-image (1)](https://github.com/ng-bootstrap/ng-bootstrap/assets/18398060/6a1ad9fc-3788-45ca-8081-984328acc23c)

**Comment by BrandonSchreck** [comment] 2024-05-28 16:41
I'm also having similar issues after upgrading my project to Angular 18. 

Minimal Reproduction Scenario:

- install angular/cli v18 `npm i -g @angular/cli`
- generate new Angular app `ng new test-app`
- install ng-bootstrap `ng add @ng-bootstrap/ng-bootstrap`

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: test-app@0.0.0
npm ERR! Found: @angular/common@18.0.0
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^17.0.0" from @ng-bootstrap/ng-bootstrap@16.0.0 
npm ERR! node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!   @ng-bootstrap/ng-bootstrap@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I found the [following discussion in the PR for Angular 18](https://github.com/ng-bootstrap/ng-bootstrap/pull/4704#issuecomment-2132365203) for a temporary fix, but I get the following error when trying to run `ng g @ng-bootstrap/ng-bootstrap:ng-add`:

```
An unhandled exception occurred: Collection "@ng-bootstrap/ng-bootstrap" cannot be resolved.
```

Or I get the following if I try to add ng-bootstrap `ng add @ng-bootstrap/ng-bootstrap`:

```
npm ERR! Unable to resolve reference $@angular/localize
```

**Comment by jsn0ob** [comment] 2024-05-29 00:29
This issue is a duplicate of #4703.

**Comment by manstie** [comment] 2024-05-29 06:36
https://github.com/ng-bootstrap/ng-bootstrap/pull/4704#issuecomment-2132365203 there is a workaround posted in the PR for Angular 18

**Comment by iferpaz7** [comment] 2024-05-29 14:40
Thanks

**Closed** 2024-05-29 14:40 UTC
