### ISSUE TITLE
Can't install with Fresh Angular project 

### ISSUE THREAD

**Issue by tomavic** [ng-bootstrap/ng-bootstrap#4355] opened 2022-07-14 17:13 UTC
I can't install ng-bootstrap through `npm` or `ng add`

I have tried with Angular 13.2.6 and Angular 14.x

```shell

myapp ➤ ng add @ng-bootstrap/ng-bootstrap                                      git:main
ℹ Using package manager: npm
✔ Found compatible package version: @ng-bootstrap/ng-bootstrap@12.1.2.
✔ Package information loaded.

The package @ng-bootstrap/ng-bootstrap@12.1.2 will be installed and executed.
Would you like to proceed? Yes
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: myapp@0.0.0
npm ERR! Found: @angular/compiler@13.2.7
npm ERR! node_modules/@angular/compiler
npm ERR!   @angular/compiler@"~13.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler@"13.3.11" from @angular/localize@13.3.11
npm ERR! node_modules/@angular/localize
npm ERR!   peer @angular/localize@"^13.0.0" from @ng-bootstrap/ng-bootstrap@12.1.2
npm ERR!   node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!     @ng-bootstrap/ng-bootstrap@"12.1.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/user/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2022-07-14T16_56_31_082Z-debug.log
✖ Package install failed, see above.
```

```shell

➤ npm install @ng-bootstrap/ng-bootstrap                                  git:feat/add-bootstrap
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: myapp@0.0.0
npm ERR! Found: @angular/common@14.0.6
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^14.0.6" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^13.0.0" from @ng-bootstrap/ng-bootstrap@12.1.2
npm ERR! node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!   @ng-bootstrap/ng-bootstrap@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/user/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2022-07-14T17_08_05_767Z-debug.log
```

**Comment by wopian** [comment] 2022-07-16 21:09
Duplicate of the pinned issue https://github.com/ng-bootstrap/ng-bootstrap/issues/4340

The beta release has Angular 14 support

**Closed** 2022-07-16 21:14 UTC
