### ISSUE TITLE
Angular 5 update

### ISSUE THREAD

**Issue by muthu0101** [ng-bootstrap/ng-bootstrap#1992] opened 2017-11-25 07:50 UTC
Hello All,

I have installed ng-bootstrap at Angular 5 project, when I tried to implement typeahead WikipediaService I got the error on jsonp, because Angular 5 not longer support for  jsonp. When we can expect the updated version for Angular 5.

**Comment by pkozlowski-opensource** [comment] 2017-11-25 07:58
Duplicate of #1938 - we will be releasing a version compatible with Angular 5 early next week.

**Closed by pkozlowski-opensource** 2017-11-25 07:58 UTC
