### ISSUE TITLE
Allow buttons in tabset navbar

### ISSUE THREAD

**Issue by seanmcilvenna** [ng-bootstrap/ng-bootstrap#3186] opened 2019-05-09 18:22 UTC
This is a feature/idea. It would be nice to have the ability to create a set of buttons in the navigation bar of a tabset. These buttons would not actually have tab pages associated with them... they might just be for actions related to the active tab, or custom navigation within the tab pages.

**Comment by pkozlowski-opensource** [comment] 2019-05-09 18:30
This is a duplicate of the existing issue #465

**Closed by pkozlowski-opensource** 2019-05-09 18:30 UTC
