### ISSUE TITLE
Input loses focus when clicking scrollbar inside a modal

### ISSUE THREAD

**Issue by msosa** [ng-bootstrap/ng-bootstrap#1734] opened 2017-08-07 15:28 UTC
### Bug description:
Whenever you click a scrollbar you lose blur the input you have focused. This does not happen when you are not in the modal.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/H9RyyYMwRMv1HEjzZkJe?p=preview

click the input then the scrollbar right below . Outside the modal you won't see the input lose focus

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.3.0

ng-bootstrap: 1.0.0-alpha.30

Bootstrap: 4.0.0-alpha.6

This issue occurs in Chrome

**Comment by pkozlowski-opensource** [comment] 2017-08-07 16:01
This is not specific to this library but rather to browser behaviour + markup used by Bootstrap for modals. To illustrate what I mean here is a simpler reproduce scenario _without_ using ng-bootstrap: https://plnkr.co/edit/XmbjAaZnwIx2QKwEbtOM?p=preview

As you can see it is enough to have the "loosing focus" behaviour with the `tabindex="-1"` on a container wrapped around input + list. We can't remove the `tabindex="-1"`as it is necessary to properly manage focus on modal windows (Bootstrap 4 also has it, check https://v4-alpha.getbootstrap.com/components/modal/)

I'm going to close this issue since I can reproduce it without ng-bootstrap involved. If you believe that  `tabindex="-1"` is "harmful" in your particular use-case than please rise an issue on the Bootstrap side.

**Closed by pkozlowski-opensource** 2017-08-07 16:01 UTC
Labels: component: modal, needs: investigation

**Comment by abyrne85** [comment] 2021-02-15 11:33
@msosa  Did you find a solution for this?  I'm coming up against the same issue
