### ISSUE TITLE
Can not import NgbAccordion with webpack

### ISSUE THREAD

**Issue by CSchulz** [ng-bootstrap/ng-bootstrap#969] opened 2016-10-26 10:43 UTC
### Bug description:
Using webpack mit ng-bootstrap and can not import NgbAccordion.

```
import {NgbAccordion} from '@ng-bootstrap/ng-bootstrap';

Module '"/node_modules/@ng-bootstrap/ng-bootstrap/index"' has no exported member 'NgbAccordion'.
```

```
import {NgbAccordion} from '@ng-bootstrap/ng-bootstrap/accordion/accordion';

accordion.js?5ed8:1 Uncaught SyntaxError: Unexpected token import
834 @ app.js:1009
__webpack_require__ @ polyfills.js:51
(anonymous function) @ app.component.ts?f052:5
129 @ app.js:78
__webpack_require__ @ polyfills.js:51
(anonymous function) @ app.module.ts?256a:11
102 @ app.js:29
__webpack_require__ @ polyfills.js:51
(anonymous function) @ main.ts?7d64:5
75 @ app.js:15
__webpack_require__ @ polyfills.js:51
0 @ app.js:7
__webpack_require__ @ polyfills.js:51
webpackJsonpCallback @ polyfills.js:22
(anonymous function) @ app.js:1
```

### Link to minimally-working plunker that reproduces the issue:
Don't have any webpack plunkr template, don't know how to get it working.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.1.1

ng-bootstrap: 1.0.0-alpha.9

Bootstrap: 4.0.0-alpha.5

**Comment by pkozlowski-opensource** [comment] 2016-10-26 11:04
> import {NgbAccordion} from '@ng-bootstrap/ng-bootstrap';

This is a duplicate of #779
The interesting question would be: why do you need it? We are still trying to gather real-life usecases before solving #779.

 > import {NgbAccordion} from '@ng-bootstrap/ng-bootstrap/accordion/accordion';

This won't work in WebPack 1 for the same reason deep-imports don't work with Angular 2. At this point there is no intention of supporting deep imports - the only public namespace is `'@ng-bootstrap/ng-bootstrap`. Once again, a concrete use-case would help weighting this way or another.

Closing as a duplicate of #779 for now.

**Closed by pkozlowski-opensource** 2016-10-26 11:04 UTC

**Comment by CSchulz** [comment] 2016-10-26 11:27
Oh damnit ... I have commented it with a use case.
