### ISSUE TITLE
TimePicker throws error with angular2 rc4 forms

### ISSUE THREAD

**Issue by amariniello** [ng-bootstrap/ng-bootstrap#529] opened 2016-08-02 10:19 UTC
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
I am trying to use the timepicker but i am facing a blocking bug. 
when using the directive in a template 

<ngb-timepicker name="test" id="test" [(ngModel)]="time"></ngb-timepicker>
i get an error on the console:
No value accessor for ''.
After a bit of digging i can confirm that this only happens with the new forms in rc4.
If i comment out the new forms setup everything works as expected.
Main.ts 
import { disableDeprecatedForms, provideForms } from '@angular/forms';

bootstrap(AppComponent, [
  disableDeprecatedForms(),
  provideForms(),
]);

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: rc4

ng-bootstrap: 1.0.0-alpha.1

Bootstrap: 4.0.0-alpha.2

**Comment by pkozlowski-opensource** [comment] 2016-08-02 10:29
Yeh, we don't support new forms yet, there is an issue for this already: #454

The good news though is that we are working on migration to new forms as we speak. We will have a new release as soon as RC5 is out and this will contain support of new forms.

Closing as duplicate of #454, follow this issue to get regular status updates.

**Closed by pkozlowski-opensource** 2016-08-02 10:29 UTC
