### ISSUE TITLE
Datepicker inside modal bug

### ISSUE THREAD

**Issue by scarmarco** [ng-bootstrap/ng-bootstrap#1068] opened 2016-11-21 18:30 UTC
### Bug description:

I have a problem with a modal with datepickers inside, when I click in any date the modal automatically closes

Proof: https://i.gyazo.com/79447830a0f104368efa508d69f6ab5b.gif

Code its pretty extensive so I won't post by now. (But has the same structure as a component driven modal: http://plnkr.co/edit/?p=preview) 

Modal also closes when I click that 'Anterior' button (which points to an empty function).

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.1.1

ng-bootstrap: 1.0.0-alpha.13

Bootstrap: 4.0.0-alpha.4

**Comment by pkozlowski-opensource** [comment] 2016-11-21 18:35
This is duplicate of #1042 and was already fixed in master via 3af8329. This fix will be part of the next (alpha.15 release) to be cut later this week.

**Closed by pkozlowski-opensource** 2016-11-21 18:35 UTC
