### ISSUE TITLE
Pagination: Ellipses is always disabled

### ISSUE THREAD

**Issue by sendilkumarn** [ng-bootstrap/ng-bootstrap#418] opened 2016-07-09 15:21 UTC
Ellipses seems to be always disabled in the demo.

`_isEllipsis` always returns true. 

guess ellipsis button can be handled similar to previous and next button

**Comment by pkozlowski-opensource** [comment] 2016-07-09 17:11
This is by design.

> guess ellipsis button can be handled similar to previous and next button

I don't think it makes much sense to duplicate functionality of buttons.

Closing as the current behaviour is the conscious decision. Feel free to argue more if you believe we should change it :-)

**Closed by pkozlowski-opensource** 2016-07-09 17:11 UTC

**Comment by sendilkumarn** [comment] 2016-07-09 19:34
I think ellipses are much more useful (with a slight tweak in their function)
Next  -> +1
Ellipses -> +maxSize  i.e.,next set  ( since we have max size) 

And again it is an optional one , users choose this on their need.

**Comment by sendilkumarn** [comment] 2016-07-09 19:38
In current scenario, ellipses helps in achieving first and last right? Again it will be a duplication for boundary links
