### ISSUE TITLE
Cannot achieve pagination with ngbTypeAhead loaded dropdown

### ISSUE THREAD

**Issue by aakash1401** [ng-bootstrap/ng-bootstrap#2697] opened 2018-09-10 07:10 UTC
A Bug / Feature Request

### Bug description:

Currently I am using ngbTypeahead to load data from server on type of key which is working fine. But it fetches all data at once. 

If I only fetch first 15-20 records in type ahead created drop-down from service, I cannot attach scroll event on this created drop-down like virtual scroll bar or ngbDropDown so I can call service on scroll end to fetch next set of records i.e. 21-40 and update existing records.

https://stackblitz.com/angular/rdkongmjovr?file=app%2Ftypeahead-basic.html

Is there any way where I can attach scroll event on dropdown created by ngbTypeahead so on Scroll I can load more records. If not, please add it in next upcoming version.

Angular: 5

ng-bootstrap: 3.0.*

Bootstrap: 4.0.*

**Comment by maxokorokov** [comment] 2018-09-10 14:57
Duplicate of #1119

**Closed by maxokorokov** 2018-09-10 14:57 UTC
Labels: component: typeahead, resolution: duplicate

**Comment by nilamjadhav** [comment] 2018-09-10 18:06
@maxokorokov
Question is related to above bug only.
How to attach received data from pagination service to nbgtypeahed window?
