### ISSUE TITLE
ModalService that can open a modal as a Component

### ISSUE THREAD

**Issue by mohammedzamakhan** [ng-bootstrap/ng-bootstrap#819] opened 2016-09-29 15:53 UTC
I want a ModalService that can create a modal in this fashion, I think we had similar thing in ui-bootstrap too

http://blog.brecht.io/Modals-in-angular2/

**Comment by pkozlowski-opensource** [comment] 2016-09-29 17:58
This is duplicate of #680 and already part of our roadmap. Closing as a duplicate.

**Closed by pkozlowski-opensource** 2016-09-29 17:58 UTC
