### ISSUE TITLE
ng-bootstrap bundle does not work with angular AOT compiled version

### ISSUE THREAD

**Issue by varghesep** [ng-bootstrap/ng-bootstrap#1858] opened 2017-09-19 12:35 UTC
### Angular AOT compiled with ng-bootstrap does not locate the components

The ```ng-bootstrap``` works well if it is used in a non AOT setup. The instructions on [this page ](https://ng-bootstrap.github.io/#/getting-started)will work. The problem is when it is built for production with [angular AOT](https://angular.io/guide/aot-compiler).

The issues are so many when the app compiled to work with ```ng-bootstrap```. This is the command that I used to generate the AOT compiled version as described on[ this page](https://angular.io/guide/aot-compiler).

```"node_modules/.bin/ngc" -p tsconfig.json```

1.  The first issue is that the ```ngc``` creates a separate folder called ```node_modules``` and ```@ng-bootstrap``` underneath it. This folder has all the factory files.

![image](https://user-images.githubusercontent.com/12233474/30591739-a37d5b44-9d09-11e7-964c-8a9cddd60bdb.png)

As an example, the accordion folder contains all the factory files:

![image](https://user-images.githubusercontent.com/12233474/30592014-c2761b66-9d0a-11e7-87c6-f58ae0a16de4.png)

I assume that the angular AOT should create only factory files of the components in the app, not the libraries that it depend on. If that is the case, running angular AOT compilation should not create any library factory files. During the run time, the app factory files should load the UMD module ```node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js```

2. Running ```ngc``` causes all components to be referenced in ```app.module.ngfactory.ts``` like below. 

![image](https://user-images.githubusercontent.com/12233474/30592180-69ad61fa-9d0b-11e7-8034-22675da1b808.png)

Configuring the ```systemjs``` configuration ```system.config``` to work with a relative path and a module map is difficult. I don't know also why an import of ```NgbModule.forRoot()``` is generating all these imports in the factory file :-( 

3. To get over the mapping issue, I updated the ```system.config``` the following way. This will get me through the initial set of errors related to mapping.

![image](https://user-images.githubusercontent.com/12233474/30592477-83c962e0-9d0c-11e7-849c-56d543917678.png)

But then it ends up in another error:

![image](https://user-images.githubusercontent.com/12233474/30592527-b8c3e42a-9d0c-11e7-8cc6-3021b8f72667.png)

### Link to minimally-working plunker that reproduces the issue:

This is a build issue, so can't reproduce it on plunker.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.4.1

Angular AOT Compiler: 4.4.1

ng-bootstrap: 1.0.0-beta.5

Bootstrap: v4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment] 2017-09-19 13:42
> I assume that the angular AOT should create only factory files of the components in the app, not the libraries that it depend on. If that is the case, running angular AOT compilation should not create any library factory files. 

This is _not_ how it works in the current Angular version - factory files are created for both your application _and_ dependent / imported code.

> Configuring the systemjs configuration system.config to work with a relative path and a module map is difficult. 

Agreed. This is exactly why we no longer suggest using systemjs for building Angular apps (angular-cli is built on top of WebPack).

> I don't know also why an import of NgbModule.forRoot() is generating all these imports in the factory file :-(

Once again, Angular compiler _will_ generate code for 3rd parties, this is expected and normal.

This library is used and build by thousands of developers across the World with AOT (including our [demo page](https://ng-bootstrap.github.io/#/home) which works perfectly fine wit AOT. As such I believe that the issue is with your setup and I would encourage you to:
* try angular-cli that makes building Angular applications super-easy;
* seek more help on dedicated support forums if you want to continue with your setup: https://github.com/ng-bootstrap/ng-bootstrap#getting-help 

> This is a build issue, so can't reproduce it on plunker.

Sure, but you can always create a small GitHub repository with a _minimal_ reproduce scenario.

Closing as a support request for now.

**Closed by pkozlowski-opensource** 2017-09-19 13:42 UTC

**Comment by varghesep** [comment] 2017-09-19 14:06
You are suggesting me not to use ```systemjs``` due to ```ng-bootstrap``` does not work with ```systemjs``` but in the [documentation ](https://ng-bootstrap.github.io/#/getting-started)says how it can be used with ```systemjs```. 

Please document that ```ng-bootstrap``` should not be used with ```systemjs```.

**Comment by pkozlowski-opensource** [comment] 2017-09-19 14:10
> You are suggesting me not to use systemjs due to ng-bootstrap does not work with systemjs

This is _not_ what I'm suggesting. I'm just saying that it is _much easier_ to work with CLI. ng-bootstrap can work perfectly fine with SystemJS given that you take time to configure it properly.

Anyhow, I don't think that there is anything ng-bootstrap specific here, all your issues described here seem to be the same for _any_ library and AOT + SystemJS combination. If you believe that there is anything specific to our npm distribution we would obviously fix it. But for now I haven't seen any evidence of issues on our end.

**Comment by varghesep** [comment] 2017-09-19 14:38
Though it was not obvious, I was able to configure the ```system.config``` to make it work. I provided the configuration in the original question. So, now I don't get any mapping errors, I get the error ```ctor is not a constructor```.

```ng-bootstrap``` does not work with ```systemjs``` 0.19.46 or above. All these leads me to stress on your statement.

**Comment by varghesep** [comment] 2017-09-21 13:40
I entered a new bug in the [angular repo](https://github.com/angular/angular/issues/19313). The dependency resolution for ```NgbModal``` is failing in the AOT mode.
