### ISSUE TITLE
ExpressionChanged error when opening modal from ngbButton

### ISSUE THREAD

**Issue by bluecaret** [ng-bootstrap/ng-bootstrap#2231] opened 2018-03-19 21:38 UTC
### Bug description:

Setting a click event on an ngbButton to open a modal causes an ExpressionChanged error in the console.

```
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.
    at viewDebugError (errors.js:52)
    at expressionChangedAfterItHasBeenCheckedError (errors.js:28)
    at checkBindingNoChanges (util.js:127)
    at checkNoChangesNodeInline (view.js:553)
    at checkNoChangesNode (view.js:520)
    at debugCheckNoChangesNode (services.js:542)
    at debugCheckRenderNodeFn (services.js:486)
    at Object.eval [as updateRenderer] (NgbdModalBasic.html:17)
    at Object.debugUpdateRenderer [as updateRenderer] (services.js:463)
    at checkNoChangesView (view.js:363)
```

In the linked stackblitz, if you click the button on the page which is an checkbox button using ngbButton, the modal opens but in the console the above error appears.

### Link to minimally-working plunker that reproduces the issue:

https://angular-ugsexc.stackblitz.io/

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.0.2
ng-bootstrap: 1.0.2
Bootstrap: 4.0.0

**Comment by pkozlowski-opensource** [comment] 2018-03-19 21:56
This is a duplicate of #1252 - the root cause is that both Angular forms _and_ modal are "fighting" for focus: `ngModel` has bindings based on focus in a control and modal is moving focus to the newly opened modal (for accessibility reasons). #1252 has more details.

Unfortunately at this point I'm still not sure what is the best solution as both `ngModel` and modal do the right thing, but the combination leads to this error...

Your best option for now is to trigger modal in `setTimout`, I'm afraid... 

Closing as a duplicate of #1252

**Closed by pkozlowski-opensource** 2018-03-19 21:56 UTC
