### ISSUE TITLE
"auto" and secondary placement of popovers is incorrectly determined

### ISSUE THREAD

**Issue by burnedram** [ng-bootstrap/ng-bootstrap#1898] opened 2017-10-13 09:58 UTC
### Related:
#1896: ngbTooltip placement issue when inside other text
#1876: Typeahead availability of placement 'bottom-left' or 'top-left' is dismissed by height, not width

### Bug description:
[Positioning.getAvailablePositions()](https://github.com/ng-bootstrap/ng-bootstrap/blob/6c7a31b08942532431eeee22f32148f948880ed6/src/util/positioning.ts#L149)'s checks are incorrect, resulting in "auto" placement being resolved to "top" if there is enough space above, even if there is not enough horizontal space. In this case "top-left" or "top-right" would be more appropriate.

[Positioning.setSecondaryPlacementForTopBottom()](https://github.com/ng-bootstrap/ng-bootstrap/blob/6c7a31b08942532431eeee22f32148f948880ed6/src/util/positioning.ts#L215) uses height instead of width to determine if there is enough space the right, as mentioned in #1876. This results in *-left being an available placement, even if there is zero space between the host element and the right edge of the window.

I'm also a bit confused why e.g. "top-left" is "Position the popover on top, and place the little arrow to the left", which results in the popover being placed to the top right. However, I also understand that changing this behaviour would break a lot of code already using these placements, but I don't think this behaviour is reflected in the [API documentiation](https://ng-bootstrap.github.io/#/components/popover/api).

I'm currently working on a pull request for the Positioning service that should fix these problems.

### Link to minimally-working plunker that reproduces the issue:
[Old, angular 4.4.4, ng-bootstrap 1.0.0-beta.5](http://plnkr.co/edit/4XSRQHO9MAu3XHI5UHx6?p=preview)
[New angular 6.0.0, ng-bootstrap 2.0.0](http://plnkr.co/edit/bCAmOVzyiO5kYyCe4UtO?p=preview)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6.0.0

ng-bootstrap: 2.0.0

Bootstrap: 4.0.0

Edit: Links points to the latest commit (as of this writing) instead of master
Edit2: Update ng-bootstrap 1.0.0-beta.5 -> 2.0.0

**Comment by pkozlowski-opensource** [comment] 2017-10-13 10:07
> I'm currently working on a pull request for the Positioning service that should fix these problems.

Awesome, please do!

**Comment by burnedram** [comment] 2017-10-13 14:39
I have created a [pull request](https://github.com/ng-bootstrap/ng-bootstrap/pull/1899) for this, and we can continue the discussion here or on the pull request, whatever you desire. 😃

**Comment by bluecaret** [comment] 2017-11-09 23:33
Does this issue cover the auto placement issue [shown here](http://plnkr.co/edit/MpCDQqq72HRbrYLmaQD5?p=preview)? The auto placement correctly doesn't display the popover on top as there is no room, nor on the right since it would still hit the top of the window and thus ends up on bottom. But since the host element is all the way on the left side of the window and the popover is centered with the element, this causes the popover to be cut off by the window. In situations like this, it should not be centered with the element but instead the left side of the popover should be aligned to the left of the element.

Or would this be a separate bug?

**Comment by burnedram** [comment] 2017-11-11 16:32
@bluecaret This issue should cover your case. In your case, the bug is that the positioning service doesn't check for horizontal space for "top" and "bottom" placements, thus resulting in "bottom" being an available placement.

You are correct in that it should choose "bottom-left" (popover on bottom, arrow on the left side, thus moving the popover to the right) and I believe that it is one of the possible placements that it finds. However, since "bottom" is available and before "bottom-left" in the placement-array, it chooses "bottom".

**Comment by bluecaret** [comment] 2017-11-11 19:17
@burnedram Awesome thanks! Looking forward to this being added then!

**Comment by pkozlowski-opensource** [comment] 2018-03-09 13:43
Here is a plunker from @bluecaret updated to the latest version, showing that the issue is still present with all the latest versions of the involved packages: http://plnkr.co/edit/q9uhBLqSKblZ3u4RLxzM?p=preview

Scheduling fix for the next release, looking into it right now...

**Comment by pkozlowski-opensource** [comment] 2018-06-15 12:12
Fixed in 7208006

**Closed by pkozlowski-opensource** 2018-06-15 12:12 UTC
Labels: component: popover, type: bug
