### ISSUE TITLE
Slow performance with multiple Typeaheads in Reactive Form

### ISSUE THREAD

**Issue by borriej** [ng-bootstrap/ng-bootstrap#1991] opened 2017-11-24 13:37 UTC
Hi!

I've noticed slow performance with multiple typeaheads in a Reactive Form. I have 3 typeaheads per row, and 60 rows for instance. All wrapped inside a Reactive Form. @pkozlowski i've emailed you a private plunkr to your gmail.

What to do?

I tried to only create the typeahead components when needed by hiding them by default:
``` *ngIf="item.showTypeahead"```

And I first show a dummy input, if the user sets focus on this input, the typeahead shows and sets focus:
```(focus)="item.showTypeahead = true" ....  ```

it's a lot less laggy then, but still typing (rendering) goes slow.

**Comment by Baso1st** [comment] 2017-11-29 21:49
I had the same problem, switched to [https://github.com/valor-software/ngx-bootstrap](url) it is much faster, but it lakes some other functionality. You might want to check it and make sure that it performs the job you want before using it.

**Comment by borriej** [comment] 2017-11-30 10:36
@Baso1st thank you for the tip! I'm really hoping the contributors have had time to look at my issue so I can stick with ng-bootstrap on this project :)

**Comment by pkozlowski-opensource** [comment] 2017-12-01 09:04
This is duplicate of #1471

**Closed by pkozlowski-opensource** 2017-12-01 09:04 UTC
