### ISSUE TITLE
typeahead won't allow grouped or nested json items

### ISSUE THREAD

**Issue by dotNetAthlete** [ng-bootstrap/ng-bootstrap#2856] opened 2018-11-08 16:02 UTC
I am trying to configre the resultformatter to accept grouped items, but to no avail.
Could someone explain what changes to 'value' I need to make to make this work ?

empFormatMatches = (value: any) => value.EmployeeName;

(value is an object with several properties, but one or more of those properties can have sub properties, I would like to list those sub-properties along with the parent)

**Comment by pkozlowski-opensource** [comment] 2018-11-08 17:54
If you want to display your sub-properties as part of one slectable row than you can use a custom template to customize a row's display.

If this is about having multiple selectable results where there a property is one row and sub-properties are subsequent selectable rows, this is not supported currently, see: #1274

I must say that the whole issue is not clear for me, I'm not sure if you are reporting a bug (in this case we need a minimal reproduce scenario as required in the issue template) or asking for support (in which case this belongs to StackOverflow).

In any case it is always good idea to include a minimal reproduce scenario in a stackblitz since it is often easier to understand code as compared to a brief textual description.

**Comment by dotNetAthlete** [comment] 2018-11-09 15:00
I'm now using ng-select which supports grouping by - I assume the typeahead doesn't support that!

**Comment by pkozlowski-opensource** [comment] 2018-11-12 15:40
I believe that this is a duplicate of #1274

**Closed by pkozlowski-opensource** 2018-11-12 15:40 UTC
Labels: component: typeahead, needs: info, needs: stackblitz
