### ISSUE TITLE
The paging component does not set up the page, where the next page displays the content

### ISSUE THREAD

**Issue by mraiguo** [ng-bootstrap/ng-bootstrap#1565] opened 2017-05-22 10:04 UTC
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:

ng-bootstrap:

Bootstrap:

**Comment by mraiguo** [comment] 2017-05-22 10:05
当我使用分页组件的时候，我想要自定义下一页的提示按钮文本，但是没有配置的地方

**Comment by mraiguo** [comment] 2017-05-22 10:05
When I use the paging component, I want to customize the text of the prompt button for the next page, but there is no configuration

**Comment by pkozlowski-opensource** [comment] 2017-05-22 15:21
This is duplicate of the existing issue #899

**Closed by pkozlowski-opensource** 2017-05-22 15:21 UTC
Labels: component: pagination, PRs plz!, type: feature
