### ISSUE TITLE
Cannot find type definition file for 'core-js' error after upgrading to alpha 12

### ISSUE THREAD

**Issue by ASHFAQPATWARI** [ng-bootstrap/ng-bootstrap#1029] opened 2016-11-11 08:31 UTC
After upgrading to alpha 12, i am getting this error:

### Bug description:

@ng-bootstrap\ng-bootstrap\modal\modal-ref.d.ts:1:0 
Cannot find type definition file for 'core-js'

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.1.0

ng-bootstrap: 1.0.0- alpha 12

Bootstrap: v4 alpha 5

**Comment by pkozlowski-opensource** [comment] 2016-11-11 08:33
Duplicate of #1027 - I'm just cutting a alpha.13 release that fixes this.

**Closed by pkozlowski-opensource** 2016-11-11 08:33 UTC

**Comment by pkozlowski-opensource** [comment] 2016-11-11 08:52
alpha.13 with the fix should be on npm now.
