### ISSUE TITLE
Tooltips move buttons in button group.

### ISSUE THREAD

**Issue by PEsteves8** [ng-bootstrap/ng-bootstrap#896] opened 2016-10-17 10:10 UTC
### Bug description:

So I noticed you added support for container: body in alpha-8. I thought that would solve the problem with tooltips in button groups, but that doesn't seem to be the case.

### Link to minimally-working plunker that reproduces the issue:

Here. I made a tiny change to your plunkr so that the buttons were in a group. 

http://plnkr.co/edit/2ddFyPuVFJD96Hm6zIjR?p=preview

Basically I just switched the 'card' class to 'btn-group'. By hovering the left button there's a slightly shift in the right button. 

That's not supposed to happen is it? I actually did notice that the tooltip does indeed get attached to the body. But I assumed that would solve the layout shift problem.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.0.1

ng-bootstrap: alpha-8

Bootstrap: alpha-4

**Comment by pkozlowski-opensource** [comment] 2016-10-17 10:25
I can see a right border of the first (leftmost) button getting different color and this creates an unpleasant effect. But:
* I can see this on Chrome, but not on FFox
* The root cause seems to be linked to the fact that the `:hover`  pseudo-class is not removed when you move mouse out in the top / down direction (it works correctly when you move mouse to the right).

Right now it doesn't seem to be linked to `ng-bootstrap` but rather might be a Chrome-specific. Could you please:
* try with different browsers (atm I've got only Chrome and FFox handy) 
* try to reproduce without `ng-bootstrap` (just regular bs4 + jQuery)

This would help us identify the root cause and re-open in a good repo.

**Comment by PEsteves8** [comment] 2016-10-17 11:19
You're right. It works fine on Edge and Firefox at least.

However, when I used it on bs4 and jQuery it worked fine even without the data container. Although I'm not sure how valuable this example is since the bs javascript is alpha-2 and if you switch between the buttons rapidly, after a while the whole thing breaks:

https://plnkr.co/edit/jGiyfjX86mckBEOAQ4Z2?p=preview

So I don't really know what to think.

**Comment by pkozlowski-opensource** [comment] 2016-10-17 12:00
Interesting... What I can see in Chrome that the `margin-left` style of the second button flips between `0px` and `-1px` while it should be `-1px` all the time...

**Comment by pkozlowski-opensource** [comment] 2016-10-18 17:26
I've just re-tested on few other browsers and here are the results (all on OSX):
* happens on Chrome  53.0.2785.143 
* doesn't happen on Safari 9.1
* doesn't happen on Firefox 49.0.1
* doesn't happen on Chrome 54.0.2840.59
* doesn't happen on Chrome Canary 56.0.2894.0 

Given the above I'm going to close this one as caused by a bug in an older version of Chrome and fixed in Chrome 54+.

**Closed by pkozlowski-opensource** 2016-10-18 17:26 UTC
Labels: component: tooltip, needs: investigation

**Comment by PEsteves8** [comment] 2016-10-19 09:37
Great. Thanks :)
