### ISSUE TITLE
(accordion) Should use ngAfterContentInit for better performance ?

### ISSUE THREAD

**Issue by changLiuUNSW** [ng-bootstrap/ng-bootstrap#1628] opened 2017-06-21 13:57 UTC
I just realize ```NgbAccordion``` use ```ngAfterContentChecked``` to populate initial state:
https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/accordion/accordion.ts#L178

This is not good for performance, because ```ngAfterContentChecked``` will be triggered in every change detection.

Maybe I missed something, but I think we should use ```ngAfterContentInit``` instead of ```ngAfterContentChecked```.

**Comment by changLiuUNSW** [comment] 2017-06-21 14:02
I just tested  ```ngAfterContentInit ```. The accordion is still working without any problems

**Comment by pkozlowski-opensource** [comment] 2017-06-21 14:05
Switching to `ngAfterContentInit` wouldn't work for cases where `activeIds` input gets updated.

> I just tested ngAfterContentInit. The accordion is still working without any problems

Did you run all the existing tests?

I believe that the current implementation is correct. Are you seeing any performance problems caused by the current implementation? 

In the longer run we are going to switch this component to `OnPush` and then `ngAfterContentInit` will only run when inputs are updated.

**Comment by changLiuUNSW** [comment] 2017-06-21 14:18
···Switching to ngAfterContentInit wouldn't work for cases where activeIds input gets updated.···
If that is the reason, I may suggest create a ```setter``` for ```activeIds``` input and trigger update inside ```setter``` like:
```
 set activeIds(value: string | string[] ) {
    if (isString(this.activeIds)) {
        this._activeIds = this.activeIds.split(/\s*,\s*/);
      }
     this._updateStates();

    // closeOthers updates
    if (this._activeIds .length > 1 && this.closeOtherPanels) {
      this._closeOthers(this._activeIds [0]);
      this._updateActiveIds();
    }
}
```

**Comment by pkozlowski-opensource** [comment] 2017-06-21 14:24
> If that is the reason, I may suggest create a setter for activeIds input and trigger update inside setter

This is not enough as `closeOthers` needs to be taken into account as well. So it would have to be a setter. Same goes for any property that influences internal state of the accordion. Multiplying those setters results in code that is super-hard to maintain.

Given this I would much rather focus on making this component `OnPush` which would have even better perf characteristics. But then again, I'm not sure if this is priority unless we've got real-life proof of the `ngAfterContentChecked()` method in accordion being a perf bottleneck.

**Comment by changLiuUNSW** [comment] 2017-06-21 14:34
What if we use ```ngOnChanges```?

**Comment by changLiuUNSW** [comment] 2017-06-21 14:38
``` I'm not sure if this is priority unless we've got real-life proof of the ngAfterContentChecked() method in accordion being a perf bottleneck.``` 
Cannot get real-life proof yet. Will keep an eye on it.

**Comment by pkozlowski-opensource** [comment] 2017-08-18 14:41
> Cannot get real-life proof yet. Will keep an eye on it.

Cleaning up issues in preparation for 1.0 release so I'm going to close this one for now. Please comment back / open a new issue if anything is not performing as expected in real-life applications.

**Closed by pkozlowski-opensource** 2017-08-18 14:41 UTC
Labels: component: accordion, type: performance
