### ISSUE TITLE
ngbModal.open(ComponentName) throws error when called from ng-template in ngx-datatable

### ISSUE THREAD

**Issue by xyrintech** [ng-bootstrap/ng-bootstrap#2058] opened 2017-12-22 15:10 UTC
```
<ng-template let-row="row" ngx-datatable-cell-template>
                    <div ngbDropdown placement="bottom-right">
                        <button class="btn btn-primary btn-flat" ngbDropdownToggle>Account history
                        </button>
                        <div ngbDropdownMenu>
                            <li class="dropdown-item" (click)="openModal(row)">Edit</li>
                        </div>
                    </div>
                </ng-template>
```

```
openModal(row: any) {
        const modalRef = this.modalService.open(AccountComponent,
            {
                size: "lg",
                windowClass: "modal-xxl"
            });
    }
```

**Comment by pkozlowski-opensource** [comment] 2017-12-22 15:18
Please follow our issue template when reporting potential bugs: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

It is not actionable / understandable as-is.

**Comment by xyrintech** [comment] 2017-12-22 15:49
version of Angular used : Angular 5.0.1
version of this library that you are using: Latest

The issue is when we load the modal after clicking on any ngx-datatable template like following:

```
<ng-template let-row="row" ngx-datatable-cell-template>
                    <div ngbDropdown placement="bottom-right">
                        <button class="btn btn-primary btn-flat" ngbDropdownToggle>Account history
                        </button>
                        <div ngbDropdownMenu>
                            <li class="dropdown-item" (click)="openModal(row)">Edit</li>
                        </div>
                    </div>
                </ng-template>
```

This is the code for modal function:

```
openModal(row: any = null) {
        const modalRef = this.modalService.open(AccountComponent,
            {
                size: "lg",
                windowClass: "modal-xxl"
            });
    }
```

This function loads the modal without any error when we load button with (click)="openModal()"

This is the error: 
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'datatable-body-cell sort-active

**Comment by xyrintech** [comment] 2017-12-22 16:19
Do you still need a plunkr? I have specified everything above.

**Comment by pkozlowski-opensource** [comment] 2017-12-22 16:21
> Do you still need a plunkr?

Of course! We can't reproduce / act using code snippets posted here...

**Comment by xyrintech** [comment] 2017-12-22 16:29
https://github.com/swimlane/ngx-datatable/issues/721
I find an issue open for ngx-datatable.
It's the same issue.

**Comment by pkozlowski-opensource** [comment] 2017-12-22 16:45
OK, I see. It is definitively linked to focus management, relevant discussion here: #1252

**Comment by pkozlowski-opensource** [comment] 2018-01-05 10:05
Closing as a duplicate of #1252

**Closed by pkozlowski-opensource** 2018-01-05 10:05 UTC
Labels: component: modal, needs: plunkr
