### ISSUE TITLE
Timepicker: Invalid string is not always removed from the field

### ISSUE THREAD

**Issue by dzagaduroska** [ng-bootstrap/ng-bootstrap#2723] opened 2018-09-18 20:09 UTC
**Bug description**: Timepicker does not remove the invalid string when you enter invalid string the second time.

Steps to reproduce this bug:
1. Type some invalid string in the hour field (or time) e.g "ab"
2. Click outside the component -> now the field should be empty
3. Type again some invalid value -> the field remains the same and the invalid value is still visible in the field

**Link to minimally-working plunker that reproduces the issue**: http://plnkr.co/edit/QU3846?p=preview

**Version of Angular, ng-bootstrap, and Bootstrap**:

Angular: 6.1.3

ng-bootstrap: 3.2.0

Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment] 2018-09-18 20:38
Duplicate of #1644

**Closed by pkozlowski-opensource** 2018-09-18 20:38 UTC
