### ISSUE TITLE
background shakes when use model window

### ISSUE THREAD

**Issue by LostOnEast** [ng-bootstrap/ng-bootstrap#2179] opened 2018-02-20 12:30 UTC
we can see this on
https://ng-bootstrap.github.io/#/components/modal/examples

when click launch btn background shifted by several pixels

Angular: 5.0.0

ng-bootstrap: 1.0.0

Bootstrap: 4.0.0

**Comment by bastienmoulia** [comment] 2018-02-20 12:43
@LostOnEast When the modal is open, the scroll bar of the page disappears so the content moves.

**Comment by pkozlowski-opensource** [comment] 2018-02-20 12:44
Duplicate of #641

**Closed by pkozlowski-opensource** 2018-02-20 12:44 UTC
