### ISSUE TITLE
Month and Year only for datepicker

### ISSUE THREAD

**Issue by Mutunus** [ng-bootstrap/ng-bootstrap#2245] opened 2018-03-22 22:49 UTC
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:

ng-bootstrap:

Hi guys. Thanks for your great work. I have previously used bootstrap with AngularJS to make my forms look pretty. With the previous version of bootstrap I had the option to only display months and years. I would like to make a request that this feature is implemented into ng-bootstrap.

Bootstrap:

**Comment by maxokorokov** [comment] 2018-03-23 13:17
Will close as duplicate of #1811 Thanks for the interest!

**Closed by maxokorokov** 2018-03-23 13:17 UTC
Labels: component: datepicker, resolution: duplicate, type: feature
