### ISSUE TITLE
Carousel control icons not aligned correctly

### ISSUE THREAD

**Issue by CarlosTorrecillas** [ng-bootstrap/ng-bootstrap#1798] opened 2017-08-31 10:44 UTC
### Bug description: 

Carousel indicator are not aligned. If you check the **carousel-control-next-icon** and **carousel-control-prev-icon** you will see that both are aligned to the left. I would have expected the **carousel-control-next-icon** aligned to the right since **carousel-control-prev-icon** is "correctly" aligned to the left.

### Link to minimally-working plunker that reproduces the issue:
Any plunker of your demos for your carousel is good: https://ng-bootstrap.github.io/#/components/carousel/examples

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.0.3

ng-bootstrap: 1.0.0-beta.3

Bootstrap: 4.0.0-beta

**Comment by pkozlowski-opensource** [comment] 2017-08-31 11:44
@CarlosTorrecillas would you mind sharing a screenshot with annotations to clearly show what is not properly aligned? I'm looking at https://ng-bootstrap.github.io/#/components/carousel/examples and for the World of me can't see the problem :-/ Maybe it is a specific browser / extension (in this case please provide more details about a browser and / or try in the incognito mode).

Also, could you check https://getbootstrap.com/docs/4.0/components/carousel/ and let me know if you see the problem in there? I'm asking since we are just using Bootstrap's CSS and should be producing the same HTML so if anything is not aligned it should be also visible on the Bootstrap site).

Would appreciate more info as right now I can't reproduce the problem...

**Comment by CarlosTorrecillas** [comment] 2017-08-31 11:56
![image](https://user-images.githubusercontent.com/648793/29921899-bd04f35c-8e53-11e7-96db-8f12439f9e73.png)

I quickly changed the background of the span to be black so you can see what I'm referring to. Hopefully you now have all information you need?

By the way, bootstrap has the exact same problem as far as I can tell:

![image](https://user-images.githubusercontent.com/648793/29922006-27cb9fa6-8e54-11e7-94fe-e2edb93dd524.png)

**Comment by pkozlowski-opensource** [comment] 2017-08-31 11:59
@CarlosTorrecillas thnx for the details, I see now. I think that this is an issue in Bootstrap's CSS (as I've said, we are building on top of Bootstrap's CSS and markup). Would you mind opening an issue in https://github.com/twbs/bootstrap/issues so Bootstrap folks are aware of this? When it gets fixed on the Bootstrap CSS side it should work here as well.

**Comment by CarlosTorrecillas** [comment] 2017-08-31 12:50
For reference I've created this: https://github.com/twbs/bootstrap/issues/23768

**Comment by pkozlowski-opensource** [comment] 2017-09-01 10:07
I'm going to close this one here as it was confirmed as a bug on the Bootstrap's side (and as such there is nothing actionable here).

**Closed by pkozlowski-opensource** 2017-09-01 10:07 UTC
Labels: blocked: bs4 issue, component: carousel, needs: investigation
