### ISSUE TITLE
Close popover on click outside

### ISSUE THREAD

**Issue by baio** [ng-bootstrap/ng-bootstrap#933] opened 2016-10-20 18:15 UTC
Hi, feature request, quite simple case - possibility to close popover when user clicked outside one.

**Comment by jrab** [comment] 2016-10-21 20:35
Was this a rewrite of the angular-ui-boostrap resulting in a lot of the bug fixes / features that existed in the prior version (angular-ui-bootsrap v1) to go missing?

**Comment by ASHFAQPATWARI** [comment] 2016-11-07 07:52
Is this released with alpha.11 ? Can't find anyting related to OutsideClick trigger in documentation.

**Comment by pkozlowski-opensource** [comment] 2016-11-07 18:00
Issue open = not fixed => not released

**Comment by ASHFAQPATWARI** [comment] 2016-11-11 17:30
@pkozlowski-opensource Any update on this one?

**Comment by pkozlowski-opensource** [comment] 2016-11-11 17:32
@ASHFAQPATWARI as you can see in this issue there is _NO_ update. If someone will start work on this issue it will be closed with a commit pointing to a sha with the new feature. Please do _not_ spam issues like this, this is not helpful nor appreciated.

**Comment by spongessuck** [comment] 2016-11-15 16:55
@pkozlowski-opensource How might you imagine an attribute for this would work? Something like `closeOnClickOutside` as a boolean, or an Output for `onClickOutside` and have it up to the dev to call `p.close()`?

**Comment by pkozlowski-opensource** [comment] 2016-11-16 08:53
@spongessuck my initial thought was to add a boolean attribute but I must say that I didn't spend too much time thinking about this one.

As a side note, there is an easy work-around as of today where you could say: `<div ngbPopover="..." #p="ngbPopover" (document:click)="p.close()">`. It is not ideal and a bit verbose but the point is that there are mechanisms in place to close popovers in response to "external" events.

**Comment by spongessuck** [comment] 2016-11-16 17:42
I wasn't able to get your example working- it seems like either the document listener is blocking clicks to the popover trigger listener or it's being called just after the trigger and closing the popover immediately.

I got a solution working by editing the raw module JS, but it's just happening without configuration.

I'm thinking that using an Output is more flexible, if more verbose, but it would be easy to support both options, so maybe we should:
```
@Input() closeOnClickOutside: boolean;
@Output() clickOutside: EventEmitter;
```

**Comment by pkozlowski-opensource** [comment] 2016-12-30 14:51
For anyone monitoring this issue here is a short write-up summarizing our options:

1. Do nothing - don't add new API as things are possible today
2. Add new Boolean flag (`closeOnOutsideClick` or similar)
3. Add new "fake"  event (`outsideClick` ?) so this "fake"  event can be used as part of the `triggers` 

ad.1 

The reason that we didn't rush to any implementation so far is that the current behavior is aligned with what Bootstrap does and people can decide to have popovers closed on the "outside click"  as follows:

```html
<button type="button" class="btn btn-secondary" placement="top"
        ngbPopover="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." 
        popoverTitle="Popover on top" 
        #p="ngbPopover" (document:click)="p.close()" (click)="$event.stopPropagation()">
  Popover on top
</button>
```

A working plunker: http://plnkr.co/edit/ZVh3vSwb5DBfuA2IFyiY?p=preview

This is something that works today and is very flexible (people have full control over an "outside" trigger). There are 3 downsides to this approach, though:
* it is a bit verbose to write `#p="ngbPopover" (document:click)="p.close()" (click)="$event.stopPropagation()"` for each and every popover instance;
* we can't have global configuration to express "close all popovers on outside click, always"
* people might not known the `#p="ngbPopover" (document:click)="p.close()" (click)="$event.stopPropagation()"` trick (this could be helped with documentation).

ad. 2

Another approach is to simply add a new `@Input` (`outsideClick`) so one could write:

```html
<button type="button" class="btn btn-secondary" placement="top"
        ngbPopover="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." 
        popoverTitle="Popover on top" 
        [outsideClick]="true">
  Popover on top
</button>
```

It is a very simple mechanism (both to implement and use) but has "hard-coded" outside event.

ad 3.

Another approach (implemented in http://angular-ui.github.io/bootstrap/#/popover and proposed in #1064) is to express "close on outside click" as part of the `triggers` `@Input()` , ex:

```html
<button type="button" class="btn btn-secondary" placement="top"
        ngbPopover="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." 
        popoverTitle="Popover on top" 
        triggers="outsideClick">
  Popover on top
</button>
```

This seems like a good idea at first but it has many issues:
* limits flexibility of triggers - what is I want to open a popover on `focus`, close on `blur` and still close such popover on outside clicks?
* has a "hard-coded" event name;
* it is not possible to express that all popovers should be closed on outside clicks in global configuration.

**Comment by pkozlowski-opensource** [comment] 2016-12-30 14:58
Given the above analysis I believe that option (3) has too many shortcomings to be part of this library API. (1) is a good work-around till we come up with something better.

Speaking of "something better" here is my proposal: let's introduce a new `@Input` named `outsideClose`. This new input could take the following values:
* `false`  - (default) current behavior 
* `true`  - close a popover on outside click
* `"click;tap"` - `;` separated event names to be used as "outside triggers"

If I don't here any comments / screams / better ideas I'm going to implement the above in the coming day(s).

**Comment by BlackTr** [comment] 2016-12-30 15:55
Can we separate triggers not by  ':', but by different symbol? E.g. with ';'
So, we can simple write in triggers:
triggers="click;document:click"

**Comment by pkozlowski-opensource** [comment] 2016-12-30 15:58
@BlackTr changing separator doesn't solve the issue as the "outside trigger" is "3rd" trigger - it can be, but don't have to be equal to close trigger. See my example in  https://github.com/ng-bootstrap/ng-bootstrap/issues/933#issuecomment-269779770

**Comment by spongessuck** [comment] 2016-12-30 16:21
@pkozlowski-opensource:

Your demo for option (1) doesn't work on either Firefox or Chrome; clicking inside the popover closes it, so it is not working as the feature is imagined to work. Am I missing something?

Regarding option (3): while I agree that 'hard-coding' the event isn't ideal, I don't think the other negative points are true. Using my PR as a model, i.e. supporting a close-on-click-outside feature by setting `triggers="click:outsideClick"`, I was able to configure this globally in my app module as follows:
```ts
export class AppModule {
  constructor(popoverCfg: NgbPopoverConfig) {
    popoverCfg.triggers = 'click:outsideClick';
  }
}
```
I was also able to use this event in conjunction with others using your example. It doesn't work as expected because the blur and outsideClick events conflict with each other, but the options aren't mutually exclusive:
```html
<input ngbPopover="hello" triggers="focus:blur outsideClick" />
```
Finally, it doesn't really matter to me how this feature is included in the library. The `outsideClose` input is how I originally implemented this feature in my PR. I think it's less elegant than the event solution, but I agree it's more applicable to other components, particularly those that don't have a `triggers` attribute (i.e. dropdown).

**Comment by spongessuck** [comment] 2016-12-30 16:32
@BlackTr triggers already supports a space-separated list of events.

**Comment by BlackTr** [comment] 2016-12-30 16:44
@pkozlowski-opensource can we just use next to implement different close triggers?:
`triggers="focus;blur focus;document:click"`

If you don't want to break API and change separtor you can do something next (I think, but I didn't try):

```
let alias = aliases[triggerPair[0]] || triggerPair;
if (alias[1]=='document') alias[1]+=':'+alias[2];
return new Trigger(alias[0], alias[1]);
```

**Comment by devoto13** [comment] 2017-01-11 22:19
One of the problems with implementing "dismiss on next click" behavior using `document:click` is that it won't work if any element in the tree between clicked one and `document` calls `e.stopPropogation()`, which is not super common, but still may produce issues.

Also see note from the original Bootstrap implementation: http://v4-alpha.getbootstrap.com/components/popovers/#dismiss-on-next-click

If I understand their approach correctly it utilizes `blur` event, which is triggered for `<a>` with `tabindex` attribute, which in turn is triggered on any click outside of `<a>` element. This approach has no issues with `e.stopPropogation()`, seems to utilize native behavior of the browser. The only disadvantage is that clicking on the popover itself will also close it.

**Comment by spongessuck** [comment] 2017-01-11 22:22
> The only disadvantage is that clicking on the popover itself will also close it.
That's a deal-breaker for me.

**Comment by devoto13** [comment] 2017-01-11 23:36
And not handling `e.stopPropagation()` is a deal breaker for my app. In case anybody is interested in the BS approach. Here is a working example (item 1):

http://plnkr.co/edit/GAwXOBvSLMgmoFM5bFKp?p=preview

It also includes showcase, that you can't handle click on popover itself, before it gets closed (item 2). Which is pretty disappointing. I can be possibly solved by closing next tick, so click handler is triggered and then popover is closed.

@spongessuck After further thinking I suspect that your use case can be covered using same approach as for my use case. Basically in the `blur` event handler we need to check for the same condition of element being contained by popup as in the `document:click` handler and instead of closing - return focus back to the trigger element.

**Comment by spongessuck** [comment] 2017-01-14 22:03
For those waiting for this to be implemented, here's what I'm using:

```ts
import { Directive, Input, HostListener } from '@angular/core';

@Directive({
  selector: '[closePopoverOnClickOutside]'
})
export class ClosePopoverOnClickOutsideDirective {

  active = false;

  @Input('closePopoverOnClickOutside') popover: { close, isOpen };

  @HostListener('document:click', ['$event.target'])
  docClicked(target): Boolean {
    if (!this.popover.isOpen()) {
      return this.active = false;
    }
    // Click that opens popover triggers this. Ignore first click.
    if (!this.active) {
      return this.active = true;
    }

    let cancelClose = false;
    let popoverWindows = document.getElementsByTagName('ngb-popover-window');

    for (let i = 0; i < popoverWindows.length; i++) {
      cancelClose = cancelClose || popoverWindows[i].contains(target);
    }
    if (!cancelClose) {
      this.popover.close();
    }

    // Deactivate if something else closed popover
    this.active = this.popover.isOpen();
  }

}
```

And use thusly:

```html
<div ngbPopover="Closes when click occurs outside"
     #p="ngbPopover"
     [closePopoverOnClickOutside]="p"></div>
```

**Comment by gilhanan** [comment] 2017-01-15 13:53
@spongessuck returning boolean cause problems on `<input type="checkbox">` , not allow to checking it.
and I'm offer to change the type of popover from `{close, isOpen}` to `NgbPopover`
Expect that, nice implementation. thanks!

**Comment by spongessuck** [comment] 2017-01-15 15:37
@gilhanan Thanks, whatever works for you! Never ran into that problem with checkbox.

**Comment by spongessuck** [comment] 2017-01-20 18:48
@gilhanan I ran into issues with my solution blocking clicks to anchors on the page, preventing navigation. Your version is definitely the preferred solution.

**Comment by gilhanan** [comment] 2017-01-21 01:45
@spongessuck Thanks for feedback :) and that's the [reason](http://stackoverflow.com/questions/128923/whats-the-effect-of-adding-return-false-to-a-click-event-listener) for the issues you ran into.

By the way, I revised a bit to another version with emphasizing on type safe:
``` typescript
import { Directive, HostListener, ElementRef, ComponentRef } from '@angular/core';
import { NgbPopover } from '@ng-bootstrap/ng-bootstrap';
import { NgbPopoverWindow } from '@ng-bootstrap/ng-bootstrap/popover/popover';

@Directive({
  selector: '[closePopoverOnClickOutside][ngbPopover]'
})
export class ClosePopoverOnClickOutsideDirective {

  constructor(private elementRef: ElementRef,
              private ngbPopover: NgbPopover) {

  }

  @HostListener('document:click', ['$event'])
  private documentClicked(event: MouseEvent): void {

    // Popover is open
    if (this.ngbPopover && this.ngbPopover.isOpen()) {

      // Not clicked on self instance
      if (!(this.elementRef.nativeElement as Element).contains(event.target as Element)) {

        // Hacking typescript to access private member
        let popoverWindowRef: ComponentRef<NgbPopoverWindow> = (this.ngbPopover as any)._windowRef;

        // If clicked outside popover window
        if (popoverWindowRef && !(popoverWindowRef.location.nativeElement as Element).contains(event.target as Element)) {
          this.ngbPopover.close();
        }
      }
    }
  }
}
```
The extra checking because it's document 

And use thusly:
``` html
<div ngbPopover="Closes when click occurs outside"
     #p="ngbPopover"
     closePopoverOnClickOutside></div>
```

**Comment by jspizziri** [comment] 2017-02-07 17:38
@pkozlowski-opensource,

Is there any word on your proposal [here](https://github.com/ng-bootstrap/ng-bootstrap/issues/933#issuecomment-269780689)? Is that the definitive API decision?

**Comment by thbt** [comment] 2017-02-08 07:26
I'm working on a proposal for this issue, it's mainly about extending the current implementation so it accepts trigger such as `document:click`. I'll be posting a PR soon

**Comment by thbt** [comment] 2017-02-14 17:12
Here is my proposal, we could use a new syntax for the triggers : 
`openTriggers/closeTriggers`
Triggers are represented with the following syntax `target:event`
The target is optional and can be either `document`, `body` or`window`

Examples : 
opens on `foo`, `bar` and `qux`, closes on `foo`, `baz` and `def`
- old syntax : `foo bar:baz qux:def`
- new syntax : `foo bar qux/foo baz def`

opens on `click` and `focus`, closes on outside click and `blur`
- old syntax (not possible, but for the sake of the example) : `focus:blur click:document:click`
- new syntax: `click focus/document:click blur`

This allows us to use Angular's syntax for HostListener, so we don't need to add a hard coded event name. It also allow the use of multiple open and/or close triggers.

I am working on a PR for this proposal, you can check out my work here : [popup-outsideclick branch in thbt/ng-bootstrap](/thbt/ng-bootstrap/tree/popup-outsideclick)

Let me know what you think

**Comment by mscu** [comment] 2017-02-18 13:24
Im'm currently using @gilhanan's solution which works well, but unfortunately not on mobile devices such as iPhone/iPad - does anybody know how to archive that? the click event doesn't seem to fire on touch devices

**Comment by BlackTr** [comment] 2017-02-18 18:18
@thbt it will be good reason, I've suggested to change on/off triggers separator in
https://github.com/ng-bootstrap/ng-bootstrap/issues/933#issuecomment-269787035

@mscu try this on mobile:
`@HostListener('document:touchend')`
 or 
`@HostListener('document:touchstart')`

**Comment by thbt** [comment] 2017-02-18 18:44
@BlackTr alright I'll put up the PR on monday
@mscu have you tried `document:tap` ?

**Comment by Zemke** [comment] 2017-06-13 07:48
Generally one might also consider to use [`NgbDropdown`](https://ng-bootstrap.github.io/#/components/dropdown) instead which might suit your use case better and supports dismissal by outside click.

**Comment by mamunoza** [comment] 2017-06-21 14:23
`#p="ngbPopover" (document:mouseup)="p.close()"`

This does the trick for me, closing the popover on outside click, and having only one popover at a time.

**Comment by pkozlowski-opensource** [comment] 2017-08-23 16:10
For anyone trying to replicate Bootstrap 4 behaviour as documented here: https://getbootstrap.com/docs/4.0/components/popovers/#dismiss-on-next-click - it is actually super-easy with `triggers="focus:blur"`: http://plnkr.co/edit/ARoho9NWD8Jh82JYADYC?p=preview

Given the above I'm not sure if we should implement more things here... Thoughts / use-cases?

**Comment by spongessuck** [comment] 2017-08-23 16:14
Given that the title of the issue is "Close popover on click outside" and the example closes it whether you click inside or outside the popover, I'm not sure this addresses the issue.

**Comment by devoto13** [comment] 2017-08-23 16:16
Agree with @spongessuck. The main idea of this issue was to implement closing on clicking outside *popover*, not outside *popover trigger* (Bootstrap's behavior). Many users in this issue pointed out that they want to prevent popover closing when clicking inside it. Example use cases are having some inputs inside the popover and let users interact with those.

**Comment by pkozlowski-opensource** [comment] 2017-08-23 16:16
> Given that the title of the issue is "Close popover on click outside" and the example closes it whether you click inside or outside the popover, I'm not sure this addresses the issue.

Valid point. I'm just trying to say to get to the level of what is proposed in Bootstrap is "works out of the box"-easy. But yeh, I guess people are after using popovers as kind of interactive sub-menus...

**Comment by Matmo10** [comment] 2017-08-23 18:11
This issue is referenced on the issues requesting this behavior for clicking outside datepickers. I'm not sure that `triggers="focus:blur"` will work for datepickers, since you can click on them to change the month/year (which should not close the datepicker). Just wanted to raise that point.

**Comment by nwp90** [comment] 2017-09-05 21:38
FWIW - the proposed workaround while we wait for this (using document:click) is totally unusable if you need a lot of potential popovers on a page - if you have a couple of hundred, your click performance degrades far too much to be usable (with Firefox at least).

**Comment by matthiasscudlik** [comment] 2017-09-05 22:05
@nwp90:

it should work if it runs outside of angluar change detection, try this:

```typescript
import { Directive, OnInit, OnDestroy, ElementRef, ComponentRef, ChangeDetectorRef, NgZone, Renderer2 } from '@angular/core';
import { NgbPopover } from '@ng-bootstrap/ng-bootstrap';
import { NgbPopoverWindow } from '@ng-bootstrap/ng-bootstrap/popover/popover';

@Directive({
  selector: '[closePopoverOnOutsideClick][ngbPopover]'
})
export class ClosePopoverOnOutsideClickDirective implements OnInit, OnDestroy {

  listener: () => void;

  constructor(private elementRef: ElementRef, private ngbPopover: NgbPopover,
              private ngZone: NgZone, private cd: ChangeDetectorRef, private renderer: Renderer2) {
  }

  ngOnInit() {
    this.ngZone.runOutsideAngular(() => {
      this.listener = this.renderer.listen('document', 'click', (event) => {
        this.closePopoverOnClickOutside(event);
      });
    });
  }

  ngOnDestroy() {
    this.listener();
  }

  private closePopoverOnClickOutside(event: MouseEvent): void {
    // Popover is open
    if (this.ngbPopover && this.ngbPopover.isOpen()) {
      // Not clicked on self element
      if (!this.elementRef.nativeElement.contains(event.target)) {
        // Hacking typescript to access private member
        const popoverWindowRef: ComponentRef<NgbPopoverWindow> = (this.ngbPopover as any)._windowRef;
        // If clicked outside popover window
        if (!popoverWindowRef.location.nativeElement.contains(event.target)) {
          this.ngbPopover.close();
          this.cd.detectChanges(); // detect changes
        }
      }
    }
  }

}

```

**Comment by bluecaret** [comment] 2017-10-17 22:34
I can't seem to get any of the potential workarounds to function right. I must be missing some instructions.

@matthiasscudlik could you provide all the code needed to make your example work? I'm assuming that block of code I save as a directive in my project, and then do I just add "closePopoverOnOutsideClick" to where I have the button that opens the popup? I feel like I'm missing something.

Thanks! This is very important for us to get working and I can't believe it's not just a standard feature.

**Comment by bluecaret** [comment] 2017-10-17 22:52
Nevermind! I just got this to work by doing the following:

```
  @ViewChild('msPopover') public popover: NgbPopover;

  constructor(private _eref: ElementRef) {}

  onClick(event) {
   if (!this._eref.nativeElement.contains(event.target)) // or some similar check
     this.popover.close();
  }
```

Doing that seems to make the popover close when clicking anywhere outside of the popover and the element that toggled it while still allowing clicks inside to keep the popover open.

**Comment by Matmo10** [comment] 2017-10-17 22:57
Yep, I pretty much did the same thing.

**Comment by matthiasscudlik** [comment] 2017-10-19 09:44
@bluecaret:

usage is like this:

```html
<ng-template #popoverTemplate>
  this is the content of the popover
</ng-template>


<a [ngbPopover]="popoverTemplate" placement="top" closePopoverOnOutsideClick>
  open popover
</a>
```

**Comment by tamtakoe** [comment] 2017-11-02 13:11
This issue is still opened. More then one year. It is incredible! It is one of the most important features, but I see all thread of excuses and temporary decisions like ` #p="ngbPopover" (document:click)="p.close()"` which will not even work with *ngFor-generated elements.

The more I use ng-bootstrap the better I understand that you, guys haven't enough real practice and you make components in abstract vacuum. It is OK that you develop theory of creating Angular components, but I still want to use your components in work.

Please, implement all features, which users need here and implement missing features from ngx-bootstrap, angularStrap etc. libraries. Do it quickly with hardcode, shitcode, bad patterns... it does not matter. After that you will understand what should be the components and can improve your code and API in v. 2.0. Because now you just waste time try to create the ideal not knowing how it should look like

**Comment by armandoxxx** [comment] 2017-11-10 12:35
Just create Popover service (like modal service) and to the logic there ... 
Popover service should hold current open popover and it's trigger to calculate "outside" clicks for closing ... I'm doing this the wrong way by referencing elementRef.nativeElement ...

**Comment by lqclester** [comment] 2018-01-19 08:57
can someone give me a good way to impliment like this https://embed.plnkr.co/plunk/K6WPaM ?-

**Comment by elessariel** [comment] 2018-01-23 12:12
is there any progress to be expected by the team on this in the foreseeable future?

**Comment by VictorCavalcante** [comment] 2018-01-24 12:09
If you're trying to allow one popover at a time (dismissible by clicking outside), you could achieve that by using the last opened popover reference and the @HostListener decorator like this:
```
lastPopoverRef: any;

@HostListener('document:click', ['$event'])
clickOutside(event) {
  // If there's a last element-reference AND the click-event target is outside this element
  if (this.lastPopoverRef && !this.lastPopoverRef._elementRef.nativeElement.contains(event.target)) {
    this.lastPopoverRef.close();
    this.lastPopoverRef = null;
  }
}
  
setCurrentPopoverOpen(popReference) {
  // If there's a last element-reference AND the new reference is different
  if (this.lastPopoverRef && this.lastPopoverRef !== popReference) {
    this.lastPopoverRef.close();
  }
  // Registering new popover ref
  this.lastPopoverRef = popReference; 
}

```
Then, use it like this:
```
<button [ngbPopover]="popoverContent" 
        #popoverRef="ngbPopover" 
        (click)="setCurrentPopoverOpen(popoverRef)">
</button>
```

**Comment by shyamal890** [comment] 2018-02-08 16:31
Wow! More than a year now. Any good enterprise application would need this feature! Someone rightly said forget about figuring out ideal implementation after all the landscape may be completely different 2-3 years down the road.

I believe the 3rd option having `outsideClick` option in the `triggers` is the best way to go about this.

**Comment by ymeine** [comment] 2018-02-08 17:14
@shyamal890 I actually wrote a generic, simple solution which handles all popup widgets and some cases such as nested popups (dropdown in a dialog for instance). I am doing this as part of my job and unfortunately had other tasks to work on in the meantime. What's remaining is the testing part (which needs to be changed completely), and then validation from integrators.

Hopefully I will open the PR next week. Sorry for adding more delay to this.

**Comment by varnastadeus** [comment] 2018-03-27 10:21
https://gist.github.com/varnastadeus/57006117a61f1877b2dc2d18a93fa011

I added a bit modified version of directive which only listens for close events when `popover` is open, and unbind those events on destroy or close. 

usage:
```html
<div>
    handlePopoverClose
    [placement]="['top-right']"
    [ngbPopover]="templateRef"
</div>
```

**Comment by Eliyar** [comment] 2018-04-13 03:40
Thanks @varnastadeus !

**Comment by bacancy-daxil** [comment] 2018-07-03 13:14
@varnastadeus you saved my day!

**Comment by hosseinGanjyar** [comment] 2018-07-17 09:51
hey @spongessuck ...Thanks...Your solution was wonderful.

**Comment by pkozlowski-opensource** [comment] 2018-07-27 09:41
For anyone tracking this issue: we've got a PR in-flight (#2554) that will bring native support for closing on outside clicks. It should land as part of the next feature release (early next week).

**Comment by spongessuck** [comment] 2018-07-27 21:03
https://www.youtube.com/watch?v=_J6-3l3hCm0

**Closed** 2018-08-03 08:42 UTC
Labels: component: popover, component: tooltip, type: feature

**Comment by davutg** [comment] 2020-08-24 15:59
For me default property works if I go for default change detection strategy
`changeDetection: ChangeDetectionStrategy.Default,`

But not if I go for OnPush
`changeDetection: ChangeDetectionStrategy.OnPush`
