### ISSUE TITLE
Cannot run gulp build:demo on MAC/Linux

### ISSUE THREAD

**Issue by masaanli** [ng-bootstrap/ng-bootstrap#1396] opened 2017-03-22 18:08 UTC
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
when running `gulp build:demo` i got this error ONLY ON MAC (on WINDOWS it's working) Tested on 3 MAC's. Got the problem with npm and yarn.
```
       Field 'browser' doesn't contain a valid alias configuration
        /repos/eb-components/$$_gendir/demo/src/app/app.module.ngfactory.html doesn't exist
[19:05:13] 'build:demo' errored after 4.52 s
[19:05:13] Error: Command `webpack --config webpack.demo.js --progress --profile --bail` failed with exit code 1
    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:513:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
bash-3.2$
```

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
2.3.3 / 2.4.5

ng-bootstrap:
alpha 20

Bootstrap:
alpha 6

**Comment by pkozlowski-opensource** [comment] 2017-03-22 22:38
I'm sorry but the only thing that I can say is that it "works for me" on both Linux and OSX (actually I'm using both OSes). Without having access to your environment it is impossible to say what is wrong on the systems that you are using. I'm afraid that you are best positioned to debug those issues as you are in front of your setup.

The only advice I can give is to do fresh npm install after pulling the latest master.

I'm going to close this one since I can't reproduce locally on 2 different systems and I can't see how we could help debugging the issue you are facing... If you dig into it and find that there is sth wrong with our setup please let us know. Good luck!

**Closed by pkozlowski-opensource** 2017-03-22 22:38 UTC
