### ISSUE TITLE
showing braces in form

### ISSUE THREAD

**Issue by jaswanth1998** [ng-bootstrap/ng-bootstrap#2969] opened 2019-01-16 06:35 UTC
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Link to minimally-working StackBlitz that reproduces the issue:

You can fork a StackBlitz from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.

Please note that we can _not_ act on bug reports without a _minimal_ reproduction scenario in a StackBlitz. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular:

ng-bootstrap:

Bootstrap:

**Comment by jaswanth1998** [comment] 2019-01-16 06:39
![erroe](https://user-images.githubusercontent.com/25882988/51230884-88eca400-1987-11e9-95df-5ba38c651f5e.png)
i am getting this type braces while using the rating can any solve this problem

**Comment by jaswanth1998** [comment] 2019-01-16 06:46
![erroe](https://user-images.githubusercontent.com/25882988/51231144-79ba2600-1988-11e9-85e3-289dc80f2c3f.png)

i am getting these braces while i am using rating can any one tell why it is forming

**Comment by benouat** [comment] 2019-01-16 09:58
Hi @jaswanth1998,

I have no idea how this could happen, but it seems you see some screen readers dedicated html code which is meant to be hidden.

https://github.com/ng-bootstrap/ng-bootstrap/blob/c37a8038cb34e1e8bc9fac9cfb3a001ed94df6fd/src/rating/rating.ts#L60-L67

What you see is the `<span class="sr-only">` which is a Bootstrap CSS class used for screen readers. (sr-only stands for screenreader-only)

Nonetheless, the bug is probably on your side, not our's. So I will close this issue. All our examples are working fine.

Did you tweak this CSS class yourself ? maybe modified it so that it's displayed ?

**Closed by benouat** 2019-01-16 09:58 UTC

**Comment by benouat** [comment] 2019-01-16 10:39
You could also double-check that you properly imported bootstrap css file 👍 It might be the cause.
