### ISSUE TITLE
Input field date format display

### ISSUE THREAD

**Issue by faisalloe** [ng-bootstrap/ng-bootstrap#1056] opened 2016-11-17 16:13 UTC
How can i format the date displayed in input box as mm/dd/yyyy

```
<form class="form-inline">
  <div class="form-group">
    <div class="input-group">
      <input class="form-control" placeholder="yyyy-mm-dd" name="dp" [(ngModel)]="model" ngbDatepicker #d="ngbDatepicker">
      <div class="input-group-addon" (click)="d.toggle()" >
        <img src="img/calendar-icon.svg" style="width: 1.2rem; height: 1rem; cursor: pointer;"/>
      </div>
    </div>
  </div>
</form>

```

**Comment by pkozlowski-opensource** [comment] 2016-11-18 17:44
Duplicate of #754

**Closed by pkozlowski-opensource** 2016-11-18 17:44 UTC
