### ISSUE TITLE
[Bug] Timepicker displays invalid time.

### ISSUE THREAD

**Issue by ZloyChert** [ng-bootstrap/ng-bootstrap#1927] opened 2017-11-01 12:44 UTC
### Bug description:
After focusing some field and entering value that is out of valid range, timepicker convert it to valid time by removing surplus and incrementing previous value. But the next time you enter invalid value, timepicker doesn't convert it to normal value.
Example:
1)Timepicker has folowing value: 13:30
2)Enter 97 to minutes (to have 13:97)
3)After focusing out you will see 14:37
4)Enter 97 to minutes again. (14:97)
5)After focusing out you will see 15:97
![timepicker](https://user-images.githubusercontent.com/17516013/32275231-7f31bef4-bf1b-11e7-9c86-2bad2bde110d.PNG)
### Version of Angular, ng-bootstrap, and Bootstrap:
Angular: 4.2.3
ng-bootstrap: 1.0.0-beta.5
bootstrap: 4.0.0-alpha.6

**Comment by ZloyChert** [comment] 2017-11-02 10:55
Investigating source code of timepicker I found something, that causes this problem
![image](https://user-images.githubusercontent.com/17516013/32322219-ce3d512a-bfd4-11e7-912c-5a62dbaa554e.png)
Input value is formatted before being sent, so, if we have six hours (ex: 06:15) and then change value on thirty (30:15), it is formatted immediately and for input value doesn't change

**Comment by pkozlowski-opensource** [comment] 2017-11-02 14:08
I believe that this is a duplicate of #1644

**Closed by pkozlowski-opensource** 2017-11-02 14:08 UTC
