### ISSUE TITLE
add class to ngb-tabset

### ISSUE THREAD

**Issue by psenechal** [ng-bootstrap/ng-bootstrap#1877] opened 2017-09-28 20:43 UTC
Angular: 4.4.3
ng-bootstrap: 1.0.0-beta.5
Bootstrap: 4.0.0-beta

I couldn't seem to find if this had been asked before or if it was possible. I'd like to be able to a custom class to the <ul> tag generated by ngb-tabset. Using ng-template seems to only be available at the tab title and tab content level.

Would this be possible to add as a feature request? Perhaps allowing [ngClass] on the <ngb-tabset>?

If there is a work-around for this other than declaring a parent class around <ngb-tabset> and moving the styling to a <ul> child of that parent class, please let me know.

Thanks!

**Comment by pkozlowski-opensource** [comment] 2017-09-28 20:45
This is a duplicate of the existing issue #1436

**Closed by pkozlowski-opensource** 2017-09-28 20:45 UTC

**Comment by psenechal** [comment] 2017-09-28 20:50
I thought that #1436 was for adding a class to the li tag, not the ul tag. If both scenarios are covered by this, great. Thanks.
