### ISSUE TITLE
Accordion Issue

### ISSUE THREAD

**Issue by radhikachitkara** [ng-bootstrap/ng-bootstrap#4459] opened 2023-01-06 07:26 UTC
Hi Team,

We are facing similar issue in our application where 2 roles are announced for accordions 'button' and 'tab', role tab is automatically getting added to HTML.

<img width="622" alt="SS" src="https://user-images.githubusercontent.com/119498590/209281483-00832b5c-733e-4733-b476-33cac34584e0.PNG">

HTML structure:

````
<ngb-accordion` #accordion="ngbAccordion" [activeIds]="activeId" (panelChange)="togglePanel($event)">
    <ngb-panel [id]="'p' + i" cardClass="expansion-panel">
      <ng-template ngbPanelHeader>
        <div [attr.aria-expanded]="openById['p' + i] ? true : false"
          (keyup.enter)="accordion.toggle('p' + i)" (click)="accordion.toggle('p' + i)"
          class="header-sleeve focus-visibility" [ngClass]="{ expanded: openById['p' + i] }" role="button">
          <div class="header-text d-flex justify-content-between">
            <div>Spend</div>
            <div class="m-r-20">$1100</div>
          </div>
          <div class="header-controls">
            <i *ngIf="openById['p' + i]" class="fal fa-chevron-up" aria-hidden="true"></i>
            <i *ngIf="!openById['p' + i]" class="fal fa-chevron-down" aria-hidden="true"></i>
          </div>
        </div>
        <p class="sm">Spend decs</p>
      </ng-template>
      <ng-template ngbPanelContent>
        <div class="row">
          <ng-container>
            <div class="col-8">
              <p> Plan1</p>
            </div>
            <div class="col-3 text-right">
              <p>$1100</p>
            </div>
          </ng-container>
        </div>
      </ng-template>
    </ngb-panel>
</ngb-accordion>
```

_Originally posted by @radhikachitkara in https://github.com/ng-bootstrap/ng-bootstrap/issues/2927#issuecomment-1363652763_

**Comment by maxokorokov** [comment] 2023-01-09 14:04
Looks like a duplicate of #4275

Also see #3898

**Closed by maxokorokov** 2023-01-09 14:04 UTC
