### ISSUE TITLE
ngDatepicker shows year 2009 instead of 2019 and Jan instead of October

### ISSUE THREAD

**Issue by sajidit** [ng-bootstrap/ng-bootstrap#3413] opened 2019-10-16 09:53 UTC
Calendar is not showing the today date or selected date when opened.

![Image 16-10-2562 BE at 16 49](https://user-images.githubusercontent.com/3327390/66908477-574b5b00-f035-11e9-963a-82f146de9b19.jpg)

I'm using following environment

Angular:
    "@angular/animations": "~8.2.11",
    "@angular/common": "~8.2.11",
    "@angular/compiler": "~8.2.11",
    "@angular/core": "~8.2.11",

ng-bootstrap:
  "@ng-bootstrap/ng-bootstrap": "^5.1.1"

Bootstrap:
  "bootstrap": "^4.3.1",

**Comment by peterblazejewicz** [comment] 2019-10-16 21:41
@sajidit I cannot see the issue, can you please create a stackblitz sample of your code snippet using stackblitz snippets from the docs?
https://ng-bootstrap.github.io/#/components/datepicker/examples
Thanks!

**Comment by sajidit** [comment] 2019-10-17 01:37
@peterblazejewicz I realized the issue was related to the 
  "angularCompilerOptions": {
    "enableIvy": true
  }
After removing it was working fine!!!

I think this issue can be closed as ivy is not stable in angular version 8 probably.

Thanks :)

**Comment by maxokorokov** [comment] 2019-10-17 13:55
@sajidit we don't support ivy yet, but it will be coming soon.

Will close as duplicate of #3257

**Closed by maxokorokov** 2019-10-17 13:55 UTC
Labels: component: datepicker, ivy, resolution: duplicate
