### ISSUE TITLE
Typeahead window should be themable

### ISSUE THREAD

**Issue by MickL** [ng-bootstrap/ng-bootstrap#2182] opened 2018-02-21 13:24 UTC
The surround of each button(ngb-typeahead-window) should be themable, too. 

Usecase: I got a more complex search result which i can display nicely with `resultTemplate`. Now I want to add label at the very top but i can't change the template of the surrounding.

**Comment by maxokorokov** [comment] 2018-02-22 15:24
Duplicate of #1619

**Closed by maxokorokov** 2018-02-22 15:24 UTC
Labels: component: typeahead, resolution: duplicate
