### ISSUE TITLE
icon in ngbPanelTitle 

### ISSUE THREAD

**Issue by sh977218** [ng-bootstrap/ng-bootstrap#1672] opened 2017-07-10 15:48 UTC
How can I put a icon <i>   in the ngbPanelTitle but not in <a>.

I want the icon to be click that does something differently than the <a> click event.

**Comment by pkozlowski-opensource** [comment] 2017-07-10 15:49
Duplicate of #465

**Closed by pkozlowski-opensource** 2017-07-10 15:49 UTC
