### ISSUE TITLE
Topmost modal to overlay any other modals

### ISSUE THREAD

**Issue by MrQwert** [ng-bootstrap/ng-bootstrap#2016] opened 2017-12-06 15:05 UTC
### Proposal description:

Sometimes it's required to show multiple modals at the same time and modal stack doesn't solve the task.

When two modals are shown the backdrop of the top one doesn't cover the body of bottom one.

What I try to reach is one modal and it's backdrop fully covering all other modals.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.4.0

ng-bootstrap: 1.9.1

Bootstrap: 4.0.0-beta

**Comment by pkozlowski-opensource** [comment] 2017-12-06 15:32
Duplicate of #643

**Closed by pkozlowski-opensource** 2017-12-06 15:32 UTC
