### ISSUE TITLE
Modal: backdrop closes modal on mouseup

### ISSUE THREAD

**Issue by crtl** [ng-bootstrap/ng-bootstrap#3405] opened 2019-10-07 12:35 UTC
### Bug description:
In a modal which has `backdrop: true` outside click release will close the modal.
For example:
When selecting/marking  the contents of an `input` using your cursor and moving it out of the modal, releasing the mousebutton (`mouseup`?) causes the modal to close.

### Link to minimally-working StackBlitz that reproduces the issue:

```
//Modal component
@Component({
    template: `
        <div class="modal-header">
            Header
        </div>
        <div class="modal-body" style="padding: 30px">
            Body
            <form>
                <input style="width: 100%">
            </form>
        </div> 
    `,
    selector: "test-modal"
})
export class TestModalComponent {

}
```

```
// calling component
ngOnInit() {

    this.modal.open(TestModalComponent, {
        size: "sm"
    })

}
```

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.2.5

ng-bootstrap: 5.1.1

Bootstrap: 4.3.1

**Comment by pkozlowski-opensource** [comment] 2019-10-07 15:40
This is a duplicate of the existing issue #1950

**Closed by pkozlowski-opensource** 2019-10-07 15:40 UTC
