### ISSUE TITLE
tabindex on timepicker

### ISSUE THREAD

**Issue by MeMeMax** [ng-bootstrap/ng-bootstrap#2583] opened 2018-08-08 06:24 UTC
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
Can´t set the tabindex for timepicker components. When I have a form and want to go to the next control via tab I have to tab several times to get into the input field of the timepicker.

### Link to minimally-working plunker that reproduces the issue:

https://ng-bootstrap.github.io/#/components/timepicker/examples

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6.1.0

ng-bootstrap: 2.2.0

Bootstrap: 4.1.1

**Comment by maxokorokov** [comment] 2018-08-08 10:07
Duplicate of #1836

**Closed by maxokorokov** 2018-08-08 10:07 UTC
Labels: component: timepicker, resolution: duplicate

**Comment by MeMeMax** [comment] 2018-08-08 10:35
It´s open since 2017 and not fixed yet? It sounds to me like an easy change...

**Comment by mateusduraes** [comment] 2018-08-24 13:05
Well, i didn't find a solution for this problem.

So, i have create a workaround that works in my case, and may be usefull for another person.

I used javascript to select the inputs inside ngb-timepicker and add tabindex dynamically.

```typescript
const container: HTMLElement = document.querySelector('.timepicker-container');
const inputElements: HTMLCollection = container.getElementsByTagName('input') as any;
Array.from(inputElements).forEach((input, index) => {
  input.setAttribute('tabindex', `${index + 1}`);
});
```


```html
<div class="row timepicker-container">
  <div class="col center-col">
    <p class="text-center"> Início </p>
      <ngb-timepicker [(ngModel)]="startTime"></ngb-timepicker>
   </div>
   <div class="col center-col">
     <p class="text-center"> Término </p>
     <ngb-timepicker [(ngModel)]="endTime"></ngb-timepicker>
   </div>
</div>
```
