### ISSUE TITLE
'undefined' set when popup not opened from input event

### ISSUE THREAD

**Issue by matjazonline** [ng-bootstrap/ng-bootstrap#1243] opened 2017-01-23 14:09 UTC

**Comment by pkozlowski-opensource** [comment] 2017-01-23 14:34
Thnx for reporting. Marking it as "needs investigation" since it is essentially the same use-case as in #698 (starting search from sth else than user input). We definitively need to support this properly / easily.

**Comment by pkozlowski-opensource** [comment] 2017-04-04 19:34
I'm going to go ahead and close is as a duplicate of #698 since we need a proper solution here.

**Closed by pkozlowski-opensource** 2017-04-04 19:34 UTC
Labels: component: typeahead, needs: investigation
