### ISSUE TITLE
Datepicker - can't set accepted format to dd.mm.yyyy 

### ISSUE THREAD

**Issue by simciskotomas** [ng-bootstrap/ng-bootstrap#1206] opened 2017-01-10 10:54 UTC
Hi

I know that this is not support page, I was looking for the solution but I haven't found any possible solution. 
I need to set date format that will be accepted by datepicker from **yyyy-mm-dd** to **dd.mm.yyyy**
I am just able to change placeholder.

Is this possibility missing or should I try better?

Thaks

**Comment by pkozlowski-opensource** [comment] 2017-01-10 12:06
Duplicate of #754

**Closed by pkozlowski-opensource** 2017-01-10 12:06 UTC
