### ISSUE TITLE
Modal backdrop doesn't fade in

### ISSUE THREAD

**Issue by tbickley-mediabowl** [ng-bootstrap/ng-bootstrap#2993] opened 2019-01-31 16:16 UTC
### Bug description:

When opening a modal, the backdrop should fade in (as per the example in the Bootstrap docs: https://getbootstrap.com/docs/4.0/components/modal/#live-demo), however it just appears immediately.

From looking at the code, Bootstrap creates its backdrop with the 'modal-backdrop' and 'fade' classes, adds it to the DOM, and then adds the 'show' class, whereas in ng-bootstrap the backdrop is created with all three classes already on it.

### Link to minimally-working StackBlitz that reproduces the issue:

https://ng-bootstrap.github.io/app/components/modal/demos/basic/stackblitz.html (this is the one from the documentation for the modal component: https://ng-bootstrap.github.io/#/components/modal/examples)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.0.0

ng-bootstrap: 4.0.2

Bootstrap: 4

**Comment by benouat** [comment] 2019-02-01 08:06
Hello @tbickley-mediabowl, unfortunately we don't support yet animations. None of them 😞
We are working on it (you can search issues like #295 and PR's about that such as  #2817 for example.

Sorry about that.
Closing for now as duplicate of other issues related to that topic.

**Closed by benouat** 2019-02-01 08:06 UTC
Labels: component: modal, resolution: duplicate, type: animate
