### ISSUE TITLE
NgbPopover doesn't display up-to-date title as title gets changed before .open()

### ISSUE THREAD

**Issue by subliminalvoice** [ng-bootstrap/ng-bootstrap#1156] opened 2016-12-22 14:37 UTC
### Bug description:

Having a title property binding (`[popoverTitle]="title"`), as you change this.title just before running NgbPopover.open() the opened popover contains the old value of this.title as a title. Closing and opening the popover then updates the title to the value of this.title.

**Expected behaviour:**
this.title gets changed before the .open() method is called, the opening popover was expected to contain the new title.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/ZpJ6VanN9kB2KZZ1VDv4

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.0.0

ng-bootstrap: 1.0.0-alpha.15

Bootstrap: v4.0.0-alpha.5

**Comment by tjaartvanderWalt** [comment] 2016-12-23 12:15
This is not related to the popover directive itself, it seems like this is the default behavior of the `@Directive` decorator in angular.

It seems that the binding to `@Input() title` only updates after the `this.p.open()` method is called.

Please see example [plunker ](http://plnkr.co/edit/DAw0si9PjI3HGQmG4mXW?p=preview)where the issue is replicated using a simple custom directive.

To overcome the issue you can set the popoverTitle by going `this.p.popoverTitle="New Title"` instead of `this.title="New Title"`.

Maybe someone else knows of a way to force the binding update before the `this.p.open()` is called.

**Comment by readme42** [comment] 2016-12-23 13:17
@tjaartvanderWalt thanks for your explanation and the workaroud. Works like a charm.

**Comment by pkozlowski-opensource** [comment] 2016-12-23 15:50
@tjaartvanderWalt is completely right here - the "issue" seems to be more with how Angular works and is not specific to this project. Closing as a support request.

**Comment by pkozlowski-opensource** [comment] 2016-12-23 15:51
Thnx @tjaartvanderWalt for helping out with the issues, much appreciated!

**Closed by pkozlowski-opensource** 2016-12-23 15:50 UTC
Labels: component: popover, needs: investigation

**Comment by bradley-dotnet** [comment] 2017-12-16 20:26
@tjaartvanderWalt  You can also do a setTimeout on the open so change detection runs before `open`. That being said; this could be fixed by doing a binding in the popover instead of manually changing the title; or handling onChanges and setting it there.

In other words; this *is* a bug; not just how Angular works.
