### ISSUE TITLE
Using Bootswatch - bootstrap themes  [feature request]

### ISSUE THREAD

**Issue by bleuscyther** [ng-bootstrap/ng-bootstrap#2557] opened 2018-07-29 03:06 UTC
Angular: 6.0.0

ng-bootstrap: 3.0.0

Bootstrap: 4.0.0

Hi guys, I like the fact that i dont need to modify many files in order to add this to angular. Good job!.

I have a relatively small feature request to allow other bootstrap themes like Bootswatch,

Normally i would include [BootSwatch ](https://bootswatch.com/)in the `style.scss` like [this](https://www.npmjs.com/package/bootswatch#via-sass-imports):

``` scss
@import "~bootswatch/dist/materia/variables";
@import "~bootstrap/scss/bootstrap.scss";
@import "~bootswatch/dist/materia/bootswatch";
```
**materia** is on of the bootswatch theme/

This assumes that i am using *scss* format. 

in ng-boostrap Because the *bootstrap.css* is automatically added to the app configuration ( schematics>ng-add>addBootstrapCSS) the recommended way to import Bootswatch is overwritten by *ng-bootstrap*.

I can add the code snippet in the main component  ( one layer under app.component) and it works.

I would suggest however a configuration option where  *ng-bootstrap* would include the bootswatch  .css instead: 

``` typescript
import {NgbModule} from '@ng-bootstrap/ng-bootstrap';

@NgModule({
  ...
  imports: [
     NgbModule.forRoot({ 
       bootswatch: 'cerulan' 
     }),
 ...],
  ...
})
export class YourAppModule {
}
```
So, if bootswatch is defined, it will use `./node_modules/bootswatch/dist/cerulan/bootstrap.min.css`,

``` javascript
function addBootstrapCSS(bootswatch_theme) {
    return (host) => {
        let url = bootswatch_theme? 
                      `./node_modules/bootswatch/dist/${bootswatch_theme}/bootstrap.min.css`  : 
                      './node_modules/bootstrap/dist/css/bootstrap.css';

        config_1.addStyle(host, url);
        return host;
    };
}

```

this is my first time going into these codes :) i don' t know if this is possible.

**Comment by pkozlowski-opensource** [comment] 2018-07-30 08:38
We are going to have a config option to use `scss` instead of `css` - it is being tracked here: https://github.com/ng-bootstrap/schematics/issues/2

Closing as a duplicate of https://github.com/ng-bootstrap/schematics/issues/2 - feel free to add more info in there if needed.

**Closed by pkozlowski-opensource** 2018-07-30 08:38 UTC
