### ISSUE TITLE
ngbDropdown doesn't work correctly inside navbar

### ISSUE THREAD

**Issue by Christodnb** [ng-bootstrap/ng-bootstrap#3296] opened 2019-07-17 08:30 UTC
### Bug description:
Hey Greetings. I'm using ngbDropdown inside navbar, but transform style is not applied.
I'm using  placement="bottom-right". This works outside the navbar, but not inside.
It was working before i updated angular (7 -> 8). If it can be fixed, i'd appreciate it, ty : )

![image](https://user-images.githubusercontent.com/37846579/61360197-8f2ee080-a843-11e9-8ca8-eec849d9094e.png)

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-k7tvyi

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.1.1

ng-bootstrap: 5.0.0

Bootstrap: 4.3.1

**Comment by fbasso** [comment] 2019-07-17 08:51
This is a duplicate of #3269. 

A the moment you can use display="dynamic" on the dropdown to retrieve the previous behavior. This change has been done because of #3030, so you need to know that your design will not behave as Bootstrap on small devices.

Dropdown positionng in navbar will be clarified in the next release with #3268

**Comment by fbasso** [comment] 2019-07-17 13:32
Closing as duplicate

**Closed by fbasso** 2019-07-17 13:32 UTC
Labels: resolution: duplicate
