### ISSUE TITLE
ngb-tabset no longer stacks (not responsive) on small widths. 

### ISSUE THREAD

**Issue by robgorman** [ng-bootstrap/ng-bootstrap#1302] opened 2017-02-08 16:32 UTC
### Bug description:

Ngb-tabset no longer stacks on small width windows. 

### Link to minimally-working plunker that reproduces the issue:

Plunker that illustrates the issue  [here](http://plnkr.co/edit/bASTGZ1FOW4IeWuRcM27) . Plunker forked directly from the current angular samples docs. 

Stacking behavior of tabs used to work perfectly. But in some recent release, or due to a dependency release, I am not sure which, tab stacking stopped working. 

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.3.1 (router 3.3.1)

ng-bootstrap: 1.0.0 alpha 20

Bootstrap: 4.0.0 alpha 6

**Comment by pkozlowski-opensource** [comment] 2017-03-03 16:32
This seem to be linked to a change between Bootstrap alpha.5 and alpha.6 and not something we can fix in this project. You can confirm that the issue is on the CSS side by looking at [this plunk](http://plnkr.co/edit/ONwIEyo90A7vvarwrsvJ?p=preview) and observing that:
* pure Bootstrap 4 example doesn't stack either;
* going back to Bootstrap alpha.5 makes tabs stack

Going to close it here as Bootstrap 4 - please open a relevant issue directly in the Bootstrap repository.

**Closed by pkozlowski-opensource** 2017-03-03 16:32 UTC
Labels: component: tab, needs: investigation

**Comment by jesben** [comment] 2017-06-12 06:56
Add this: "flex-column flex-md-row" to make it stack again

`<ul class="nav nav-tabs flex-column flex-md-row" role="tablist">`

**Comment by dannyhchan** [comment] 2017-06-15 20:11
Jesben, how did you inject the classes in the UL?  Do you have a code sample?

Thanks,

**Comment by jesben** [comment] 2017-06-18 11:28
dannyhchan, I just created an pull request: [Link](https://github.com/ng-bootstrap/ng-bootstrap/pull/1621)

For my prod. build right now, I added it in:
node_modules\@ng-bootstrap\ng-bootstrap\tabset\tabset.js

Before: (line 113)
[class]=\"'nav nav-' + type + '  justify-content-' + justify\"

After: (line 113)
[class]=\"'nav nav-' + type + ' flex-column flex-md-row justify-content-' + justify\"

**Comment by dannyhchan** [comment] 2017-06-18 11:41
Thank you.

**Comment by geetee24** [comment] 2017-06-20 03:11
Hummmm....  If I have say 20 tabs (as a poor example), the tabs do not turn into multi rows of tabs. Instead they flow off the screen on one line of tabs.   I added the flex-column flex-md-row  but it did not do it.

Is there a way to affect this behavior?

**Comment by rakesh4u51** [comment] 2017-07-10 14:27
Hi i am also facing same problem i have changed like above solution but not working any solution help me

**Comment by jesben** [comment] 2017-07-10 19:24
Hi 

You right, I was too fast. What about this, not the nicest, but I think it works?

Before: (line 113)
`<ul [class]=\"'nav nav-' + type + ' justify-content-' + justify\" role=\"tablist\">\n      <li class=\"nav-item\" *ngFor=\"let tab of tabs\">\n`

After: (line 113)
`<ul [class]=\"'nav nav-' + type + ' d-md-inline-block flex-column flex-md-row justify-content-' + justify\" role=\"tablist\">\n      <li class=\"nav-item float-md-left\" *ngFor=\"let tab of tabs\">\n`

CSS class:
```
@media (min-width: 768px) {
  .d-md-inline-block {
    width: 100%;
    display: inline-block !important;
  }
}
```

**Comment by jesben** [comment] 2017-07-10 19:36
Better solution:
`<ul [class]=\"'nav nav-' + type + ' d-inline-block w-100 flex-column flex-row justify-content-' + justify\" role=\"tablist\">\n      <li class=\"nav-item float-sm-left\" *ngFor=\"let tab of tabs\">\n`

**Comment by bvandenbon** [comment] 2017-07-20 13:04
It would be convenient if there was an easy way to inject custom classes/styles. e.g. something like 
`` <ngb-tabset **inject-class="flex-col flex-md-row**">...</ngb-tabset>
