### ISSUE TITLE
Datepicker format

### ISSUE THREAD

**Issue by andreas-aeschlimann** [ng-bootstrap/ng-bootstrap#1172] opened 2017-01-03 15:59 UTC
I would like to suggest a custom format for the date in an input field when using the NgbDatepicker. This seems to be an important feature especially for people of countries who are used to the reverse format of the standard "datetime".

An option like

`<input ... [format]="dd.mm.yyyy" ... >`

would probably already suffice most use cases.

Sorry in case this has already been posted. Thanks!

**Comment by pkozlowski-opensource** [comment] 2017-01-05 09:33
This is duplicate of #754 - more details in https://github.com/ng-bootstrap/ng-bootstrap/issues/754#issuecomment-247767027

**Closed by pkozlowski-opensource** 2017-01-05 09:33 UTC
