### ISSUE TITLE
Tabs don't have same activeId and nextId after navigating pages

### ISSUE THREAD

**Issue by paradox37** [ng-bootstrap/ng-bootstrap#1075] opened 2016-11-22 13:18 UTC
I think that title is self-explanatory.

I have three tabs on one page. If I navigate with the menu to some other page, then press back in browser, tabs do not have same id's. They are incremented.

So instead of ngb-tab-0, ngb-tab-1, ngb-tab-2, I get ngb-tab-3, ngb-tab-4, ngb-tab-5.

This is problematic, because I have IF condition based on nextId.

**Comment by pkozlowski-opensource** [comment] 2016-11-22 13:31
Yes, auto-generated IDs won't survive component destruction / re-creation. This is by design and we don't have much technical means of changing it (changes here would require some kind of persistent store to dump and restore component's state and this is not something we want to do in this library).

If you want to have consistent / fixed IDs just don't use the auto-generated ones an provide IDs that make sense in your context:

```html
<ngb-tabset>
  <ngb-tab title="Simple" id="myFixedId">
    <template ngbTabContent>
      <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth
      master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh
      dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum
      iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</p>
    </template>
  </ngb-tab>
</ngb-tabset>
```

Going to close this one as you've got already means of having ids that don't change and we don't want to persist auto-generated IDs.

**Closed by pkozlowski-opensource** 2016-11-22 13:31 UTC
