### ISSUE TITLE
Datepicker does not close when input to open has focus

### ISSUE THREAD

**Issue by Zwergenpunk** [ng-bootstrap/ng-bootstrap#3583] opened 2020-02-11 13:07 UTC
# Bug description:

When an input element has an ngbDatepicker as directive and the datepicker opens on (focus), a select click does not close the popover.
That last working versions is 5.1.1.

You can fix it if you change (focus) to (click), but still it should not be that way.

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-cmwpeh?file=src%2Fapp%2Fapp.component.html

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.2.14

ng-bootstrap: 5.2.2

Bootstrap: 4.1.1

**Comment by maxokorokov** [comment] 2020-02-12 09:30
@Zwergenpunk PTAL at #3483 

Here is how you could restore the behavior in `5.2.x` → https://stackblitz.com/edit/angular-useeq4?file=src/app/app.component.html

However, it becomes tricky with `(focus)` to restore focus correctly after the datepicker closure...

I'll close this one as a duplicate of #3843, please reopen if necessary though

**Closed by maxokorokov** 2020-02-12 09:30 UTC
Labels: component: datepicker, resolution: duplicate, resolution: support
