### ISSUE TITLE
NgbCarousel with ngFor and dynamic ids

### ISSUE THREAD

**Issue by ronaldofs89** [ng-bootstrap/ng-bootstrap#1397] opened 2017-03-22 22:47 UTC
### Bug description:

I have a component that I made using NgbCarousel with ngFor, but when I add a dynamic "id" the following error occurs: 
 - "EXCEPTION: Cannot read property 'id' of undefined" or
 - "ORIGINAL EXCEPTION: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'".

Also doesn't work using index or tow way bind.

### Link to plunker:

https://plnkr.co/edit/IMmIP6Tymn1yAcpSWuek

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.4.2

ng-bootstrap: 1.0.0-alpha.16

Bootstrap:  v4.0.0-alpha.5

**Comment by jnizet** [comment] 2017-03-22 23:02
The syntax of NgFor, when used on a template, is different from the usual `*ngFor` syntax. You need to wrap your template with the ngbSlide attribute into another template using this alternate syntax. Or easier, wrap it into an `<ng-container>` which can use the usual syntax:

    <ng-container *ngFor="let slide of slides">
      <template ngbSlide [id]="slide.id">
        ...

See https://plnkr.co/edit/LwkNbXzgPGwE9IKT6Prp?p=preview

**Comment by ronaldofs89** [comment] 2017-03-23 01:54
But still the problem remains. The console accuses: "EXCEPTION: Cannot read property 'id' of undefined"

**Comment by pkozlowski-opensource** [comment] 2017-03-23 09:16
I can confirm that sth funky is going on here - for some reason getNextSlide is called 2x in rapid successions and on the second call the slides query is empty! For now it looks like a bug in the Angular itself but this issue needs more investigation.

**Comment by ronaldofs89** [comment] 2017-03-23 19:24
So, there is another way to use the method "select"?

**Comment by pkozlowski-opensource** [comment] 2017-03-25 14:17
OK, I can see what is going on - in fact things work as expected - it is just a user's error caused by the unclosed `<ngb-carousel>` tag in a template. Here is a fixed markup that shows perfectly working carousel: http://plnkr.co/edit/dqArOmxQYslmbxsPpWFM?p=preview (also demonstrates proper ngFor syntax for dynamic slides).

Closing as a support request.

**Closed by pkozlowski-opensource** 2017-03-25 14:17 UTC
Labels: component: carousel, needs: investigation, type: bug

**Comment by kelyane** [comment] 2018-02-28 23:27
I am having this same problem, even using the last plunker that worked for angular2/4, but in newest versions are not.
@ng-bootstrap/ng-bootstrap : 1.0.0
Angular: 5.0.1
bootstrap: 4.0.0

**Comment by shivroy121** [comment] 2019-03-26 09:24
This is how i used and it is working fine


<ngb-carousel   class="carousel slide col-md-12" data-ride="carousel" id="myCarousel">
             
			  
				   <ng-template  ngbSlide id={{i}} *ngFor="let newsgroupItem of newsItems | count let i=index" >
		 				 
				  </ng-template>
				   
             </ngb-carousel>

**Comment by mokshadev** [comment] 2020-02-16 23:12
Hi
I am current doing a project based on carousel
I want to display each row of data from mysql database on different slide.
And increase slides dynamically in case a new row of data has been added to the database.
Anyone know how to do this?

Thanks <3

**Comment by hamleet** [comment] 2020-04-27 08:45
Seems like a memory leak with @ViewChild
You are looking for
https://stackoverflow.com/questions/54274954/how-to-get-index-image-in-ng-bootstrap-carousel
use [id] to bind your index selector
etc
in component **html**
**[id]="'slideId_' + i"**
in component **ts**
**const itemIndex = parseInt(slideEvent.current.replace("slideId_", ""), 10);**
