### ISSUE TITLE
Firefox freezes when datepicker and ag-grid is on one page

### ISSUE THREAD

**Issue by MeMeMax** [ng-bootstrap/ng-bootstrap#2522] opened 2018-07-12 11:27 UTC
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
Hi, we are using ng-bootstrap together with ag-grid. Unfortunately the whole browsertab (only Mozilla Firefox) freezes if you want to open a datepicker which is on the same site as a ag-grid. Is this a known problem? I couldn´t find anything about it.

### Link to minimally-working plunker that reproduces the issue:

https://stackblitz.com/edit/angular-cdrx9w

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6.0.8

ng-bootstrap: 2.2.0

Bootstrap: 4.1.0

ag-grid: 18.1.1/18.0.1

**Comment by MeMeMax** [comment] 2018-07-12 13:30
Maybe this is even an issue with ag-grid. There are some open issues on this:
https://github.com/ag-grid/ag-grid/issues/2463

**Comment by maxokorokov** [comment] 2018-07-12 13:36
Observations:
- looks like if you remove `[gridAutoHeight]="true"` it works
- if you we remove positioning it works as well: [here](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/datepicker/datepicker-input.ts#L196-L202)

anyway it's like position change triggers something in ag-grid, that triggers position change, etc.

@pkozlowski-opensource, this will not fix the issue, but shouldn't we do positioning ONLY when the popup is open and attached to body?

**Comment by maxokorokov** [comment] 2018-07-12 13:39
Also seems similar to #1250

**Comment by MeMeMax** [comment] 2018-07-12 13:40
For me it doesn´t work, if I remove `[gridAutoHeight]="true"`. If you made a change in stackblitz you have to refresh the whole page. Before this it seems to work. After this it is broken again.

https://stackblitz.com/edit/angular-cdrx9w-fismfr

**Comment by maxokorokov** [comment] 2018-07-12 13:44
@MeMeMax, oh, looks like you're right, thanks!

**Comment by dominikg** [comment] 2018-07-16 07:40
the root cause is ag-grid using MutationObserver in a ResizeObserver polyfill and ng-bootstrap doing dom changes in ngZone onStable.

related:
https://github.com/ag-grid/ag-grid-angular/issues/221#issuecomment-402667743
https://github.com/ng-bootstrap/ng-bootstrap/issues/2342#issuecomment-402726519

**Comment by pkozlowski-opensource** [comment] 2018-07-17 12:01
> @pkozlowski-opensource, this will not fix the issue, but shouldn't we do positioning ONLY when the popup is open and attached to body?

@maxokorokov most definitively! I'm not sure why we invoke this logic all the time :-/

**Comment by pkozlowski-opensource** [comment] 2018-07-17 12:05
You can blame me for re-positioning menu all the time :-/ https://github.com/ng-bootstrap/ng-bootstrap/commit/c7a16a5444917d855ef03fca6b6cf855420eaf98#diff-ed4f415f7194ca32cfe9021c01b9badf

**Comment by maxokorokov** [comment] 2018-07-17 13:21
> I'm not sure why we invoke this logic all the time :-/

@pkozlowski-opensource, you have to invoke it all the time, if you attach popup to body, I think. On the other hand it will most likely be attached to body if used inside the ag-grid (we had issues for this with popovers and tooltips)

**Comment by pkozlowski-opensource** [comment] 2018-07-17 13:22
>  you have to invoke it all the time, if you attach popup to body, I think

Sure. What I've meant is that I don't know why we reposition it when dropdown is not open.

**Comment by dominikg** [comment] 2018-07-17 19:49
@pkozlowski-opensource 
I don't think ng-bootstrap repositions something while not open (dropdown checks isOpen() in _positionMenu, datepicker checks _cRef which only exists after open() and is reset in close()).

@maxokorokov 
For this issue it does not matter if the element is attached to body or inside ag-grid. The MutationObserver ag-grid uses sits on [document](https://github.com/ag-grid/ag-grid/blob/4f4d37fabcb9e2b9096070496dbba0de7dfdcb74/packages/ag-grid/src/ts/resizeObserver.ts#L244)

Is it really needed to automatically check positioning of a dynamically placed element in every onstable? 
Relative positions of  2 elements won't change for most onstable events and there could also be cases where onstable is not fired while relative positions have changed.

Maybe exposing some kind of 'updatePosition' api that can be called manually could be an alternative?

**Comment by harithay** [comment] 2018-07-23 20:41
Check my comment https://github.com/ag-grid/ag-grid-angular/issues/221#issuecomment-407193843

**Comment by seanlandsman** [comment] 2018-07-24 08:56
I've just done a beta release for this - ag-grid 18.1.2-beta.1

I'd encourage you all to try and see if this resolves the issue 

thanks!

**Comment by pkozlowski-opensource** [comment] 2018-07-24 13:14
Thnx @harithay ! Closing it here as my understanding is that it more of ag-grid / polyfills issue. Feel free to follow-up if you believe that we still should do something here, in this project.

**Closed by pkozlowski-opensource** 2018-07-24 13:14 UTC
Labels: component: datepicker, needs: investigation, type: bug

**Comment by dominikg** [comment] 2018-08-02 06:58
fyi: ag-grid reopened related issues because the new version still has issues in IE and FF.

see [my comment there](https://github.com/ag-grid/ag-grid/issues/2487#issuecomment-408326700) for a trace of the loop in FF.
